Kitware/vtk-js

Sources/Rendering/Core/Viewport/index.js, Sources/Rendering/OpenGL/Camera/index.js, Sources/Rendering/OpenGL/Renderer/index.js
add getTileSizeAndOrigin method and support for it in camera
none
=> feat($compile): fix window resize support

Sources/Rendering/OpenGL/Actor/index.js, Sources/Rendering/OpenGL/Actor2D/index.js, Sources/Rendering/OpenGL/ImageSlice/index.js
OpenGL was rendering props regardless of their
visibility flag. This topic fixes that issue.
=> fix(Rendering): honor visibility flag on Props

Sources/Filters/General/ImageStreamline/api.md, Sources/Filters/General/ImageStreamline/example/controller.html, Sources/Filters/General/ImageStreamline/example/index.js, Sources/Filters/General/ImageStreamline/index.js, Sources/Filters/General/ImageStreamline/test/testStreamline.js, Sources/Filters/General/OutlineFilter/api.md, Sources/Filters/General/OutlineFilter/example/controlPanel.html, Sources/Filters/General/OutlineFilter/example/index.js, Sources/Filters/General/OutlineFilter/index.js, Sources/tests.js
This allow computation of streamline within an ImageData
=> feat(ImageStreamline): Add vtkImageStreamline filter

Documentation/content/docs/misc_contributing.md
I just noticed the error by taking a look at the link in https://kitware.github.io/vtk-js/docs/misc_contributing.html#Updating-Documentation
=> docs(update .md format): Change {% code %} to ``` in misc_contributing.md

Sources/IO/Misc/ElevationReader/example/index.js, Sources/IO/Misc/ElevationReader/index.js, Sources/Rendering/Core/Actor/index.js, Sources/Rendering/Core/Prop/index.js, Sources/Rendering/Core/Texture/index.js, Sources/Rendering/OpenGL/Actor/index.js, Sources/Rendering/OpenGL/Texture/index.js
Also fix a couple issues that turned up in OpenGL
with texture maps added after the first render.
=> feat(IO): add texture coordinates to elevation reader

Sources/Filters/General/MoleculeToRepresentation/index.js, Sources/Filters/General/WarpScalar/index.js, Sources/Interaction/Style/InteractorStyleManipulator/index.js, Sources/Rendering/Core/Actor/index.js, Sources/Rendering/Core/Camera/index.js, Sources/Rendering/Core/ColorTransferFunction/index.js, Sources/Rendering/Core/ImageSlice/index.js, Sources/Rendering/Core/Renderer/index.js, Sources/Rendering/OpenGL/Renderer/index.js, Sources/Rendering/OpenGL/Texture/index.js, Sources/macro.js, Utilities/config/webpack.loaders.js
=> fix(Logger): Implement vtkErrorMacro / vtkDebugMacro / vtkWarnMacro

Sources/Rendering/Core/ColorTransferFunction/index.js, Sources/Rendering/Core/Texture/index.js, Sources/Rendering/OpenGL/Actor/index.js, Sources/Rendering/OpenGL/Texture/index.js, Sources/Representation/Geometry/OBJRepresentation/index.js
Textures should handle incomplete images now
Two bad code segments in color transfer function
=> fix(Rendering): minor fix to ctfun plus onload for textures

Sources/Rendering/Core/ColorTransferFunction/index.js, Sources/Rendering/Core/Mapper/index.js
A couple bugs in the clor transfer function
when applying an existing table
=> fix(Rendering): fixes to color transfer function

Sources/Common/Core/Math/index.js
Bad called vector in angleBetweenVectors which causes NaN
=> fix(Math): Fix function angleBetweenVectors

Sources/macro.js
The first test was not working as console is always
defined while the methods (log,debug,error) may not be.
=> fix(Core): fix issues with the edge browser

Sources/Rendering/OpenGL/DynamicFloat32Array/index.js, Sources/Rendering/OpenGL/RenderWindow/index.js
There was an error in the DynamicArray that could
cause valid colors to be mapped as NaN resulting
in rendering artifacts.
=> fix(Rendering): scalar colors could yield NaN

Sources/Rendering/OpenGL/DynamicFloat32Array/index.js
It looks faster to me and I like the code better.
This version should have a better memory footprint
and far fewer allocations if nothing else.
=> perf(Rendering): maybe make things faster

Sources/Common/Transform/LandmarkTransform/index.js
Add some fixes for constant and the using of gl-matrix
=> Constant issues landmark transform

Sources/Interaction/Manipulators/TrackballPan/index.js, Sources/Interaction/Manipulators/TrackballRoll/index.js, Sources/Interaction/Manipulators/TrackballRotate/index.js, Sources/Interaction/Manipulators/TrackballZoom/index.js, Sources/Interaction/Manipulators/TrackballZoomToMouse/index.js, Sources/Interaction/Style/InteractorStyleManipulator/index.js, Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js, Sources/Rendering/Core/RenderWindowInteractor/index.js
Recent commits broke touch event handliing.
=> fix(Interaction): fix for touch events

Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js, Sources/Rendering/Core/RenderWindowInteractor/index.js
=> fix(Interaction): fix a multitouch issue

Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js, Sources/Rendering/Core/RenderWindowInteractor/index.js
This topic adds a final high res render after animation had ended.
It also uses the animation logic for multitouch movements.
=> perf(Rendering): add high res render as needed, multitouch

Sources/Common/Core/LookupTable/index.js, Sources/Rendering/Core/Mapper/index.js, Sources/Rendering/OpenGL/Actor/index.js, Sources/Rendering/OpenGL/Actor2D/index.js, Sources/Rendering/OpenGL/Camera/index.js, Sources/Rendering/OpenGL/ImageMapper/index.js, Sources/Rendering/OpenGL/ImageSlice/index.js, Sources/Rendering/OpenGL/PolyDataMapper/index.js, Sources/Rendering/OpenGL/RenderWindow/index.js, Sources/Rendering/OpenGL/Renderer/index.js, Sources/Rendering/OpenGL/Texture/index.js, Sources/Rendering/OpenGL/Volume/index.js, Sources/Rendering/OpenGL/VolumeMapper/index.js, Sources/Rendering/SceneGraph/RenderPass/index.js, Sources/Rendering/SceneGraph/ViewNode/index.js, Sources/Rendering/SceneGraph/index.js
In prep for mixed colume and surfaces add render passes
and update the code to use them.
=> refactor(Rendering): update to use render passes

Sources/Rendering/OpenGL/Texture/index.js
A few critical bugs in newly added texture code.
=> fix(Rendering): fix bugs in new texture resize code

Sources/Rendering/Core/RenderWindowInteractor/index.js, Sources/Rendering/OpenGL/VolumeMapper/index.js, Sources/Rendering/OpenGL/VolumeMapper/test/testComposite.js, Sources/Rendering/OpenGL/VolumeMapper/test/testComposite16Bit.js, Sources/Rendering/OpenGL/VolumeMapper/test/testIntermixed.js, Sources/Rendering/OpenGL/VolumeMapper/test/testLighting.js
Now also honors still update rates which will help
with underpowered devices so that they do not hang
while trying to render a full resolution image
=> fix(Rendering): improve LOD support for volumes

Sources/Rendering/OpenGL/Texture/index.js, Sources/Rendering/OpenGL/VolumeMapper/index.js
encode in a nonlinear manner to keep magnitude relative
rsolution more constant.
=> perf(Rendering): encode gradient opacity using sqrt

Sources/Rendering/OpenGL/VolumeMapper/index.js, Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl
Some minor shader improvements
=> perf(Rendering): minor volume rendering performance

Sources/Rendering/Misc/SynchronizableRenderWindow/index.js, Sources/Rendering/Misc/SynchronizableRenderWindow/vtkObjectManager.js, Sources/Rendering/Misc/index.js, package.json
The vtkSynchronizableRenderWindow is designed to be kept in sync with a ParaView/VTK view on the server side, or even with some other source of state.
=> feat(SynchronizableRenderWindow): Provide a new type of vtkRenderWindow

Sources/Rendering/OpenGL/ImageMapper/index.js
=> fix(Rendering): another case of using mipmaps on greyscale

Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl
=> fix(Rendering): volume rend went one step too far

Sources/Rendering/OpenGL/Camera/index.js, Sources/Rendering/OpenGL/Renderer/index.js
missing some key scissor and viewport calls
=> fix(Rendering): handle multiple renderers

Sources/Filters/Sources/RTAnalyticSource/api.md, Sources/Filters/Sources/RTAnalyticSource/index.js, Sources/Filters/Sources/index.js, Sources/Interaction/Style/InteractorStyleImage/index.js, Sources/Rendering/Core/Camera/index.js, Sources/Rendering/Core/ImageMapper/example/index.js, Sources/Rendering/Core/ImageMapper/index.js, Sources/Rendering/OpenGL/ImageMapper/index.js
Enable the image mapper to andjust slice based on
camera focal point. Add RTAnalyticSource as a more
useful image data source.  Implement a couple distance
methods in Camera
=> fix(Rendering): implement some missing methods

Sources/Rendering/Core/Camera/index.js
Set physicalViewUp and physicalViewNorth to map world coordinates
to the device.
=> fix(Rendering): add support for js device orientations to Camera

Sources/Rendering/Core/Camera/index.js
It previously was not working in perspective mode
=> fix(Rendering): make the camera support window center

Sources/macro.js
Function must always return something, the inpout or undefined.
=> fix(Macro): Fix GetInputConnection method

Sources/Rendering/OpenGL/PolyDataMapper/api.md, Sources/Rendering/OpenGL/PolyDataMapper/index.js
User can use callback to update shaders' attributes.
@jpouderoux has participated to this pull request.
=> feat(OpenGLPolyDataMapper): Allow to create callback on mapper

Examples/WebGL/SimpleCone/index.js
Added SimpleCone as a very minimal example of using vtk.js
=> docs(Example): provide a simple minimal example

Sources/Rendering/OpenGL/PolyDataMapper/index.js
remove left over debugging code
=> fix(Rendering): fix for left over debugging code

Sources/Rendering/OpenGL/ShaderProgram/index.js
Use similar code that what existed for uniform3.
=> feat(ShaderProgram): Add functions to set uniform2 and 4

Sources/IO/Misc/OBJReader/index.js, Sources/Rendering/OpenGL/ShaderProgram/index.js
=> style(eslint): Fix eslint errors

Sources/Rendering/Core/VolumeMapper/example/index.js
the sample distance was a tad small and desired
update rate a tad high
=> fix(Rendering): better settings for VR example

Sources/Common/DataModel/DataSetAttributes/FieldData.js, Sources/macro.js
eslint is complaining about no-return-assign. Code was changed to pass the error.
BREAKING CHANGE: none
none
=> fix(eslint): no-return-assign error from eslint

Sources/IO/Core/HttpSceneLoader/index.js, Sources/Rendering/Core/Camera/index.js, Sources/Rendering/Core/Prop3D/index.js, Utilities/ParaView/export-scene-macro.py
update pv export macro to also export actor pos/origin/scale/rot
update scene importer to import the values
=> fix(IO): export actor position/origin/scale/rotation

Sources/IO/Core/HttpSceneLoader/index.js, Utilities/ParaView/export-scene-macro.py
=> fix(HttpSceneLoader): Add support for texture export/load

Sources/IO/Core/HttpSceneLoader/index.js, Sources/Rendering/OpenGL/Texture/index.js
now if repeat is on the texture will be set to repeat
=> fix(Rendering): texture was not honoring Repeat setting

Sources/Common/DataModel/Box/index.js, Sources/Common/DataModel/Box/test/testBox.js, Sources/Common/DataModel/index.js, Sources/tests.js
Add the vtkCube class + associated test
=> feat(vtkCube): Add vtkCube class

Sources/Common/DataModel/Box/test/testBox.js
Error are raised when test is launched
=> fix(Box): Fix eslint when test is launched

Sources/Rendering/Core/AbstractPicker/index.js, Sources/Rendering/Core/Picker/api.md, Sources/Rendering/Core/Picker/index.js, Sources/Rendering/Core/PointPicker/api.md, Sources/Rendering/Core/PointPicker/index.js, Sources/Rendering/Core/RenderWindowInteractor/index.js, Sources/Rendering/Core/index.js
Add the point picker to pick 3D point from mouse clicking.
=> feat(Picker): Add a point picker

Sources/Filters/Sources/SLICSource/api.md, Sources/Filters/Sources/SLICSource/example/index.js, Sources/Filters/Sources/SLICSource/index.js, Sources/Filters/Sources/index.js
SLIC stands for Simple Linear Iterative Clustering to generate vtkImageData
=> feat(SLICSource): Create a new source which leverage SLIC

Sources/Common/Core/Math/index.js, Sources/Common/DataModel/Cell/api.md, Sources/Common/DataModel/Cell/index.js, Sources/Common/DataModel/Line/Constants.js, Sources/Common/DataModel/Line/api.md, Sources/Common/DataModel/Line/index.js, Sources/Common/DataModel/Line/test/testLine.js, Sources/Common/DataModel/Triangle/api.md, Sources/Common/DataModel/Triangle/index.js, Sources/Common/DataModel/Triangle/test/testTriangle.js, Sources/Common/DataModel/index.js, Sources/Rendering/Core/AbstractPicker/api.md, Sources/Rendering/Core/AbstractPicker/index.js, Sources/Rendering/Core/CellPicker/api.md, Sources/Rendering/Core/CellPicker/example/PickerInteractorStyle.js, Sources/Rendering/Core/CellPicker/example/index.js, Sources/Rendering/Core/CellPicker/index.js, Sources/Rendering/Core/Picker/index.js, Sources/Rendering/Core/index.js, Sources/tests.js
Implement cell picker which use vtkCell and particulary vtkTriangle.
The cellPicker can only pick triangles for now because other kind of cells are not implemented.
An example if the cell picker have been added : press shift key + click
=> Add cell picker and cell notion

Examples/Volume/MultiSliceImageMapper/controlPanel.html, Examples/Volume/MultiSliceImageMapper/index.js
=> chore(MultiSliceImageMapper): Add interaction to change brightness

.travis.yml, Documentation/content/index.jade, README.md, Sources/Interaction/Widgets/PiecewiseFunctionWidget/example/index.js, Sources/Interaction/Widgets/PiecewiseFunctionWidget/index.js, Sources/Interaction/Widgets/index.js, Sources/Interaction/index.js, karma.conf.js, package-lock.json, package.json
=> feat(PieceWiseFunctionEditor): Add new widget component

Sources/Rendering/OpenGL/VolumeMapper/index.js
If the minimum extnt for an image data was not 0,0,0
the rendering would be off. This fixes that.
=> fix an issue where vol ren did not handle non zero min ext

Examples/Applications/SceneExplorer/index.js, Sources/Interaction/Style/InteractorStyleImage/index.js, Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js, Sources/Rendering/Core/Mapper/index.js, Sources/Rendering/Core/RenderWindow/index.js, Sources/Rendering/Core/RenderWindowInteractor/index.js, Sources/Rendering/OpenGL/PolyDataMapper/index.js, Sources/Rendering/SceneGraph/ViewNode/index.js
Most camera manipulation was causing double renders
making the apparent render rate half of what it
should be.
Some other minor perf improvements.
=> fix(Rendering): improve rendering performance

Sources/Rendering/Core/Picker/index.js
The user matrix need to be transpose before being used to project points
=> Fix picker

Sources/Common/DataModel/Cylinder/api.md, Sources/Common/DataModel/Cylinder/index.js, Sources/Common/DataModel/ImplicitBoolean/Constants.js, Sources/Common/DataModel/ImplicitBoolean/api.md, Sources/Common/DataModel/ImplicitBoolean/example/controller.html, Sources/Common/DataModel/ImplicitBoolean/example/index.js, Sources/Common/DataModel/ImplicitBoolean/index.js, Sources/Common/DataModel/index.js, Sources/Filters/General/ImageMarchingCubes/index.js
Added cylinder implicit function
Added boolean method to combine implicit functions
Fixed extent traversal bug in ImageMarchingCubes
Made performance improvements to ImageMarchingCubes
=> Implicit function contributions

Sources/Common/Core/DataArray/index.js, Sources/Common/DataModel/DataSetAttributes/index.js, Sources/Interaction/Widgets/SphereHandleRepresentation/index.js, Sources/Rendering/Core/Actor/index.js, Sources/Rendering/Core/Prop/index.js, Sources/Rendering/Core/Prop3D/index.js, Sources/Rendering/Core/RenderWindowInteractor/index.js, Sources/Rendering/Core/Renderer/index.js, Sources/Rendering/Core/Viewport/index.js, Sources/Rendering/OpenGL/Actor/index.js, Sources/Rendering/OpenGL/ForwardPass/index.js, Sources/Rendering/OpenGL/HardwareSelector/index.js, Sources/Rendering/OpenGL/ImageMapper/index.js, Sources/Rendering/OpenGL/PolyDataMapper/index.js, Sources/Rendering/OpenGL/RenderWindow/index.js, Sources/Rendering/OpenGL/Renderer/index.js, Sources/Rendering/OpenGL/ShaderProgram/api.md, Sources/Rendering/OpenGL/ShaderProgram/index.js, Sources/Rendering/OpenGL/SphereMapper/index.js, Sources/Rendering/OpenGL/StickMapper/index.js, Sources/Rendering/OpenGL/VertexArrayObject/index.js, Sources/Rendering/OpenGL/VolumeMapper/index.js, Sources/Rendering/SceneGraph/RenderPass/index.js, Sources/Rendering/SceneGraph/ViewNode/index.js, Sources/macro.js
A fair number of calls were being done that didn't
need to be done. Also some VAO rebuilding was always
happening when it should not have.
=> fix(Rendering): more performance improvements

Sources/Filters/General/ImageMarchingCubes/api.md, Sources/Filters/General/ImageMarchingCubes/example/controller.html, Sources/Filters/General/ImageMarchingCubes/example/index.js, Sources/Filters/General/ImageMarchingCubes/index.js
Added the ability to compute normals. Points may or may not be
merged. The example was changed to enable/disable point merging
and normal computation.
=> feat(ImageMarchingCubes): Added normal computation; point merging

Sources/Interaction/UI/VolumeController/index.js
Provide better range of edge enhancement values
and spacing values.
=> perf(Rendering): update values for volumeViewer

Sources/Rendering/OpenGL/RenderWindow/index.js, Sources/Rendering/OpenGL/VolumeMapper/index.js
added linux and Netscape to webgl2 defaults
=> perf(Rendering): more systems default to webgl2

Sources/Common/DataModel/ImplicitBoolean/index.js, Sources/Filters/General/ImageMarchingSquares/api.md, Sources/Filters/General/ImageMarchingSquares/caseTable.js, Sources/Filters/General/ImageMarchingSquares/example/controller.html, Sources/Filters/General/ImageMarchingSquares/example/index.js, Sources/Filters/General/ImageMarchingSquares/index.js, Sources/Filters/General/index.js
A new isocontouring algorithm for 2D images or a zslice from a
volume has been added. Multiple contours are supported, and merging
intersection points along edges may be enabled or disabled.
=> feat(ImageMarchingCubes): Added 2D image or slice contouring

Sources/Rendering/OpenGL/PixelSpaceCallbackMapper/index.js
Recent changes broke this class.
=> fix(Rendering):  pixel space callback issues

Sources/Rendering/Core/Glyph3DMapper/index.js, Sources/Rendering/Core/Mapper/test/testVectorComponent.js
1) the bounds when using scale by magnitude were too small
when there were mure than one component.
2) The scaleFactor was use din the bounds but not in the actual
rendering.
=> fix(Rendering): fix two issues with glyph scaling

Examples/Applications/GeometryViewer/index.js, Examples/Applications/VolumeViewer/index.js, Sources/IO/Core/BinaryHelper/index.js, Sources/IO/Core/index.js, Sources/IO/XML/XMLImageDataReader/index.js, Sources/IO/XML/XMLPolyDataReader/index.js, Sources/IO/XML/XMLReader/index.js
WIP
This adds initial capabilities to read data arrays out of a VTI/VTP appended data file format, as generated from VTK.
=> Add vti/vtp appended data format support

Examples/Geometry/DepthTest/index.js
=> fix(Rendering): missed a change

Sources/Rendering/OpenGL/Glyph3DMapper/index.js, Sources/Rendering/OpenGL/VertexArrayObject/index.js
Support instacing on Webgl1 when the extension is
present. In spite of being named ANGLE many non
angle based browsers support this extension.
=> perf(Rendering): support ANGLE_instanced_arrays

Sources/Rendering/OpenGL/Glyph3DMapper/index.js
redo a change lost with a recent MR
=> fix(Renderfing): glyph fix for some systems

Sources/Common/Core/ImageHelper/index.js, Sources/Interaction/Widgets/OrientationMarkerWidget/Constants.js, Sources/Interaction/Widgets/OrientationMarkerWidget/api.md, Sources/Interaction/Widgets/OrientationMarkerWidget/example/index.js, Sources/Interaction/Widgets/OrientationMarkerWidget/index.js, Sources/Rendering/Core/AnnotatedCubeActor/api.md, Sources/Rendering/Core/AnnotatedCubeActor/index.js
Adds AnnotatedCubeActor and OrientationMarkerWidget, as well as ImageHelper.
=> Add orientation/axes cube

Documentation/content/docs/develop_test.md
=> docs(test): Documentation about creating/changing a baseline for tests

Sources/Common/Core/MatrixBuilder/index.js
@sankhesh FYI, that was the missing part.
=> fix(MatrixBuilder): Allow apply() to be chain

Sources/Rendering/OpenGL/glsl/readme.txt
Found some typos, which I fixed.
=> Fixing some typos

Sources/Rendering/OpenGL/ForwardPass/index.js
Support multiple renderers as layers. Specifically
fix issue https://github.com/Kitware/vtk-js/issues/465
=> fix(Rendering): handle layers better

Sources/Rendering/OpenGL/ImageMapper/index.js
In many cases trhe data passed to an image mapper
pointger was not correct especially with extents
that did not start at 0.
=> fix(Rendering): fix bad data for image mapper

Sources/Testing/testMacro.js, Sources/macro.js
This adds priorities to event listeners, as well as capability for event listeners to abort the continuation/propagation of a vtkjs event.
=> Priority event listeners and event abort

Sources/Filters/Sources/ConcentricCylinderSource/example/controlPanel.html, Sources/Filters/Sources/ConcentricCylinderSource/example/index.js, Sources/Filters/Sources/ConcentricCylinderSource/index.js
Add startTheta and endTheta parameters, in degrees, to allow drawing
partial cylinders. Expand the example code to exercise the new
params.
The sides of a partial cylinder are capped.
Fix a few typos, and rename 'nb' to 'num'.
=> fix(ConcentricCylinderSource): Add start/end angles.

Sources/Interaction/Manipulators/CameraManipulator/example/controller.html, Sources/Interaction/Manipulators/CameraManipulator/example/index.js, Sources/Interaction/Manipulators/CameraManipulator/index.js, Sources/Interaction/Manipulators/TrackballZoom/index.js, Sources/Interaction/Style/InteractorStyleManipulator/index.js
=> feat(cameraManipulator): expose pinch/scroll event to manipulators

Sources/Interaction/Manipulators/SliceManipulator/index.js, Sources/Interaction/Manipulators/index.js, Sources/Rendering/Core/ImageMapper/example/index.js, Sources/Rendering/Core/ImageMapper/index.js, Sources/Rendering/OpenGL/ImageMapper/index.js
- add slicing manipulator: vtkSliceManipulator
- improve ImageMapper to:
- clamp slicing to the volume bounds
- allow slicing from X, Y and Z axis from the camera
=> SliceManipulator and ImageMapper improvements

Sources/Interaction/Widgets/OrientationMarkerWidget/api.md, Sources/Interaction/Widgets/OrientationMarkerWidget/example/index.js, Sources/Interaction/Widgets/OrientationMarkerWidget/index.js
This implements a bounded square viewport for the orientation marker.
=> Orientation marker: better viewport

Sources/Interaction/Manipulators/CameraManipulator/index.js, Sources/Interaction/Manipulators/MouseManipulator/index.js, Sources/Interaction/Manipulators/RangeManipulator/example/index.js, Sources/Interaction/Manipulators/RangeManipulator/index.js, Sources/Interaction/Manipulators/index.js, Sources/Interaction/Style/InteractorStyleManipulator/index.js
- Add `MouseManipulator` to hold mouse and modifier keys properties, and extend it with `CameraManipulator` for manipulators using the camera.
- Add `RangeManipulator` to generate generic values between a range with a specific step.
- Add example for `RangeManipulator`:
- control window vertical grab
- control level with horizontal grab
- control Z slice with scroll/pinch
=> Range manipulator

Sources/Rendering/OpenGL/ImageMapper/index.js, Sources/Rendering/OpenGL/VolumeMapper/index.js
for the imagemapper and volumemapper so that they do
not rebuild as often.
=> fix(Rendering): tighten up the shader rebuild code

Sources/Interaction/Widgets/OrientationMarkerWidget/example/index.js, Sources/Rendering/Core/AnnotatedCubeActor/index.js
This adds ability to rotate faces by specifying degrees.
=> fix(AnnotatedCubeActor): Support face rotations

Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js
An issue was occurring when I was scrolling hover a window which has never been clicked
=> fix(interaction): Fixed issue when scrolling in unclicked window

Sources/Proxy/Core/ProxyManager/core.js, Sources/Proxy/Core/ProxyManager/index.js
Adds a `proxyRegistrationChange` event to the Proxy manager.
=> fix(ProxyManager): Add proxy registration event

Sources/Rendering/OpenGL/SphereMapper/index.js, Sources/Rendering/OpenGL/StickMapper/index.js
Fix to work with earlier changes made in polydata mapper
=> fix(Rendering): fix sphere and stick mapper with depth pass

Sources/Rendering/Core/CellPicker/index.js
Fixes issue (1) from https://github.com/Kitware/vtk-js/issues/545
=> fix(CellPicker): correctly populate pCoords

Sources/Common/Core/Math/api.md, Sources/Common/Core/Math/index.js, Sources/Interaction/Widgets/PiecewiseGaussianWidget/index.js, Sources/Rendering/OpenGL/Texture/index.js
=> Volume rendering performance

Sources/Common/DataModel/ITKHelper/index.js, Sources/Common/DataModel/index.js
=> fix(ITKHelper): Add ITK to VTK js image converter

Sources/Common/DataModel/ITKHelper/index.js
I forgot to add default arg to options oops
Also adds image pixel type detection per https://github.com/Kitware/vtk-js/pull/578#pullrequestreview-95979701 @thewtex
=> More itkhelper fixes

Sources/Proxy/Representations/GeometryRepresentationProxy/index.js, Sources/Proxy/Representations/SliceRepresentationProxy/index.js, Sources/Proxy/Representations/VolumeRepresentationProxy/index.js
1. Remove hardcoded property links to rely on dynamic property links instead: https://github.com/kitware/vtk-js/commit/28f40b2
2. Add some properties on geometry representation
=> Improve linked properties

Sources/Common/DataModel/ITKHelper/index.js
ITK images have N explicit dimensions
CC: @floryst @jourdain
=> fix(ITKHelper): Support conversion of 2D images

Sources/Proxy/Core/ProxyManager/core.js, Sources/Testing/testProxy.js, Sources/macro.js, Sources/tests.js
setActive is default true, so code must explicitly disable this.
=> fix(ProxyManager): Optionally set proxy to active, if possible

Sources/Proxy/Core/ViewProxy/index.js, Sources/Rendering/Core/RenderWindowInteractor/index.js
- orientationAxes -> orientationAxesVisibility
- orientationAxesCorner
- orientationAxesSize
=> couple fixes

Sources/Interaction/Widgets/PiecewiseGaussianWidget/index.js
…Gaussian
CC: @agirault @jourdain
=> fix(PiecewiseGaussianWidget): Enable API adjustment of Gaussians

Sources/Rendering/OpenGL/Skybox/index.js
Now it should update with new textures
=> fix for when the textures change skybox was not updating

Sources/Rendering/OpenGL/Skybox/index.js, Sources/Rendering/OpenGL/Texture/index.js
=> fix issue with texture release and skybox update

Sources/Rendering/OpenGL/RenderWindow/index.js, Sources/Rendering/OpenGL/ShaderCache/index.js, Sources/Rendering/OpenGL/VolumeMapper/index.js, Sources/Rendering/OpenGL/glsl/vtkVolumeFS2.glsl
cc: @martinken 
- Use a fixed for loop instead of float variable loop.
=> webgl2 change

Sources/Proxy/Core/AbstractRepresentationProxy/index.js, Sources/Proxy/Core/ViewProxy/index.js, Sources/macro.js
use `type` to define where the link lives: `source` (default) or `application`.
=> fix(proxy): allow links to be on the application level

Sources/Rendering/Core/Mapper/api.md, Sources/macro.js
Need the inverse of capitalize.
Fix a few doc typos.
=> fix(macro): add uncapitalize function

Sources/Common/Core/DataArray/index.js, Sources/Common/DataModel/Box/index.js, Sources/Common/DataModel/Box/test/testBox.js, Sources/Common/DataModel/Plane/index.js, Sources/Common/DataModel/Plane/test/testPlane.js
speed up `dataArray.getTuple` and `Plane/Box.evaluateFunction`.
=> Speed improvements

Sources/Filters/Core/Cutter/example/controlPanel.html, Sources/Filters/Core/Cutter/example/index.js, Sources/Filters/Core/Cutter/index.js, Sources/Filters/Core/Cutter/test/testCutter.js, Sources/Filters/Core/index.js, Sources/Filters/index.js, Sources/Proxy/Representations/SlicedGeometryRepresentationProxy/index.js, Sources/macro.js, Sources/tests.js
=> Adding vtk cutter

Sources/Interaction/Manipulators/MouseCameraTrackballZoomManipulator/index.js, Sources/Interaction/Manipulators/MouseRangeManipulator/index.js, Sources/Interaction/Style/InteractorStyleImage/index.js, Sources/Interaction/Style/InteractorStyleManipulator/index.js, Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js, Sources/Rendering/Core/RenderWindowInteractor/index.js, Sources/macro.js
References related to mouse wheel delta problem:
- info (wheelDelta): https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel
- issue: https://stackoverflow.com/questions/5527601/normalizing-mousewheel-speed-across-browsers
- solution: https://github.com/facebookarchive/fixed-data-table/blob/master/src/vendor_upstream/dom/normalizeWheel.js
- package: https://www.npmjs.com/package/normalize-wheel
=> Fix scroll values from mouse wheel event

Externals/ITK/dependencies.js, Externals/README.md, Sources/IO/Misc/ITKImageReader/index.js, Sources/IO/Misc/index.js, Sources/Interaction/Widgets/index.js
=> Fix widget exposure

Sources/Interaction/Manipulators/MouseRangeManipulator/index.js
Leftovers from https://github.com/Kitware/vtk-js/commit/a768180556a08ca23fecd46bc20ae904359021be
=> style(MouseRangeManipulator): remove console log

Sources/Rendering/Core/ColorTransferFunction/ColorMaps.js
Haven't tested addPreset and removePresetByName, but they look reasonable thus far.
=> Support adding and removing colormap presets

Sources/Rendering/OpenGL/RadialDistortionPass/index.js
Forgot to add the actual class for radial distortion
=> fix(Rendering): add missing class

Sources/Common/DataModel/PiecewiseFunction/index.js, Sources/Interaction/Widgets/PiecewiseGaussianWidget/index.js, Sources/Proxy/Core/PiecewiseFunctionProxy/index.js
Some code refactors to use the new API.
=> fix(PiecewiseFunction): Add setNodes() to API

Sources/Common/DataModel/PiecewiseFunction/index.js, Sources/Filters/General/ImageSliceFilter/index.js, Sources/Filters/General/ScalarToRGBA/example/index.js, Sources/Filters/General/ScalarToRGBA/index.js
=> fix(ScalarToRGBA): try to answer request

.travis.yml, Utilities/ci/travis-release.sh
Also switch order of doc publish and version release so we get new
versions sooner.
=> ci(travis): Try out npm ci

Sources/Interaction/Widgets/LineRepresentation/index.js, Sources/Interaction/Widgets/SphereHandleRepresentation/index.js
The selection color of a handle widget must be editable
=> feat(SphereHandleRepresentation): Expose property and selectProperty

Sources/IO/Misc/JSONNucleoReader/example/index.js, Sources/IO/Misc/JSONNucleoReader/index.js, Sources/IO/Misc/index.js
=> fix(JSONNucleoReader): Add new reader

Sources/Rendering/OpenGL/ImageMapper/index.js
Make the system recognize the state change and respond
when vtkImageProperty.setInterpolationType is called.
=> fix(ImageMapper): Render InterpolationType changes

Sources/Rendering/OpenGL/Glyph3DMapper/index.js, Sources/Rendering/OpenGL/ImageMapper/index.js, Sources/Rendering/OpenGL/PolyDataMapper/index.js, Sources/Rendering/OpenGL/VolumeMapper/index.js
=> fix(OpenGL): Fix currentInput check

Sources/Filters/General/MoleculeToRepresentation/index.js
=> fix(MoleculeToRepresentation): Fix color mapping of the bonds when elements are hidden

Sources/Filters/General/ImageCropFilter/api.md, Sources/Filters/General/ImageCropFilter/example/controlPanel.html, Sources/Filters/General/ImageCropFilter/example/index.js, Sources/Filters/General/ImageCropFilter/index.js
Adds an image cropping filter. Crops in IJK space. Accomplishes #713, but this is a slower approach. 
@aylward
=> feat(ImageCropFilter): Add image cropping filter

Sources/Filters/General/ImageCropFilter/index.js, Sources/Interaction/Widgets/ImageCroppingRegionsRepresentation/index.js
ImageCroppingRegionsRepresentation: Use outline mapper as rep mapper
=> fix(Cropping):  Correctly handle cropping extent

Sources/Filters/General/ImageCropFilter/index.js
=> CropFilter: Add reset and fix crop bounds not bounded by extent

Utilities/DataGenerator/vtk-data-converter.py
Referencing Pull Request #790.
=> Converting to Py3.6

Documentation/content/docs/develop_example.md
Do I need to do anything other than edit the Markdown for a docs change? I am assuming the CI will build the docs.
Thanks!
=> docs(typo) Patch a typo in the "Creating a new example" page

Sources/Rendering/Core/Prop/index.js
This includes a couple improvements to Prop:
- Fix incorrect `removeTexture()` implementation
- Simplify `hasTexture()` implementation
=> Fix removing texture

Sources/Proxy/Core/ProxyManager/state.js
Errors that occur inside the promise should be handled accordingly.
=> fix(ProxyManager): Reject promise on save/load error

Sources/IO/XML/XMLReader/index.js
=> fix(XMLReader): Fetch data in binary mode

Sources/Rendering/Core/ImageSlice/index.js, Sources/Rendering/OpenGL/ImageMapper/index.js
=> Expose the property's opacity in ImageMapper (1C).

Sources/Rendering/Core/Glyph3DMapper/index.js, Sources/Rendering/Core/ImageProperty/index.js, Sources/Rendering/Core/ImageSlice/index.js, Sources/Rendering/Core/Mapper/index.js, Sources/Rendering/OpenGL/VolumeMapper/test/testIntermixedImage.js, Sources/Testing/testUtils.js
Cell scalar fix
https://github.com/Kitware/vtk-js/issues/840
Also improve test output to indicate which image is the
test image and which is the baseline.
Also fix for ImageSlice issue
https://github.com/Kitware/vtk-js/issues/842
=> fix(Rendering): fix rendering of data with cell scalars

Sources/Rendering/OpenGL/HardwareSelector/index.js, Sources/Rendering/OpenGL/HardwareSelector/test/testHardwareSelectorSpeed.js
Skip the extra render at the end and save framebuffer
between picks.
=> perf(Picking): another round of speed improvements for picking

Sources/Filters/Texture/TextureMapToPlane/api.md, Sources/Filters/Texture/TextureMapToPlane/index.js, Sources/Filters/Texture/TextureMapToPlane/test/testTextureMapToPlane.js, Sources/Filters/Texture/index.js, Sources/tests.js
Whole filter has been copying from VTK c++ filter.
=> feat(TextureMapToPlane): Add vtkTextureMapToPlane filter and its test

Sources/Imaging/Core/ImageReslice/index.js
=> fix(ImageReslice): Fix center Z coordinate

Sources/Rendering/OpenGL/ShaderCache/index.js, Sources/Rendering/OpenGL/Texture/index.js
Some texture methods have not the same name with webgl 1
@martinken @mcmigliore 
Written in collaboration with Lucas Gandel
=> fix(Webgl): Add webgl 1 extension for texture and mipmap

Documentation/content/api/index.md
=> doc(content): Fix typo in "Interaction"

Examples/Applications/VolumeViewer/index.js, Sources/Interaction/UI/VolumeController/index.js, Sources/Rendering/Core/RenderWindowInteractor/index.js
For interactor observers, the interation events need to be defined with the others.
=> Add interaction events

Sources/Proxy/Core/LookupTableProxy/index.js
This matches what PiecewiseFunctionProxy does.
=> Export constants from LookupTableProxy

Sources/Interaction/Widgets/OrientationMarkerWidget/index.js, Sources/Widgets/Core/AbstractWidgetFactory/index.js, Sources/Widgets/Core/StateBuilder/index.js, Sources/Widgets/Core/StateBuilder/nameMixin.js, Sources/Widgets/Core/StateBuilder/orientationMixin.js, Sources/Widgets/Representations/ContextRepresentation/index.js, Sources/Widgets/Representations/ConvexFaceContextRepresentation/index.js, Sources/Widgets/Representations/HandleRepresentation/index.js, Sources/Widgets/Widgets3D/InteractiveOrientationWidget/behavior.js, Sources/Widgets/Widgets3D/InteractiveOrientationWidget/example/index.js, Sources/Widgets/Widgets3D/InteractiveOrientationWidget/index.js, Sources/Widgets/Widgets3D/InteractiveOrientationWidget/state.js, Sources/Widgets/Widgets3D/index.js
=> Orientation Widget

Sources/Interaction/UI/FPSMonitor/index.js
See individual commits. The last commit is a more comprehensive internal refactor, but should increase the reliability and maintainability of the code.
=> Refactor FPSMonitor to ensure visibility is always correct

Sources/Proxy/Core/ProxyManager/state.js, Sources/Rendering/Core/Camera/index.js, Sources/Rendering/OpenGL/Camera/index.js
Some cleanup and camera fixes.
=> fix(Rendering): some fixes to the camera calcs for VR

Sources/Widgets/Representations/OutlineContextRepresentation/index.js, Sources/Widgets/Widgets3D/ImageCroppingWidget/example/controlPanel.html, Sources/Widgets/Widgets3D/ImageCroppingWidget/example/index.js, Sources/Widgets/Widgets3D/ImageCroppingWidget/index.js
This is a port of the image cropping regions widget to the new widget architecture.
=> Port ImageCroppingWidget to new widgets

Sources/Filters/General/index.js
fix(TubeFilter): Register filter to parent index
=> fix(TubeFilter): Register filter to parent index

Sources/Rendering/Core/Renderer/index.js, Sources/Rendering/OpenGL/PolyDataMapper/index.js
=> fix(light): Restore Scene and camera light type

CONTRIBUTING.md, Documentation/content/docs/misc_contributing.md
* docs: Update and unify contribution docs
=> Improve the contribution process

Sources/Rendering/OpenGL/RenderWindow/index.js
On chrome, canvas not updated to be with Vr view, but in firefox its work prefect, so that I suggest to re-request animation to update scene if chrome and its work perfect dependence of test.
Note: Tested on Latest Version from Chrome & Firefox for 64 bit.
=> Fixing Side-Effect CanvasInVR chrome issue

README.md, Utilities/ci/azure-pipelines.yml, package-lock.json
The `build` target starts a development webpack configuration, which
time's out on CI.
=> Azure configuration tweaks

Utilities/DataGenerator/vtk-data-converter.py
=> fix(data-generator): Update jsmapping

Sources/Filters/General/index.js, Sources/Rendering/Core/AnnotatedCubeActor/index.js, Sources/Widgets/Widgets3D/index.js
=> fix: Add ImageCropFilter and ImageCroppingWidget to exports

Sources/Common/DataModel/PolyData/Constants.js, Sources/Common/DataModel/PolyData/index.js, Sources/IO/XML/XMLImageDataWriter/example/index.js, Sources/IO/XML/XMLImageDataWriter/index.js, Sources/IO/XML/XMLPolyDataWriter/example/index.js, Sources/IO/XML/XMLPolyDataWriter/index.js, Sources/IO/XML/XMLWriter/Constants.js, Sources/IO/XML/XMLWriter/index.js, package.json
Generates a VTI file from a vtkImageData
=> feat(XMLWriter): Add XML Data Writer

Sources/Common/Core/ProgressHandler/index.js, Sources/Common/Core/index.js, Sources/Common/DataModel/index.js, Sources/Filters/General/index.js, Sources/Filters/Sources/index.js, Sources/IO/Legacy/index.js, Sources/IO/XML/index.js, Sources/Proxy/Representations/index.js, Sources/Widgets/Manipulators/index.js, Sources/Widgets/Representations/index.js
@jourdain Let me know if there are any classes that shouldn't be exported.
=> Fix exports

Sources/Rendering/OpenGL/VolumeMapper/index.js
Per discussion in #1071 with @martinken
=> perf(vtkOpenGLVolumeMapper): Remove mat allocs from render loop

Sources/Rendering/OpenGL/PolyDataMapper/index.js
update the algorithm to be a bit clearer
=> fix(Rendering): make line rendering unlit when flat

Sources/Common/Core/ScalarsToColors/index.js
=> fix(Rendering): an issue with using RGBA ScalarsToColors

Sources/Filters/General/PaintFilter/PaintFilter.worker.js, Sources/Filters/General/PaintFilter/index.js
Add the possibility to paint on only one slice of a volume instead of painting on a whole sphere.
=> feat(PaintFilter): Add slicing to PaintFilter

Examples/Volume/TestVolumeTypes/index.js
was missing from the multicomponent MR
=> feat(Rendering): add an example of many types of volume Rendering

Sources/Proxy/Core/ViewProxy/index.js
=> feat(ViewProxy): Add dynamic orientation axis actor list

Sources/Filters/General/AppendPolyData/api.md
Fixes the example usage section
Fixes #1111
=> docs: Update the vtkAppendPolyData documentation

Sources/Interaction/Widgets/ResliceCursor/example/index.js, Sources/Rendering/OpenGL/PolyDataMapper/index.js
Fix issue https://github.com/Kitware/vtk-js/issues/1120
=> fix(Rendering): Fix lighting on points

Sources/Rendering/Core/AbstractMapper3D/index.js, Sources/Rendering/Core/Picker/index.js
=> fix(AbstractMapper3D): Fix usage and implementation of getCenter

Sources/Proxy/Core/ViewProxy/index.js
=> feat(ViewProxy): Focus camera to a given point

Sources/Interaction/Style/InteractorStyleMPRSlice/index.js
=> fix(InteractorStyleMPRSlice): Properly unsubscribe from camera

Sources/Widgets/Widgets3D/ShapeWidget/behavior.js
=> fix(ShapeWidget): Cancel animation when losing focus in ShapeWidget.

Sources/Rendering/Core/Renderer/api.md, Sources/Rendering/Core/Renderer/index.js
Copies the intent of removeAllLights, which was implemented but not documented.
=> feat(Core/Renderer): Implement removeAllActors(), removeAllVolumes()

Sources/Filters/General/PaintFilter/index.js
=> feat(vtkPaintFilter): Add functions to know if undo/redo is possible.

Sources/Filters/General/PaintFilter/PaintFilter.worker.js, Sources/Widgets/Widgets3D/PaintWidget/index.js
=> fix(PaintFilter): Fix vtkPaintWidget was missing first trail, fix DDA algorithm.

Sources/Rendering/OpenGL/VolumeMapper/index.js, Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl
also a fix for webgl1 trilinear interpolation
=> fix(Rendering): do not use shading with MIP/MinIP

Sources/Widgets/Widgets3D/DistanceWidget/behavior.js, Sources/Widgets/Widgets3D/DistanceWidget/example/controlPanel.html, Sources/Widgets/Widgets3D/DistanceWidget/example/index.js, Sources/Widgets/Widgets3D/DistanceWidget/index.js, Sources/Widgets/Widgets3D/DistanceWidget/state.js
Adds a simple distance widget. This is distinct from the existing DistanceWidget in `Interaction/Widgets` in that this one uses the new widget architecture.
=> Add distance widget

Sources/Widgets/Widgets3D/AngleWidget/behavior.js, Sources/Widgets/Widgets3D/AngleWidget/example/controlPanel.html, Sources/Widgets/Widgets3D/AngleWidget/example/index.js, Sources/Widgets/Widgets3D/AngleWidget/index.js, Sources/Widgets/Widgets3D/AngleWidget/state.js
=> Add angle widget

Sources/Common/DataModel/CardinalSpline1D/index.js, Sources/Common/DataModel/KochanekSpline1D/index.js, Sources/Common/DataModel/Spline1D/index.js, Sources/Common/DataModel/Spline3D/Constants.js, Sources/Common/DataModel/Spline3D/index.js, Sources/Filters/General/LineFilter/api.md, Sources/Filters/General/LineFilter/index.js, Sources/Filters/General/PaintFilter/PaintFilter.worker.js, Sources/Filters/General/PaintFilter/index.js, Sources/Filters/General/TriangleFilter/index.js, Sources/Filters/General/TubeFilter/index.js, Sources/Widgets/Representations/SplineContextRepresentation/index.js, Sources/Widgets/Widgets3D/PaintWidget/example/controlPanel.html, Sources/Widgets/Widgets3D/PaintWidget/example/index.js, Sources/Widgets/Widgets3D/SplineWidget/behavior.js, Sources/Widgets/Widgets3D/SplineWidget/example/controlPanel.html, Sources/Widgets/Widgets3D/SplineWidget/example/index.js, Sources/Widgets/Widgets3D/SplineWidget/index.js, Sources/Widgets/Widgets3D/SplineWidget/state.js
=> Polygon painting

Sources/Common/Core/Base64/index.js, Sources/IO/Core/DataAccessHelper/HtmlDataAccessHelper.js, Sources/IO/Core/Serializer/ArraySerializer.js, Sources/IO/Core/Serializer/FieldDataSerializer.js, Sources/IO/Core/Serializer/ImageDataSerializer.js, Sources/IO/Core/Serializer/PolyDataSerializer.js, Sources/IO/Core/Serializer/index.js, Sources/IO/Core/ZipMultiDataSetReader/index.js, Sources/IO/Core/ZipMultiDataSetWriter/index.js, Sources/IO/XML/XMLReader/index.js, Sources/Rendering/Misc/SynchronizableRenderWindow/index.js, Sources/macro.js, package-lock.json, package.json
DO NOT MERGE
Need to finish it up first but don't want to forget about it...
=> Travel contrib

Sources/Common/Core/Base64/index.js
Fixes #1173
Two issues:
- condition "remain === 1" didn't increment charIndex
- the original base64-js dependency parsed "=" chars in the middle of a base64 string as null chars, but treated the ending "=" chars as actual padding to be discarded. Very strange.
Remove license since it turns out that I mis-attributed the source code.
=> Fixes base64 implementation

Sources/Rendering/Core/PixelSpaceCallbackMapper/index.js, Sources/Widgets/Core/StateBuilder/index.js, Sources/Widgets/Core/WidgetManager/index.js, Sources/Widgets/SVG/SVGLandmarkRepresentation/index.js, Sources/Widgets/SVG/SVGRepresentation/index.js, Sources/Widgets/Widgets3D/PolyLineWidget/index.js
DO NOT MERGE
To make sure I don't forget so I could finish it someday
=> Svg overlay widget

Sources/Common/Core/Math/index.js, Sources/Interaction/Widgets/PiecewiseGaussianWidget/ComputeHistogram.worker.js, Sources/Interaction/Widgets/PiecewiseGaussianWidget/index.js
To test inside glance by just swap vtk.js.
=> Piecewise widget update

Sources/Common/Core/Math/index.js, Sources/Common/DataModel/BoundingBox/index.js, Sources/Common/DataModel/ImageData/index.js, Sources/Common/DataModel/Sphere/index.js, Sources/Interaction/Widgets/LabelRepresentation/Constants.js, Sources/Interaction/Widgets/LabelRepresentation/index.js, Sources/Interaction/Widgets/LabelWidget/example/index.js, Sources/Widgets/Representations/CircleContextRepresentation/index.js, Sources/Widgets/Representations/RectangleContextRepresentation/index.js, Sources/Widgets/Widgets3D/EllipseWidget/behavior.js, Sources/Widgets/Widgets3D/EllipseWidget/index.js, Sources/Widgets/Widgets3D/EllipseWidget/state.js, Sources/Widgets/Widgets3D/PaintWidget/example/controlPanel.html, Sources/Widgets/Widgets3D/PaintWidget/example/index.js, Sources/Widgets/Widgets3D/RectangleWidget/behavior.js, Sources/Widgets/Widgets3D/RectangleWidget/index.js, Sources/Widgets/Widgets3D/RectangleWidget/state.js, Sources/Widgets/Widgets3D/ShapeWidget/Constants.js, Sources/Widgets/Widgets3D/ShapeWidget/behavior.js, Sources/Widgets/Widgets3D/ShapeWidget/example/controlPanel.html, Sources/Widgets/Widgets3D/ShapeWidget/example/index.js, Sources/Widgets/Widgets3D/ShapeWidget/index.js
=>  feat(ShapeWidget): Add text labeling to ShapeWidget

Sources/Rendering/OpenGL/RenderWindow/index.js
=> fix(OpenGLRenderWindow): Pass in options

Sources/Interaction/Manipulators/MouseRangeManipulator/index.js, Sources/Rendering/OpenGL/RenderWindow/index.js
=> Better size handling

Utilities/ci/azure-pipelines.yml
@thewtex @jourdain This is a PR to see if I can fix the azure failures.
=> Fix Azure pipeline

Sources/Rendering/Core/Renderer/index.js
@agirault for finding this issue
=> fix(Renderer): Clear actors/volumes array when removing all

Sources/Rendering/Core/CellPicker/example/index.js
Also fixed small error in comment.
As discussed in https://discourse.vtk.org/t/cellpicker-example-glitch/1852/4
=> docs(CellPicker example): Put tolerance of CellPicker in example on 0

Sources/Rendering/Core/Camera/api.md, Sources/Rendering/Core/Camera/index.js
Add unimplemented functions, both matching vtk c++ function and a new thickness function that seems more useful. Also update docs for clarity and style.
#Hacktober
=> feat(Camera): add Thickness functions

Sources/Filters/General/PaintFilter/index.js
While deriving a class from vtkPaintFilter to add new operations, users can not access the history variable, which stops them from being able to use undo/redo functionality in their new operations.
This exposes the filter's history to child classes.
=> feat(PaintFilter): improve and factorize PaintFilter's labelMap modification methods

Sources/Common/DataModel/ITKHelper/index.js
Following up on https://github.com/InsightSoftwareConsortium/itk-js/issues/260
This merge request adds a convertVtkToItkImage function to ITKHelper. It also brings a minor change to convertItkToVtkImage to use the ITKPixelTypes enum instead of integers.
=> feat(ITKHelper): Add convertVtkToItkImage

Sources/IO/Misc/ITKPolyDataReader/index.js, Sources/IO/Misc/index.js
Enables reading files as vtk.js PolyData via VTK C++, e.g. .vtu
XML vtkUnstructuredGrid or binary .vtp XML vtkPolyData files.
=> feat(IO): Add vtkITKPolyDataReader

Sources/Rendering/OpenGL/PolyDataMapper/index.js
Always update MCVC/MCDC uniform matrices to make sure that inverseShiftAndScale matrix values are correct.
Currrently, view matrices in vtk.js are only updated in case of camera or actor changes.
With the introduction of coordinate shifting/scaling to the mapper, it is now necessary to properly update view matrices before each draw call, because inverse shift/scale matrices can be different for each CellArrayBufferObject and affect the value of the MCVC/MCDC matrices. Not doing so could result in incorrect rendering when modifying the mapper's input geometry, or rendering multiple objects.
For reference, this is similar to the way things are done in VTK's vtkOpenGLPolyDataMapper.
This fixes current issues with the LineWidget and HandleWidget examples.
=> fix(vtkOpenGLPolyDataMapper): Always update MCVC/MCDC uniform matrices

Sources/Proxy/Core/ViewProxy/index.js
Add an animatable moveCamera() function to the 3D view proxy that allows the camera to change to any focal point, position, and view point. This function was based upon the updateOrientation() function above it.
=> feat(ViewProxy): Add generic animatable moveCamera() function

Documentation/content/docs/develop_widget.md, Documentation/tpl/__sidebar__
=> doc(Widgets): Add Widgets development documentation

Sources/Widgets/Core/WidgetManager/index.js
This modifies the parent element to be a positioned element. Hopefully
this does not interfere with apps that require the containing element to
be non-positioned.
The key updates are in the function `enableSvgLayer()`. Most everything else is a refactoring to remove unnecessary elements.
Fixes #1277, except for the cursor not updating.
=> fix(WidgetManager): Correct svg layer positioning

Documentation/content/docs/develop_widget.md, Documentation/tpl/__en__
=> doc(develop_widget): Add title

Sources/Common/Core/MatrixBuilder/index.js, Sources/Common/Core/MatrixBuilder/test/testMatrixBuilder.js, Sources/tests.js
=> fix(MatrixBuilder): Incorrect construction of rotation axis

Documentation/content/docs/tutorial.md, Documentation/tpl/__en__, Documentation/tpl/__sidebar__
=> doc(tutorials): Add reference to the tutorials

Sources/Widgets/Core/StateBuilder/boundsMixin.js
=> fix(boundsMixin): Place bounds at origin before scaling

Sources/Common/Core/LookupTable/index.js
Also support setting and getting individual table values.
Fixes #1257
=> LookupTable: Support setting table in constructor

Sources/Rendering/OpenGL/Framebuffer/index.js, Sources/Rendering/OpenGL/HardwareSelector/example/index.js, Sources/Rendering/OpenGL/HardwareSelector/index.js, Sources/Rendering/OpenGL/HardwareSelector/test/testHardwareSelector.js, Sources/Rendering/OpenGL/PolyDataMapper/index.js
If selector.captureZValues is set to true in the
HardwareSelector then a selection will include both
displayPosition and worldPosition values of the selection.
Where multiple pixels are selected the closest pixel is
used. That is, the pixel closest to the front clipping plane.
=> feat(Picking): Support returning coordinates of

Documentation/content/docs/index.md, README.md
Provides a citation for referencing a specific version of the software. The DOI and citation
content is automatically updated on release by Zenodo.
=> doc(Citation): Add Zenodo DOI badge

Documentation/content/docs/develop_widget.md
Adds some docs for mixins. Specifically meant to clarify the colorMixin.
=> docs(widgets): Add initial mixin docs

Sources/Interaction/Manipulators/MouseCameraTrackballZoomToMouseManipulator/index.js, Sources/Interaction/Style/InteractorStyleManipulator/example/controller.html, Sources/Interaction/Style/InteractorStyleManipulator/index.js
Adds a way to use the ZoomToMouseManipulator with the scroll wheel.
=> feat(Interaction): add mouse position for scroll

Sources/macro.js
Cleanup some copy-and-paste cruft.
=> refactor(macro): Remove unused keystore parameters

Sources/Filters/General/index.js
=> fix(Filters): Correctly export two filters

Sources/Rendering/Core/ColorTransferFunction/api.md, Sources/Rendering/Core/ColorTransferFunction/index.js
=> feat(vtkColorTransferFunction): Add discretize option

Sources/IO/Geometry/DracoReader/example/index.js, Sources/IO/Geometry/DracoReader/index.js
Added the option to use the DracoReader with dracos WASMLoader instead of the javascript decoder.
That improves the decoding performance.
=> feat(DracoReader): Added WASM decoder

Examples/Volume/TestVolumeTypes/controlPanel.html, Examples/Volume/TestVolumeTypes/index.js, Sources/Filters/General/ImageOutlineFilter/example/index.js, Sources/IO/Geometry/DracoReader/example/index.js, Sources/Proxy/Representations/SliceRepresentationProxy/index.js, Sources/Rendering/Core/ImageMapper/example/index.js, Sources/Rendering/Core/ImageProperty/api.md, Sources/Rendering/Core/ImageProperty/index.js, Sources/Rendering/Core/Volume/api.md, Sources/Rendering/Core/VolumeProperty/index.js, Sources/Rendering/OpenGL/ImageMapper/index.js, Sources/Rendering/OpenGL/Texture/index.js, Sources/Rendering/OpenGL/VolumeMapper/index.js, Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl, Sources/Widgets/Widgets3D/PaintWidget/example/index.js
@martinken not quite ready, but comments welcome.
=> multi-component image slice rendering

Examples/Volume/TestVolumeTypes/index.js, Sources/Rendering/OpenGL/ImageMapper/index.js
Remove console log statement accidentally left in by #1326
=> chore(cleanup): Remove debug print statements

Sources/Rendering/OpenGL/ImageMapper/index.js
If no piecewise function is specified for a given component, fill with the max value as a default.
=> fix(ImageMapper): Provide reasonable default if no function

Sources/Rendering/Core/ImageMapper/api.md, Sources/Rendering/Core/ImageMapper/index.js, Sources/Rendering/Core/Mapper/CoincidentTopologyHelper.js, Sources/Rendering/Core/Mapper/index.js, Sources/Rendering/OpenGL/ImageMapper/index.js, Sources/Rendering/OpenGL/PolyDataMapper/index.js, Sources/Rendering/OpenGL/ReplacementShaderMapper/index.js
re #1377, this is the proposed implementation.
@finetjul fyi
=> feat(vtkImageMapper): support coincident topology

Sources/Rendering/Core/Prop3D/index.js
Implement the function setOrientation to take into account an initial orientation of vtkProp3D objects
=> feat(Prop3D): add setOrientation function

Sources/Common/DataModel/Box/index.js, Sources/Common/DataModel/Box/test/testBox.js
Add a static function intersectPlane for vtkBox , the code is borrowed from C++ version
=> feat(Box): Add intersectPlane for vtkBox

Sources/Rendering/Core/Coordinate/api.md
=> docs(Coordinate): fix typo

Sources/macro.js
=> fix(macro): return false in setArray if new array brings no change

Sources/Common/DataModel/PolyData/index.js, Sources/Common/DataModel/PolyData/test/testPolyData.js
Fix getCellPoints when polydata is made of multiple cell types
fix #1455
=> fix(polydata): fix getCellPoints

Sources/Common/Core/Math/index.js, Sources/Imaging/Core/ImageReslice/index.js, Sources/Widgets/Core/WidgetManager/Constants.js, Sources/Widgets/Representations/ResliceCursorContextRepresentation/Constants.js, Sources/Widgets/Representations/ResliceCursorContextRepresentation/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/helpers.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/state.js
=> Reslice cursor new widget architecture

Sources/Common/DataModel/Spline3D/index.js, Sources/Widgets/Representations/SplineContextRepresentation/index.js, Sources/Widgets/Widgets3D/SplineWidget/example/controlPanel.html, Sources/Widgets/Widgets3D/SplineWidget/example/index.js, Sources/Widgets/Widgets3D/SplineWidget/state.js
Fixes #1479
Shown in the `SplineWidget` example:
=> Fix cardinal spline

.github/workflows/actions.yml
Need to trigger github actions on pull requests as well. PRs that were from forks weren't triggering checks...
=> chore(github): Run checks against pull requests

Sources/Widgets/Representations/ResliceCursorContextRepresentation/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/api.md, Sources/Widgets/Widgets3D/ResliceCursorWidget/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/state.js
=> feat(ResliceCursorWidget): Add options to enable/disable rotations

Sources/Widgets/Representations/ResliceCursorContextRepresentation/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/api.md, Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/state.js
=> feat(ResliceCursorWidget): Add possibility to user to manually set center

Sources/Widgets/Representations/ResliceCursorContextRepresentation/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/api.md, Sources/Widgets/Widgets3D/ResliceCursorWidget/state.js
=> feat(ResliceCursorWidget): Add the possibility to hide the actor's center

Sources/Interaction/Widgets/PiecewiseGaussianWidget/index.js
=> Piecewise gaussian tweaks

Sources/Widgets/Core/StateBuilder/index.js, Sources/Widgets/Core/StateBuilder/textMixin.js
For use with SVG representations.
=> fix(StateBuilder): Add textMixin

Sources/Widgets/Core/WidgetManager/index.js
Renders can be out of order if Promise.all receives an empty array.
Some thoughts: Ideally we wouldn't use vtkPixelSpaceCallbackMapper and just synchronously compute world-to-display, so we wouldn't have to deal with promise chains just for SVG renders (and this wouldn't be a bug anymore). However, that could incur many unnecessary renders since this approach tosses out any previously started renders from a given render, since those are invalidated anyways by the current render.
=> fix(WidgetManager): Ignore previous renders

Sources/IO/Core/DataAccessHelper/HttpDataAccessHelper.js
This PR adds an option for HttpDataAccessHelper for setting headers on a request.
=> feat(HttpDataAccessHelper): Support setting headers

Sources/Filters/Core/Cutter/index.js
Adds cutting of triangle strips.
=> fix(Cutter): Cut triangle strips

Sources/IO/Geometry/STLReader/index.js
SolidWorks outputs binary STLs with "solid" in the header, which
triggers a false positive on detecting binary vs ascii STL files.
This fix checks the size of the STL file against the number of triangles + header. It is improbable that an ASCII STL file would ever trigger a false-positive for the binary test. See here: https://stackoverflow.com/questions/7377954/how-to-detect-that-this-is-a-valid-valid-binary-stlstereolithography-file
Fixes #1559
=> fix(STLReader): Use a different binary STL heuristic

Sources/Rendering/Core/RenderWindowInteractor/index.js
Before, when pressing two buttons, releasing one button would cause the
listener for the other button to also be removed, since the code assumed
only one button press at a time.
This should allow multiple buttons to be pressed, without unhooking the listener prematurely.
Fixes https://github.com/Kitware/paraview-glance/issues/366
=> fix(RenderWindowInteractor): Handle simultaneous button events

Sources/Proxy/Representations/SliceRepresentationProxy/index.js
Previously, when passing in a slicing mode to the constructor, the
mapper would not be updated because model.slicingMode is already set.
=> fix(SliceRepresentationProxy): Update slicing mode

Sources/Widgets/Widgets3D/ResliceCursorWidget/api.md, Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/state.js
=> improvement(reslicecursorwidget): allow to keep orthogonality when rotating

Sources/Proxy/Representations/VolumeRepresentationProxy/index.js
The volume mapper does not support rendering single-slice volumes. When loading these volumes with the vtkVolumeRepresentationProxy, this causes artifacts to be shown, but not the actual volume.
This is a problem in Paraview-Glance especially, as loading a scene exported from ParaView's slice representation doesn't show the expected result.
This MR adds a tweak to vtkVolumeRepresentationProxy to make sure that we don't enable the volume mapper when rendering such volumes, but instead enable the slice actors.
Example volume: 
[singleSlice.vtkjs.zip](https://github.com/Kitware/vtk-js/files/5393173/singleSlice.vtkjs.zip)
=> feat(vtkVolumeRepresentationProxy): Disable volume rendering with 2D volumes

Sources/Widgets/Widgets3D/ResliceCursorWidget/Constants.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/api.md, Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/helpers.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/state.js
=> improvement(reslicecursorwidget): add mouse scrolling to move slice

Documentation/content/examples/index.md, Examples/Geometry/TimeSeries/controller.html, Examples/Geometry/TimeSeries/index.js, Sources/IO/XML/XMLPolyDataReader/index.js, Sources/IO/XML/XMLReader/index.js
vtkXMLPolyDataReader now parses FieldData and stores it in output polydata.
One note: field data array references are shared across all polydata pieces generated from a single vtp file.
=> Vtp field data

Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/index.js
- Fix rendering when volume origin is not [0, 0, 0]
- Setup te correct camera's view up on sagittal view
@finetjul
=> Fix reslice cursor

Sources/Widgets/Core/WidgetManager/Constants.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/helpers.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/index.js
Remove medical meaning to variable names.
BREAKING CHANGE: Rename of ViewTypes
=> refactor(reslicecursor): rename reslice cursor view types

Documentation/content/docs/tutorial.md, Documentation/tpl/__en__
~I'm adding the webinar commit prior to moving vtk.js to v15~ @jourdain @finetjul 
EDIT: This can merge whenever
=> docs(tutorials): Add webinar to tutorials section

Sources/IO/Geometry/PLYReader/example/index.js, Sources/IO/Geometry/PLYReader/index.js, Sources/IO/Geometry/index.js
Add support for loading PLY file format using PLYReader
#1554
=> feat(plyreader): add support for PLY files

Sources/IO/Geometry/PLYReader/index.js
Correctly set PLY normals in the vtkDataArray
fix #1649
=> fix(plyreader): fix PLY normals parsing

Sources/Common/Core/Math/index.js, Sources/Common/Core/Math/test/testMath.js, Sources/Common/Core/MatrixBuilder/index.js, Sources/Interaction/Widgets/ResliceCursor/ResliceCursorLineRepresentation/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js, Sources/tests.js
=> fix(vtkmath): fix RotateVector function

Utilities/config/rules-vtk.js
=> fix(rules-vtk): Typo in no-fallback

Utilities/config/dependency.js
=> fix(dependency): postcss-loader options object

Sources/IO/Core/HttpSceneLoader/index.js
Import more properties, color transfer functions and opacity piecewise functions
Paraview scene before export:
vtk-js after import:
=> feat(vtkhttpsceneloader): import additional volumeProperty values

Sources/Widgets/Widgets3D/ResliceCursorWidget/state.js
When creating more than one vtkResliceCursorWidget, the AxisStates of vtkResliceCursorWidget are
shared with each other.
=> fix(vtkreslicecursorwidget): axisStates are shared

Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js
=> fix(reslicecursorwidget): fix first scrolling to update display image

Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js
Setup the updateMethodName when scrolling (mouse click + move and mouse scrolling) in order to be consistent.
The user can need this out of the Reslice Cursor Widget.
@finetjul
=> fix(ResliceCursorWidget): setup correct updateMethodName when scrolling

Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js
=> fix(ResliceCursorWidget): Correct reslice cursor interactions

Sources/Widgets/Widgets3D/ResliceCursorWidget/Constants.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/state.js
Fix the view up in order to fit with Slicer
@finetjul
=> fix(ResliceCursorWidget): Setup correct viewUp for Z view

Sources/Rendering/Core/ColorTransferFunction/index.js
This fixes an incorrect call to hsv2rgb.
=> fix(ColorTransferFunction): Typo on hsv2rgb call

Sources/IO/Core/HttpSceneLoader/index.js
=> fix(httpsceneloader): properly handle .vtkjs files with no actor

Sources/Interaction/Widgets/ResliceCursor/ResliceCursorLineRepresentation/index.js, Sources/Interaction/Widgets/ResliceCursor/ResliceCursorRepresentation/index.js, Sources/Interaction/Widgets/ResliceCursor/example/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js
Correct first reslice cursor visualization
@finetjul
=> Fix initial reslice cursor

Sources/Rendering/OpenGL/VolumeMapper/index.js
Hi everyone,
We've been evaluating the rendering performance in some soon-to-be-public work on top of VTK.js. One of the odd things that came up is that inside the ShaderCache, the md5 hash of the combined vertex, fragment, and geometry shaders is used as the key to avoid the creation of duplicate programs.
That all sounds fine in theory, but it appears that for things like the VolumeMapper, this md5 hash call was very slow, upwards of 5 milliseconds. We are using multiple VTK.js viewports and noticed that these md5 calls were over 50% of the entire CPU time during the rendering. With this change we have dramatically improved performance in our examples (7 viewports synced with volume mappers), but I think it will improve performance in general.
So we thought about maybe replacing the md5 …
=> fix(VolumeMapper): Avoid unnecessary recreation of the shader when the actor changes

Sources/IO/Core/DataAccessHelper/JSZipDataAccessHelper.js, Sources/IO/Core/HttpSceneLoader/index.js, Sources/Interaction/Animations/TimeStepBasedAnimationHandler/example/controller.html, Sources/Interaction/Animations/TimeStepBasedAnimationHandler/example/index.js, Sources/Interaction/Animations/TimeStepBasedAnimationHandler/index.js
- ~~Waiting on series reader: https://github.com/Kitware/vtk-js/pull/1665~~
- ~~Integrate the series reader~~ 
- ~~Waiting on JSZip fix~~
- ~~Waiting on Paraview Changes: https://gitlab.kitware.com/paraview/paraview/-/merge_requests/4628~~
- ~~Needs some cleanup~~
Questions:
- ~~I'm not sure what directory makes more sense than Rendering~~
=> Add timestep-based animation handler for the scene loader

package.json, rollup.config.js
- Move loaders out of regular deps
- Use char classes for path seps in regex
Fixes a vtk.js beta build issue.
=> Fix bad es build

Sources/IO/XML/XMLWriter/index.js, package-lock.json, package.json, rollup.config.js
- Updates to xmlbuilder2
JSZip-related code should still work (only tested reading), and xmlbuilder-related code now works.
=> More fixes for the ES build

Sources/Imaging/Core/ImageReslice/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/example/controlPanel.html, Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js
To create slab in ImageResclie, getCompositeFunc was implemented by referring to vtkGetCompositeFunc implemented in [VTK C++ Implementation](https://github.com/Kitware/VTK/blob/master/Imaging/Core/vtkImageReslice.cxx#L1555).
=> feat(vtkimagereslice): create a slab in image reslice

rollup.config.js
This inlines webworkers instead of making a network request. @jourdain
=> fix(rollup): Inline webworkers

Sources/Widgets/Widgets3D/EllipseWidget/behavior.js, Sources/Widgets/Widgets3D/PaintWidget/example/controlPanel.html, Sources/Widgets/Widgets3D/PaintWidget/example/index.js, Sources/Widgets/Widgets3D/ShapeWidget/behavior.js, Sources/Widgets/Widgets3D/ShapeWidget/example/controlPanel.html, Sources/Widgets/Widgets3D/ShapeWidget/example/index.js, Sources/Widgets/Widgets3D/SplineWidget/behavior.js
Add manipulator data update from shapeWidget example, add visibility update for widgets that are not on slice.
Debug painting tool for paintWidget example when it uses shapeWidget data.
=> fix(ShapeWidget & SplineWidget): place widget correctly on ImageSlice

Sources/Rendering/OpenGL/PolyDataMapper/index.js
This commit add support for backface property when provided
fix #1545
=> feat(polydatamapper): add support for backface property

Sources/Common/Core/Math/api.md, Sources/Common/Core/Math/index.js, Sources/Common/Core/Math/test/testMath.js, Sources/Common/Core/MatrixBuilder/index.js, Sources/Common/DataModel/Plane/api.md, Sources/Common/DataModel/Plane/index.js, Sources/Filters/Sources/PlaneSource/index.js, Sources/Widgets/Representations/ResliceCursorContextRepresentation/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/Constants.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/api.md, Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/helpers.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/state.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/test/testHelper.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/test/testMultipleRotationPlanes.js, Sources/tests.js
Add a method which allows developpers to rotate specific plane
around specific plane normal (which should be X, Y or Z, not a defined rotated axis)
Also add a test to avoid regression on viewup computation
=> feat(ResliceCursorWidget): Add possibility to programmatically rotate axis

Sources/IO/Geometry/PLYReader/index.js
=> fix(plyreader): fix header length computation of the PLYReader

Sources/Rendering/Core/SurfaceLICInterface/Constants.js, Sources/Rendering/Core/SurfaceLICInterface/index.js, Sources/Rendering/Core/SurfaceLICMapper/index.js, Sources/Rendering/OpenGL/SurfaceLIC/LineIntegralConvolution2D/index.js, Sources/Rendering/OpenGL/SurfaceLIC/LineIntegralConvolution2D/pingpong.js, Sources/Rendering/OpenGL/SurfaceLIC/SurfaceLICInterface/index.js, Sources/Rendering/OpenGL/SurfaceLIC/SurfaceLICMapper/example/controller.html, Sources/Rendering/OpenGL/SurfaceLIC/SurfaceLICMapper/example/index.js, Sources/Rendering/OpenGL/SurfaceLIC/SurfaceLICMapper/index.js, Sources/Rendering/OpenGL/SurfaceLIC/glsl/vtkLineIntegralConvolution2D_AAH.glsl, Sources/Rendering/OpenGL/SurfaceLIC/glsl/vtkLineIntegralConvolution2D_AAV.glsl, Sources/Rendering/OpenGL/SurfaceLIC/glsl/vtkLineIntegralConvolution2D_CE.glsl, Sources/Rendering/OpenGL/SurfaceLIC/glsl/vtkLineIntegralConvolution2D_EE.glsl, Sources/Rendering/OpenGL/SurfaceLIC/glsl/vtkLineIntegralConvolution2D_LIC0.glsl, Sources/Rendering/OpenGL/SurfaceLIC/glsl/vtkLineIntegralConvolution2D_LICI.glsl, Sources/Rendering/OpenGL/SurfaceLIC/glsl/vtkLineIntegralConvolution2D_LICN.glsl, Sources/Rendering/OpenGL/SurfaceLIC/glsl/vtkLineIntegralConvolution2D_SC.glsl, Sources/Rendering/OpenGL/SurfaceLIC/glsl/vtkLineIntegralConvolution2D_VT.glsl, Sources/Rendering/OpenGL/SurfaceLIC/glsl/vtkLineIntegralConvolution2D_quadVS.glsl, Sources/Rendering/OpenGL/SurfaceLIC/glsl/vtkSurfaceLICInterface_CE.glsl, Sources/Rendering/OpenGL/SurfaceLIC/glsl/vtkSurfaceLICInterface_DCpy.glsl, Sources/Rendering/OpenGL/SurfaceLIC/index.js, Sources/Rendering/OpenGL/ViewNodeFactory/index.js
This is a port of the VTK Surface LIC implementation to vtk-js.
Screenshot of the example:
=> Add Surface LIC mapper

Sources/Interaction/Widgets/PiecewiseGaussianWidget/index.js
The nifty Piecewise Gaussian Widget abandons web worker instances with each call to `setDataArray`
=> fix(piecewisegaussianwidget): terminate leaking histogram web workers

Sources/Rendering/WebGPU/Actor/index.js, Sources/Rendering/WebGPU/BufferManager/Constants.js, Sources/Rendering/WebGPU/BufferManager/index.js, Sources/Rendering/WebGPU/Device/index.js, Sources/Rendering/WebGPU/Pipeline/index.js, Sources/Rendering/WebGPU/PolyDataMapper/index.js, Sources/Rendering/WebGPU/Sampler/index.js, Sources/Rendering/WebGPU/SwapChain/index.js, Sources/Rendering/WebGPU/Texture/index.js, Sources/Rendering/WebGPU/TextureManager/index.js, Sources/Rendering/WebGPU/TextureView/index.js, Sources/Rendering/WebGPU/VertexInput/index.js
Can now do interpolatebefore using textures
and can handle simple textue mapping cases.
Adjusted caches to use WeakMaps
=> feat(WebGPU): add some support for texture mapping

Sources/Rendering/OpenGL/CellArrayBufferObject/index.js, Sources/Rendering/WebGPU/Actor/api.md, Sources/Rendering/WebGPU/BufferManager/index.js, Sources/Rendering/WebGPU/Pipeline/index.js, Sources/Rendering/WebGPU/PolyDataMapper/index.js, Sources/Rendering/WebGPU/TextureManager/index.js, Sources/Rendering/WebGPU/index.js
WebGPU should now handle
- cellScalar coloring
- wireframe and point representations
Fix an issue with degeerate cell rendering in both WebGPU and WebGL
re https://github.com/Kitware/vtk-js/issues/1777
=> feat(WebGPU): support for wireframe, point and cellData

Sources/Rendering/WebGPU/PolyDataMapper/index.js, Sources/Rendering/WebGPU/README.md
fix lines and poits without normals
add Readme file that was missed in prior commits
=> fix(WebGPU): fix non lighted geometry

Sources/Interaction/Widgets/LabelRepresentation/index.js
had some shared objects that needed ot be moved out
=> fix(Widgets): fix an issue with shared default objects

Sources/Widgets/Core/WidgetManager/vdom.js, Sources/Widgets/Representations/PolyLineRepresentation/index.js, Sources/Widgets/SVG/SVGLandmarkRepresentation/index.js, Sources/Widgets/SVG/SVGRepresentation/index.js, Sources/Widgets/Widgets3D/LineWidget/behavior.js, Sources/Widgets/Widgets3D/LineWidget/index.js, Sources/Widgets/Widgets3D/LineWidget/state.js
=> feat(linewidget): enlarge line and make it draggable

Sources/Rendering/Core/CubeAxesActor/index.js, Sources/Rendering/OpenGL/ForwardPass/index.js, Sources/Rendering/OpenGL/HardwareSelector/index.js, Sources/Rendering/OpenGL/PixelSpaceCallbackMapper/index.js, Sources/Rendering/WebGPU/ForwardPass/index.js, Sources/Rendering/WebGPU/Pipeline/index.js, Sources/Rendering/WebGPU/PixelSpaceCallbackMapper/index.js, Sources/Rendering/WebGPU/PolyDataMapper/index.js, Sources/Rendering/WebGPU/Texture/index.js, Sources/Rendering/WebGPU/TextureManager/index.js, Sources/Rendering/WebGPU/VertexInput/index.js, Sources/Rendering/WebGPU/ViewNodeFactory/index.js
- It was recomputing the text atlas far too often
basically every camera change as when the camera changes it
was calling update with the camera as an argument which
made the force argument true.
- It was redrawing the grid lines twice every time
- Exposed an issue with missing default value for lastAspectRatio
- Now works with WebGPU
- minor updates to WebGPU due to recent changes in the spec
- added a faceVisibilityAngle where you can specify what angle
a face must be towards the viewer before it is visibile. Defaults
to 8 degrees.
=> fix(CubeAxes): various fixes to CubeAxesActor

Sources/Common/DataModel/Cell/index.d.ts, Sources/Common/DataModel/DataSet/index.d.ts, Sources/Common/DataModel/PointSet/index.d.ts, Sources/Common/DataModel/PolyData/index.d.ts, Sources/Filters/Sources/Arrow2DSource/index.d.ts, Sources/Filters/Sources/ArrowSource/index.d.ts, Sources/Filters/Sources/CircleSource/index.d.ts, Sources/Filters/Sources/ConeSource/index.d.ts, Sources/Filters/Sources/CubeSource/index.d.ts, Sources/Filters/Sources/Cursor3D/index.d.ts, Sources/Filters/Sources/CylinderSource/index.d.ts, Sources/Filters/Sources/LineSource/index.d.ts, Sources/Filters/Sources/PlaneSource/index.d.ts, Sources/Filters/Sources/PointSource/index.d.ts, Sources/Filters/Sources/SphereSource/index.d.ts
Add more typescript definitions
fix #466
=> docs(ts): add more typescript definitions

.github/FUNDING.yml, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
This will allow to streamline the dev process and collects more infos from users when reporting issues or questions
=> chore(github): Use github templates for issues and PRs

Sources/Widgets/Widgets3D/index.js
=> build(reslicecursorwidget): export ResliceCursorWidget to unpkg

Sources/Imaging/Core/AbstractImageInterpolator/index.js, Sources/Imaging/Core/ImageReslice/index.js
=> build(imagereslice): export SlabMode to unpkg

Sources/IO/Geometry/PLYReader/example/index.js, Sources/IO/Geometry/PLYReader/index.js
For PLY file with face texture, currently vtk.js cannot support the texture coordinates.
I add basic support to convert face texture to points texture.
=> feat(PLYReader): add basic support for face texture

Sources/Rendering/WebGPU/PolyDataMapper/index.js
Turn of lighting on non-surfaces to match OpenGL
=> feat(WebGPU): add support for backfacing polygons

Examples/Applications/GeometryViewer/index.js, Sources/Rendering/Core/CubeAxesActor/index.js, Sources/Rendering/Core/ScalarBarActor/index.js
Add a scalar bar actor that when given a scalarToColors
instance (or subclass such as lookuptable) will draw
an annotation showing the colors, and ranges of the data.
Also draws a title as specified by the user.
If automated is true then it will try to scale and position
itself automatically to look nice.
=> feat(ScalarBar): add ScalarBarActor

Sources/Rendering/Core/RenderWindowInteractor/index.d.ts, Sources/Rendering/Core/RenderWindowInteractor/index.js
This provide the first render in the callback of interactor as well. As some actions should be performed on that specific renderer in the style.
=> Interactor first renderer

Sources/IO/Geometry/PLYReader/index.js
This pull request fixes a regression that can prevent the rendering of PLY.
=> fix(plyreader): fix regression caused by face texture support

Sources/IO/Core/HttpDataSetSeriesReader/index.js, Sources/IO/Core/HttpSceneLoader/index.js, Sources/Interaction/Animations/TimeStepBasedAnimationHandler/index.js, Sources/Proxy/Animation/AbstractAnimationProxy/index.js, Sources/Proxy/Animation/AnimationProxyManager/example/controller.html, Sources/Proxy/Animation/AnimationProxyManager/example/index.js, Sources/Proxy/Animation/AnimationProxyManager/example/proxyConfiguration.js, Sources/Proxy/Animation/AnimationProxyManager/index.js, Sources/Proxy/Animation/TimeStepBasedAnimationHandlerProxy/index.js
An implementation of animations in the proxy system, with support for the vtkTimeStepBasedAnimationHandler.
The goal is integration into Paraview Glance.
=> feat(animationproxymanager): add animation manager, and animation proxies

Sources/Rendering/OpenGL/RenderWindow/index.js, Sources/Rendering/SceneGraph/RenderWindowViewNode/index.js, Sources/Rendering/WebGPU/RenderWindow/index.js
Move common code from api specific render windows into
a common superclass. A prep stage to making a more
general hardware selector api.
=> chore(Rendering): clean some common code

Sources/Widgets/Widgets3D/index.js
=> feat(widgets): Add widgets to package

Sources/Common/DataModel/Plane/index.d.ts, Sources/Filters/Sources/PlaneSource/index.d.ts, Sources/Filters/Texture/TextureMapToPlane/index.d.ts, Sources/Filters/Texture/TextureMapToSphere/index.d.ts, Sources/IO/Misc/ElevationReader/index.d.ts, Sources/IO/Misc/JSONReader/index.d.ts, Sources/IO/Misc/MTLReader/index.d.ts, Sources/IO/Misc/OBJReader/index.d.ts, Sources/IO/Misc/PDBReader/index.d.ts
Add more typescript definitions for Filters & IO
=> docs(ts): add more typescript definitions for Filters and IO

Sources/Rendering/WebGPU/Camera/api.md, Sources/Rendering/WebGPU/Camera/index.js, Sources/Rendering/WebGPU/ForwardPass/index.js, Sources/Rendering/WebGPU/FullScreenQuad/index.js, Sources/Rendering/WebGPU/OrderIndependentTranslucentPass/index.js, Sources/Rendering/WebGPU/PolyDataMapper/index.js, Sources/Rendering/WebGPU/README.md, Sources/Rendering/WebGPU/RenderEncoder/index.js, Sources/Rendering/WebGPU/Renderer/index.js, Sources/Rendering/WebGPU/ShaderDescription/index.js, Sources/Rendering/WebGPU/ShaderModule/index.js, Sources/Rendering/WebGPU/Texture/index.js, Sources/Rendering/WebGPU/TextureManager/index.js, Sources/Rendering/WebGPU/UniformBuffer/index.js, Sources/Rendering/WebGPU/VertexInput/index.js, Sources/Rendering/WebGPU/ViewNodeFactory/index.js, Sources/Rendering/WebGPU/Volume/api.md, Sources/Rendering/WebGPU/Volume/index.js, Sources/Rendering/WebGPU/VolumeMapper/api.md, Sources/Rendering/WebGPU/VolumeMapper/index.js, Sources/Rendering/WebGPU/VolumePass/index.js
Add basics for single volume rendering but right now
Dawn doesn't support 3D textures so very minimal
development.
Updated to new WebGPU spec where var<in/out> is no
longer allowed. So moved everything to input and output
structures.
=> feat(WebGPU): add volumes and update to new spec

Sources/Rendering/WebGPU/BufferManager/Constants.js, Sources/Rendering/WebGPU/BufferManager/index.js, Sources/Rendering/WebGPU/Camera/index.js, Sources/Rendering/WebGPU/FullScreenQuad/index.js, Sources/Rendering/WebGPU/PolyDataMapper/index.js, Sources/Rendering/WebGPU/README.md, Sources/Rendering/WebGPU/Renderer/index.js, Sources/Rendering/WebGPU/ShaderDescription/index.js, Sources/Rendering/WebGPU/SphereMapper/index.js, Sources/Rendering/WebGPU/Texture/index.js, Sources/Rendering/WebGPU/UniformBuffer/index.js, Sources/Rendering/WebGPU/ViewNodeFactory/index.js
Also some cleanup to buffer requests, shader creation
and the rendererUBO as part of this MR.
=> feat(WebGPU): add sphere mapper support on webgpu

Sources/Rendering/WebGPU/PolyDataMapper/index.js, Sources/Rendering/WebGPU/README.md, Sources/Rendering/WebGPU/RenderWindow/index.js, Sources/Rendering/WebGPU/ShaderDescription/index.js, Sources/Rendering/WebGPU/StickMapper/index.js, Sources/Rendering/WebGPU/VertexInput/index.js, Sources/Rendering/WebGPU/ViewNodeFactory/index.js
Also fix an issue with inputs on the vertex shader
when it has both vertex inputs and builtin inputs
Add support for instancing and use it in the StickMapper
Fix an issue with removing normals when swithcing to
reps that don't use normals
=> feat(WebGPU): add stick mapper for webgpu

Sources/Rendering/WebGPU/HardwareSelectionPass/index.js, Sources/Rendering/WebGPU/Renderer/index.js
A couple old code bits that needed to be updated
=> fix(WebGPU): fix issue with hardware selector on webgpu

Sources/Interaction/Style/InteractorStyleMPRSlice/example/index.js
Fixes the interactor mpr slice example
=> docs(InteractorStyleMPRSlice): fix example

Sources/Rendering/WebGPU/OrderIndependentTranslucentPass/index.js, Sources/Rendering/WebGPU/RenderEncoder/index.js, Sources/Rendering/WebGPU/Texture/index.js
Missing required store settings in RenderEncoder
=> fix(WebGPU): fix missing values that firefox detected

Sources/Rendering/WebGPU/BufferManager/Constants.js, Sources/Rendering/WebGPU/BufferManager/index.js, Sources/Rendering/WebGPU/Device/index.js, Sources/Rendering/WebGPU/FullScreenQuad/index.js, Sources/Rendering/WebGPU/Glyph3DMapper/index.js, Sources/Rendering/WebGPU/OrderIndependentTranslucentPass/index.js, Sources/Rendering/WebGPU/PolyDataMapper/index.js, Sources/Rendering/WebGPU/README.md, Sources/Rendering/WebGPU/Renderer/index.js, Sources/Rendering/WebGPU/ShaderDescription/index.js, Sources/Rendering/WebGPU/SphereMapper/index.js, Sources/Rendering/WebGPU/StickMapper/index.js, Sources/Rendering/WebGPU/StorageBuffer/index.js, Sources/Rendering/WebGPU/Texture/index.js, Sources/Rendering/WebGPU/Types/index.js, Sources/Rendering/WebGPU/VertexInput/index.js, Sources/Rendering/WebGPU/ViewNodeFactory/index.js, Sources/Rendering/WebGPU/VolumeMapper/index.js
Add implementaiton of glyph3d mapper as well as
as StorageBuffer (SSBO) to make it easier.
Update shader replacement calls to all be autogenerated
from the shader template. Should make it easier to
customize etc.
=> feat(WebGPU): add glyph3dMapper and StorageBuffer

Sources/Widgets/Widgets3D/ImageCroppingWidget/behavior.js
Fixes #1905 
Fixes a typo in a variable name.
=> fix(ImageCroppingWidget): Typo in name

Sources/Rendering/WebGPU/BindGroup/index.js, Sources/Rendering/WebGPU/Device/index.js, Sources/Rendering/WebGPU/MapperHelper/index.js, Sources/Rendering/WebGPU/Pipeline/index.js, Sources/Rendering/WebGPU/README.md, Sources/Rendering/WebGPU/RenderEncoder/index.js, Sources/Rendering/WebGPU/Renderer/index.js, Sources/Rendering/WebGPU/StorageBuffer/index.js, Sources/Rendering/WebGPU/Texture/index.js, Sources/Rendering/WebGPU/TextureManager/index.js, Sources/Rendering/WebGPU/TextureView/index.js, Sources/Rendering/WebGPU/Types/index.js, Sources/Rendering/WebGPU/VolumePass/index.js, Sources/Rendering/WebGPU/VolumePassFSQ/index.js
Many fixes to bind groups and the move to MapperHelper
Better texture handing
Cleanup samplers from texture views
Fixed an issue in the Volume Mapper FSQ
Added error checking for bind groups
=> chore(WebGPU): bug fixes and more developement

Sources/Rendering/OpenGL/SurfaceLIC/SurfaceLICMapper/index.js
See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7535 and
https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7793
Some recent fixes have been added to VTK regarding the surface LIC mapper, specifically issues with face culling and normals not being properly loaded sometimes.
I reproduced related issues with the vtk.js mapper, which this PR fixes.
Light complexity should always be > 0, as we always need normals when rendering LIC.
Handle property settings for culling when needed. Disable culling when rendering to quads, then restore to initial state.
The mapper will now work when polyDatas have their own normals, instead of showing an initial black render.
Face culling will be supported by the mapper.
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> fix(surfacelicmapper): backport LIC fixes from VTK

Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js
Add missing import following updates in the HttpDataSetReader
@finetjul
=> Fix ResliceCursorWidget example

Sources/Rendering/WebGPU/MapperHelper/index.js, Sources/Rendering/WebGPU/README.md, Sources/Rendering/WebGPU/RenderWindow/index.js, Sources/Rendering/WebGPU/Texture/index.js, Sources/Rendering/WebGPU/TextureManager/index.js, Sources/Rendering/WebGPU/TextureView/index.js, Sources/Rendering/WebGPU/Volume/index.js, Sources/Rendering/WebGPU/VolumePass/index.js, Sources/Rendering/WebGPU/VolumePassFSQ/index.js
Test out a few 3d texture paths and fix them (webgpu)
Add gradient opacity support for volume rendering and
many fixes and improvements (webgpu)
=> chore(WebGPU): better 3d texture support and volren

Sources/Interaction/Widgets/ResliceCursor/ResliceCursor/index.js, Sources/Interaction/Widgets/ResliceCursor/ResliceCursorLineRepresentation/index.js, Sources/Interaction/Widgets/ResliceCursor/ResliceCursorRepresentation/index.js, Sources/Interaction/Widgets/ResliceCursor/example/index.js
Setup correct viewup on old ResliceCursor widget in order to be consistent with the new one
@finetjul
=> fix(reslicecursor): keep correct viewUp on rotation

Sources/Interaction/Widgets/ResliceCursor/ResliceCursor/index.js
@finetjul , I finnaly found out the last issue about camera position on the old reslice cursor widget.
=> fix(ResliceCursor): Setup correct initial normal to axis view

Utilities/ci/build-npm-package.js
The UMD build does have folders structure, while ESM build does not, this cause the relative import to not work correctly with the ESM build. The import path should relative in dev (to let TS transpiler work) and absolute when packaged.
https://github.com/Kitware/vtk-js/pull/1914#discussion_r639090476
https://github.com/Kitware/vtk-js/pull/1914#discussion_r639778439
Change has been made the build script to rewrite the import path to '@kitware/vtk.js/...' for the ESM build and 'vtk.js/Sources/...' for the UMD build.
TS intellisense and typing should work for ESM and UMD builds.
Check the import paths for each build
**ESM**
**UMD**
_This contribution is funded by my employer._
=> fix(package): rewrite TS import path

Sources/Widgets/Widgets3D/ImageCroppingWidget/example/index.js
Update ImageCroppingWidget to use the volume clip planes.
Cropping still works, but we no longer use the ImageCropFilter for this example.
Nothing here for now.
=> docs(ImageCroppingWidget): Use clipping planes

Sources/Filters/General/WindowedSincPolyDataFilter/example/index.js
It was missing HttpDataAccessHelper
=> docs(windowedsincpolydatafilter): fix windowedsincpolydatafilter example

Examples/Applications/SkyboxViewer/index.js, Sources/Interaction/Misc/DeviceOrientationToCamera/index.js
Update getOpenGLRenderWindow to getAPISpecificRenderWindow
Make sure requestAnimation has a requestor as now required
=> fix(SkyboxViewer): fix errors in the SkyboxViewer

Sources/IO/XML/XMLPolyDataReader/index.js, Sources/IO/XML/XMLReader/index.js
In order to make XMLImageDataReader and XMLPolyDataReader support FieldData of DataSet at the same time, I refer to the Cpp VTK, put the FieldData parser into the XMLReader and parse the FieldData into outputs after calling the XML parsing function.
=> feat(XMLReader): XMLImageDataReader supports FieldData.

Sources/macro.js, Sources/vtk.js, package-lock.json, package.json
`global` is not necessarily defined in browsers:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis
Update in macro.js.
=> fix(macro): global object to globalThis

Sources/Rendering/OpenGL/SurfaceLIC/SurfaceLICMapper/example/controller.html, Sources/Rendering/OpenGL/SurfaceLIC/SurfaceLICMapper/example/index.js
=> docs(licsurfacemapper): improve LICSurfaceMapper example

BREAKING_CHANGES.md, Sources/IO/XML/XMLImageDataWriter/example/index.js, Sources/IO/XML/XMLPolyDataWriter/example/index.js
Fix 2 examples and update breaking changes.
=> Update breaking changes doc

Utilities/ci/macro-shim.d.ts
I forgot to add the shim file to #2001 
- Adds a missing file
Builds should now work.
=> fix(ci): Add missing shim file

.github/pull_request_template.md, .github/workflows/pr-checks.yml, .husky/commit-msg, Utilities/prepare.js, package-lock.json, package.json
Ensure that PRs follow semantic-release and have correctly formatted code.
- Add housekeeping checklist for ensuring PRs are mergeable.
- Updated PR template
N/A
N/A
=> chore(github): Add PR checklist to PR template

Sources/Rendering/Core/Glyph3DMapper/index.d.ts, Sources/Widgets/Representations/ResliceCursorContextRepresentation/index.d.ts, Sources/Widgets/Representations/ResliceCursorContextRepresentation/index.js, Sources/Widgets/Representations/WidgetRepresentation/index.d.ts, Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/index.js
Rotation handle always had a fixed position, regardless of rotationHandlePosition.
=> Fix handle position

Sources/Interaction/Style/InteractorStyleManipulator/api.md
=> docs(InteractorStyleManipulator): Fix class name in api.md

Sources/Rendering/WebGPU/StickMapper/index.js
Fix due to changes in WGSL, was erroring otherwise
=> fix(WebGPU) fix issue with stick mapper on webgpu

Sources/Rendering/Core/VolumeMapper/Constants.js, Sources/Rendering/Core/VolumeMapper/index.js, Sources/Rendering/WebGPU/VolumePassFSQ/index.js
Add support for those 4 blend modes into the volume Rendering
for WebGPU. Also implement ipScalarRange filtering but leave
it commented for now as there and some WebGL changes on another
MR that needs to land first.
=> feat(WebGPU): add in min/max/average/additive volume blend modes

Sources/Interaction/Manipulators/MouseCameraTrackballZoomManipulator/index.js
Adds setter/getter on the zoomScale member to the manipulator API.
=> fix(Interaction): Expose zoomScale parameter on zoom manipulator

Examples/Applications/SkyboxViewer/index.js
Due to WebGPU support, the method name to access the WebGL view has changed.
See similar changes at f2457f04e007b76cc2781145399ffb7110b4cdbc in regards to the original issue [https://github.com/Kitware/vtk-js/issues/1916](https://github.com/Kitware/vtk-js/issues/1916) relating to `Examples/Geometry/VR`.
Fixes issue previously discussed in [https://github.com/Kitware/vtk-js/issues/1916](https://github.com/Kitware/vtk-js/issues/1916) for a different example.
Previous behavior on "Send to VR":
```
Uncaught TypeError: r.getOpenGLRenderWindow is not a function
```
Corrected behavior: "Send to VR" button succeeds in launching in VR display
- **Browser**: Chrome 95.0.4638.54
=> docs(SkyboxViewer): fix SkyboxViewer VR example

Sources/Rendering/OpenGL/index.js
=> fix: export vtkForwardPass in UMD build

.eslintrc.js
Examples are failing to build with the following error:
```
0:0  error  Parsing error: No Babel config file detected for \vtk-js\Sources\macros.js. Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files
✖ 1 problem (1 error, 0 warnings)
@ ../Sources/IO/Core/DataAccessHelper/HtmlDataAccessHelper.js 2:0-42 7:20-39 8:20-39 102:25-44
@ ./Geometry/VR/index.js 13:0-70
```
Examples should now build
Testing is not impacted
=> chore(eslint): specify babel config file to parser

Sources/Common/DataModel/ITKHelper/index.js
See description in issue: https://github.com/Kitware/vtk-js/issues/2162
- remove itkImage.direction.data since it is an array instead of object
- add ITKPixelTypes lookup so that switch statement is not always default case
ITKHelper now successfully loads .nii files when used in following way:
```
const niftiReader = vtkITKImageReader.newInstance();
niftiReader.setFileName('image.nii');
niftiReader
.parseAsArrayBuffer(res)
.then(() => {
const source = niftiReader.getOutputData();
return source;
})
.then((source) => {
...
```
- vtk.js: 17.17.2
- itk-wasm: ^1.0.0-a.8
- OS: iOS 11.3.1
- Browser: Chrome 95.0.4638.69
=> ITKHelper itk-wasm compatibility fixes

Sources/Rendering/Core/Actor2D/test/testActor2D.js
There was a test.only accidentally merged that prevented testing other tests.
- [ x ] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [ x ] Run `npm run reformat` to have correctly formatted code
- [ x ] This change adds or fixes unit tests
- [ x ] All tests complete without errors on the following environment:
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> test(actor2d): revert back to testing all tests

.github/workflows/pr-checks.yml, .github/workflows/test-only-check.sh
Prevent `test.only` from being merged into master.
Future PRs should fail if they include a `test.only` call.
=> chore(github): do not allow test.only in tests

CONTRIBUTING.md
Update CONTRIBUTING.rst, and closes #2182.
This is a docs change with no functional changes.
=> docs(CONTRIBUTING): update testing info

package-lock.json, package.json
- remove tap-markdown, since we don't use it anymore.
No more tap-markdown
=> chore(package): remove tap-markdown

Sources/macros.js
Just optimize code structure of shouldUpdate.
=> refactor(macros): optimize code structure of shouldUpdate

Utilities/Karma/tape-html-reporter.js
- test results folder creation should not error out with EEXIST
=> chore(karma): ignore EEXIST on mkdir

Sources/Rendering/WebGPU/VolumePass/index.js
Since we always have a full sized texture just use that
for the small viewport interactive rendering. That removes
a second texture, and allows us to update the scale
as often as we want since we are not resizing the
texture.
=> perf(WebGPU): improve interactive volume rendering

Sources/Widgets/Widgets3D/ResliceCursorWidget/helpers.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/test/testBoundPlane.js
@finetjul 
Finally, it won't work with 10e-6 but ok with 10e-7
Need to be reviewed after #2237
=> Fix reslice cursor precision

Sources/IO/Core/ImageStream/DefaultProtocol.d.ts, Sources/IO/Core/ImageStream/index.d.ts, Sources/Rendering/Misc/SynchronizableRenderWindow/index.d.ts, Sources/Rendering/OpenGL/RenderWindow/index.d.ts
Add typescript definitions for SynchronizableRenderWindow.
Minor fix & tightening of type definitions for RenderWindow & ImageStream
=> fix(SynchronizableRenderWindow): add type annotations

Sources/Rendering/WebGPU/FullScreenQuad/index.js, Sources/Rendering/WebGPU/Glyph3DMapper/index.js, Sources/Rendering/WebGPU/HardwareSelector/index.js, Sources/Rendering/WebGPU/ImageMapper/index.js, Sources/Rendering/WebGPU/MapperHelper/index.js, Sources/Rendering/WebGPU/OrderIndependentTranslucentPass/index.js, Sources/Rendering/WebGPU/PolyDataMapper/index.js, Sources/Rendering/WebGPU/RenderWindow/index.js, Sources/Rendering/WebGPU/Renderer/index.js, Sources/Rendering/WebGPU/Sampler/index.js, Sources/Rendering/WebGPU/ShaderDescription/index.js, Sources/Rendering/WebGPU/SphereMapper/index.js, Sources/Rendering/WebGPU/StickMapper/index.js, Sources/Rendering/WebGPU/StorageBuffer/index.js, Sources/Rendering/WebGPU/TextureView/index.js, Sources/Rendering/WebGPU/UniformBuffer/index.js, Sources/Rendering/WebGPU/VertexInput/index.js, Sources/Rendering/WebGPU/VolumePass/index.js, Sources/Rendering/WebGPU/VolumePassFSQ/index.js
The context was being recreated every frame causing some odd
issues.
Update all the [[foo()]] type stuff to the new @foo() format
WebGPU now uses.
=> fix(WebGPU): update to latest chrome canary, fix context bug

Sources/Rendering/OpenGL/RenderWindow/index.js, Sources/Rendering/SceneGraph/RenderWindowViewNode/index.js, Sources/Rendering/WebGPU/RenderWindow/index.js, Sources/Widgets/Core/WidgetManager/index.js
When using the hardware selector and widgets that are
in a different renderer (such as the orientation widget)
there was an issue with picking where the widget's renderer
was not being used.
=> fix(Picking): fix issue with picking and widgets

Sources/Rendering/WebGPU/HardwareSelectionPass/index.js, Sources/Rendering/WebGPU/OrderIndependentTranslucentPass/index.js, Sources/Rendering/WebGPU/RenderEncoder/index.js, Sources/Rendering/WebGPU/VolumePass/index.js
Handle the change to loadValue -> loadOp and clearValue etc
=> fix(WebGPU): just updating to latest WebGPU standards

Sources/Common/Core/DataArray/index.d.ts, Sources/Common/Core/DataArray/index.js, Sources/Common/Core/DataArray/test/testDataArray.js
The existing `createRangeHelper` and `computeRange` functions trigger the garbage collector a lot and slow down the whole operation.
A new `fastComputeRange` function has been added, that provides a 3x speed improvement over the existing function. While not triggering a single GC action.
~I would like to completely remove the slow `createRangeHelper` but I need to better understand how it's used first. Some help would be apreciated.~
**Before**
**After**
- **vtk.js**: 
- **OS**: 
_This contribution is funded by [Sirona Medical](https://sironamedical.com)._
=> perf: improve computeRange performance

.github/pull_request_template.md
- Based on the recent PRs, I noticed that the template could be improved.
- Move PR and Code Checklist section down because it is less important
than Context Results and Changes.
- Commnent Funding section by default because developers tend to leave it
with example.
- No testing performed
=> docs(git): tweak pull request template

Sources/Rendering/Misc/SynchronizableRenderWindow/index.d.ts
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> docs(ts): fix vtkSynchronizableRenderWindow typescript definition

Sources/Rendering/Core/CubeAxesActor/index.js, Sources/Rendering/OpenGL/CubeAxesActor/index.js, Sources/Rendering/OpenGL/Profiles/All.js, Sources/Rendering/OpenGL/Profiles/Geometry.js, Sources/Rendering/OpenGL/index.js, Sources/Rendering/WebGPU/CubeAxesActor/index.js, Sources/Rendering/WebGPU/Profiles/All.js, Sources/Rendering/WebGPU/Profiles/Geometry.js, Sources/Rendering/WebGPU/index.js
Update cube actor to better handle multiple backends and
to more quickly update text when it changes.
=> fix(Rendering): fix cube axes actor with multiple backends

LICENSE
Fix license file that it can be parsed by GH
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> docs(license): fix license file

Sources/Rendering/Core/RenderWindowInteractor/index.js
readjust the mouse wheel timer delay to 200ms so that
we do not get unintended zooms. Ideally the mouse wheel
movements would be single fire events as opposed to
start, move, stop but there may be code relying on the
start/move/stop approach.
Add the notion of extending the animation end time.
Now when a mouse wheel event is ending we tell the
RenderWindowInteractor to continue animation for another
600ms. The idea is to stay in animation mode for
longer so that a slow non-interactive render doesn't happen
when the user is really still being interactive.
=> fix(Interaction): improve mouse wheel interaction

Examples/Volume/ItkWasmVolume/index.js, Sources/Common/DataModel/ITKHelper/index.js
- docs(ItkWasmVolume): Add example
- fix(convertVtkToItkImage): Update for itk-wasm
=> itk wasm fixes examples

Sources/Rendering/WebGPU/HardwareSelectionPass/index.js, Sources/Rendering/WebGPU/OrderIndependentTranslucentPass/index.js, Sources/Rendering/WebGPU/RenderEncoder/index.js
Just updating to the latest chrome canary WebGPU build
=> fix(WebGPU): update to handle stencil loadop change

Sources/Interaction/Manipulators/MouseRangeManipulator/index.js
This change allows to set a `usePointerLock` flag to the `MouseRangeManipulator` so that the mouse is hidden while the user is interacting with the view.
This is especially useful because users may move their mouse outside the view while dragging their cursor to quickly interact with the view.
The PR is based on https://github.com/Kitware/vtk-js/pull/1272
Before, the user would keep seeing their cursor as they dragged it around, if the mouse went outside the view it could cause different issues since it could interfere with other UI elements.
After, the cursor is hidden while the user holds their button down, preventing the above issues.
I couldn't find TS definitions for this module.
- **vtk.js**: 
- **OS**: 
This contribution is funded by [Sirona …
=> feat: add support for Mouse Lock API to MouseRangeManipulator

Sources/Widgets/Representations/SphereContextRepresentation/index.js, Sources/Widgets/Widgets3D/SphereWidget/behavior.js, Sources/Widgets/Widgets3D/SphereWidget/example/controlPanel.html, Sources/Widgets/Widgets3D/SphereWidget/example/index.js, Sources/Widgets/Widgets3D/SphereWidget/index.d.ts, Sources/Widgets/Widgets3D/SphereWidget/index.js, Sources/Widgets/Widgets3D/SphereWidget/state.js
Add a widget for specifying a sphere.  It has two control handles, the center
and a border.  A border is an arbitrary point on the sphere border. It is used
to set the radius.
=> feat: add vtkSphereWidget

Examples/Geometry/ItkWasmGeometry/index.js, Sources/Common/DataModel/ITKHelper/index.js
=> feat(ITKHelper): Add conversion functions for PolyData

Examples/Geometry/ItkWasmGeometry/index.js, Examples/Volume/ItkWasmVolume/index.js
- docs(ItkWasmGeometry): Use itk-wasm.min.js UMD bundle
- docs(ItkWasmExamples): Bump version to 1.0.0-b.8
=> wasm bumps

Sources/interfaces.d.ts
Fix the typescript definition following comment on https://github.com/Kitware/vtk-js/commit/596775b46a88a604057ab3b9417031753b149180#r69726419
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> fix(ts): fix vtkAlgorithm typescript definitions

Sources/Rendering/Core/Prop/index.d.ts
fix #2317
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> docs(ts): fix vtkProp typescript definitions

Sources/Rendering/Core/Actor/index.js
- getActors() should return an array.
- getActors() returns an array.
=> fix(Actor): getActors returns array

Sources/Rendering/OpenGL/OrderIndependentTranslucentPass/index.js
Specifically with systems that do not support webgl2
Addresses issue https://github.com/Kitware/vtk-js/issues/2344
=> fix(WebGL): fix issue with order independent translucency

Utilities/ci/reset-gh-pages-history.sh
- clear out any working tree changes before resetting gh-pages
- publish workflow finishes
=> chore(ci): reset and clean before checking out

.github/workflows/build-test.yml, .github/workflows/publish.yml, Sources/Common/Core/Base64/index.d.ts, Utilities/build/rewrite-imports.js, package-lock.json, rollup.config.js, tsconfig.esm-check.json, tsconfig.json, tsconfig.umd-check.json
- Certain definition file imports were incorrect, namely those that are not index.d.ts.
- Fixes #2362
- Tested via build-time checks
=> Fix d.ts import rewrites

Sources/Common/DataModel/DataSetAttributes/FieldData.d.ts, Sources/Rendering/Core/RenderWindowInteractor/index.d.ts
=> docs(ts): renderWindowInteractor events and FieldData

Sources/Interaction/Manipulators/MouseCameraAxisRotateManipulator/index.js, Sources/Interaction/Manipulators/MouseCameraTrackballMultiRotateManipulator/index.js, Sources/Interaction/Manipulators/MouseCameraTrackballPanManipulator/index.js, Sources/Interaction/Manipulators/MouseCameraTrackballRotateManipulator/index.js, Sources/Interaction/Manipulators/MouseCameraTrackballZoomManipulator/index.js, Sources/Interaction/Manipulators/MouseCameraUnicamManipulator/index.js, Sources/Interaction/Manipulators/MouseCameraUnicamRotateManipulator/index.js, Sources/Interaction/Style/InteractorStyleManipulator/index.js, Sources/Rendering/Core/RenderWindowInteractor/index.js, Sources/Widgets/Manipulators/TrackballManipulator/index.js
Some of the interactions are "slower" for renderers that do not take up the full canvas size, since some of the interaction logic incorrectly depends on the renderwindow size rather than the renderer/viewport size.
This is relevant for when the interaction surface is limited to a particular renderer that may be smaller than the entire render window.
- certain manipulators now use viewport size rather than the entire canvas size.
=> fix(Manipulators): use renderer size

Sources/Common/DataModel/ITKHelper/index.d.ts
This commit adds support for ITKHelper typescript's defs
fix #2397
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> docs(ts): add ITKHelper typescript defs

Sources/Common/Core/Math/index.js
This new implementation is 60% faster
Faster array creation
https://jsbench.me/77l3d67rvo/1
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> perf: faster createArray function

Examples/Rendering/ManyRenderers/index.js, Sources/Rendering/Core/RenderWindowInteractor/index.d.ts, Sources/Rendering/Core/RenderWindowInteractor/index.js
Using pointer capture retargets events to the specified element,
allowing for interaction to continue even if the pointers move out of
the target element. Furthermore, pointer events unify the touch/mouse interaction API.
Closes: https://github.com/Kitware/vtk-js/issues/2347, https://github.com/Kitware/vtk-js/issues/2329
- pointer capture and events make for more robust handling of mouse, touch, and pen.
- IE 10 will no longer be supported (I don't think we ever did before this MR anyways...)
- InteractorStyleTrackballCamera example
- ManyRenderers example 
- InteractorStyleManipulator
=> Use pointer events (and pointer capture)

Sources/Rendering/WebGPU/CellArrayMapper/index.js, Sources/Rendering/WebGPU/ImageMapper/index.js, Sources/Rendering/WebGPU/OrderIndependentTranslucentPass/index.js, Sources/Rendering/WebGPU/Renderer/index.js, Sources/Rendering/WebGPU/SimpleMapper/index.js, Sources/Rendering/WebGPU/SphereMapper/index.js, Sources/Rendering/WebGPU/StickMapper/index.js, Sources/Rendering/WebGPU/VolumePass/index.js, Sources/Rendering/WebGPU/VolumePassFSQ/index.js
@stage(vertex) is now @vertex etc
=> chore(WebGPU): update to latest spec. Simple syntax changes

Sources/Proxy/Core/ViewProxy/index.js
- orientationWidget is not cleared properly when container is cleared
- properly handle object cleanup
=> fix(ViewProxy): handle object cleanup

.github/workflows/build-test.yml
The `upload-artifact` action occasionally fails due to external factors, marking checks as failed. This is undesirable.
Ignore `upload-artifact` failures.
=> chore(actions): ignore upload-artifact errors

Sources/Common/Core/DataArray/index.d.ts, Sources/Common/DataModel/DataSetAttributes/FieldData.d.ts, Sources/IO/Core/HttpSceneLoader/index.d.ts, Sources/Rendering/Core/Camera/index.d.ts, Sources/Rendering/Core/CellPicker/index.d.ts, Sources/Rendering/Core/Coordinate/index.d.ts, Sources/Rendering/Core/ImageMapper/index.d.ts, Sources/Rendering/Core/ImageSlice/index.d.ts, Sources/Rendering/Core/InteractorObserver/index.d.ts, Sources/Rendering/Core/Picker/index.d.ts, Sources/Rendering/Core/RenderWindow/index.d.ts, Sources/Rendering/Core/Renderer/index.d.ts, Sources/Rendering/Core/VolumeProperty/index.d.ts, Sources/Rendering/Misc/SynchronizableRenderWindow/index.d.ts, Sources/Rendering/OpenGL/RenderWindow/index.d.ts, Sources/Widgets/Core/WidgetManager/index.d.ts
Fixed some typescript and applied the patch from [VolView ](https://github.com/KitwareMedical/VolView/blob/master/patches/%40kitware%2Bvtk.js%2B24.5.6.patch)project
Fixed #2488
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> docs(ts): fix typescript defs

BREAKING_CHANGES.md, Sources/Common/Core/Math/index.d.ts, Sources/Common/Core/Math/index.js, Sources/Common/Core/Math/test/testMath.js, Sources/Common/DataModel/Line/index.js, Sources/Common/Transform/LandmarkTransform/index.js, Sources/Common/Transform/LandmarkTransform/test/testLandmarkTransform.js, Sources/Filters/General/OBBTree/index.js, Sources/Filters/Texture/TextureMapToPlane/index.js, Sources/Rendering/Core/ImageMapper/index.js, Sources/Rendering/OpenGL/PolyDataMapper/test/testMoreClippingPlanes.js, Sources/types.d.ts
fix #2325.
In issue #2325, it was mentionned that it is preferable to have only one format for matrices. For performance reason, it should be number[] .
The matrix format used in the math module (and therefore wherever those functions are called) are in number[] format. Tests have been added for these functions.
Changed : testMath, math, TextureMapToPlane, MeshClipPlane, OBBTree, LandmarkTransform, ImageMapper, Line, Triangle
- **vtk.js**: 24.5.2
- **Browser**: Chrome 100.0.4896.88
=> Fix inconsistent matrix representation

Documentation/content/docs/develop_webxr.md
Adds missing content link for WebXR volume rendering demo at [https://kitware.github.io/vtk-js/docs/develop_webxr.html](https://kitware.github.io/vtk-js/docs/develop_webxr.html).
Before
After
- **vtk.js**:  `master`
- **OS**:  Windows 10
- **Browser**:  Chrome 102.0.5005.115
=> docs(webxr): add missing resource link to WebXR summary docs page

Sources/Rendering/Core/Actor/index.d.ts, Sources/Rendering/Core/ImageSlice/index.d.ts, Sources/Rendering/Core/Volume/index.d.ts, Sources/Rendering/Core/VolumeMapper/index.d.ts, Sources/Rendering/Core/VolumeProperty/index.d.ts
fix #2510
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> docs(ts): fix vtkImageSlice typescript defs

Examples/Volume/WebXRVolume/index.js
Adds manual reslice step to WebXRVolume example so that default head MR volume faces towards the
camera at startup. Note that the head is still rotated in other examples where it is easier to
interactively rotate the volume.
vtk.js WebXR interactivity support is still in its infancy and does not yet include rotating objects while in VR. As a result it is useful for the documented example volume to already have a "comfortable" orientation for demos.
Old behavior
New behavior
Added reslice step in WebXRVolume example
- **vtk.js**:  `master`
- **OS**:  Windows 10
- **Browser**:  Chrome 103.0.5060.114
The orientation issue seems to originate with the data and not the VR camera, other examples such as [https://kitware.github.io/vtk-js/examples/VolumeMapperLightAndShadow.html](https://kitware.gi …
=> docs(webxrvolume): reslice default head volume to face the camera

Sources/Rendering/Core/SphereMapper/example/index.js, Sources/Rendering/Core/StickMapper/example/index.js
The old code had them as wireframe which isn't what
we want.
=> docs(Stick/Sphere): make stick and sphere examples surface

Sources/Rendering/Core/Actor2D/index.d.ts, Sources/Rendering/Core/ColorTransferFunction/ColorMaps.d.ts, Sources/Rendering/Core/Property2D/index.d.ts, Sources/Rendering/Core/VolumeProperty/index.d.ts, Sources/Rendering/Core/VolumeProperty/index.js
Closes #2530, #2534, #2538.
- Fixes some incorrect types
No tests are changed.
=> docs(Rendering): fix types

Sources/Common/DataModel/BoundingBox/api.md, Sources/Common/DataModel/BoundingBox/index.js, Sources/Common/DataModel/ImageData/index.js
Cleanup code for manipulating bounds.
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> refactor(imagedata): simplify bounds usage

Sources/Common/Core/DataArray/index.d.ts, Sources/Common/Core/DataArray/index.js, Sources/Common/Core/DataArray/test/testDataArray.js, Sources/Common/Core/Points/index.d.ts, Sources/Common/Core/StringArray/index.js, Sources/Common/Core/VariantArray/index.js, Sources/Filters/Core/Cutter/test/testCutter.js, Sources/Filters/General/ClipClosedSurface/index.js, Sources/Filters/General/ImageStreamline/index.js, Sources/Filters/General/PaintFilter/index.js, Sources/Filters/General/TubeFilter/index.js, Sources/Filters/General/WindowedSincPolyDataFilter/index.js, Sources/Rendering/Core/HardwareSelector/example/index.js, Sources/Rendering/OpenGL/PolyDataMapper2D/index.js
On current master:
Assuming `da` is a vtkDataArray
```
const p1 = da.getTuple(0);
const p2 = da.getTuple(10);
const p3 = [];
const p4 = [];
da.getTuple(0, p3);
da.getTuple(10, p4);
console.log(p1 === p2) // prints true
console.log(p3 === p4) // prints false
```
The function currently allow to not give a tuple to fill or not and uses a tuple holder if no tuple is given. The tuple holder is however common to the hole class, which causes calling of `getTuple` twice with no tuple on the same instance of the dataArray not working as intended
Fix the `getTuple` function. 
- **vtk.js**: v25.7.2
- **Browser**: Chromium 100.0.4852.0
=> fix(dataarray): getTuple

Sources/Filters/General/index.js
fix #2565
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> fix(trianglefilter): export vtkTriangleFilter

Sources/Rendering/OpenGL/RenderWindow/index.js
I tried to compile the code base with the Google Closure Compiler, which recognizes the affected line as an error:
```
Failed to inspect file
[...]/node_modules/@kitware/vtk.js/Rendering/OpenGL/RenderWindow.js
it was required from
[...]/node_modules/@cornerstonejs/core/dist/umd/index.js
Errors encountered while trying to parse file
[...]/node_modules/@kitware/vtk.js/Rendering/OpenGL/RenderWindow.js
{:line 521, :column 0, :message "Invalid delete operand. Only properties can be deleted."}
```
Out of curiosity, I tried compiling the code with webpack and, unsurprisingly, it didn't raise any errors. I guess webpack doesn't complain here because `delete` of anything other than an object property is just ignored.
In any case, I noticed that `model._textureResourceIds` is a `Map` object, so …
=> Remove redundant `delete` operator

Sources/Rendering/OpenGL/ShaderProgram/index.js, Sources/Rendering/OpenGL/ShaderProgram/test/testSubstitute.js
this new implementation is 40-60% faster (depending if the `all` flag is set to true or not)
https://jsbench.me/kil8a6dx31/1
- **vtk.js**: 
- **OS**: 
This contribution is funded by [Sirona Medical](https://sironamedical.com).
=> perf: substitute

Sources/Rendering/Core/Follower/index.js
Fixes #2531 
vtkFollower actors are positioned correctly.
=> fix(Follower): follower matrix multiply ordering

BREAKING_CHANGES.md, Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js
Further improve reslice cursor widget and update documentation.
=> Clean reslice cursor widget

.mailmap
Produce consistent author list
Merge authors in git commands
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> chore(git): add mailmap to fix author emails

BREAKING_CHANGES.md
Updates some dependencies and the breaking changes doc.
=> Prepare beta for v26 release

Examples/Applications/SkyboxViewer/index.md
Minor copy-edits for clarity; minor formatting tweaks.
This is a documentation-only change.
=> docs(Skybox Viewer): Update index.md

Sources/Rendering/OpenGL/VolumeMapper/index.js
This pull request aims to fix an issue with the correct rendering of the [volumeOutline](https://kitware.github.io/vtk-js/examples/VolumeOutline.html) by ensuring the correct computation of the world to [projection matrix in the shader](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl#L512). The projection matrix calculation depends on an accurate clipping range within the camera. Previously, the `interactorMPRSlice` was [correctly setting the clipping range to be](https://github.com/Kitware/vtk-js/blob/master/Sources/Interaction/Style/InteractorStyleMPRSlice/index.js#L296) `(model.distance, model.distance + 0.1)`, but for use cases that do not use the interactorSlice, the projection matrix was being calculated incorrectly (with the wrong …
=> fix(VolumeMapper): use the correct clipping range for key matrices for labelOutline

Sources/Interaction/Manipulators/CompositeCameraManipulator/index.d.ts, Sources/Interaction/Manipulators/CompositeGestureManipulator/index.d.ts, Sources/Interaction/Manipulators/CompositeKeyboardManipulator/index.d.ts, Sources/Interaction/Manipulators/CompositeMouseManipulator/index.d.ts, Sources/Interaction/Manipulators/CompositeVRManipulator/index.d.ts, Sources/Interaction/Manipulators/GestureCameraManipulator/index.d.ts, Sources/Interaction/Manipulators/MouseBoxSelectorManipulator/index.d.ts, Sources/Interaction/Manipulators/MouseCameraTrackballMultiRotateManipulator/index.d.ts, Sources/Interaction/Manipulators/MouseCameraTrackballPanManipulator/index.d.ts, Sources/Interaction/Manipulators/MouseCameraTrackballRollManipulator/index.d.ts, Sources/Interaction/Manipulators/MouseCameraTrackballRotateManipulator/index.d.ts, Sources/Interaction/Manipulators/MouseCameraTrackballZoomManipulator/index.d.ts, Sources/Interaction/Manipulators/MouseCameraTrackballZoomToMouseManipulator/index.d.ts, Sources/Interaction/Manipulators/MouseRangeManipulator/index.d.ts, Sources/Interaction/Style/InteractorStyleManipulator/index.d.ts, Sources/Proxy/Core/AbstractRepresentationProxy/index.d.ts, Sources/Proxy/Core/LookupTableProxy/index.d.ts, Sources/Proxy/Core/PiecewiseFunctionProxy/index.d.ts, Sources/Proxy/Core/ProxyManager/index.d.ts, Sources/Proxy/Core/SourceProxy/index.d.ts, Sources/Proxy/Core/View2DProxy/index.d.ts, Sources/Proxy/Core/ViewProxy/index.d.ts, Sources/Proxy/Representations/SliceRepresentationProxy/index.d.ts, Sources/Proxy/Representations/VolumeRepresentationProxy/index.d.ts, Sources/Rendering/Core/InteractorStyle/Constants.d.ts, Sources/Rendering/Core/InteractorStyle/index.d.ts, Sources/Rendering/OpenGL/RenderWindow/index.d.ts, Sources/Widgets/Core/StateBuilder/index.d.ts
These types are being upstreamed from the VolView project. 
- Improves type coverage
Testing is achieved by building the ESM module and testing out name and property auto-complete.
=> Adds more typescript types

Examples/Volume/Scrolling2DMixedImages/index.js, Sources/Common/DataModel/Collection/index.d.ts, Sources/Common/DataModel/Collection/index.js, Sources/Common/DataModel/Collection/test/testCollection.js, Sources/Rendering/Core/AbstractImageMapper/helper.js, Sources/Rendering/Core/AbstractImageMapper/index.d.ts, Sources/Rendering/Core/AbstractImageMapper/index.js, Sources/Rendering/Core/AbstractImageMapper/test/testAbstractImageMapper.js, Sources/Rendering/Core/CellPicker/index.js, Sources/Rendering/Core/ImageArrayMapper/index.d.ts, Sources/Rendering/Core/ImageArrayMapper/index.js, Sources/Rendering/Core/ImageArrayMapper/test/testImageArrayMapper.js, Sources/Rendering/Core/ImageArrayMapper/test/testImageArrayMapperColorTF.js, Sources/Rendering/Core/ImageArrayMapper/test/testImageArrayMapperFunctions.js, Sources/Rendering/Core/ImageArrayMapper/test/testImageArrayMapperNN.js, Sources/Rendering/Core/ImageMapper/index.d.ts, Sources/Rendering/Core/ImageMapper/index.js, Sources/Rendering/Core/PointPicker/index.js, Sources/Rendering/OpenGL/ImageMapper/index.js, Sources/Rendering/OpenGL/Texture/index.js, Sources/Testing/testUtils.js, package-lock.json
Add a new class `vtkImageArrayMapper` that extends `vtkAbstractImageMapper`. This class will render a collection of images that may have variable properties such as pixel-type, number of channels, and width/height. This feature is required, since the current `vtkImageMapper` assumes such properties to be consistent across slices. Therefore, the current image mapper (`vtkImageMapper`) only supports a specific kind of image series' that have consistent properties and can be defined on a regular grid and a single pixel array (all pixels of single type). Hence, some radiological diagnostic workflows that require acquiring images along different planes as well as mixing of grayscale and RGB images in a single series is not supported in the current mapper.
- **vtk.js**: master 
- **OS**: …
=> feat(ImageArrayMapper): New mapper for array of mixed images

Sources/Rendering/OpenGL/Texture/index.js
On Apple platforms, WebKit doesn't doesn't seem to allocate textures of type short and unsigned short with `texStorage` and the `EXT_texture_norm16` extension. This change ensures that when this combination is used, texture allocation reverts to using `texImage2D/3D` calls with the norm16 extension.
- **OS**: macOS 
- **Browser**: Chrome, Safari, Firefox
=> fix(rendering): Use texImage2D/3D on Mac WebGL2 for Norm16 textures

Sources/Rendering/Core/RenderWindowInteractor/index.js
This attempts to fix the problem of not being able to scroll a volume by 1 slice for each mouse wheel.
Depending on the OS and the browser, doing a mouse wheel event typically procuces a spin value > 1 (always <1 for trackpad). This can be explained because mouse wheel events are designed to "scroll a page by multiple lines at once".
In VTK.js specific domain, having a scroll spin value of 1 makes sense by default, hence the normalization factor.
With most OS/browser configurations, we can't browse a volume slice by slice with the mouse wheel.
The first mouse wheel event now scrolls always by 1 (e.g. if spin was 3 it now worths 1), subsequent scrolls are a factor of the original scroll value (e.g. if spint was 6 it now worths 2 because original first spin was 3).
Behavior for trackpads is …
=> refactor(mousewheel): normalize mouse wheel event spin values

Sources/Common/DataModel/SelectionNode/Constants.d.ts, Sources/Common/DataModel/SelectionNode/index.d.ts, Sources/Rendering/Core/ColorTransferFunction/index.d.ts, Sources/Rendering/Core/Mapper/index.d.ts, Sources/Rendering/Core/Renderer/index.d.ts, Sources/Rendering/OpenGL/RenderWindow/index.d.ts
Some typescript definitions are incorrect.
Fixes some incorrect definitions.
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> Miscellaneous typescript def fixes: vtkSelectionNode, vtkMapper, vtkColorTransferFunction, vtkOpenGLRenderWindow

Sources/Rendering/Core/AxesActor/index.js, Sources/Rendering/Misc/SynchronizableRenderWindow/ObjectManager/index.js
Allow VtkLocalView to show AxesActor and get things pretty close to VTK/C++.
=> Sync view axes actor

Documentation/content/docs/old_intro_vtk_es6.md, package.json
fix #2727
- **Browser**: Chrome latest
=> docs(old approach): add dependencies to the Old Approach documentation

Sources/Common/DataModel/ITKHelper/index.js
The function exports in [ITKHelper/index.d.ts](https://github.com/Kitware/vtk-js/blob/master/Sources/Common/DataModel/ITKHelper/index.d.ts) are not actually exported.
- Add function exports to match the typescript definition file.
=> fix(ITKHelper): match exports in definition file

Sources/Common/DataModel/BoundingBox/index.d.ts, Sources/Rendering/Core/HardwareSelector/index.d.ts, Sources/Rendering/Core/ImageMapper/index.d.ts, Sources/Rendering/Core/RenderWindowInteractor/index.d.ts, Sources/Rendering/Core/Renderer/index.d.ts, Sources/Rendering/OpenGL/HardwareSelector/Constants.d.ts, Sources/Rendering/OpenGL/HardwareSelector/index.d.ts, Sources/vtk.d.ts
This PR adds more missing types to vtk.js
Better type coverage
=> fix: adds more missing types

Sources/Rendering/Misc/SynchronizableRenderWindow/ObjectManager/index.js
Before, the state properties that were being converted to an array were being deleted. This meant that if the same state was loaded again (which can happen, for instance, if it gets mounted again by the visibility being toggled), the behavior in the second mount would be different.
In particular, we saw that a normals array was being removed on the second mount because it essentially thought that the normals array was no longer a part of the data (even though it was - it was just moved out of the properties and into the array).
To fix this, do not delete state properties, but instead, create a local copy that has the properties removed before proceeding (the properties still need to be removed for some further steps). This fixes the round-trip issue.
=> fix(SynchronizableRenderWindow): do not delete state properties

Sources/Interaction/Style/InteractorStyleImage/index.d.ts, Sources/Interaction/Style/InteractorStyleTrackballCamera/index.d.ts
Adds Typescript definitions for vtkInteractorStyleImage and vtkInteractorStyleTrackballCamera
- Improved type coverage
Testing done by running `npm run build:release` and `npx tsc -p tsconfig.esm-check.json` with no issues.
=> fix(types): add types for interactor styles

.github/workflows/build-test.yml, .github/workflows/pr-checks.yml
This PR allows the PR checks and Build & Test checks to run on merge queue. This is a necessary step prior to enabling merge queues in vtk.js.
For "Build and Test", we disable archiving build and test artifacts for merge queue checks in the interest of reducing check overhead on the merge queue.
If having these artifacts makes sense in the future, we can re-enable them.
This repo is ready to enable merge queues.
We'll see if this works soon enough.
=> chore(github): enable merge queue checks

Sources/Rendering/Core/Actor2D/index.d.ts
Adds `setMapper` and `getMapper` to the Actor2D types
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> fix(Actor2D): add set/getMapper

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Fix GH forms issues
See https://github.com/daker/vtk-js/issues/new/choose
=> chore(github): fix issue forms

Sources/Rendering/Core/ImageResliceMapper/example/index.js
Dev server proxies map `Data` to `/data` endpoint. The deployed examples should use that lowercase endpoint for fetching data.
=> test(imagereslicemapper): fix URL where example fetches data from

Sources/Widgets/Core/AbstractWidgetFactory/index.d.ts
AbstractWidget should extend vtkObject.
AbstractWidget extends vtkObject.
Validated in an IDE.
=> fix(AbstractWidgetFactory): extends vtkObject

.github/workflows/publish.yml
Github Actions should publish on maintenance branches.
=> chore(github): publish on maint branches

package.json
Capitalize Kitware in the repo URL.
=> chore(package.json): update repo url

Sources/Rendering/Core/ImageResliceMapper/example/controlPanel.html, Sources/Rendering/Core/ImageResliceMapper/example/index.js, Sources/Rendering/OpenGL/ImageResliceMapper/index.js
Interpolation type set on the image property was not being properly applied with the vtkImageResliceMapper.
Interpolation type is being respected.
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> Reslice mapper interpolation

Sources/Rendering/Core/ImageResliceMapper/example/controlPanel.html, Sources/Rendering/Core/ImageResliceMapper/example/index.js, Sources/Widgets/Widgets3D/ImplicitPlaneWidget/index.js
Features like MIP (maximum intensity projection) are best demonstrated on vascular structures such as Lung CT data. Upgrade the `ImageResliceMapper` to use Lung CT data and adjust other parameters accordingly.
Partially addresses: https://github.com/Kitware/vtk-js/issues/2783
| Before | After |
|--|--|
|<img width="582" alt="image" src="https://github.com/Kitware/vtk-js/assets/22624785/2cc37492-6664-4f3d-aa18-da0af92861f5"> | <img width="590" alt="image" src="https://github.com/Kitware/vtk-js/assets/22624785/943e5e77-f21e-4a26-8f30-b221658de98e"> |
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> Upgrade ImageResliceMapper example with vascular data

Sources/Rendering/SceneGraph/ViewNode/index.js
`ViewNode.removeUnusedNodes()` uses a slow deletion strategy when lots of children are expected to be deleted.
Use an in-place children deletion strategy, avoiding an extra allocation and filter/includes combination.
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> perf(ViewNode): faster removeUnusedNodes

BREAKING_CHANGES.md
The BREAKING_CHANGES doc is missing a release and has incorrect change attribution.
Fixed the BREAKING CHANGES doc.
=> chore: fix BREAKING_CHANGES.md

Sources/Rendering/Core/ImageResliceMapper/example/controlPanel.html, Sources/Rendering/Core/ImageResliceMapper/example/index.js, Sources/Rendering/OpenGL/ImageResliceMapper/index.js, Sources/Widgets/Widgets3D/ImplicitPlaneWidget/index.js
The vtkImageResliceMapper allows reslicing the volume with custom polydata. However, when switching between a vtkPlane and vtkPolyData as the slicing function, the mapper was failing to update graphics buffers. 
Also fixed a regression in the vtkImplicitPlaneWidget due to recent changes in handleEvents API of widgets.
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> Reslice mapper pd

Examples/Applications/OfflineLocalView/index.js
Extend OfflineLocalView example to support embedded base64 data inside HTML.
=> docs(OfflineLocalView): Add support for embedded data

Sources/Rendering/OpenGL/PolyDataMapper/index.js
The specular component calculation was using an approximation of the reflected light direction. This change removes this approximation and computes the vector component of the light direction along the reflection about the vertex normal.
See https://github.com/Kitware/trame-vtk/issues/17
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> fix(rendering): specular component of the light model

Sources/Filters/General/ImageDataOutlineFilter/index.js, Sources/Filters/Sources/CubeSource/index.js
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> Fix vtkCubeSource apply transforms only if properties are defined/not-null

Sources/Rendering/OpenGL/ImageMapper/index.js
Removes a debugging console.log line.
=> style(ImageMapper): remove console.log

Documentation/content/docs/vtk_vue.md
Since `@kitware/vtk.js` no longer targets ES5 directly, we add a note to the vue docs on how to enable ES5 transpilation.
=> docs(vue): add transpileDependencies note

Sources/Widgets/Core/WidgetManager/index.d.ts, Sources/Widgets/Core/WidgetManager/index.js
=> feat(WidgetManager): remove deprecated APIs

Sources/Rendering/Misc/GenericRenderWindow/index.js
Fixes #2952 
GenericRenderWindow now imports the rendering APIs.
ResliceCursorWidget now runs locally
=> fix(GenericRenderWindow): import rendering APIs

Sources/Widgets/Manipulators/LineManipulator/index.js
This PR fixes the case when the line manipulator are changing in a direction perpendicular to the view normal. The fix just apply no changes in the line manipulator. Without this fix, in perpendicular cases, bizarre unwanted  behaviour occurs because of Nan value multiplication.
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> fix(LineManipulator): fix line manipulator in perpendicular vector case

Sources/Rendering/Core/Picker/index.js
I find the vtkPicker code really hard to read and maintain. In my opinion a bit of refactoring wouldn't be bad.
refactor by extracting the compute tolerance stuff.
- **OS**: linux
- **Browser**: chrome
=> refactor(picker): extract computeTolerance

Sources/Rendering/Core/ImageResliceMapper/test/testImageResliceMapperShareOpenGLTexture.js, Sources/Rendering/Core/ImageResliceMapper/test/testImageResliceMapperSlabTypes.js, Sources/Rendering/Core/VolumeMapper/test/testAverageIntensityProjection.js, Sources/Rendering/Core/VolumeMapper/test/testComposite.js, Sources/Rendering/Core/VolumeMapper/test/testComposite16Bit.js, Sources/Rendering/Core/VolumeMapper/test/testCompositeParallelProjection.js, Sources/Rendering/Core/VolumeMapper/test/testIntermixed.js, Sources/Rendering/Core/VolumeMapper/test/testIntermixedImage.js, Sources/Rendering/Core/VolumeMapper/test/testMaximumIntensityProjection.js, Sources/Rendering/Core/VolumeMapper/test/testMinimumIntensityProjection.js, Sources/Rendering/OpenGL/ImageMapper/test/testImageWindowLevel.js, Sources/Rendering/OpenGL/Skybox/test/testSkybox.js, Sources/Rendering/OpenGL/Skybox/test/testSkyboxBackground.js, Sources/Rendering/OpenGL/Texture/test/testCreateCubeFromRawTexture.js, Sources/Rendering/OpenGL/VolumeMapper/test/testLabelmapOutlineManyRenderer.js, Sources/Rendering/OpenGL/VolumeMapper/test/testLighting.js, Sources/Rendering/OpenGL/VolumeMapper/test/testVolumeMapperBounds.js, Sources/Rendering/OpenGL/VolumeMapper/test/testVolumeMapperClip.js, Sources/Widgets/Widgets3D/ResliceCursorWidget/test/testMultipleRotationPlanes.js
If vtkHttpDataSetReader fails with an unhandled promise rejection, the tests hang instead of resolving as failed. See: #2979 
Tests involving vtkHttpDataSetReader should fail instead of timing out when an unhandled promise rejection is encocuntered.
=> test: fix tests using vtkHttpDataSetReader

Sources/Widgets/Manipulators/LineManipulator/index.js
Fix handle manipulation when the view direction is parallel to the line manipulator line direction.
To verify the issue, go to the cropper example
https://kitware.github.io/vtk-js/examples/ImageCroppingWidget.html
and without any rotation try to manipulate the center of the screen handle.
I´ve put an check to not allow changes if the manipulator lineDirection is parallel to the viewPlaneNormal
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> fix: cropper handle manipulation

Examples/Volume/ItkWasmVolume/index.js
ITK-Wasm image-io is now distributed in its own package, @itk-wasm/image-io.
It is available as an ESM bundle. We load this with a dynamic import.
readImageArrayBuffer is now readImage. The `webWorker` argument is not required. Data is passed as object with a `data` Uint8Array and path string.
=> docs(ItkWasmVolumeExample): update to use @itk-wasm/image-io

Sources/Rendering/Core/PixelSpaceCallbackMapper/index.d.ts
Fix type definition for typescript.
[Error occurs when using vtkPixelSpaceCallbackMapper with TypeScript](https://discourse.vtk.org/t/error-occurs-when-using-vtkpixelspacecallbackmapper-with-typescript/12853)
Callback parameters work with TypeScirpt. 
=> fix: Added type defs to PixelSpaceCallbackMapper

Sources/Interaction/Manipulators/MouseRangeManipulator/index.d.ts, Sources/Interaction/Widgets/OrientationMarkerWidget/Constants.js, Sources/Interaction/Widgets/OrientationMarkerWidget/index.d.ts, Sources/Rendering/Core/RenderWindowInteractor/index.d.ts, Sources/Rendering/Core/VolumeProperty/index.d.ts, Sources/Rendering/OpenGL/RenderWindow/index.d.ts, Utilities/build/rewrite-imports.js
Fixes and improves various type definitions.
=> fix(types): improve various type definitions

Sources/Filters/General/ContourLoopExtraction/example/index.js, Sources/Proxy/Representations/ResliceRepresentationProxy/example/index.js, Sources/Rendering/Core/ImageCPRMapper/Constants.d.ts, Sources/Rendering/Core/ImageCPRMapper/Constants.js, Sources/Rendering/Core/ImageCPRMapper/example/controller.html, Sources/Rendering/Core/ImageCPRMapper/example/index.js, Sources/Rendering/Core/ImageCPRMapper/index.d.ts, Sources/Rendering/Core/ImageCPRMapper/index.js, Sources/Rendering/OpenGL/ImageCPRMapper/index.js, Sources/Widgets/Widgets3D/LabelWidget/example/index.js
Add MIP in CPR with Maximum, Minimum and Average modes.
See the example for a demonstration of how to use MIP.
=> Add MIP to ImageCPRMapper

Sources/Rendering/Core/VolumeMapper/example/controller.html, Sources/Rendering/Core/VolumeMapper/example/index.js, Sources/Rendering/Core/VolumeProperty/index.d.ts, Sources/Rendering/Core/VolumeProperty/index.js, Sources/Rendering/OpenGL/VolumeMapper/index.js, Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl
Add the option to force neareset interpolation for any component
Also refactor the Volume Mapper (it is in a different commit)
Add a sphere to the example and checkboxes to force nearest on the two components
=> Add a force nearest option for each component of a volume

Examples/Geometry/AxesActor/controlPanel.html, Examples/Geometry/AxesActor/index.js, Sources/Rendering/Core/AxesActor/index.d.ts, Sources/Rendering/Core/AxesActor/index.js
This PR aims to enable the ability to invert axis in AxesActor. I creates an example, named AxesActor, that one can test the functionality.
- [] Tested environment:
- **vtk.js**:  latest
- **OS**:  Windows 11
- **Browser**:  Chrome
=> refactor(AxesActor): ability to invert axis

BREAKING_CHANGES.md, Sources/Rendering/Core/AxesActor/index.d.ts, Sources/types.d.ts
The type definition of the following methods of vtkAxesActor were modified to support the current required parameters:
- setXAxisColor
- setYAxisColor
- setZAxisColor
```ts
axes.setZAxisColor([255, 0, 0])
```
But the type definition required to supply r,g,b as three arguments, instead of inside an array
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> Fix vtkAxesActor types

package-lock.json, package.json
=> fix(wslink): relax peer dependency version constraint

Examples/Applications/OfflineLocalView/viewer.module.css
This allows to avoid creating scrollbars when using the offline viewer with trame-vtk in the context of jupyter notebooks.
cc: @jourdain 
-  [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
-  [x] Run `npm run reformat` to have correctly formatted code
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> docs(offlineviewer): update style to avoid scrollbars when embeded as iframe

Sources/Common/Core/DataArray/index.d.ts, Sources/Rendering/Core/Viewport/index.d.ts
Incorrect types
Fixes types for `fastComputeRange`, `computeRange`, and `addActor2D`
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> Fix types for fastComputeRange and addActor2D

Sources/Common/Core/Points/index.d.ts
Fix #3048
Fixes the interface of the `insertNextPoint` method on the  `vtkPoints` class.
Updates the interface on the `Points.d.ts` file.
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> fix(type): fix type returned when inserting a point

Sources/Rendering/Core/CellPicker/index.js
The volume picker does not function correctly for volumes generated from SAGITTAL and CORONAL images. The solution is straightforward: the current implementation overlooks the use of the provided worldToIndex transform found in the vtkImageData object. This PR updates the code to utilize this transform properly.
- **vtk.js**:  latest
- **OS**:  Windows 11
- **Browser**:  Chrome 125.0.6422.113
=> fix(volumePicker): use worldToIndex transform

Sources/Widgets/Manipulators/AbstractManipulator/index.d.ts, Sources/Widgets/Manipulators/AbstractManipulator/index.js, Sources/Widgets/Manipulators/CPRManipulator/index.js, Sources/Widgets/Manipulators/LineManipulator/index.js, Sources/Widgets/Manipulators/PickerManipulator/index.js, Sources/Widgets/Manipulators/PlaneManipulator/index.js, Sources/Widgets/Manipulators/TrackballManipulator/index.js, Sources/Widgets/Widgets3D/AngleWidget/behavior.js, Sources/Widgets/Widgets3D/ImageCroppingWidget/behavior.js, Sources/Widgets/Widgets3D/ImplicitPlaneWidget/index.js, Sources/Widgets/Widgets3D/LabelWidget/behavior.js, Sources/Widgets/Widgets3D/LineWidget/behavior.js, Sources/Widgets/Widgets3D/PolyLineWidget/behavior.js, Sources/Widgets/Widgets3D/PolyLineWidget/index.js, Sources/Widgets/Widgets3D/SeedWidget/behavior.js, Sources/Widgets/Widgets3D/ShapeWidget/behavior.js, Sources/Widgets/Widgets3D/SphereWidget/behavior.js, Sources/Widgets/Widgets3D/SplineWidget/behavior.js
Dragging widget handles has a jerky behavior, as the handles jump to the mouse position.
The manipulators now return a new property, `worldDelta`, which is the 3D vector delta between the current and the previous call to `handleEvent`.
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> feat(Widgets): smooth drag behavior

Sources/Widgets/Widgets3D/ImplicitPlaneWidget/index.js
=> fix(ImplicitPlaneWidget): autocomplete typo

Sources/Rendering/Core/HardwareSelector/test/testHardwareSelector.js, Sources/Rendering/OpenGL/Actor/index.js
PropID of the last rendered prop was returned by the hardware selector when picking translucent actors overlaid on each other.
fix #2800 
Corrent prop ids being returned.
=> Picking translucent

Sources/Rendering/OpenGL/RenderWindow/index.d.ts
It didn't inherit the view node and inherited vtkAlgorithm even if it is not one
=> Fix ogl render window typing

Sources/Rendering/Core/HardwareSelector/test/testHardwareSelectorManyCells.js, Sources/Rendering/Core/Mapper/index.js, Sources/Rendering/OpenGL/HardwareSelector/index.d.ts, Sources/Rendering/OpenGL/HardwareSelector/index.js, Sources/Rendering/OpenGL/PolyDataMapper/index.js
Picking with >2**24 cells was broken as the `ID_HIGH24` didn't work.
It is likely that it never worked.
Add a test to avoid regressions.
=> Fix hardware selector picking with many cells

Sources/Rendering/OpenGL/ImageCPRMapper/index.js, Sources/Rendering/OpenGL/ImageMapper/index.js, Sources/Rendering/OpenGL/ImageResliceMapper/index.js, Sources/Rendering/OpenGL/RenderWindow/resourceSharingHelper.d.ts, Sources/Rendering/OpenGL/RenderWindow/resourceSharingHelper.js, Sources/Rendering/OpenGL/VolumeMapper/index.js
Add resource sharing for the vtkImageCPRMapper.
Factorize the computation of hashes to avoid deoptimization of resource sharing.
=> Add GPU resource sharing for the CPR image mapper

Sources/Filters/General/Calculator/index.js
The [Calculator](https://kitware.github.io/vtk-js/examples/Calculator.html) example doesn't map the colors correctly due to an uncaught exception. Introduced in 46b13cc.
The calculator example now works again.
- Guard against undefined inputs
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> fix(Calculator): exception on undefined input data

Sources/Rendering/OpenGL/SurfaceLIC/LineIntegralConvolution2D/index.js
The [SurfaceLICMapper](https://kitware.github.io/vtk-js/examples/SurfaceLICMapper.html) example was not rendering due to an uncaught exception stemming from an undefined variable. Introduced in 2d94482fd2f6c4ab38be8483de554b8c3e9d3026.
The SurfaceLICMapper example now renders.
- Guard against an undefined framebuffer when calling `getSize()`
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> fix(SurfaceLIC): guard against undefined framebuf

package-lock.json, package.json
Publishing pre-releases on `beta` will post github comments on PRs, indicating that the PR is available on a beta release. This can be spammy given our current git workflow of updating beta when we need it, rather than developing directly on it.
FYI @jourdain @finetjul I'm testing this out, so I'll be merging this shortly after CI passes. If we decide this is an unnecessary change, we can roll it back.
Prevent pre-release branches from posting github comments.
=> chore(semantic-release): no github msgs for beta

Sources/Interaction/Manipulators/KeyboardCameraManipulator/index.d.ts
Add index.d.ts file for vtkKeyboardCameraManipulator
=> feat(KeyboardCameraManipulator): Add typescript

.github/workflows/build-test.yml
=> chore(github): use upload-artifact@v4

.github/workflows/build-test.yml
Addresses github CI write conflicts when using upload-artifact
=> chore(github): fix upload-artifact write conflicts

Sources/Rendering/Core/AbstractPicker/index.d.ts, Sources/Rendering/Core/AbstractPicker/index.js
Init pickFromList to false not 0.
Fix TypeScript defs.
=> fix(AbstractPicker): model.pickFromList type is boolean

Sources/Rendering/Misc/SynchronizableRenderWindow/BehaviorManager/CameraSynchronizer.js
Camera synchronizer is used all the way up to trame.
fix 
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> fix(camerasynchronizer): fix src/dest renderer changed listeners registration

Sources/IO/Geometry/PLYReader/example/controller.html, Sources/IO/Geometry/PLYReader/example/index.js, Sources/IO/Geometry/PLYReader/index.d.ts, Sources/IO/Geometry/PLYReader/index.js, Sources/IO/Geometry/PLYReader/test/testPLYReader.js
fixes #2841
fixes #2877
fixes #3047
| Before | After |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/9434edbc-a0cf-416e-8638-4a378a86150d)| ![image](https://github.com/user-attachments/assets/e23e8adc-db95-442e-b00c-12bb998676f9)    |
| Before | After |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/c9efecbe-aae8-4f5d-826f-ad2e1e1abc35) | ![image](https://github.com/user-attachments/assets/662456a2-2231-4da6-a6a7-2910d129cf89)   |
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> fix(PLYReader): add support for duplicatePointsForFaceTexture

Sources/Rendering/Core/Texture/index.d.ts, Sources/Rendering/Core/Texture/index.js, Sources/Rendering/WebGPU/Texture/index.js, Sources/Rendering/WebGPU/TextureManager/index.js
This commit generates mipmaps for a given GPU texture using a compute shader.
fixes #3260
| Before | After |
| -------- | ------- |
| ![old-generateMipmaps](https://github.com/user-attachments/assets/a9b9b519-6a6f-48a0-8aca-297d07bb68d0) | ![new-generateMipmaps](https://github.com/user-attachments/assets/b6f6a055-6c5d-4a76-aa3e-d226dc1d2676) |
https://github.com/user-attachments/assets/95f65b1f-bf02-4a46-8ba2-0d90aa2fef47
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> fix(WebGPU): optimize vtkTexture.generateMipmaps

Sources/Rendering/OpenGL/Texture/index.d.ts, Sources/Rendering/OpenGL/Texture/index.js
feat(Texture): add support for ImageBitmap texture in WebGL
perf(Texture): optimize HTMLImageElement upload performance 
also fixes: #3268
```
Chrome:
HTMLImageElement -> Canvas -> texSubImage2D
create2DFromImage: 34.530029296875 ms
HTMLImageElement -> texSubImage2D
create2DFromImage: 75.85693359375 ms
Firefox:
HTMLImageElement -> Canvas -> texSubImage2D
create2DFromImage : 54 ms
HTMLImageElement -> texSubImage2D
create2DFromImage : 20 ms
```
| Image with Canvas| Image only |
| -------- | ------- |
| ![FF-Image-Canvas](https://github.com/user-attachments/assets/6a3d1f4f-8939-445b-842e-7d67c05ba9ff) | ![FF-Image](https://github.com/user-attachments/assets/8d5340c1-645a-4442-bdc4-2e75c312311c)  |
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> feat(Texture): add support for ImageBitmap texture in WebGL

Sources/Rendering/Core/VectorText/Utils.js, Sources/Rendering/Core/VectorText/example/controller.html, Sources/Rendering/Core/VectorText/example/index.js, Sources/Rendering/Core/VectorText/index.d.ts, Sources/Rendering/Core/VectorText/index.js, Sources/Rendering/Core/index.js
feat(VectorText): add vtkVectorText
fixes #653
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> feat(VectorText): add vtkVectorText

Sources/Common/Transform/Transform/index.d.ts, Sources/Common/Transform/Transform/index.js, Sources/Filters/General/TransformPolyDataFilter/index.d.ts, Sources/Filters/General/TransformPolyDataFilter/index.js, Sources/Filters/General/TransformPolyDataFilter/test/testTransformPolyDataFilter.js, Sources/Filters/General/index.js
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> feat(TransformPolyDataFilter): add vtkTransformPolyDataFilter

Sources/Rendering/OpenGL/VolumeMapper/index.js
In the calculation of the number of lights, there is no check to determine whether `model.currentValidInputs` is empty. However, later on, `firstVolumeProperty` is used for judgment.
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> fix(VolumeMapper): Fixed accessing property with no valid input

Sources/Common/Core/CellArray/index.js, Sources/Common/DataModel/Triangle/index.d.ts, Sources/Common/DataModel/Triangle/index.js, Sources/Common/DataModel/TriangleStrip/example/index.js, Sources/Common/DataModel/TriangleStrip/index.d.ts, Sources/Common/DataModel/TriangleStrip/index.js, Sources/Common/DataModel/TriangleStrip/test/testTriangleStrip.js, Sources/Common/DataModel/index.js
- **vtk.js**: 
- **OS**: 
- **Browser**:
=> feat(TriangleStrip): add vtkTriangleStrip

Sources/Interaction/Style/InteractorStyleManipulator/index.js
This enhances pan then rotate interaction with InteractorStyleManipulator.
After panning, move the center of rotation the same vector the camera position moved.
Before, if the user panned the camera, zoomed in, then rotated, they would rotate around a point that was not in the center of the camera.  This made it hard to zoom in on a region of interest and rotate around it.
vtkInteractorStyleManipulator is used widely, especially in [VolView](https://github.com/Kitware/VolView.git) and in trame-vtk via  [vue-vtk-js](https://github.com/Kitware/vue-vtk-js.git). 
I'm optimistic this change will transparently upgrade their default camera controls for the better.
To get a feel for the rotation before and after run:
```
npm run example -- InteractorStyleManipulator
```
Try to pan and zoom in on …
=> feat(InteractorStyleManipulator): update center of rotation on pan
