Kitware/vtk-js

Sources/Rendering/Core/ImageMapper/index.js
Sources/macro.js

@martinken @jourdain
This line of code is blowing away my static input data, where I don't have an input connection. My code works when I comment this line out. Ken mentioned that this line might not even be needed. Just wanted to confirm before checking in a change to remove it. Let me know.
There's another potential issue here:
https://github.com/Kitware/vtk-js/blob/static-input-data/Sources/macro.js#L313
But I'm not sure when `update` is actually called.

Don't blow away static input data

---

Utilities/DataGenerator/vtk-data-converter.py

On Windows filesystem a file should be closed before removed else system throws an error.

fix can't remove temporary files for convert python script on windows

---

Sources/Rendering/OpenGL/BufferObject/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js

This topic fixes two issues. The first
When the setting of edge visibility changed the polydata
mapper for OpenGL was not rebuilding its buffers.
The second was that when freeing an old buffer the
method name was incorrect and caused an error.

fix(Rendering): bad buffer free and rebuilding

---

Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js

The blend function was not being set so translucent
objects appeared opaque.
When points were rendered in surface mode lighting was
being applied even if the points had no normals. Fixed
so that lighting is only applied on points with normals.

fix(Rendering): fix alpha blending and point lighting

---

Sources/Common/Core/DataArray/index.js
Sources/Common/Core/ScalarsToColors/index.js
Sources/Common/DataModel/DataSet/index.js
Sources/Filters/General/WarpScalar/index.js
Sources/Filters/Sources/ConeSource/index.js
Sources/Filters/Sources/ImageGridSource/index.js
Sources/Filters/Sources/SphereSource/index.js
Sources/Rendering/Core/Mapper/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/test/testInterpolateScalarsBeforeMapping.js

tuple was used in a few places to represent the number
of components. This topic changes the wording to
use numberOfComponents instead.

refactor(Common): Make use of tuple more consistent

---

Examples/WebGL/Texture/index.js

There was a typo in the texture example causing it
to have incorrect texture coordinates

docs(Rendering): fix the texture example

---

Sources/Rendering/Core/Mapper/index.js

The mapper was not considering its LookupTable when
computing it mtime causing changes in the LookupTable
to be ignored.

fix(Rendering): Handle LookupTable Mtime in Mapper

---

Sources/macro.js

The computation for when a filter should reexecute had
an issue that could cause it to always reexecute. This
change makes it so that a filter will always execute if
its inputs are more recent than its outputs or if its
mtime is more recent than its outputs. A filter is not
explicitly modified when executing and may have a mtime
that is lower than its inputs.

fix(Pipeline): fix an issue with shouldUpdate

---

Sources/Rendering/OpenGL/Camera/index.js

It seems that on some systems the matrices passed to
webgl may be used after they are passed resulting in
potentially bad matrices being used.

fix(Rendering): the wcvc matrix was getting corrupted

---

Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js
Sources/Rendering/Core/RenderWindowInteractor/index.js

Pressing a key while interacting could populate the
camera with NaNs as the keyboard events position
is NaN. Do not use the position of a keyboard event.

fix(Rendering): Do not use key event positions

---

Sources/Common/Core/DynamicTypedArray/index.js
Sources/Rendering/OpenGL/CellArrayBufferObject/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/SphereMapper/index.js
Sources/Rendering/OpenGL/StickMapper/index.js

The original implementation only supported floats for
the VBO/CABO. This updates the code to use unsigned chars
by default for colors in the VBO. It also updates the stick
mapper to use unsigned chars for the offsets. The end result
is a 12 byte per point savings for color and an 8 byte per
point savings for offset.

perf(Rendering): Store colors etc as uchars instead of float

---

Sources/Common/Core/LookupTable/index.js
Sources/Common/Core/ScalarsToColors/index.js
Sources/Rendering/Core/ColorTransferFunction/index.js

ScalarsToColors, LookupTable and ColorTransferFunction
had multiple definitions of the range to map. This topic
consolidates those to one set of ivars mappedRange for
clarity.

refactor(Rendering): consolidate scalartocolors ranges

---

Sources/Common/DataModel/DataSet/Constants.js
Sources/Common/DataModel/SelectionNode/Constants.js
Sources/Common/DataModel/SelectionNode/index.js
Sources/Rendering/OpenGL/Actor/index.js
Sources/Rendering/OpenGL/Framebuffer/index.js
Sources/Rendering/OpenGL/HardwareSelector/Constants.js
Sources/Rendering/OpenGL/HardwareSelector/index.js
Sources/Rendering/OpenGL/HardwareSelector/test/testHardwareSelector.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/Renderer/index.js
Sources/Rendering/OpenGL/Shader/index.js
Sources/Rendering/OpenGL/ShaderCache/index.js
Sources/Rendering/OpenGL/ShaderProgram/index.js
Sources/Rendering/OpenGL/Texture/index.js
Sources/macro.js
Sources/tests.js

This topic adds a hardwareslector class that can be used
to perform hardware picks and return the prop and propid.
In the future we can extend it to support the other passes
such as composite id and attribute id.
To support this we added a SelectionNode class that contains
information and properties about a selection.
Since webgl doesn't really have an option to turn of bufferswapping
we add a framebuffer class so that the hardware picking can take
place in the framebuffer instead of the visible buffer. The
framebuffer class will of course be useful for a lot of other
cases.
Fixed a bug where is a class initialized mtime to zero it
would not be honored and would instead use the global mtime.

feat(Rendering): add hardware selector and framebuffers

---

Sources/Rendering/Core/Mapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js

Two issues. There was a typo between unit and units in
the offset code. Renamed all to offset.
The code to compute lighting on edges was not triggering
resulting in odd lighting.

fix(Rendering): fix surface with edges failure

---

Utilities/config/webpack.loaders.js

This is not a complete pull request as it misses documentation but I would like to let you know that I was able to use vtk.js with webpack 2.2.1 by making these changes. Feel free to close this PR as I also don't know if the changes are backward compatible to webpack 1, I guess not.
My `webpack.config.js`:
```javascript
const path = require('path');
const webpack = require('webpack');
const merge = require('webpack-merge');
const parts = require('./webpack.parts');
const pkg = require('./package.json');
const loaders = require('./node_modules/vtk.js/Utilities/config/webpack.loaders.js');
const commonConfig = merge([
{
entry: {
app: pkg.paths.src.js + 'app.js'
output: {
path: pkg.paths.dist.js,
filename: 'bundle.js'
},
module: {
rules: [
{
test: require.resolve("./src/js/app.js"),
loader: …
```

Update webpack.loaders.js to webpack 2

---

Sources/Common/Core/Math/index.js

The vtkRotate fnction takes 5 arguments. In VTK, the first arguments is set inside the function. Actually, it's the first attribute of the JacobiN function which is set. So the first argument of thevtkRotate function is never set.

Fix function vtkRotate used inside JacobiN function

---

Sources/Rendering/OpenGL/ShaderCache/index.js

We were requesting the derivatives extension for
the vertex shader when we only need it on the
fragment shader. On edge this resulted in a failed
shader compilation.

fix(Rendering): microsoft edge was not working

---

Sources/Rendering/OpenGL/RenderWindow/index.js

setContainer() can take null or undefined to unmount the render window

fix(RenderWindow): Allow render window to be unmount

---

Sources/Rendering/Core/Coordinate/index.js

Allow setValue(x,y) to work as well with an implicit z of 0.0

fix(Rendering): support setValue(x,y) signature on coord

---

Examples/WebGL/ZipHttpReader/index.js

Modified the ZipHTTPReader example to download a small
volume first and then later download the full res

perf(Example): modify example to use LOD

---

Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

On apple nvidia gtx750M based systems it seems they have
a bug with webgl and if (a || b) statements. This was
impacting volume rendering. This works fix around the issue.

fix(Rendering): work around apple nvidia webgl bug

---

Sources/Rendering/OpenGL/ImageSlice/index.js

image mapper would not be rendered if it
was the only object in view as it was not
responding to the query pass

fix(Rendering): fix issue with image mapper

---

Sources/Interaction/Style/InteractorStyleImage/index.js
Sources/Rendering/Core/ImageMapper/example/index.js
Sources/Rendering/OpenGL/VolumeMapper/test/testIntermixed.js

There was an old method signature causing the interactor style
image to not work. Modified the ImageMapper example to use
that interactor style.

fix(Rendering): issue with interactor style image

---

Sources/Rendering/OpenGL/Texture/index.js

Only default to mipmaps for RGBA

fix(Rendering): webgl spec does not guarantee luminance mipmap

---

Sources/Rendering/OpenGL/Texture/index.js

The added support for cube maps caused an issue with
regular texture maps.

fix(Rendering): issue with textures after cube maps

---

Sources/Common/Core/Math/index.js
Sources/Rendering/Core/Mapper/index.js
Sources/Rendering/Core/Renderer/index.js
Sources/Rendering/Core/VolumeMapper/index.js

`createUninitializedBounds ` was called by ImageMapper but it crashed during execution. The real function was defined under the name `createUninitializedBouds`.

fix(vtkMath): Update the name of a function

---

Sources/Rendering/OpenGL/RenderWindow/index.js

If enabled via a model flag, the render window will call the image ready callback with the extracted
canvas image after each render.  This allows an application, for example, to have a live screenshot
preview.

WIP: fix(OpenGLRenderWindow): Support a callback on each render

---

Sources/IO/Core/DataAccessHelper/HttpDataAccessHelper.js
Sources/IO/Misc/OBJReader/index.js

This also adds support in the OBJ Reader to make use of this new API.
We can add this to more methods within HttpDataAccessHelper, but I wanted to put this out there for comment to see if you think this is an OK approach.

feat(HttpDataAccessHelper): Expose progress in API

---

Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

It seems that some mix of chrome 58/angle and nvidia has introduced
a bug where the break statement is not being handled correctly
in webgl. This works around the bug.

fix(Rendering): work around chrome/angle/nvidia bug

---

Sources/Filters/Sources/PointSource/test/testPointSource.js
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

Fix a few calls in the opengl volume mapper
Make the pointsource test more resilient to GPU changes
Ad an option to request a webgl2 context and query
if we have a webgl2 context

fix(Rendering): add basic webgl2 support and bug fixes

---

Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

On some systems it seems glsl breaking out of a for loop is
not improving the performance so the full loop count
is being executed. So we tighten up the loop count so that
we have the minimum count required for the step size.

perf(Rendering): improve volume rendering perf on some devices

---

Sources/Interaction/Manipulators/TrackballZoom/index.js

The `vtkRenderWindowInteractor` no longer has a `getActiveCamera()` method.  This fix allows the zoom manipulator to get its hands on the active camera via the current renderer belonging to the interactor style of the render window interactor.

fix(TrackballZoom): Fix broken zoom manipulator

---

Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/ShaderCache/index.js
Sources/Rendering/OpenGL/Texture/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS2.glsl

This topic adds support for using webgl2 API when volume
rendering. It is currently disabled. The webgl2 API shows
a 50% performance improvement as it can leverage 3D textures.

fix(Rendering): add webgl2 path for Volume Rendering

---

Sources/Rendering/Core/RenderWindowInteractor/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

There were some instabilities and issues with the LOD
in the Volume Rendering Mapper. Partially due to the
timing often being a few frames behind the rendering
as OpenGL is async. This topic significantly improves
the process and only reallocs the FO on canvas resizes.

fix(Rendering): fix some LOD issues in the VR Mapper

---

Sources/Rendering/Core/Renderer/index.js
Sources/Rendering/OpenGL/Renderer/index.js
Sources/macro.js
Utilities/ParaView/export-scene-macro.py

Expand the setArray macro to allow mulitple array sizes.
Allow a background color of 3 or 4. If it's length 3, assume opaque.
Also fix export-scene-macro.py to be Py3 compatible.
@martinken @scottwittenburg Here's the change that allows a background image/div to show through.

fix(Renderer): allow a transparent clear color

---

Sources/Rendering/OpenGL/RenderWindow/index.js

There was a mismatch in the code for Webgl2 that caused
issues when using data types other than float/uchar in
textures

fix(Rendering): fix an issue with textures of short/int

---

Sources/Rendering/Core/Viewport/index.js

The conversion to normalized display coordinates was
incorrect.

fix(Rendering): fix conversion to normalize display

---

Sources/Rendering/Core/InteractorObserver/index.js
Sources/Rendering/Core/Renderer/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js

The world to view conversions in Renderer were hardcoded to
a 1.0 aspect ratio and an incorrect zvalue range. This change
requires the aspect ratio to be passed in. As a convinience
when doing conversions that involve world -- view methods
have been added on the view (OpenGL/RenderWindow). These
methods take the renderer as an argument and include display -- world
and view -- world conversions.

fix(Rendering): fix world to view conversions

---

Sources/Rendering/OpenGL/RenderWindow/index.js

@martinken , is this PR is relevant ? Because I have an error when I press shift + mouse click and move.

fix(OpenGLRenderWindow): Call the right function to convert display coord

---

Sources/Common/Core/Math/index.js

The method determinant2x2 only take two arguments. But this method was called several times with 4 parameters.

fix(vtkMath): Determinant2x2 was called with 4 arguments but only 2 were consider

---

Sources/Rendering/OpenGL/RenderWindow/index.js

There was two occurances of y, y that should have been x, y

fix(Rendering): bug in coordinate conversions

---

Sources/Rendering/Core/InteractorObserver/index.js

I pushed this static method because I'm implementing the widget (vtkWidgetRepresentation). These methods are used in SizeHandlesRelativeToViewport and SizeHandlesInPixels

feat(InteractorObserver): Add static methods to convert points coordinate

---

Sources/Common/DataModel/Cell/index.js
Sources/Rendering/Core/CellPicker/index.js

We don't want to recreate a vtkPoints when we call initialize on a vtkCell.
With the cellpicker and a mesh with 120000 cells, we pick on 4 sec. With this modification, we pick on 0.5sec.

perf(Cell): Don't recreate vtkPoints when vtkCell is initialize

---

Sources/Interaction/Widgets/AbstractWidget/api.md
Sources/Interaction/Widgets/AbstractWidget/index.js
Sources/Interaction/Widgets/HandleRepresentation/Constants.js
Sources/Interaction/Widgets/HandleRepresentation/api.md
Sources/Interaction/Widgets/HandleRepresentation/index.js
Sources/Interaction/Widgets/HandleWidget/Constants.js
Sources/Interaction/Widgets/HandleWidget/api.md
Sources/Interaction/Widgets/HandleWidget/example/index.js
Sources/Interaction/Widgets/HandleWidget/index.js
Sources/Interaction/Widgets/PointPlacer/api.md
Sources/Interaction/Widgets/PointPlacer/index.js
Sources/Interaction/Widgets/SphereHandleRepresentation/api.md
Sources/Interaction/Widgets/SphereHandleRepresentation/index.js
Sources/Interaction/Widgets/WidgetRepresentation/api.md
Sources/Interaction/Widgets/WidgetRepresentation/index.js
Sources/Interaction/Widgets/index.js
Sources/Rendering/Core/Coordinate/index.js
Sources/Rendering/Core/InteractorObserver/index.js
Sources/Rendering/Core/RenderWindowInteractor/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/Renderer/index.js
Sources/Rendering/OpenGL/ViewNodeFactory/index.js
Sources/Rendering/SceneGraph/GenericWidgetRepresentation/index.js
Sources/Rendering/SceneGraph/ViewNode/index.js
Sources/Rendering/SceneGraph/ViewNodeFactory/index.js
Sources/Rendering/SceneGraph/index.js
Sources/macro.js

This PR add the possibility to create widget.
A handleWidget have been implemented (+ an using example)
Some modifications needs to be added and should be reviewed :
- [vtkCoordinate] the value should be get
- [vtkRenderWindowInteractor] A macro `get ` has been added to the `canvas` because some attributes of the `clientBoundingRect `are used to change 2D picking position. If we don't modify it, then there's a shift when mouse move (cf vtkHandleWidget when we get the event position)
- [vtkOpenGLRenderWindow/vtkViewNode] In VTK, a WidgetRepresentation can have several actors. To avoid adding each actor as actor in the renderer (`addActor`), we would like to only add the representation which will render it's child = actors. So we add a new method which get ViewProps and create a sceneGraph …

Add widget notion (+ widget representation)

---

Sources/Rendering/OpenGL/SphereMapper/index.js
Sources/Rendering/OpenGL/StickMapper/index.js

For Stick and Sphere mappers turing scalar visibility on and
then off would leave the rendering in the on state.

fix(Rendering): make sure scalar visibility works properly

---

Sources/Rendering/Core/Camera/index.js

The clipping range was applied correctly resulting in
bad clippinig of the data.

fix(Rendering): fix the matrix calc for parallel projection

---

Sources/Common/Core/Points/index.js
Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js
Sources/Interaction/Widgets/SphereHandleRepresentation/index.js
Sources/Rendering/Core/InteractorStyle/index.js
Sources/Rendering/Core/Prop/index.js
Sources/Rendering/Core/RenderWindow/index.js
Sources/Rendering/Core/RenderWindowInteractor/index.js
Sources/Rendering/Core/Viewport/index.js
Sources/Rendering/OpenGL/Actor/index.js
Sources/Rendering/OpenGL/Camera/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/Renderer/index.js
Sources/Rendering/SceneGraph/ViewNode/index.js

Clean up some of the rendering interaction code to better
manage animating and to ignore render calls when in the
middle of interacting. Also remove some calls that were
rendering the still image twice.
Also some code cleanup to improve performance some. Still a ways
to go in cases with hundreds of actors.

fix(Rendering): some fixes and performance improvements

---

Sources/Rendering/OpenGL/Helper/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/VertexArrayObject/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

The old code was using emulation for webgl2 which
is slower and makes no sense.

fix(Rendering): use VAOs on webgl2 contexts

---

Sources/Rendering/Core/Prop3D/index.js
Sources/Rendering/Core/Renderer/index.js
Sources/Rendering/Core/Viewport/index.js
Sources/Rendering/OpenGL/Actor/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/Renderer/index.js
Sources/Rendering/OpenGL/ShaderProgram/index.js
Sources/Rendering/SceneGraph/ViewNode/index.js
Sources/macro.js

prop3d was reporting not identity all the time
More reduction in heap allocations.
Cache a couple frequently made opengl calls to avoid
unnecc webgl calls.

fix(Rendering): fix for prop3d isIdentity and more perf fixes

---

Sources/Rendering/Core/ImageMapper/index.js

gl-matrix 2.0 and up changed the vec3.normalize() API to
vec3.normalize(out, in), requiring explicit parameters for input and
output vectors.

fix(ImageMapper): Fix usage of vec3.normalize

---

Examples/Applications/VolumeViewer/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl
Sources/Rendering/OpenGL/glsl/vtkVolumeFS2.glsl

By default volume rendering will use a jitter texture
to reduce banding when the sample distance is too
large to the rate of changhe in the data.

feat(Rendering): add jitter to volume rendering

---

Sources/Rendering/Core/Glyph3DMapper/Constants.js
Sources/Rendering/Core/Glyph3DMapper/example/controlPanel.html
Sources/Rendering/Core/Glyph3DMapper/example/index.js
Sources/Rendering/Core/Glyph3DMapper/index.js
Sources/Rendering/Core/Mapper/Constants.js
Sources/Rendering/Core/Mapper/api.md
Sources/Rendering/Core/Mapper/index.js
Sources/Rendering/Core/index.js
Sources/Rendering/OpenGL/Glyph3DMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/test/testAddShaderReplacements.js
Sources/Rendering/OpenGL/ViewNodeFactory/index.js
Sources/Rendering/OpenGL/index.js
Sources/Testing/Examples/ActorSerialization/example/actor.json

This is a first implementaiton of a glyph3d mapper
designed to more quickly render colored, scaled,
positioned, and oriented glyphs. This is a first
cut and will be followed quickly by an update that
adds a faster rendering path for implementations
that support instancing like webgl 2

fix(Rendering): add a glyph3d mapper

---

Sources/Rendering/OpenGL/BufferObject/index.js
Sources/Rendering/OpenGL/Camera/index.js
Sources/Rendering/OpenGL/CellArrayBufferObject/index.js
Sources/Rendering/OpenGL/ForwardPass/index.js
Sources/Rendering/OpenGL/Framebuffer/index.js
Sources/Rendering/OpenGL/Glyph3DMapper/index.js
Sources/Rendering/OpenGL/HardwareSelector/index.js
Sources/Rendering/OpenGL/Helper/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/PixelSpaceCallbackMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/Renderer/index.js
Sources/Rendering/OpenGL/SphereMapper/index.js
Sources/Rendering/OpenGL/StickMapper/index.js
Sources/Rendering/OpenGL/Texture/index.js
Sources/Rendering/OpenGL/VertexArrayObject/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

Add support for instanced rendering for webgl2 glyphs
Fix an issue with image mapper not redrawing correctly
after a modification.
Cleanup the use of window versus olgwindow versus
openGLRenderWindow naming to be more consistent.
Move more towards setting the window as opposed to the context.

fix(Rendering): instanced glyphs, cleanup, fix imaging

---

Sources/Rendering/OpenGL/PolyDataMapper/index.js

They were being cached too aggresively.

fix(Rendering): camera matricies were not being updated

---

.eslintrc.js
Examples/Geometry/VR/controller.html
Examples/Geometry/VR/index.js
Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js
Sources/Rendering/Core/Camera/index.js
Sources/Rendering/Core/InteractorStyle/Constants.js
Sources/Rendering/Core/InteractorStyle/index.js
Sources/Rendering/Core/RenderWindowInteractor/Constants.js
Sources/Rendering/Core/RenderWindowInteractor/index.js
Sources/Rendering/Core/Renderer/index.js
Sources/Rendering/Misc/FullScreenRenderWindow/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js

Tested on Firefox with the Vive. Supports the notion
of WorldToPhysical coordinate systems and uses the
gamepad API to poll controller events. Currently the
right controller trackpad is used to control movement.
ResetCamera will compute reasonable values for PhysicalScale
and PhysicalTranslation.
Still needs to be tested against DayDream and other VR
systems. Support for their gamepads needs to be added.

feat(Rendering): Add initial support for WebVR

---

Sources/Rendering/Core/Camera/api.md
Sources/Rendering/Core/Camera/index.js
Sources/Rendering/Core/PixelSpaceCallbackMapper/index.js
Sources/Rendering/Core/Renderer/index.js
Sources/Rendering/OpenGL/Camera/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js

Remove the Transform from some method names as we do not
have a Transform class. The old names were returning the
Transform's matrix. The vtk.js methods have no transform
so the name doesn't really make sense. We are just returning
the matrix.

style(Rendering): clean some camera method names

---

Sources/Rendering/OpenGL/ImageMapper/index.js

When trying to add an actor with an image with 4 components, the shader can't build. It seemed that the vec4 constructor wasn't good. 
Does @martinken can confirm ?

fix(OpenGLImageMapper): shader modification to create a vec4

---

Sources/IO/XML/XMLReader/index.js

Since we only need to set the first several bytes as the length header,
simply create an array view that has length 1.

fix(XMLReader): Buffer length may not fit the typed array

---

Sources/Testing/testUtils.js

When an image comparison test fails, the recorder will now also record
the difference image in Documentation/content/coverage/tests.md

test(testUtils): Show a difference image in the test log

---

Sources/IO/XML/XMLReader/index.js

This only affects data files whose data arrays' uncompressed sizes align with 32768 (or whatever the uncompressed block size is specified in the compression header).

Fix incorrect interpretation of last block size in zLib+appended vt* formats

---

Sources/IO/Misc/OBJReader/index.js

If an obj file has spaces at the end of faces line, it adds a non existing point to the face
Example:
"f 10 10 10  " will create a face with 4 points and the last one will point to a memory adresse that doesn't exist.

perf(OBJReader): Filters faces if spaces have been added

---

Sources/Rendering/Core/ImageMapper/example/index.js

Default slice mode was `None`. Since d0bec193, the slicing from
camera focal point is based on the slicing mode. We therefore
use the slicing mode in this example as well as adjust the camera
orientation to face the slicing axis.

fix(imageMapper): fix example by setting slicing mode

---

Sources/Interaction/Widgets/OrientationMarkerWidget/index.js

A previous commit in the most recent merge request dealing with this
file removed control over widget corner placement.

fix(OrientationMarkerWidget): Regression in widget corner specification

---

Sources/Proxy/Representations/VolumeRepresentationProxy/index.js

To access the lookuptable, use:
`getLookupTableProxy(${arrayName}).getLookupTable()`
Same thing with piecewiseFunction.

fix(VolumeRepresentationProxy): remove useless get macro

---

Sources/IO/Core/BinaryHelper/index.js

This also removes some old code that likely doesn't persist arraybuffers in memory, but might as well remove them just in case.

fix(BinaryHelper): Use TextDecoder for arraybuffer->string

---

Sources/IO/Core/BinaryHelper/index.js

Latin1 is single byte encoding, which is what we want for a 1-to-1
conversion of the arraybuffer to a string.

fix(BinaryHelper): Use latin1 for text decoding

---

Sources/Interaction/Widgets/AbstractWidget/api.md
Sources/Interaction/Widgets/AbstractWidget/index.js
Sources/Interaction/Widgets/HandleWidget/api.md
Sources/Interaction/Widgets/HandleWidget/index.js
Sources/Interaction/Widgets/ImageCroppingRegionsWidget/index.js
Sources/Interaction/Widgets/LineWidget/index.js
Sources/Rendering/Core/RenderWindowInteractor/index.js
Sources/macro.js

Abstract widget events handling

---

Sources/Rendering/OpenGL/Glyph3DMapper/index.js

It was producing bad shaders when edge visibility was on

fix(Rendering): fix glyph mapper with edge visibility on

---

Sources/Rendering/OpenGL/Glyph3DMapper/index.js
Sources/Rendering/OpenGL/HardwareSelector/index.js
Sources/Rendering/OpenGL/HardwareSelector/test/testHardwareSelectorGlyph.js
Sources/Rendering/OpenGL/glsl/vtkPolyDataVS.glsl
Sources/tests.js

Now picking on a glyoph3dmapper should fill the composite id
of the glyphs that were picked.

fix(Rendering): glyph3dmapper honors the composite_index pass

---

BREAKING_CHANGES.md

`pinch` was replaced by `scroll` in 92bd10ae, but then replaced by `scrollEnabled` in 5920eea0, both within the switch to 6.0.

doc(BREAKING_CHANGE): remove reference to scroll

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

The `Set` was shared between every instance of RenderWindowInteractor.
Co-Authored-by: @floryst

fix(RenderWindowInteractor): do not share animation requesters

---

Sources/Interaction/Style/InteractorStyleManipulator/index.js
Sources/Rendering/Core/RenderWindowInteractor/index.js

Do not use same key for animations due to mouse drag and due to mouse wheel
or the second event will not be registered as an animation requester, and
the animation will stop when the first event terminates.
@jourdain no rush to integrate it on my side, can be merged with anything else that comes up later.

fix(InteractorStyleManipulator): properly register animation requesters

---

Sources/Rendering/OpenGL/Texture/index.js

Co-authored-by: Ken Martin <ken.martin@kitware.com>

perf(Texture): Only scale cube texture to power of two when not WebGL2

---

Sources/Filters/Sources/CubeSource/index.js

This is follow-up to Kitware/vtk-js@12681ad21d4893d454eff87165aeb1d421120008. A translation was
added there even though the center translation already occurs in the preceeding code.
CC: @jourdain @scottwittenburg

fix(CubeSource): Do not translate twice

---

Examples/Volume/MultiSliceImageMapper/controlPanel.html
Examples/Volume/MultiSliceImageMapper/index.js
Sources/Common/DataModel/ITKHelper/index.js
Sources/Interaction/Manipulators/MouseRangeManipulator/example/index.js
Sources/Interaction/Widgets/ImageCroppingRegionsWidget/example/controlPanel.html
Sources/Interaction/Widgets/ImageCroppingRegionsWidget/example/index.js
Sources/Proxy/Core/AbstractRepresentationProxy/index.js
Sources/Proxy/Core/View2DProxy/index.js
Sources/Proxy/Representations/SliceRepresentationProxy/index.js
Sources/Proxy/Representations/VolumeRepresentationProxy/index.js
Sources/Rendering/Core/ImageMapper/Constants.js
Sources/Rendering/Core/ImageMapper/example/index.js
Sources/Rendering/Core/ImageMapper/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js

- Needed to transpose it from ITK to VTK.
- Tested with numerous datasets with orientation matrices different than identity.
- Only supports it if X, Y, Z are orthogonal to I, J, K axis for now (aka flips and permutations). Will still do it if one of those component is > 0.99 (so with a small tilt). All world axis that do not perfectly align one of IJK axis should require a reformat to compute the slice, but this will be added in future work (@martinken promised :clinking_glasses: )
- Still use indexes for X, Y, Z for now (instead of world coordinates) since they currently still map to IJK. In the future, X, Y, Z or any world axis slicing (ex: normal to the camera or to a plane widget...) should be in world coordinates (based on imagedata spacing/bounds).

Fix orientations + XYZ slicing

---

Sources/Interaction/Widgets/PiecewiseGaussianWidget/ComputeHistogram.worker.js
Sources/Rendering/OpenGL/Texture/ComputeGradients.worker.js

This addresses builds with
npm run build:release
Uglify bundled with Webpack does not support ES6, and chokes on ES6
constructs. Workarounds described:
https://stackoverflow.com/questions/42633716/unexpected-token-punc-expected-punc-when-creating-chunk-from-uglifyjs
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/104
do not work reliably.
As described at https://github.com/webpack-contrib/uglifyjs-webpack-plugin
webpack =< v3.0.0 currently contains v0.4.6 of this plugin under
webpack.optimize.UglifyJsPlugin as an alias. For usage of the latest version
(v1.0.0), please follow the instructions below. Aliasing v1.0.0 as
webpack.optimize.UglifyJsPlugin is scheduled for webpack v4.0.0
So refactor the web workers to use ES5, and revert this patch after moving to
Webpack 4.
CC: …

fix(Webpack): Fix webworker webpack release build

---

Sources/Common/DataModel/PolyData/index.js
Sources/IO/XML/XMLImageDataReader/index.js
Sources/IO/XML/XMLPolyDataReader/index.js
Sources/Rendering/Core/Glyph3DMapper/index.js
Sources/Rendering/Core/Mapper/index.js
Sources/Rendering/Core/RenderWindow/index.js

`getNumberOf*` methods on polydata were incorrectly capitalized as `getNumberOfverts`, when it should be `getNumberOfVerts`, and so forth.
Other minor changes and spelling changes.

Misc fixes

---

Sources/Rendering/OpenGL/Texture/index.js

Co-Authored-by: @martinken 
fix #609 and https://github.com/Kitware/pv-web-viewer/issues/29

fix(OpenGLTexture): correct reformattedGradients size in webGL1

---

Sources/Rendering/Core/VolumeMapper/example/index.js

Otherwise, a re-render does not occur until the user clicks on the
scene.

fix(VolumeMapperExample): Update rendering after lighting activated

---

Sources/Rendering/OpenGL/Texture/ComputeGradients.worker.js
Sources/Rendering/OpenGL/Texture/index.js

Performance improvements (& windows fixes)

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

Fix the problem in mobile device when user touches renderWindow, release touches and then use GUI component. The mouse/touch event weren't removed.

fix(RenderWindowInteractor): Disable mouse/touch event listener

---

Sources/Rendering/Core/CellPicker/index.js
Sources/Rendering/Core/Picker/index.js

getMatrix() function returns a reference to the matrix. As we revert the matrix, it modifies the original which is not requested.

fix(Picker): Deep copy matrix to not modify original matrix

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

When an arrow key is pressed 'keyPressEvent' is not emited. 
Listening 'keyDownEvent' fix this.

fix(RenderWindowInteractor): handle keydown event

---

Sources/Rendering/Core/AnnotatedCubeActor/index.js

Textures got inverted in 43ed0fb, so as a workaround we Y-flip the faces.  @agirault

fix(AnnotatedCubeActor): Vertically flip face textures

---

Examples/Applications/SkyboxViewer/index.js
Examples/Applications/SkyboxViewer/index.md
Sources/Rendering/OpenGL/ForwardPass/index.js
Sources/Rendering/OpenGL/Framebuffer/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/Skybox/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

Add a second order radial distorion pass to vtk.js
To support this, change the size queries on render
window to use the size of the active framebuffer
which may be the hardware buffer or a framebuffer
object.
Fix an issue in the skybox where the interpolaiton of
coordinates was incorrect. Most noticable for larger
view angles.

fix(Rendering): add distortion pass, fix sizing, skybox

---

Sources/Common/DataModel/PiecewiseFunction/index.js
Sources/Proxy/Core/PiecewiseFunctionProxy/Constants.js
Sources/Proxy/Core/PiecewiseFunctionProxy/index.js
Sources/Proxy/Core/PiecewiseFunctionProxy/test/testPiecewiseFunctionProxy.js
Sources/Proxy/Core/index.js
Sources/Proxy/Representations/VolumeRepresentationProxy/index.js
Sources/Testing/testUtils.js
Sources/tests.js

Adds Points and Nodes modes to piecewise function proxy. 
Adds `arrayEquals` and `objEquals` to test utils. Adds PiecewiseFunctionProxy test.
Fixes naming error in PiecewiseFunction (Midpoint -> midpoint, Sharpness -> sharpness).

PiecewiseFunctionProxy modes

---

Sources/IO/Misc/ITKImageReader/index.js
package-lock.json

itk.js 9.0.0 contains breaking changes. This changeset keeps
ITKImageReader backwards compatible with pre-9.0.0 itk.js installs.
This just terminates all webworkers after a single use. Do we want this configurable?
@thewtex

fix(ITKImageReader): Support itk.js 9.0.0

---

Sources/Interaction/Widgets/LineWidget/index.js
Sources/Rendering/Core/InteractorObserver/index.js

In Manipulate mode, when hovering the render window, the LineWidget could trigger an unnecessary
InteractionEvent and refresh

fix(LineWidget): Do not unnecessary refresh view on mouse move

---

Sources/Filters/General/MoleculeToRepresentation/index.js

Took some debugging to understand why the example would work fine, but the bond colors would be wrong when running interactively in Paraview Glance. In the end it was a one line fix.

fix(MoleculeToRepresentation): Fix bond colors when hiding atoms interactively

---

Sources/Interaction/Widgets/ImageCroppingRegionsRepresentation/Constants.js
Sources/Interaction/Widgets/ImageCroppingRegionsRepresentation/index.js
Sources/Interaction/Widgets/ImageCroppingRegionsWidget/Constants.js
Sources/Interaction/Widgets/ImageCroppingRegionsWidget/example/index.js
Sources/Interaction/Widgets/ImageCroppingRegionsWidget/index.js

This iteration of the crop widget provides a means of manipulating a box in 3D space. Cropping planes are exported out via an event or via `widget.getCroppingPlanes()`. This is a first pass.
There are three sets of control handles: face handles, edge handles, and corner handles.
A small demo is shown below with face and corner handles.
@jourdain @martinken @wschroed @aylward

Crop widget v2

---

Sources/Rendering/Core/Camera/index.js

This change provides the ability to set the camera key matrices directly
from an external application. This ability opens up the posibility of
integrating vtk-js within a larger WebGL application.

refactor(Camera): Allow setting key matrices directly

---

Sources/Proxy/Core/ProxyManager/state.js

There shouldn't be any reason to set this to 1000 that I can tell, so set this timeout to 0 so renderers don't "jump" after 1 second.

fix(ProxyManager): Set state rendering timeout to 0

---

Sources/Rendering/Core/Light/api.md

Following https://github.com/Kitware/vtk-js/commit/393eed5, the Light class no longer has separate ambient, diffuse, and specular color attributes. Update the documentation to reflect this change.

docs(Light): Update color attribute documentation

---

Sources/Proxy/Core/ViewProxy/index.js

This prevents multiple calls to requestAnimation with the same ViewProxy
publicAPI as the requestor, for example, during pipeline initiation
prior to rendering when ViewProxy.updateOrientation may be called
multiple times.

fix(ViewProxy): Use unique animation requestor id in updateOrientation

---

Sources/Rendering/OpenGL/Texture/index.js

Base and max levels should be sent to WebGL in order to be able to access all levels through `textureLod`.  
Remove `generateMipMap` for cubemaps (all levels are manually uploaded).

fix(Rendering): Update maxLevel of texture mipmap

---

Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/SphereMapper/index.js
Sources/Rendering/OpenGL/StickMapper/index.js

The stick, sphere, and coincincident point support was
not fully working on webgl2 resulting in incorrectly rendered
spheres/sticks/polydata. This topic fixes that.

fix(Rendering): support FragDepth on webgl2

---

Sources/IO/XML/XMLReader/index.js

appendedBuffer can either be a String or ArrayBuffer.
Fixes: https://github.com/Kitware/paraview-glance/issues/195

fix(XMLReader): Incorrect offset assignment

---

Sources/Filters/General/ImageCropFilter/index.js

Fixes cropping multi-component, e.g. RGB, images.
Rename byteSize to componentSize.
Move computation of beginOffset and stripSize out of the inner loop.

fix(ImageCropFilter): Fix cropping multi-component images

---

Sources/Rendering/OpenGL/Glyph3DMapper/index.js
Sources/Rendering/OpenGL/HardwareSelector/index.js
Sources/Rendering/OpenGL/HardwareSelector/test/testHardwareSelectorSpeed.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/StickMapper/index.js

Since we only support Actor and composite picking we can
make it run quite a bit faster by not rebuilding shaders
and skipping the LOW_ID pass. Current takes about 2.5 times
the cost of a sequental render for 500 actors.

perf(Picking): improve picking performance

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

All mouse interactions (left, middle and right button) are stopped once the cursor leaves the renderwindow. This is necessary because the buttonUp events are not received if the cursor is outside the renderwind
ow. In my opinion, this fix greatly improves the usability.

fix(RenderWindowInteractor): listen to mouseleave event

---

Sources/Common/DataModel/ImageData/index.js

The index to world and world to index transforms were
incorrect when the image had a direction that included
an inverted axis.

fix(Rendering): fix ImageData transformations

---

Sources/Rendering/Core/Prop/index.js
Sources/Rendering/Core/Viewport/index.js

Calling code is expecting to be able to concat the results of these functions. For example see the implementation of vtkRenderer::getActors() implementation. The current implementation
ends up with nulls in the array and iteration issues.

fix: return [] rather than null

---

Sources/Filters/General/index.js
Sources/Widgets/Widgets3D/index.js

The paint widget code was merged, but isn't included in the dist/vtk.js build without this export.

fix(widgets): add exports for PaintWidget

---

Sources/Rendering/Core/ImageMapper/example/index.js
Sources/Rendering/Core/ImageProperty/api.md
Sources/Rendering/Core/ImageProperty/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js

This adds a scalarOpacity function to ImageProperty, and adds support for it in ImageMapper.
Helps address #714 
Does having a scalarOpacity function for images make enough sense as a whole? To me, this seems like a reasonable approach for layering transparent images on top of one another. Also, as I've not done WebGL much before, a code review would be great @jourdain @martinken

Add opacity function to ImageProperty

---

Sources/Rendering/OpenGL/Texture/index.js

See https://bugs.chromium.org/p/chromium/issues/detail?id=896307 for details on this bug and a minimal reproducing example.

fix(Texture): Work around a Chrome canvas-webgl bug

---

Sources/Interaction/Manipulators/MouseRangeManipulator/example/index.js
Sources/Interaction/Manipulators/MouseRangeManipulator/index.js
Sources/Proxy/Core/View2DProxy/index.js

Modifieds View2DProxy and MouseRangeManipulator to support non-integer steps when performing window width/level operations, i.e. in the range [0,1].
Seems to fix https://github.com/Kitware/paraview-glance/issues/217, and fixes #808 as well.

Allow for non-integer steps in MouseRangeManipulator

---

Sources/Proxy/Core/ProxyManager/state.js

Previously, restoring representations after restoring LUTs/PWFs resulted in the restored LUT/PWF data ranges being reset (in the case of vtkVolumeRepresentationProxy). To preserve the restored LUT/PWF states, we restore these after the representations have been restored.
Also fixes incorrect code when setting LUT and PWF data ranges.

fix(ProxyManager): Restore luts/pwfs after representations

---

Sources/IO/Core/ImageStream/index.js

Make it possible to create your own ViewStream and register it
in the ImageStream:
```
function createMyViewStream(imageStream, viewId = '-1', size = [400, 400]){
const { setServerAnimationFPS,
getServerAnimationFPS,
unregisterViewStream } = imageStream;
const viewStream = MyViewStream.newInstance({
protocol: imageStream.getProtocol(),
unregisterViewStream,
sharedAPI: {
setServerAnimationFPS,
getServerAnimationFPS,
},
});
viewStream.setViewId(viewId);
viewStream.setSize(size[0], size[1]);
return viewStream;
};
const viewStream = createMyViewStream(imageStream, viewId);
view.imageStream.registerViewStream(viewStream);
```

feat(ImageStream): Add ViewStream inheritance support

---

Sources/Interaction/Style/InteractorStyleManipulator/index.js

Reference conversation: https://github.com/Kitware/vtk-js/commit/ba24cf817e6636e52c3dd9967ac9630965457fd5#commitcomment-31598937
Since we are handling keyboard modifiers for wheel events, we need a separate "current wheel manipulator" tracker.

InteractorStyleManipulator: Don't mix wheel manips with mouse manips

---

Sources/Proxy/Core/ProxyManager/core.js

The views bind listeners to global object document.body. When deleting views with ProxyManager, the listeners should be removed to prevent a memory leak.

fix(ProxyManager): Unbind DOM event listener before deleting proxy

---

Sources/Proxy/Core/ProxyManager/core.js

Check if view proxy has container before try to unbind when deleting view proxy.
This is a bug fix for https://github.com/Kitware/vtk-js/pull/994

fix(ProxyManager): Use setContainer() to gain ability to check if unbind is needed

---

Sources/Common/Core/MatrixBuilder/index.js

Use a more tolerant epsilon. I was running into issues where epsilon was too narrow, resulting in a zero vector after vector transformation.

fix(MatrixBuilder): Use a more tolerant epsilon for zero-comparison

---

Utilities/config/dependency.js

Fixes #993 
I tested this on the geode repo and this alleviated the need for the babel.config workaround (namely `ignore: [/\/core-js/]`).

Scope build rules to source tree

---

Sources/Rendering/OpenGL/RenderWindow/index.js

Fixing VR in chrome issue "submitFrame must be called within a VRDisplay.requestAnimationFrame"
Note: tested on Chrome 72 (64-bit) & Firefox 65.0 (64-bit)

Update OpenGl RenderWindow index.js

---

Utilities/config/dependency.js

This addresses a regression from
5f2439e03981bc00ef5f3c14950782c646119951
where sources are ignored for required Webpack loaders on Windows.

fix(DependencyWebpackRules): vtk.js source identification on Windows

---

Sources/Rendering/OpenGL/RenderWindow/index.js

Stop adding bgImage to DOM unless setBackgroundImage has been called.
Background images are necessary for remote rendering, but the `<img>` tag is currently being added to
the DOM unnecessarily, even if the user is not using remote rendering. This change prevents this
from occurring.
fix #1007 
This fix seems to be working for me.

fix(OpenGL/RenderWindow): Stop adding bgImage to DOM

---

Examples/Geometry/DepthTest/index.js
Examples/Geometry/SpheresAndLabels/index.js

Adds interactor styles to two examples that didn't have them.
Fixes #981. Pinging #1011 because it references this issue.

fix(Examples): Add interactors to DepthTest and SpheresAndLabels

---

Sources/Filters/General/PaintFilter/index.js

Correctly record history when using voxelFunc to threshold voxels.
Fixes #1028 
@agirault

fix(PaintFilter): Record history when using voxelFunc

---

Sources/Interaction/Manipulators/MouseRangeManipulator/example/index.js
Sources/Interaction/Manipulators/MouseRangeManipulator/index.js

Reverts part of 2fca89d.
Fixes #1035 
To test:
```
git checkout patch-mouse-range-manipulator
npm run example -- ImageMapper
```

fix(MouseRangeManipulator): Round stepsToDifference

---

Sources/Filters/General/PaintFilter/index.js
Sources/Widgets/Widgets3D/PaintWidget/example/index.js

Uses a more memory-intensive approach to undo/redo that is simpler and more flexible in history length.
Older approach had issues with incorrect undo behavior when restoring label values.

Paint filter: better undo redo

---

Sources/Widgets/Core/WidgetManager/index.js

Similar to when we update our subscriptions with the interactor "onEndAnimation" event (a little
higher up in setRenderer()), we should first check if picking is enabled before calling the method
to enable it.

fix(WidgetManager): Support turning off picking before setRenderer()

---

Sources/IO/Core/ImageStream/ViewStream.js
Sources/Interaction/Style/InteractorStyleRemoteMouse/index.js

Make sure the remote image re-renders when the mouse is released
when there's no camera.
Re-order events on mouse interaction so high-DPI displays get
the right starting offset, because the image size changes.

fix(ViewStream): Trigger remote image render and interaction fix

---

Sources/Rendering/Core/Mapper/index.js
Sources/Rendering/OpenGL/CellArrayBufferObject/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js

This PR allows the user to upload point data attributes to the VBO in order to access them from a custom shader.  
The name of the attribute in the shader is the name of the array with the suffix `MC` standing for `Model Coordinates`.

feat(PolyDataMapper): Upload point data to VBO

---

Sources/IO/XML/XMLImageDataReader/index.js
Sources/IO/XML/XMLPolyDataReader/index.js

These methods did the same work as the "superclass", except they invoked a method which doesn't actually exist.

fix(XMLReaders): Remove broken methods from sub-types

---

Sources/Rendering/OpenGL/ForwardPass/index.js
package-lock.json

Modified ForwardPass to render layered renderers in correct order.
Rendering order was always based on the order that renderers were added to the renderwindow regardless of the layer number setting of the renderer. Modified ForwardPass to render by layer number order.

fix(ForwardPass): Render layered renderers in correct order

---

Sources/Rendering/Core/Renderer/index.js

The prior default of 1 caused nothing to be drawn

fix(Rendering): set default rendering layer to 0

---

Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/Texture/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl
webpack.settings.js

Add support for multicomponent volumes with 2, 3, or 4
components, with or without gradient opacity, and both
dependent and independent components.

feat(Rendering): add support for multiple component vtkVolume

---

Sources/IO/Core/ImageStream/index.js

The subscription variable name was incorrect, and
the connected flag needed to be turned off.

fix(ImageStream): typo in disconnect

---

Sources/Rendering/OpenGL/Volume/index.js

Initialize model.keyMatrixTime with mtime=0 so that actor matrices are calculated on first pass

fix(OpenGLVolume): Properly initialize keyMatrixTime with mtime=0

---

Sources/Rendering/OpenGL/Texture/index.js

This workaround was causing performance issues.  
Removing it since the bug was fixed in Chrome 70.

fix(perf): Remove Chrome 69 fix

---

Sources/Common/DataModel/ITKHelper/index.js
Sources/Interaction/Widgets/ResliceCursor/example/index.js

Support reading multi-component images from itk.js.
All pixel data is added to the vtkImageData's PointData "Scalars" to
facilitate multi-component volume rendering.
If the itk.js PixelType is Vector or CovariantVectors and the dimension
is 3 and there are 3 vector components, the DataArray is also set as the
vtkImageData's PointData "Vectors". VTK does not distinguish vectors and
covariant vectors. ITK images can be N-dimensional and the number of
vector components do not always match the image dimension.
If the itk.js PixelType is SymmetricSecondRankTensor or
DiffusionTensor3D and the dimension is 3 and there are 6 tensor
components, the DataArray is also set as the vtkImageData's PointData
"Tensors".

fix(ITKHelper): Support multi-component pixel types

---

Sources/Filters/General/ImageCropFilter/example/controlPanel.html
Sources/Filters/General/ImageCropFilter/index.js
Sources/Rendering/OpenGL/Texture/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

Fix an issue where a texture is reused multiple times
with cropped data.
Fix an issue with the crop filter where the inputs
extent is not considered when computing offsets.
Fix a rendering issue where the mapping of the volume
to pixels was not quite correct resulting in deformations
when rendering cropped images.

fix(Rendering): fix bugs in volume Rendering

---

Sources/Rendering/Core/Camera/api.md
Sources/Rendering/Core/Camera/index.js

Refactor Camera code for clarity, moving unimplemented functions together, implemented `applyTransform()` function.
Fix docs to remove bad references, update function defs to be more clear.
Removed "Scissor" references that were not implemented nor referenced anywhere, even in VTK C++ code.
Related to https://github.com/Kitware/vtk-js/issues/1135

refactor(Core/Camera): Refactor Camera Docs, implement applyTransform()

---

Sources/Interaction/Style/InteractorStyleMPRSlice/index.js

fix(InteractorStyleMPRSlice): Keep clipping range consistent between mouse movement and initial setup
This is a tiny change that I have already discussed once with @floryst. Essentially we use 0.1 in one place:
https://github.com/Kitware/vtk-js/blob/c9fa0ceb23390af7b9059056b18024ffa96fa9c5/Sources/Interaction/Style/InteractorStyleMPRSlice/index.js#L295-L300
and 1 in the other for the width of the clipping range. It seems more sensible to make them both 0.1.
I'm only sending this PR because I ran into different behaviour in the mapper during mouse movement / initial setup.
Right now changing this won't really have much impact, but in an upcoming PR we have a special path for cases where the ray path distance is less than sampling distance, and in that case this value being smaller will …

fix(InteractorStyleMPRSlice): Keep clipping range consistent

---

Sources/Filters/Sources/CylinderSource/index.js

Fixes issue where points were not being centered around origin before applying rotation.

fix(CylinderSource): Translate points to center before rotate

---

Sources/Common/Core/MatrixBuilder/api.md
Sources/Common/Core/MatrixBuilder/index.js

BREAKING CHANGE: Remove getVTKMatrix function as it had a side-effect, was poorly named, and was not referenced anywhere else. If the user wants to transpose the matrix, they can do it after calling `getMatrix()`

docs(MatrixBuilder): Create documentation for and refactor MatrixBuilder class

---

Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

Addresses #1146 
- Checks inside `computeIndexSpaceValues` if the length of the ray is smaller than the sample distance. If so, sets numSteps to 1.0 so we can skip some unnecessary computations
- Adds early exits for each blend mode in case numSteps is 1.0. In this case, we can skip the whole ray traversal loop and just take the first value.
- Stores the initial position along the ray so it can be passed to applyBlend as startResidualIS.
The idea is that the first sample along the ray would be from the initial position in the volume, and then there would be the usual sampling loop up to 1-step away from the end, and finally the residual step to sample the end position. That is why we are computing `initialPosIS = posIS - startResidual`.
I'm leaving this as a draft for now because I am …

fix(vtkVolumeFS): Address sampling issues during thin-slice volume rendering

---

Sources/Widgets/Representations/SplineContextRepresentation/index.js

feat(SplineContextRepresentation): Do not display error border when less than three points are given.

---

Sources/Rendering/OpenGL/HardwareSelector/index.js

When there were hundreds of actors the math was incorrect
being done in float instead of int.

fix(Rendering): fix hardware selection of many actors

---

Sources/Widgets/Core/WidgetManager/index.js
Sources/Widgets/SVG/SVGRepresentation/index.js
Sources/Widgets/Widgets3D/DistanceWidget/index.js

- change where SVG layer is inserted (immediately after canvas)
- don't buffer points when calling worldPointsToPixelSpace. This was from an old idea that was scrapped, but the code wasn't changed to reflect that we don't need to buffer anymore.

Misc SVG widget changes

---

Sources/Common/DataModel/Plane/api.md
Sources/Common/DataModel/Plane/index.js
Sources/Common/DataModel/Plane/test/testPlane.js

Similar to, but not the same as the c++ vtk plane logic, where the c++ version expects a
bound/finite plane and an infinite plane. While the function title might assume being passed another vtkPlane object, I did not build in such function overloading, so the function call expects the normal and origin as separate vectors.
Also updates the documentation for visual clarity and grammar.
With both Plane intersection and Line intersection, I can then build a "3 plane intersection" function.

feat(vtkPlane): Add intersectWithPlane function

---

Sources/Filters/General/PaintFilter/index.js

@floryst , this PR just returns a promise from `endStroke` that resolves to the `strokeBuffer`.
re #1207

feat(Sources/Filters/General/PaintFilter/index.js): Return strokeBuffer promise from paint filter.

---

Sources/IO/Geometry/DracoReader/example/index.js
Sources/IO/Geometry/DracoReader/index.js
Sources/IO/Geometry/index.js
package-lock.json
package.json
webpack.common.js

This pull requests adds vtkDracoReader, a reader for (triangle) meshes that were compressed using Google's Draco library.
The reader decodes the draco file, and provides the decoded mesh as vtkPolyData. Supports normals and texture coordinates.
This PR has a dependency to the draco3d package. I'm not certain what the best course of action is to add this dependency.
Draco: https://github.com/google/draco
Note: I lack experience with both JS and vtk.js, so any feedback is welcome.

WIP: feat(vtkDracoReader): Add Draco reader

---

Sources/Filters/General/OutlineFilter/index.js
Sources/Widgets/Representations/CroppingOutlineRepresentation/index.js
Sources/Widgets/Representations/OutlineContextRepresentation/index.js
Sources/Widgets/Widgets3D/ImageCroppingWidget/behavior.js
Sources/Widgets/Widgets3D/ImageCroppingWidget/helpers.js
Sources/Widgets/Widgets3D/ImageCroppingWidget/index.js
Sources/Widgets/Widgets3D/ImageCroppingWidget/state.js

This creates CroppingOutlineRepresentation just for the ImageCroppingWidget and makes OutlineContextRepresentation use bounding box.
Bounding box doesn't work for oriented images, so we have CroppingOutlineRepresentation to show the cropping for an oriented image.
Also exports the bounds map and line array from outline filter.

Fix cropping outline

---

Sources/Common/Core/DataArray/index.js

Allows a provider to set the range of a DataArray after its construction. This is useful if you are don't know the value a priori, so can't set it on construction, but have it external to vtkjs by the time you wish to make calls to `getRange`.
For example in my current usecase I am filling up the data array as it comes from an external source, and wish to set the range as the buffer is filled.

feat: 🎸 setRange functionality for DataArray

---

package-lock.json
package.json

This change updates the resemblejs package from 3.1.0 to 3.2.3 and fixes VTK.js build with node v12.
The updated files come directly from running `npm install resemblejs@3.2.3` (npm 6.11.3, node v12.11.1).
See also:
https://github.com/rsmbl/Resemble.js/issues/176

fix: Fix compilation with node v12 by updating resemblejs

---

package-lock.json
package.json

This is an attempt to remove the es6-promise transitive dependency
causing an issue as reported in
https://github.com/InsightSoftwareConsortium/itkwidgets/issues/216.

fix(Dependencies): Bump jszip to v3.2.2

---

Sources/Proxy/Core/ViewProxy/index.js
Sources/Rendering/OpenGL/HardwareSelector/index.js
Sources/Widgets/Core/WidgetManager/Constants.js
Sources/Widgets/Core/WidgetManager/example/index.js
Sources/Widgets/Core/WidgetManager/index.js

Adds `captureOn` option. When it is `CaptureOn.MOUSE_RELEASE`, capture will take place at end of scene animation, and will capture entire buffer. When it is `CaptureOn.MOUSE_MOVE`, capture will take place when mouse moves, and will capture just the pixel under the mouse cursor. Default value is MOUSE_RELEASE.
Addresses https://github.com/Kitware/paraview-glance/issues/270

Tweak hardware selector picking

---

Sources/Rendering/OpenGL/CellArrayBufferObject/api.md
Sources/Rendering/OpenGL/CellArrayBufferObject/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js

This implements coordinate shifting/scaling in vtk-js, similarly to the way it is currently implemented in VTK.
This fixes issues with large coordinates:
Before:
After: 
re: #1217
Attached: [test data](https://github.com/Kitware/vtk-js/files/3756779/TestMeshNotFollowingGeometryFix-mesh.vtp.tar.gz)  from #1217

feat: Add coordinate shift/scale to PolyDataMapper

---

Sources/Widgets/Core/WidgetManager/index.js

Widgets should be rendered for picking when capturing buffers.

fix(WidgetManager): Render picking buffer with capture-on-move

---

Sources/Rendering/OpenGL/HardwareSelector/index.js

This fixes an issue where the color picking buffer is antialiased when it shouldn't be, since beginSelection() wasn't binding the existing framebuffer.

fix(HardwareSelector): Existing framebuffer not being bound to context

---

Sources/Widgets/Core/WidgetManager/index.js
Sources/Widgets/Core/WidgetManager/vdom.js
Sources/Widgets/SVG/SVGRepresentation/index.js

Using a VDOM allows us to maintain the same SVG widget rendering API
while avoiding unnecessary updates to the DOM.

feat(WidgetManager): Use a simple vdom

---

Examples/Volume/VolumeOutline/index.js
Sources/Rendering/Core/VolumeProperty/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

This PR adds the option to render labelmaps with an outline of a specified thickness.
The logic is placed inside the VolumeMapperFS shader as it uses a lot of the same logic. If `useLabelOutline` is set true on the volume mapper the outline logic will be used.
The example is under `npm run example -- VolumeOutline`:
Example (Note the gif is compressed and the lines are smooth in actual usage):
I'm making this PR to get some initial feedback, but I understand the shader logic might need to be refactored somewhere else.
P.S. Quite new to writing shader code, if I've done anything stupid computationally I'd really appreciate constructive feedback! :)

Border fill

---

Sources/Interaction/Style/InteractorStyleManipulator/index.js

The array of manipulators can have `null` values since[ removing a manipulator will not remove its key from the list, but only set its value to `null`](https://github.com/Kitware/vtk-js/blob/a96658a/Sources/Interaction/Style/InteractorStyleManipulator/index.js#L181-L200).
Another fix instead would be to change the behavior of those `removeGesture` functions to actually remove the key/value and not just set the value to `null`, I can do that if you'd prefer @jourdain.

fix(Manipulators): Ensure manipulators aren't null

---

Sources/Common/DataModel/ImageData/index.js

Enables the use case:
image2.setDirection(image1.getDirection())

fix(ImageData): Support setDirection with Float32Array

---

Sources/Proxy/Core/ProxyManager/core.js

Need to unregister proxies that aren't in the same group as Views, Representations, and Sources.

fix(ProxyManager): Unregister proxies that don't need special cleanup

---

Sources/Common/Core/DataArray/api.md
Sources/Common/DataModel/ImageData/api.md
Sources/Common/DataModel/ImageData/index.js

* Write vtkImageData API Docs.
* Refactor vtkImageData functions to put similar functions in proximity, and return arrays in the worldToIndex and indexToWorld function, to match the behavior of the *bounds functions.
* Provide a new function to get the scalar data index from a given x,y,z world coordinate. This effectively matches the c++ function of `vtkImageData.getScalarComponentAsDouble()`
We needed the ability to select a point in screen space, convert to world space, then find the corresponding voxel index to get its value. Our c++ app used the above getScalar function, but I had to write the functionality locally. By having these functions in VTK, I can reduce my own code.
I debated also including a full `getScalarComponent` function that returned the actual voxel data, but wanted …

feat(vtkImageData): add getIndexFromWorld function

---

Sources/Widgets/Core/WidgetManager/index.js

This will allow for visually rendering widgets without having picking
enabled. In addition, this creates a clearly named method for rendering
widgets when some representation property has changed, e.g. SVG circle
color.

feat(WidgetManager): Split render method out from enablePicking

---

Sources/Interaction/Style/InteractorStyleManipulator/Presets.js
Sources/Interaction/Style/InteractorStyleManipulator/index.js

The first person interaction preset uses the keyboard for movement, and the mouse for "free look"
style camera interactions. This PR also provides a way to access the keyboard manipulator so that the movement speed can be set externally.

feat(InteractionPresets): Add first person interaction preset

---

Sources/Interaction/Manipulators/KeyboardCameraManipulator/example/index.js
Sources/Interaction/Manipulators/KeyboardCameraManipulator/index.js
Sources/Interaction/Manipulators/MouseCameraTrackballFirstPersonManipulator/example/index.js

resetMovementSpeed() generates a movement speed based upon the longest length of the rendering
bounding box. It is intended to just be a reasonable guess as to what a good movement speed would
be. The user is able to modify the movement speed via setMovementSpeed(). If the movement speed is
not set in the options when the KeyboardCameraManipulator is constructed, upon the first movement,
resetMovementSpeed() will be used to generate a reasonable speed.

feat(KeyboardCameraManipulator): Add ability to reset movement speed

---

Documentation/content/api/index.md
Documentation/content/examples/index.md

This just makes it so links will appear for them in the documentation.
My text editor automatically removes trailing white space. Let me know if I should undo the trailing white space removals...

docs(FirstPerson): Add docs and examples for first person manipulators

---

Sources/IO/Core/HttpDataSetReader/index.js

Previously,
```
reader.enableArray('pointData', 'arrayA');
reader.loadData();
```
would not effect the reader's output dataset, because `arrayA` had already been registered through `pointData.addArray`.
This change ensures array registration only occurs when the array data has been fetched by `reader.loadData()`.
It seems to work for my use case, but if I'm missing something please let me know!

fix(HttpDataSetReader): Only register newly loaded arrays to dataset

---

Sources/Rendering/OpenGL/PolyDataMapper/index.js

Add basic wide line support that relies on the lineWidth
function in webgl. Note that lineWidth in webgl is only
required to support a width of 1.0 (how dumb is that) so
this implementation may not work on your system. Support
for other lineWidths is vendor dependent.

feat(Rendering): add wide line support

---

Sources/Rendering/OpenGL/RenderWindow/index.js

Do not attach the background image on an undefined container

Fix OpenglRenderWindow::SetContainer

---

Sources/Rendering/Core/CellPicker/test/testCellPicker.js
Sources/Rendering/Core/Coordinate/Constants.js
Sources/Rendering/Core/Coordinate/api.md
Sources/Rendering/Core/Coordinate/index.js
Sources/Rendering/Core/Coordinate/test/testCoordinate.js
Sources/Rendering/Core/PointPicker/test/testPointPicker.js
Sources/Rendering/Core/Renderer/index.js
Sources/Rendering/Core/Viewport/api.md
Sources/Rendering/Core/Viewport/index.js
Sources/Rendering/OpenGL/Camera/index.js
Sources/Rendering/OpenGL/Glyph3DMapper/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/Skybox/index.js
Sources/Rendering/OpenGL/SphereMapper/index.js
Sources/Rendering/OpenGL/StickMapper/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkSphereMapperVS.glsl
Sources/Rendering/OpenGL/glsl/vtkStickMapperVS.glsl
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl
Sources/Rendering/OpenGL/glsl/vtkVolumeVS.glsl

view is now consistent between shaders and vtkCoordinate
projection is a new vtkCoordinate value that matches
what shaders used to call device coordinates.
This also makes the camer methods make more sense as
GetViewMatrix actually returns WCVC matrix and
GetProjectionMatrix returns VCPC

clean up coordinate system names

---

Sources/Rendering/OpenGL/RenderWindow/index.js

Fixes a small bug where a call to projectionToNormalizedDisplay was done as a member of the renderWindow (method doesn't exist) instead of the renderer.

fix(vtkOpenGLRenderWindow): Fix wrong call to projectionToNormalizedDisplay

---

Sources/IO/Legacy/LegacyAsciiParser/index.js

Use default value for numberOfComponents if not present
Some tools export legacy vtk without numberOfComponents if it is equal to 1. This is allowed, but vtk.js does not take it into account. 
On page 5 in the file-formats.pdf: "... the numComp variable is optional—by default the number of components is equal to one"

fix(LegacyAsciiParser): Use default value for numberOfComponents

---

Sources/Rendering/OpenGL/index.js

Add missing export of PixelSpaceCallbackMapper
For users who use dist-ready vtk.js, not webpack

fix(OpenGL): Add missing export of PixelSpaceCallbackMapper

---

Sources/Widgets/Core/WidgetManager/index.js

If the widgetManager is deleted, it does not unsubscribe to events. If an event is triggered
(svgSetSize for example), the vizualization will crash since widgetManager does no longer exist.

fix(WidgetManager): Unsubscribe to events when widgetManager is deleted

---

Sources/Widgets/Core/WidgetManager/index.js

WidgetManager may be deleted between updateSvg() and the promise
resolution callback.
Fixes #1382 @finetjul

fix(WidgetManager): Guard against object deletion

---

Sources/Widgets/Core/WidgetManager/index.js

Uses computed styles to determine if we need to update the vtk.js container's styles. @agirault

fix(WidgetManager): Better handling of svg layer CSS

---

Sources/Rendering/Core/ImageProperty/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js

This PR reduces the computation done to generate the lookup table and piecewise function strings used to determine whether those buffers should be rebuilt, while still causing them to rebuilt when necessary.  Also addresses an issue introduced by changing `setScalarOpacity` method to `setPiecewiseFunction` without providing the backward compatibility allowing the method to be called with a single argument.
Fixes #1396

More imagemapper fixes

---

Sources/Rendering/OpenGL/RenderWindow/index.js

Firefox 75 introduced a regression in vtk-js. The LabelWidget and HandleWidget examples for example show some strange flickering when moving the cursor over the widgets.
[This](https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=ae2a8d6e0c958b9d2d27c21b797100994bb488a2&tochange=73572c522da83cb8e8392c723da1f6a01c619250) is the change that introduced the regression.
What the change does is stop presenting the draw buffer when canvas size is modified but the size is the same as the current canvas size.
This affected us in vtk-js because changing cursor type (which widgets do a lot) also caused the canvas sizes to be modified. That's what this commit is preventing, and it seems like an effective workaround.

fix(vtkOpenGLRenderWindow): Only update canvas size when needed

---

Sources/Interaction/Widgets/index.js

Expose missing Reslice cursor classes to be able to reproduce the example using the vtk.js bundle
fix #1413

fix(Widgets): Expose missing classes

---

Sources/Rendering/OpenGL/Framebuffer/index.js
Sources/Rendering/OpenGL/ShaderProgram/index.js
Sources/Rendering/OpenGL/Texture/index.js

This brings a few fixes and features to some of the WebGL utility classes, with a focus on improving
WebGL2 support:
* Allow attaching and detaching multiple color textures to framebuffers if WebGL 2 is enabled
* Allow attaching and detaching a depth texture to framebuffers if WebGL 2 is enabled
* Fix an error in vtkFrameBuffer.releaseGraphicsResources
* Use user-specified internal texture type if present
* Fix an error in ShaderProgram
* Use 32 bit floats for depth textures (when type is Float32Array and with WebGL 2)

feat: improve support for webGL2 features

---

Sources/Proxy/Core/LookupTableProxy/index.js
Sources/Rendering/Core/ColorTransferFunction/index.js

Currently the `vtkLookupTableProxy` ignores the midpoint and sharpness values we might provide when calling `setRGBPoints`.  This PR allows us to do the following:
```
rgbPoints = [];
rgbPoints.push([v, r, g, b, mid, sharp]);
...
lutProxy.setRGBPoints(rgbPoints);
```

fix(LookupTableProxy): Support midpoint/sharpness in rgbpoints

---

Sources/Widgets/Core/AbstractWidgetFactory/index.js
Sources/Widgets/Core/WidgetManager/example/index.js
Sources/Widgets/Representations/CircleContextRepresentation/index.js
Sources/Widgets/Representations/ConvexFaceContextRepresentation/index.js
Sources/Widgets/Representations/CroppingOutlineRepresentation/index.js
Sources/Widgets/Representations/CubeHandleRepresentation/index.js
Sources/Widgets/Representations/ImplicitPlaneRepresentation/index.js
Sources/Widgets/Representations/OutlineContextRepresentation/index.js
Sources/Widgets/Representations/PolyLineRepresentation/index.js
Sources/Widgets/Representations/RectangleContextRepresentation/index.js
Sources/Widgets/Representations/SphereHandleRepresentation/index.js
Sources/Widgets/Representations/SplineContextRepresentation/index.js
Sources/Widgets/Representations/WidgetRepresentation/api.md
Sources/Widgets/Representations/WidgetRepresentation/index.js
Sources/Widgets/SVG/SVGRepresentation/index.js

Applies coincident topology parameters to mappers created by widget representations.
Default values are -1.0, -1.0, but users can change those (see Sources/Widgets/Core/WidgetManager/example/index.js)

fix(Widgets): Apply coincident topology parameters

---

Sources/Filters/General/PaintFilter/PaintFilter.worker.js

The polygon paint filter would sometimes paint to the slice above the current slice.

fix(PaintFilter): fix polygon paint filter painting the wrong slice

---

Utilities/ci/azure-pipelines.yml

Installing the canvas package is having some issues, most notably node-pre-gyp isn't pulling prebuilts for it. So, we support fallback build-from-source. But even that doesn't work the first time you run `npm ci`, so run it twice for it to work.
This (hopefully) fixes the build issue where `karma` isn't found on LinuxNode12. That was due to the install being prematurely terminated because of a failed install of canvas.

Fix azure builds

---

Sources/Proxy/Core/View2DProxy/index.js
Sources/Proxy/Representations/SliceRepresentationProxy/index.js
Sources/macro.js

When an image's spacing is not 1, then we may either skip slices or have too many slice values map to the same slice. This fixes that issue.

fix(SliceRepresentationProxy): Use spacing in slice values

---

Sources/Widgets/Core/WidgetManager/api.md
Sources/Widgets/Core/WidgetManager/index.js

Also add more documentation to the WidgetManager API.
If anyone has any reason to keep `MOUSE_RELEASE` as the default, this will be a good discussion place.

fix(WidgetManager): Switch to MOUSE_MOVE as default

---

Utilities/ExampleRunner/example-runner-cli.js

Previously, passing in a non-existent example would fail with an opaque
message. This commit clarifies this non-existent case.

fix(ExampleRunner): Fail with nicer error message

---

Sources/Widgets/Widgets3D/SplineWidget/behavior.js
Sources/Widgets/Widgets3D/SplineWidget/example/controlPanel.html
Sources/Widgets/Widgets3D/SplineWidget/example/index.js
Sources/Widgets/Widgets3D/SplineWidget/index.js

_Extracted from #1422_
- The normal and origin of the plane manipulator should be set before searching for an intersection. Fixes #1423
- Improve the API
- Make private methods actually private (updateHandlesSize, addPoint,
getHoveredHandle)
- Use `macro.setGet` to add public APIs around the model properties, and
remove manual setters (sethandleSizeInPixels and setFreehandMinDistance)
- Override setHandleSizeInPixels and setResolution to update the model
representations
- Remove updateResolution which hardcoded a non-standard behavior when
pressing "Shift". Instead, the setResolution API can be used by the
application with a custom keyDown listener.
- Add missing event callbacks in grab/loseFocus
- Improve the example:
- Improve the control Panel to interact with most spline parameters …

Spline widget fixes and improvements

---

Sources/Rendering/Core/Glyph3DMapper/Constants.js
Sources/Rendering/Core/Glyph3DMapper/index.js
Sources/Widgets/Core/StateBuilder/cornerMixin.js
Sources/Widgets/Core/StateBuilder/index.js
Sources/Widgets/Representations/CircleContextRepresentation/index.js
Sources/Widgets/Representations/RectangleContextRepresentation/index.js
Sources/Widgets/Widgets3D/EllipseWidget/behavior.js
Sources/Widgets/Widgets3D/EllipseWidget/state.js
Sources/Widgets/Widgets3D/PaintWidget/example/index.js
Sources/Widgets/Widgets3D/PaintWidget/index.js
Sources/Widgets/Widgets3D/RectangleWidget/behavior.js
Sources/Widgets/Widgets3D/RectangleWidget/state.js
Sources/Widgets/Widgets3D/ShapeWidget/behavior.js
Sources/Widgets/Widgets3D/ShapeWidget/example/index.js
Sources/Widgets/Widgets3D/ShapeWidget/index.js

The widget was constrained to face the X, Y, or Z axis using the `setSlicingMode` API, which was limiting when wanting to create the widget on an arbitrary plane (example: IJK slicing of a dataset with a non-identity direction matrix).
The widgets now face the camera like other 2D widgets (SplineWidget, DistanceWidget) when being placed. It then holds on to its initial plane when being manipulated, even if the camera axis changes.

Orientation support for ShapeWidget

---

Sources/Proxy/Representations/VolumeRepresentationProxy/index.js

Gradient magnitudes for natural images are likely to have a power-law
distribution. To provide linear scale to a user adjusting gradient
opacity with a slider, make gradient opacity maximum and minimum steps
on a log scale.

fix(VolumeRepresentationProxy): Adjust on a log scale

---

Sources/Filters/Core/Cutter/index.js

Cells are not guaranteed to have the same number of vertices as other
cells in the array.
This fixes incorrect cutting of polydata that have varying polygon shapes.

fix(Cutter): Incorrect cell array traversal

---

Sources/Proxy/Representations/SliceRepresentationProxy/index.js

Window level average should be using level min/max, not level min/width max.

fix(SliceRepresentationProxy): Incorrect level mean

---

Documentation/content/docs/concepts_widgets.md
Sources/Widgets/Core/WidgetManager/index.js
Sources/Widgets/Representations/SphereHandleRepresentation/index.js
Sources/Widgets/Representations/WidgetRepresentation/index.js
Sources/Widgets/Widgets3D/PolyLineWidget/example/controlPanel.html
Sources/Widgets/Widgets3D/PolyLineWidget/example/index.js
Sources/Widgets/Widgets3D/PolyLineWidget/index.js
Sources/Widgets/Widgets3D/PolyLineWidget/state.js

This sphere handle will scale to keep the same screen-space size. It
requires widgets to invoke `attachScaleListener` to their behaviors for
this to work.
This is more or less copied from what I played with in Glance. Right now the API requires a whole new representation (the ScaledSphereHandleRepresentation), since initially I thought to make the distinction between widget state scale1 and the camera-dependent scaling in this PR. This could technically be achieved by using the regular SphereHandleRepresentation, and having the camera listener call `setScale1(scale)`, but then you wouldn't be able to control the relative size of the sphere handle via the widget state. That's why this is currently in a separate representation.
Another idea is to just merge the `attachScaleListener` into …

Display-scaled widget representations

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

When tabs are not active browser will step calling
requestAnimationFrame callbacks. See:
https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame
This causes the RenderWindowInteractor lastFrameStart to be inaccurate,
which results in an incorrect lastFrameTime. This can cause the
VolumeMapper, which adjusts its the sampling distance based on the
framerate, to assume too low of a frame rate and produce poor quality
renderings.
Use the Page Visibility API:
https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
to detected when tabs are switched, and reset the RenderWindowInteractor
lastFrameStart.
Co-authored-by: Ken Martin <ken.martin@kitware.com>

fix(RenderWindowInteractor): Reset lastFrameStart with tab switch

---

Sources/Rendering/OpenGL/ImageMapper/index.js

Fixes #310, which is caused by discontinuities the user can build
into the piecewise function.  Respecting the transfer function for
single components was added to support images with only a label
map, where we would like to highlight certain labels.  Support for
that will be added back using another approach.

fix(ImageMapper): Ignore piecewise function for single components

---

Sources/Interaction/Widgets/LabelRepresentation/index.js

Device pixel ratio is not handled correctly when going from display space to CSS space and vice-versa.
Fixes #1509

fix(LabelRepresentation): Handle devicePixelRatio

---

Sources/Proxy/Core/ViewProxy/index.js

So the caller can know when the capture is complete.

fix(ViewProxy): Return Promise from openCaptureImage

---

Sources/macro.js

Without shallow equality, we may end up with excess update calls when
lists are checked. (Right now shallow object checking isn't done, but
macro getters don't clone objects, unlike the array getter.)

fix(macro): Perform shallow equals

---

Sources/Interaction/Widgets/PiecewiseGaussianWidget/index.js

Instead of passing a pointer to render, pass an anonymous function over
render. This allows extending the render function.

fix(PiecewiseGaussianWidget): Allow for extensibility

---

Sources/Proxy/Core/PiecewiseFunctionProxy/index.js
Sources/Proxy/Core/PiecewiseFunctionProxy/test/testPiecewiseFunctionProxy.js

Gaussians should be deep-copied. If they are modified, then the original
gaussians will also be modified. (This happens when working in tandem
with the piecewise gaussian editor.)

fix(PiecewiseFunctionProxy): Deep copy gaussians

---

Sources/Rendering/OpenGL/Texture/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

Fixed a couple issues that showed up when a large
volume was rendered uising webgl1 specifically when the volume
had to be subsampled.

fix(Rendering): Volume rendering on webgl1

---

Sources/Interaction/Manipulators/GestureCameraManipulator/index.js

Pan gestures weren't working because of an invalid interactor style ref.
Should fix #1519, #1523, and #1527.

fix(GestureCameraManipulator): Get correct interactor style ref

---

Sources/Widgets/Core/WidgetManager/example/controlPanel.html

This was causing builds to fail. Here's a quick post-mortem:
- The issue only manifested when kw-doc was invoked with minify option, so terser was complaining about something.
- Parallel-webpack wasn't logging any webpack errors, hence the build error of "file not found" remained cryptic.
- terser-plugin minifies html, and this html was invalid.

doc(WidgetManager): Fix invalid example html

---

Sources/Interaction/Manipulators/MouseCameraTrackballZoomManipulator/index.js

Allows consumers to reverse the in/out up/down directions when using the ZoomManipulator
Our other image viewer is in the reverse direction. This would allow us to make our app's interfaces congruent.

 feat(ZoomManipulator): Configurable zoom in/out direction 

---

Sources/Rendering/OpenGL/ImageMapper/index.js

Before, adding a piecewise function to a texture after the texture has been rendered would not do anything. Now, piecewise functions added/removed during the lifetime of the texture will be used appropriately.

fix(OpenGL/ImageMapper): Reset texture format for pwf

---

Sources/Rendering/Misc/FullScreenRenderWindow/index.js

Instead of filling the viewport, fill the parent element. This fixes
issues with how Chrome on Android treats 100vh as including the address
bar height, resulting in the lower ~56px being cut off. This should have
minor (but positive) impacts on desktop browsers, as vw/vh may include
scrollbar width/height, causing the "fullscreen" aspect to actually
extend beyond the visible viewport.

fix(FullScreenRenderWindow): Use 100% height/width instead of 100vw/vh

---

Sources/Imaging/Core/ImageReslice/index.js

Some versions of Webkit may complain about invalid TypedArray
constructors when using `.from`. Use the TypedArray constructor instead.
Fixes #1557
@finetjul If there is some subtlety for using `.from` here rather than the TypedArray constructor, please let me know.

fix(ImageReslice): Do not use TypedArray.from()

---

Sources/Rendering/Core/InteractorStyle/index.js

ImageProperty and VolumeProperty do not have wireframe/surface/point
representations.
Fixes #1572

fix(InteractorStyle): Add actor property method guards

---

Sources/IO/XML/XMLReader/index.js

Data array offset is not guaranteed to be aligned according to the array's datatype. If so, then a slice copy must be made.
Fixes #1570

fix(XMLReader): Handle non-aligned data offset

---

Sources/Interaction/Widgets/OrientationMarkerWidget/index.js

Previously, the viewport was not being re-computed when min/max sizes
were set.
Fixes the second issue mentioned in #1381

fix(OrientationMarkerWidget): Update viewport on modified

---

Sources/Common/Core/Math/api.md
Sources/Common/Core/Math/index.js

If x or y is the same array as out, then the result will be wrong due to
inter-dependence between components.
Fixes #1594

fix(Math): Cross results incorrect when doing in-place

---

Sources/Common/DataModel/DataSetAttributes/index.js
Sources/Filters/General/TubeFilter/index.js

- Copy cell data from tube filter
- initialize attribute copy flags on DataSetAttributes creation
- Remove a call to `initialize` in `copy<NAME>Off`, since `initialize` clears `model.arrays`, which is not desired behavior when turning copy off

Tube filter copy celldata

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

Currently, when you try to navigate with a mouse's side buttons while hovering over a vtk context, an error is thrown in the console.

fix(renderwindowinteractor): ignore mouse events from back and forward buttons

---

Sources/Widgets/Widgets3D/AngleWidget/behavior.js
Sources/Widgets/Widgets3D/DistanceWidget/behavior.js
Sources/Widgets/Widgets3D/PolyLineWidget/behavior.js
Sources/Widgets/Widgets3D/SplineWidget/behavior.js

Manipulators may return an empty result, so a guard must be in place.
FYI @laurennlam @finetjul I know you've been doing widgets stuff, so if any of these changes conflict or apply to your PRs, feel free to copy the changes to your PRs as to avoid conflicts.

fix(Widgets): Guard against empty worldCoords

---

Sources/Rendering/OpenGL/ForwardPass/index.js

Hey,
Renderers currenlty have a `draw` property, which the api docs show should prevent a redraw if set to false, however this is never checked.
I've added the check to the forwardPass, confirmed locally it works when you have multiple `renderer`s on a single `renderWindow`.

fix(vtkforwardpass): check to see if a renderer should be drawn

---

CONTRIBUTING.md

semantic-release can push to `vtk.js@next` and `vtk.js@next-major` tags without impacting the primary `vtk.js` package. In the interest of encouraging release testing (with next/next-major) and ensuring multiple PR merges increment the version numbers by 1 for each batch of PRs, I've set up `next` and `next-major` branches.

docs(CONTRIBUTING): Add info on release channels

---

Sources/Widgets/Representations/ImplicitPlaneRepresentation/index.js
Sources/Widgets/Widgets3D/ImplicitPlaneWidget/api.md
Sources/Widgets/Widgets3D/ImplicitPlaneWidget/index.js

Adds support for setting and getting the visibility of the normal, plane, origin, and outline components of the ImplicitPlaneWidget.
Closes #1630

Implicit plane visibility

---

Sources/IO/Core/HttpSceneLoader/index.js

Related to: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7409 and https://gitlab.kitware.com/paraview/paraview/-/merge_requests/4531
Also related: https://github.com/Kitware/paraview-glance/pull/380
This would allow the HTTP scene loader to load volumes that were exported from ParaView/VTK

feat(httpsceneloader): support importing volumes

---

Sources/Interaction/Widgets/OrientationMarkerWidget/index.js

This avoids unnecessary resize updates when the scene isn't actually resizing.
@laurentmalka @finetjul This should fix your Z buffer issue. Below is a brief summary of what I think is happening.
Prior to this PR, `vtkOrientationMarkerWidget.updateViewport()` gets called every time the interactor view is updated (which includes mouse movement). `updateViewport()` calls `interactor.render()`, which will of course render the scene. Now consider how vtkOpenGLHardwareSelector works. At a high level, it tells the renderer to do a picking render to populate the picking buffer. When moving the mouse over the scene, we trigger calls to the hardware selector to render the picking buffer. Somehow, during the rendering phase of the hardware selector, the interactor `onModified` callbacks are being …

fix(OrientationMarkerWidget): Use resize observer

---

Sources/Widgets/Core/WidgetManager/index.js

When adding a widget to the environment of 1 renderwindow and n renderers, selectedState does not work properly in mouse move event.
I think It compares the pokedRenderer that is passed to the mouse move event and the Renderer that WindgetManager has, and if they are different, it seems that there is no need to handle picking.

The selection condition was added

---

Sources/Widgets/Representations/ResliceCursorContextRepresentation/index.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/Constants.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/index.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/state.js

After setting translation on the reslice cursor, then, when applying rotation, keep reslice cursor center and "moves" image instead.
It avoids a reslice cursor translation visual effect.
@finetjul

Stabilize reslice cursor center on rotation

---

Utilities/ExampleRunner/template-config.js
package-lock.json
package.json
webpack.common.js

The latest versions of JSZip seem to have broken the JSZipDataAccessHelper.
Calling JSRoot.file().async() returns a promise that never resolves. This breaks .vtkjs loading functionality.
People having the same issue:
https://github.com/Stuk/jszip/issues/724
https://github.com/Stuk/jszip/issues/712
Downgrading to 3.2.0 fixes the issue.

fix(JSZipDataAccessHelper): Downgrade JSZip version

---

Sources/Rendering/Core/ColorTransferFunction/index.js
Sources/Rendering/Core/ColorTransferFunction/test/testColorTransferFunction.js

A discretized ColorTransferFunction would return incorrect values (0, 0, 0) when the discretized `x` was exactly equal to the beginning of the mapping range.
This fixes the issue.

fix(colortransferfunction): fix discretized CTF returning incorrect values

---

.github/workflows/publish.yml

I'm pretty sure the default github app token's permissions don't work
for committing to gh-pages branch.

chore(github): Use custom github publish token

---

.github/workflows/publish.yml
package.json

Add a beta pre-release channel. This allows for publishing beta packages for major releases. This differs from next and next-major in that this is a pre-release channel, so releases will be of the form `vX.X.X-beta-#`. This will allow us to merge several breaking PRs into the pre-release channel without affecting the default channel releases and without bumping major versions on every merge.
More info: https://github.com/semantic-release/semantic-release/blob/0ef52e7a5f4f4c2bc3daecf7d71eeb1323491374/docs/recipes/pre-releases.md
@jourdain what do you think?

Add prerelease beta branch

---

Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js

@finetjul 
Issue:
- rotate sagittal view
- scroll on axial view
Result: both axis are moving instead of one.
ImageSpacing was badly used when computing the new center.
When we are not axis aligned, we cannot use the spacing because it transformed the moving direction.

fix(ResliceCursorWidget): update how to move center when scrolling

---

Utilities/rollup/plugin-rewrite-filenames.js
rollup.config.js

NAME/index.js files are now hoisted up one folder to become NAME.js
files.
node_modules imports are now all bundled inside _vendor/vendor.js.
The rewrite-filenames plugin has been moved to a separate file.
Handle circular xmlbuilder and jzip targets.

chore(rollup): Hoist entrypoint index.js files

---

Sources/Widgets/Core/WidgetManager/index.js

- Fixes ordering of widget delete and unfocus. Unfocus should occur before delete.
- Address each usage of `enablePicking` inside WidgetManager

Fix widget delete

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

Adds screen position information to wheel event call data.
WheelEvent inherits from MouseEvent, and so has position information.
Fix case: scrolling on a slice with an active widget handle doesn't correctly position the handle, because positioning the widget doesn't happen on wheel event.
Also, move from Object.assign to object spread operator for conciseness.
FYI @agirault @finetjul, if either of you ran into the aforementioned widget issue before.

Wheel event position

---

Sources/Common/DataModel/Plane/api.md
Sources/Imaging/Core/ImageReslice/index.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/helpers.js

With very particular dataset, in very particular condition, scrolling axial was making the coronal view "jump" slices. 
Closes #1746

ResliceCursorWidget: Fix jump

---

Sources/Rendering/OpenGL/Texture/index.js

Profiling reduces this from 380 ms to 132 ms.

perf(OpenGL/Texture): Optimize create3DFilterableFromRaw

---

Sources/Widgets/Widgets3D/ResliceCursorWidget/helpers.js

When keep-orthogonality is false, the lines were not correct.

fix(ResliceCursorWidget): Fix reslice cursor lines directions

---

.eslintrc.js
.github/workflows/publish.yml
.gitignore
Utilities/ci/build-npm-package.js
package.json

This will result in two packages: `vtk.js`, and `@kitware/vtk.js`.
- `vtk.js` will still provide `vtk.js/Sources/*` as well as the UMD build. `vtk.js@beta` no longer contains the ESM build.
- `@kitware/vtk.js` will only provide the ESM build. `@kitware/vtk.js/Sources/*` no longer exists.
A few things to note:
- `build-npm-package.js` generates two packages: the ESM and UMD packages.
- Both packages have customized package.json entries.

fix(package): Manually create npm packages

---

Sources/Widgets/Widgets3D/ResliceCursorWidget/index.js

displayFocal has 3 elements and not 2

fix(reslicecursor): fix reslice cursor when aspect ratio is != 1

---

Sources/Common/Core/MatrixBuilder/index.d.ts
Sources/macro.d.ts

This should fix the `vtkMatrixBuilder` and `setData` definitions
fix #466

docs(ts): fix typescript definitions

---

Sources/Common/DataModel/DataSetAttributes/FieldData.d.ts
Sources/Common/DataModel/DataSetAttributes/index.d.ts
Sources/Filters/General/AppendPolyData/index.d.ts
Sources/Filters/General/ImageCropFilter/index.d.ts
Sources/Filters/General/ImageOutlineFilter/index.d.ts
Sources/Filters/General/ImageSliceFilter/index.d.ts
Sources/Filters/General/LineFilter/index.d.ts
Sources/Filters/General/OutlineFilter/index.d.ts
Sources/Filters/General/TriangleFilter/index.d.ts
Sources/Filters/General/TubeFilter/index.d.ts
Sources/IO/Geometry/DracoReader/index.d.ts
Sources/IO/Geometry/PLYReader/index.d.ts
Sources/IO/Geometry/STLReader/index.d.ts
Sources/IO/Geometry/STLWriter/index.d.ts

Add typescript definitions for the following classes:
* AppendPolyData
* DataSetAttributes
* ImageCropFilter
* ImageOutlineFilter
* ImageSliceFilter
* LineFilter
* OutlineFilter
* TriangleFilter
* TubeFilter
Readers:
* STLReader
* PLYReader
* DracoReader
Writers:
* STLWriter
fix #466

Add typescript definitions for filters

---

Sources/Rendering/Core/RenderWindowInteractor/index.d.ts
Sources/Rendering/Core/RenderWindowInteractor/index.js

This commit fixes the Interaction event name
fix #1780

fix(renderwindowinteractor): fix interaction event name

---

rollup.config.js

This fixes an issue where the js extension is missing for rollup-generated intermediate files. Webpack rules might not pick these files up correctly depending on the loader rules.

fix(esm): Output all files with js extension

---

Sources/Rendering/Core/ImageProperty/index.d.ts

fix type definition for getRGBTransferFunction in vtkImageProperty

docs: fix type definition for getRGBTransferFunction in vtkImageProperty

---

Sources/IO/Core/HttpDataSetReader/index.js

A clear and concise description of what the problem was and how this pull request solves it.
The reader caches array instances to avoid having to load and instanciate the same array multiple times. Arrays are
cached using a hash of the binary data they contain.
This means a vtkPoints and vtkDataArray sharing the same data could be cached under the same index.
This case can happen quite often with empty meshes, as all arrays will share the same hash.
This fix appends the class type to the caching key to avoid these conflicts.

fix(httpdatasetreader): when caching array data, differentiate by class

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/performance_issue.md
.github/pull_request_template.md
README.md

Fix #1875
- Updated GitHub templates for issues and pull requests
- Reorganized a section of the `README.md`
- issue labels automatically assigned (test [here](https://github.com/agirault/vtk-js/issues/new/choose))
- "Using vtk.js" section in `README.md` (visible [here](https://github.com/agirault/vtk-js/blob/new-issue-templates/README.md#using-vtkjs))
N/A, doc/chore only

Improve Github templates + README for contributions and support

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

Fix console errors coming from `vtkRenderWindowInteractor` after unbinding and rebinding events.
#1858 Changed the `bindEvents` method in the RWI to add key event listeners on the `document` rather than the `body`.  This change fixes the `unbindEvents` methods to match, i.e. it uses the `document` rather than the `body` to `removeEventListener`.

fix(RenderWindowInteractor): add/remove event listeners on same object

---

Documentation/content/api/index.md
Documentation/content/docs/develop_requirement.md
Documentation/content/docs/intro_vtk_as_es6_dependency.md
Documentation/content/docs/old_intro_vtk_es6.md
Documentation/content/docs/vtk_react.md
Documentation/content/docs/vtk_vanilla.md
Documentation/content/docs/vtk_vue.md
Documentation/tpl/__en__
Documentation/tpl/__sidebar__

This PR updates the documentation to use the new `@kitware/vtk.js` ESM build. The old webpack-dependent approach is still supported, but its use in new projects is discouraged.
Fixes issue #1867 
This only introduces documentation changes.

docs: Overhaul intro docs to use the ESM build

---

Utilities/ci/build-npm-package.js

Fixes #1904 (fyi @daker)
The ESM build now includes the typescript definition files.

fix(esm): Include typescript definition files

---

Sources/Rendering/WebGPU/BindGroup/index.js
Sources/Rendering/WebGPU/Camera/api.md
Sources/Rendering/WebGPU/Camera/index.js
Sources/Rendering/WebGPU/Device/index.js
Sources/Rendering/WebGPU/MapperHelper/index.js
Sources/Rendering/WebGPU/OrderIndependentTranslucentPass/index.js
Sources/Rendering/WebGPU/Pipeline/index.js
Sources/Rendering/WebGPU/PolyDataMapper/index.js
Sources/Rendering/WebGPU/RenderEncoder/index.js
Sources/Rendering/WebGPU/Renderer/index.js
Sources/Rendering/WebGPU/Sampler/index.js
Sources/Rendering/WebGPU/StorageBuffer/index.js
Sources/Rendering/WebGPU/TextureView/index.js
Sources/Rendering/WebGPU/UniformBuffer/index.js
Sources/Rendering/WebGPU/VolumePass/index.js
Sources/Rendering/WebGPU/VolumePassFSQ/index.js

Flesh out the multivolume renderer a bit more
Add a bind group class as WebGPU only requires support for 4 bind group
layouts and the old approach could easily go past 4. With the bind group
class we typically only have two bind groups active, one for the
renderer and one for the mapper. Tons of changes to support this.

chore(WebGPU): more volume support, add bind group

---

Sources/Proxy/Core/ViewProxy/index.js
Sources/Rendering/Core/RenderWindow/index.js
Sources/Rendering/OpenGL/RenderWindow/api.md
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/WebGPU/RenderWindow/index.js

Currently the screenshot capture functionality captures the render window image as it appears on the screen.  However, some applications could benefit from the ability to specify an arbitrary size when capturing an image and have it rendered at full resolution rather than resampled.
I haven't tried this with WebGPU, but just provided an implementation the same as that for OpenGL.

fix(RenderWindow): Support custom sizes for screenshots

---

Examples/Volume/VolumeMapperBlendModes/controller.html
Examples/Volume/VolumeMapperBlendModes/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

fix #1924
https://discourse.vtk.org/t/averageipscalarrange/5544/4
averageIPScalarRange working for single component volumes (from some angles).
averageIPScalarRange can now accept float values.
Previously setting the range to a float: 
`mapper.setAverageIPScalarRange(0.0, 0.9);`
would result in a blank canvas on a volume and shader errors.
Currently: Adjusting the max slider between 0.0 and 1.0 results in this: 
run 
`npm run example -- VolumeMapperBlendModes`
switch the drop down to Average Intensity.

 fix(setAverageIPScalarRange)

---

Sources/Rendering/WebGPU/Pipeline/index.js
Sources/Rendering/WebGPU/RenderEncoder/index.js

Catch encore/pipeline attachment mismatches earlier
in the code to make them easier to debug.

chore(WebGPU): better render encoder checks

---

.github/FUNDING.yml

Commit https://github.com/Kitware/vtk-js/commit/df03201f388a981dcaae682bbcb11e8d89ebb266 introduce error preventing users from successfully clicking on the "sponsor" link.
Implement change based on  format documented at https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/displaying-a-sponsor-button-in-your-repository
NA
NA

Ensure clicking on Sponsor button displays links

---

Examples/Widgets/Box/index.js

This example still used getOpenGLRenderWindow
Use getApiSpecificRenderWindow instead
The example works again
- **vtk.js**: 
- **OS**: 
- **Browser**:

doc(box): fix the Box widget example

---

Sources/Filters/General/TubeFilter/test/testTubeFilter.js

Seeding the rng in global scope meant that any call to Math.random() in previous tests would alter the random sequence produced in testTubeFilter, thus altering the results.
This MR makes sure that Math.random is properly seeded right before the
test is executed.
The addition of testPaintEllipse caused this test to fail (because testPaintEllipse creates a worker, which causes a call to Math.random).
Make sure that vtkMath.random is initialized at the right time in testTubeFilter.
testTubeFilter passes again.
- **OS**:  linux
- **Browser**: chromium 91.0.4472.77

test(testtubefilter): fix rng consistency

---

Sources/Interaction/Manipulators/MouseCameraUnicamManipulator/index.js
Sources/Interaction/Manipulators/MouseCameraUnicamRotateManipulator/index.js

fix issue when using the unicam style and picking on top of an object.
Also clean up some small code typos that had no impact.
Fixes issue https://github.com/Kitware/vtk-js/issues/1935

fix(Interaction): fix the unicam interactor

---

Examples/Volume/VolumeMapperBlendModes/controller.html
Examples/Volume/VolumeMapperBlendModes/index.js
Sources/Rendering/Core/VolumeMapper/Constants.js
Sources/Rendering/Core/VolumeMapper/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

We had a need for an additive blend mode. Here's a simple implementation using the existing average blend mode.
Added in an additive blend mode
Renamed AverageIPScalar to ipScalar, since it is now used for average and additive.
Added in a depreciation warning for AverageIPScalar and a handler to pass it through to ipScalar
`npm run example -- VolumeMapperBlendModes`
Then select additive from the dropdown.

Addtive Blending Mode

---

Sources/Filters/General/PaintFilter/PaintFilter.worker.js

Ellipse painting would fail under some conditions
* Instead of setting the slice axis to zero, directly set min and max values to the center for this axis.
* Make sure sqrt parameters are >= 0
Ellipse painting is more consistent
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(paintfilter): avoid NaNs while painting vtkPaintFilter ellipses

---

Sources/Filters/General/TriangleFilter/index.js

The SplineWidget example is currently broken (surface area missing a triangle).
This is due to a change that caused the vtkTriangleFilter to stop supporting cells that duplicate the last point when triangulating.
If a cell is found to have its last point duplicated, ignore this last point when triangulating the cell.
The SplineWidget example is fixed

fix(vtkTriangleFilter): ignore duplicated last points before triangulating cells

---

Sources/IO/Geometry/DracoReader/index.js

Since Draco 1.4.0, Emscripten has been updated to V2, this causes the Draco codec modules to return a promise instead of the module directly.
[Draco Release https://github.com/google/draco/releases/tag/1.4.0](https://github.com/google/draco/releases/tag/1.4.0)

fix(DracoReader): Compatible with Draco 1.4.0

---

Sources/Common/Core/ClassHierarchy/index.js
Sources/Widgets/Core/AbstractWidgetFactory/index.js
Sources/macro.js

Fixes #1910 
- Introduces `ClassHierarchy`, which subclasses Array. This is used to remove duplicates only when items are added via `.push`.
- Fixes unnecessary class hierarchy additions to AbstractWidget
model.classHierarchy should now not have any duplicates. Any existing code using classHierarchy should continue to operate correctly.
I tested this by modifying the `PolyLineWidget` example to output the class hierarchy of the widget via `viewWidget.get('classHierarchy').classHierarchy`. The result should be the following:
```
ClassHierarchy(5) ["vtkObject", "vtkProp", "vtkInteractorObserver", "vtkAbstractWidget", "vtkPolyLineWidgetProp"]
```

Unique class hierarchy

---

Sources/Common/Core/ImageHelper/index.js

`vtkImageHelper.ImageToImageData` only properly works with `Image` in squared size (width == height = true)
in `ImageToImageData` changed ctx.drawImage parameter to use image.height
- [ x ] Documentation and TypeScript definitions were updated to match those changes
Rectangle-sized image can be converted into vtk.js imagedata
Try convert (512,128) sized image into vtkImageData using `vtkImageHelper.ImageToImageData`, render usign `vtkImageSlice`.
Originally, it displays nothing, and this change resolves the problem.
- [ x] This change adds or fixes unit tests
- **OS**: all
- **Browser**: Chrome 89.0.4389.128

Should be able to convert non-squared image into `vtkimagedata`

---

Sources/Testing/testAlgorithm.js
Sources/Testing/testMacro.js
Sources/interfaces.d.ts
Sources/macro.d.ts
Sources/macro.js

- Fixes #1996 
- Adds support for cancelling debounced calls.
- Fixes `macro shouldUpdate()` to check for output dataset deletion status
- Adds support for cancelling debounced calls via `debouncedFunction.cancel()`

WIP Fix #1996 and add debounced function cancellation

---

Sources/IO/Geometry/STLReader/index.js

Assign progressCallback property to the model object, so it will be passed to dataAccessHelper upon
calling setUrl method.
Without this fix, when you use method [setUrl](https://kitware.github.io/vtk-js/api/IO_Geometry_STLReader.html#setUrl) and pass your function as [progressCallback option](https://github.com/Kitware/vtk-js/blob/master/Sources/IO/Geometry/STLReader/index.d.ts#L7) it will never be called.
The reason why it's never called is that it's not passed to `dataAccessHelper` as [compression option do](https://github.com/Kitware/vtk-js/blob/master/Sources/IO/Geometry/STLReader/index.js#L128). I updated the code to assign `progressCallback` property to the model object the same way as `compression`.
- **vtk.js**: 18.7.2 
- **OS**: MacOS 11.4 
- **Browser**: Chrome 91.0.4472.114 …

fix(STLReader): fix progressCallback

---

Sources/Rendering/Core/ScalarBarActor/index.js

fix #2020
Allow user to get / set autoLayout function, previously called computeAndApplyAutomatedSettings
ScalarBarActor doesn't seem to have documentation or TypeScript definitions yet.
https://kitware.github.io/vtk-js/api/Rendering_Core_ScalarBarActor.html
I've successfully been able to customize the autoLayout function! 
Not sure the best way to develop test changes to vtk.js module:
https://discourse.vtk.org/t/npm-link-for-vtk-js/6283
- latest master: 
- macOS 12.2.1: 
- Firefox 
_This contribution is funded by [Pollination](https://www.pollination.cloud/)._

feat(ScalarBarActor): make layout function settable / gettable

---

Examples/Geometry/VR/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js

Due to WebGPU support, the method name to access the WebGL view has changed.
I tried to run the example with no luck
The name of the method to access the WebGL view has been changed.
Added more explicit error messages.
Example is still failing on my machine without VR display, but at least I do not have any other error.
- **Browser**: Chrome 89.0.4389.128

docs(vr): fix VR example

---

Sources/Filters/Sources/CylinderSource/index.d.ts
Sources/Filters/Sources/CylinderSource/index.js
Sources/Widgets/Representations/ResliceCursorContextRepresentation/index.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js

Reslice cursor widget lines were rendered with some odd look and feel.
Before:
After:
- **Browser**: Chrome 89

Improve reslice cursor line rendering

---

Sources/Interaction/Manipulators/MouseCameraTrackballRotateManipulator/index.js

Fixes an error when the world up vector setting is used with a non-origin center of rotation as mentioned [here](https://github.com/Kitware/vtk-js/pull/2043#issuecomment-898999801)

fix(View): Fix center of rotation when used with world up vector setting

---

Sources/Filters/General/ImageMarchingCubes/index.js

The marching cubes filter was not handling images
with an extent that started with anything other than 0,0,0.
This MR fixes that issue https://github.com/Kitware/vtk-js/issues/2051

fix(Filters): fix marching cubes position/extent error

---

Sources/Widgets/Widgets3D/PaintWidget/index.js

The method 'handleLeftButtonRelease' wasn't returning any value. This was affecting the behavior
of widgets inherited from this one. A change was made to absorb the event if the widget has the
focus.
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(paintwidget): fix paintwidget 'handleLeftButtonRelease'

---

Sources/Common/Core/HalfFloat/index.d.ts
Sources/Common/Core/HalfFloat/index.js
Sources/Common/Core/index.js
Sources/Rendering/WebGPU/Texture/index.js
Sources/Rendering/WebGPU/TextureManager/index.js
Sources/Rendering/WebGPU/VolumePassFSQ/index.js

Use half float to support types other than uint8
Fix a matrix computation that impacts imageData that
has a direction in its transformations.

feat(WebGPU): support more data types for volume rendering

---

rollup.config.js

All assets are considered js files. This ensures that bundlers treat
imports correctly, as some of the generated imports do not suffix with a
proper extension.
Fixes #2072 
- [ESM] Forces all output chunks to end with .js

fix(rollup): force .js extension for all files

---

Sources/Rendering/WebGPU/Texture/index.js

When a native array of element size != 2 was converted
to half float not all of the entries were copied during the conversion.

fix(WebGPU): fix an issue with half float textures

---

Documentation/content/docs/develop_build.md
Documentation/content/index.pug

Update build docs to mention running `npm install` to install dependencies.
We might want to hold off on merging this until `npm run dev` and `npm run build` both work as build commands. They don't work for me at the moment.
I added a paragraph describing what building means in this case, since that was confusing for me as someone new to this type of development:
> When you use vtk.js as a dependency in your project (e.g. [like this](https://kitware.github.io/vtk-js/docs/vtk_vanilla.html)) you are pulling a package that was put together by the continuous integration. When developing vtk.js, you will have to put that package together yourself, and we call that "building."
Please let me know if I made any mistakes or could explain something more clearly.
Finally, there is a commit updating …

docs: build doc fix

---

Sources/Rendering/WebGPU/README.md
Sources/Rendering/WebGPU/Volume/index.js

Specifically for non axis aligned volumes. The old code took
the axis aligned bounding box form the image data while
this version uses the original corner points and transforms
them. This results in a much tighter bounding cube for oriented
image data.

perf(WebGPU): improve WebGPU volume rendering performance

---

Sources/Rendering/WebGPU/Texture/index.js

Issue when a Uint8Array had a row length other than
256 bytes.

fix(WebGPU): fix an issue with typed array textursd in webgpu

---

Examples/Volume/VolumeMapperBlendModes/index.js
Sources/Rendering/Core/VolumeMapper/index.js
Sources/Rendering/OpenGL/Texture/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

Recently half float precision for 2D textures was [added](https://github.com/sedghi/vtk-js/commit/29f0cb94b57485ccbe008d0a44ed16a6004a5d89), this PR will try to add it for the 3D textures too.  
Data used is a full body CT from [TCIA](https://wiki.cancerimagingarchive.net/display/Public/Head-Neck+Cetuximab) (download .vti from [here](https://www.dropbox.com/sh/4pq08njcfmos2nf/AACFoqprysqp5migPtLS9rUua?dl=0)). 
run `npm run example -- VolumeMapperBlendModes` with the data
https://user-images.githubusercontent.com/7490180/131192577-9433a02b-084e-41de-b866-0324261749c7.mp4
Chrome task manager before 
https://user-images.githubusercontent.com/7490180/131192631-bae03a2a-79e6-4b68-b948-601772f5186f.mp4
Chrome task manager after 
- **OS**: macOS 10.15.7
- **Browser**: …

feat(Rendering): Add support for halfFloat 3D textures

---

Sources/Rendering/OpenGL/Actor/index.js

The zbuffer values were not being computed on translucent
actors in WebGL. So when zbuffer values were needed to compute
world coordinates on translucent actors they were incorrect.
Fixes issue https://github.com/Kitware/react-vtk-js/issues/37

fix(WebGL): zvalue hardware selection of translucent actors

---

Sources/IO/Core/BinaryHelper/index.js
Sources/IO/XML/XMLReader/index.js

Should allow usage of XMLReaders in web workers

fix(XMLReader): use xml library over builtins

---

BREAKING_CHANGES.md
Sources/Common/Core/Math/index.d.ts
Sources/Common/Core/Math/index.js
Sources/Common/DataModel/ImageData/index.js
Sources/Widgets/Representations/CircleContextRepresentation/index.js
Sources/Widgets/Representations/ContextRepresentation/index.js
Sources/Widgets/Representations/RectangleContextRepresentation/index.js
Sources/Widgets/SVG/SVGLandmarkRepresentation/Constants.js
Sources/Widgets/SVG/SVGLandmarkRepresentation/index.js
Sources/Widgets/Widgets3D/EllipseWidget/behavior.js
Sources/Widgets/Widgets3D/EllipseWidget/index.js
Sources/Widgets/Widgets3D/EllipseWidget/state.js
Sources/Widgets/Widgets3D/LineWidget/index.js
Sources/Widgets/Widgets3D/PaintWidget/behavior.js
Sources/Widgets/Widgets3D/PaintWidget/example/index.js
Sources/Widgets/Widgets3D/PaintWidget/index.js
Sources/Widgets/Widgets3D/PaintWidget/state.js
Sources/Widgets/Widgets3D/PolyLineWidget/index.js
Sources/Widgets/Widgets3D/RectangleWidget/behavior.js
Sources/Widgets/Widgets3D/RectangleWidget/index.js
Sources/Widgets/Widgets3D/RectangleWidget/state.js
Sources/Widgets/Widgets3D/ShapeWidget/Constants.js
Sources/Widgets/Widgets3D/ShapeWidget/behavior.js
Sources/Widgets/Widgets3D/ShapeWidget/example/index.js
Sources/Widgets/Widgets3D/ShapeWidget/index.js

A recent change makes the widget behavior no longer share the widget factory model.
Furthermore, LabelRepresentation is about to be removed (old-style widget), so widgets using this should use SVGLandmarkRepresentation for text rendering.
- Fix ShapeWidget (use SVGLandmarkRepresentation instead of LabelRepresentation)
- Fix PaintWidget (use SVGLandmarkRepresentation instead of LabelRepresentation)
- Fix a bug in ShapeWidget example causing labels to not being centered
- Fix PaintWidget example by importing the module HttpDataAccessHelper
- Add a way of changing text alignment and position
**Behaviour of text alignment**
Possible values for horizontal alignment: 
- `start`
- `middle`
- `end`
Possible values for vertical alignement (defined in `SVGLandmarkRepresentation/Constants.js`):
- …

fix(shapewidget): Fix and improve ShapeWidget

---

Sources/Rendering/Core/ImageMapper/test/testImageColorTransferFunction.js
Sources/Rendering/WebGPU/ImageMapper/index.js

Fix an issue where colored tfuns were being converted to
greyscale in the fragment shader.
Fix an issue where the color tfun texture was not
getting created correctly in one case.

fix(WebGPU): Fix issue with the image mapper and colors

---

Sources/Rendering/WebGPU/RenderWindow/index.js

In cases where the webgpu render window was destroyed
before the async initialization completed the async
would error trying to access the deleted model.

fix(WebGPU): fix for initialize after destroy/delete

---

Sources/Rendering/WebGPU/BufferManager/index.js
Sources/Rendering/WebGPU/Camera/index.js
Sources/Rendering/WebGPU/Glyph3DMapper/index.js
Sources/Rendering/WebGPU/HardwareSelectionPass/index.js
Sources/Rendering/WebGPU/HardwareSelector/index.js
Sources/Rendering/WebGPU/OrderIndependentTranslucentPass/index.js
Sources/Rendering/WebGPU/PolyDataMapper/index.js
Sources/Rendering/WebGPU/README.md
Sources/Rendering/WebGPU/RenderEncoder/index.js
Sources/Rendering/WebGPU/Renderer/index.js
Sources/Rendering/WebGPU/ShaderDescription/index.js
Sources/Rendering/WebGPU/VolumePass/index.js
Sources/Rendering/WebGPU/VolumePassFSQ/index.js

Switch the zbuffer on WebGPU to be an inverted
depth buffer. Update mappers to handle this. See the README
for more information on how it works.
Improve surface with edges by using thicker edges and
a tiny bit of offset.
Update for recent changes in WebGPU that require flat interpolation
for integral outputs/inputs.

feat(WebGPU): use invereted depth and improve edges

---

Sources/Rendering/OpenGL/Actor/index.js
Sources/Rendering/OpenGL/Actor2D/index.js
Sources/Rendering/OpenGL/ImageSlice/index.js
Sources/Rendering/OpenGL/RenderWindow/index.d.ts
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/Renderer/index.js
Sources/Rendering/OpenGL/Skybox/index.js
Sources/Rendering/OpenGL/Volume/index.js

When a scene contained only translucent actors, depth mask was never turned off before the translucent pass. This is because the renderer was setting it to true without notifying the render window.
Translucent actors without opaque actor:
Translucent actors with opaque actors:
Got the send image even without the opaque actors.
The issue with faces ordering is still there though... (different problem)

fix(renderwindow): fix inconsistent depth mask value

---

Sources/Interaction/Manipulators/VRButtonPanManipulator/index.js
Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js

The physical scale was being divided by when it should have been
multiplied by.

fix(WebVR): controller movement was off for scales far from 1

---

Sources/IO/Core/ImageStream/DefaultProtocol.d.ts
Sources/IO/Core/ImageStream/ViewStream.d.ts
Sources/IO/Core/WSLinkClient/index.d.ts
Sources/Rendering/Misc/RemoteView/index.d.ts

Adds definitions for ViewStream, RemoteView, fixes definitions for WSLinkClient
- **vtk.js**: 
- **OS**: 

docs(ts): Add and update TypeScript definitions

---

Sources/Interaction/Manipulators/MouseBoxSelectorManipulator/index.js

Fixed a problem with rectangle rendering. It didn't render to right
position if container is having margins or page is scrolled. This fix
closes issue #2177.
Explain why this change is needed. Please include relevant links supporting this change, such as:
- fix #2177 (from issue tracker)
Add `xShift` and `yShift` to the calculated `div.style.left` and `div.style.top` to take margins into account. I also added `window.scrollX` and `window.scrollY`, which are fixing another issue (rectangle gets rendered to wrong position if page is scrolled).
The problem can be spotted with the following code:
```html
<!DOCTYPE html>
<html>
<body>
<div id="wrap" style="margin: 100px">
<div id="container" style="width: 500px; height: 500px; margin: 0px; padding: 0px">
</div>
</div>
<script type="module"> …
```

fix(vtkMouseBoxSelectorManipulator.applyStyleToDiv): rectangle position

---

Examples/Applications/SkyboxViewer/index.js
Examples/Geometry/VR/index.js
Sources/Rendering/Core/RenderWindowInteractor/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js

Replaces WebVR with WebXR methods for running an immersive VR session from an OpenGL RenderWindow.
[WebXR](https://immersiveweb.dev/) exposes methods for both VR and AR sessions across a diverse set of platforms, including standalone headsets, fixed displays, and mobile devices. These changes use WebXR to run a VR session in a dedicated headset or mobile viewer. `Applications/SkyboxViewer` and `Geometry/VR` examples are updated for API changes.
Planned future additions (outside the scope of this PR):
- WebXR polyfill
- XR gamepad API
- AR
- `Applications/SkyboxViewer` and `Geometry/VR` examples query VR availability and launch/halt VR sessions correctly in WebXR-compatible browsers
- VR examples compatible with tethered headsets (such as HTC Vive Pro) or mobile headsets with dedicated …

feat(XR): Update to WebXR functionality in OpenGL RenderWindow

---

Sources/Filters/General/ImageCropFilter/index.js

Since v21.0.0, default array values can be null but can't be empty array.
https://discourse.vtk.org/t/unable-to-implement-imagecrop-filter/7254
Fix ImageCropFilter example 

fix(imagecropfilter): fix image crop filter instantiation

---

Sources/IO/Geometry/STLReader/index.js

The method `parseAsArrayBuffer` has a line which sets the global object possibly for debugging
purposes. Thus commenting this line as a browser running this line won't have the global object
which is specific to node.js
#2197
- **vtk.js**: 
- **OS**: 

fix(vtkstlreader): preventing the use of global object

---

Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js
Sources/Rendering/Core/RenderWindowInteractor/Constants.js
Sources/Rendering/Core/RenderWindowInteractor/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js

In moving from WebVR to WebXR we must also integrate changes from the updated [WebXR gamepad API](https://www.w3.org/TR/webxr-gamepads-module-1/). VR controllers are exposed solely under the [`xr-standard` extension to the Gamepad API](https://www.w3.org/TR/gamepad/#dom-gamepadmappingtype) which remaps buttons/axes and exposes controller transforms as XRPose objects.
- VR locomotion is re-introduced to `OpenGL/RenderWindow` and the `Geometry/VR` example so that the user may "fly" around their dataset. Locomotion is technically present in the `Applications/SkyboxViewer` example as well, but is not visible to the user as that example consist of just a skybox.
- **vtk.js**: v21.1.4
- **Browser**: Chrome 96.0.4664.45

feat(XR): Enable translation with WebXR gamepad API

---

Examples/Applications/GeometryViewer/index.js
Examples/Geometry/AR/controller.html
Examples/Geometry/AR/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/WebGPU/RenderWindow/index.js

First step in adding AR support as part of our WebXR investigation.
- Updates `OpenGL/vtkRenderWindow` to support `immersive-ar` sessions via the [WebXR AR module](https://www.w3.org/TR/webxr-ar-module-1/)
- Forks VR cone example for a basic AR example
- AR is functional in WebXR emulator and in mobile device testing
- **vtk.js**: v21.3.0
- **Browser**: Chrome 96.0.4664.110
- See [WebXR emulator extension repo](https://github.com/MozillaReality/WebXR-emulator-extension) for install instructions
- For testing on mobile, run the example with `npm test example -- AR` and visit the displayed LAN address in your mobile browser. May require adjusting firewall rules on your host machine.

feat(XR): Add base WebXR AR support to OpenGL RenderWindow

---

Sources/Rendering/Core/ColorTransferFunction/index.js
Sources/Rendering/Misc/SynchronizableRenderWindow/vtkObjectManager.js
Sources/macros.js

SynchronizedRenderWindow was rebuilding several objects even if their content were remaining the same.
This fix that issue which improve greatly the performances when using local rendering with remote vtk view object.
No API change
See major perf boost when dealing with large geometries
Manual testing using trame app in `examples/VTK/PerfTests/scene-export-time.py`.

fix(SynchronizableRenderWindow): prevent invalid object modification

---

Sources/Rendering/WebGPU/StorageBuffer/index.js
Sources/Rendering/WebGPU/UniformBuffer/index.js
Sources/Rendering/WebGPU/VolumePass/index.js

Deal with deprecation of [[block]] and handle firefox
validation of UBO sizes to be a multiple of alignment
Also fix a bug with mixing geometry and volumes under webgpu

fix(WebGPU): update to account for changes in webgpu

---

Sources/Rendering/Core/AbstractMapper/index.d.ts
Sources/Rendering/Core/AbstractMapper/index.js
Sources/Rendering/Core/AbstractMapper/test/testAbstractMapper.js
Sources/Rendering/Core/VolumeMapper/index.js

These changes fix problems with Mapper classes found during https://github.com/Kitware/vtk-js/pull/2113.
Specifically:
- The class hierarchy for AbstractMapper was missing
- VolumeMapper was calling `macro.obj` and `macro.algo` (once through parent)
- AbstractMapper.removeClippingPlane was using indexes instead of instances
- AbstractMapper.removeClippingPlane was checking classes too specifically
- AbstractMapper methods were not calling modified.
BREAKING CHANGE:
Changed removeClippingPlane to use instance instead of index.

fix(AbstractMapper): Cleanup mapper classes

---

Sources/Common/Core/MatrixBuilder/index.d.ts

Fix typo in the documented example of class vtkMatrixBuilder. Change of case: buildfromDegree ->
buildFromDegree.
- **vtk.js**: 
- **OS**: Windows 10 Pro, Version 10.0.19044 Build 19044 
- **Browser**: Chrome 97.0.4692.71

docs(core/matrixbuilder): fix typo in documented example MatrixBuilder

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

Fixes an issue where an XRInputSource is not guaranteed to have a `gripSpace` property. In the case of the [AR example](https://kitware.github.io/vtk-js/examples/AR.html) tapping the screen creates an input source with a `targetRaySpace` but not a `gripSpace` because there is no independently tracked game controller.
Previous behavior: tapping the mobile device screen in the [AR example](https://kitware.github.io/vtk-js/examples/AR.html) causes an exception to be thrown and halts rendering.
New behavior: tapping the screen does not throw an exception or affect rendering.
- **vtk.js**: `master`
- **Browser**: Chrome 97.0.4692.71 (Windows 10)

fix(XR): Resolve mobile AR issue with absent gripspace

---

Sources/Rendering/Core/RenderWindowInteractor/index.js
Sources/Rendering/WebGPU/VolumePass/index.js
Sources/Rendering/WebGPU/VolumePassFSQ/index.js

The volume pass now uses the recentAnimaitonFrameRate
to render to a smaller texture when the view is animating to try
to reach the DesiredUpdateRate.
Added a new approach for checking frame rate to the
RenderWindowInteractor as web browsers are becoming more
strict about reporting exact elapsed times (due to fingerprinting)
so the new approach is designed to use a longer time frame thus
avoiding the anti fingerprint rounding the Date.now() does.

feat(WebGPU): support interactive volume rendering

---

Sources/Rendering/Core/AnnotatedCubeActor/index.d.ts

`IO/Core/ImageStream/example` doesn't compile with typescript without this change.
This PR only changes the typescript definitions, not the actual js code.
- **vtk.js**: 
- **OS**: 

doc(AnnotatedCubeActor): add missing type annotations

---

Sources/Common/DataModel/ITKHelper/index.js

itkjs use an integer pixel type, while the wasm version uses a string. Only look up the pixelType in the PixelTypes map if using wasm.
- **vtk.js**: 
- **OS**: 

BUG: itkImage pixelTypes wasm compatibility bug

---

Sources/Filters/General/AppendPolyData/test/testAppendPolyData.js
Sources/Filters/Sources/Arrow2DSource/index.js
Sources/Filters/Sources/ArrowSource/index.js
Sources/Filters/Sources/CircleSource/index.js
Sources/Filters/Sources/ConcentricCylinderSource/index.js
Sources/Filters/Sources/ConeSource/index.js
Sources/Filters/Sources/CubeSource/index.js
Sources/Filters/Sources/CylinderSource/index.js
Sources/Filters/Sources/LineSource/index.js
Sources/Filters/Sources/PlaneSource/index.js
Sources/Filters/Sources/PointSource/index.js
Sources/Filters/Sources/SLICSource/index.js
Sources/Filters/Sources/SphereSource/index.js
Sources/Filters/Sources/ViewFinderSource/index.js

Use Float64 instead of Float32 to define points coordinate of all source filters. It will avoid precision error.
@finetjul @martinken

perf(sources filters): use 64bits numbers for points coordinates

---

Examples/Applications/VolumeViewer/index.js
Sources/Rendering/Core/RenderWindowInteractor/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

Update the renderwindowinteractor to set the recentFrameTime
from the new approach which uses at least a one second
timeframe to compute rendering rates.
Update the WebGL VolumeMapper to use a callback for when the
animation rate changes on the renderwindowinteractor
and simplify a bit how the use of the smaller viewport
is handled.
Adjust the volumeviewer example to be 30 fps because 15fps
feels slow.

perf(WebGL): rework WebGL volumeMapper interactive rendering

---

package-lock.json
package.json

When building vtk.js as a dependency on CI, patch-package returns an error because we patch a dev dependency, which is not installed.
@finetjul 
- We only have patches relevant to rollup plugins, so only patch on rollup build.
using vtk.js as a dependency on CI should not fail.

chore(patch-package): only patch on rollup build

---

Sources/Widgets/Widgets3D/SplineWidget/behavior.js

Hovering a spline handle while the moveHandle was not initialized (origin=null) was causing errors.
Fix this by calculating the distance between moveHandle and handle only if their positions are set.
- **vtk.js**: 22.2.1
- **OS**: Ubuntu 20.04 LTS
- **Browser**: Chromium 98.0.4697.0

fix(splinewidget): fix crash when moveHandle is not initialized

---

Sources/Rendering/WebGPU/BindGroup/index.js
Sources/Rendering/WebGPU/Buffer/index.js
Sources/Rendering/WebGPU/BufferManager/index.js
Sources/Rendering/WebGPU/Device/index.js
Sources/Rendering/WebGPU/Glyph3DMapper/index.js
Sources/Rendering/WebGPU/HardwareSelectionPass/index.js
Sources/Rendering/WebGPU/HardwareSelector/index.js
Sources/Rendering/WebGPU/ImageMapper/index.js
Sources/Rendering/WebGPU/MapperHelper/index.js
Sources/Rendering/WebGPU/OpaquePass/index.js
Sources/Rendering/WebGPU/OrderIndependentTranslucentPass/index.js
Sources/Rendering/WebGPU/Pipeline/index.js
Sources/Rendering/WebGPU/PolyDataMapper/index.js
Sources/Rendering/WebGPU/RenderEncoder/index.js
Sources/Rendering/WebGPU/Renderer/index.js
Sources/Rendering/WebGPU/Sampler/index.js
Sources/Rendering/WebGPU/StorageBuffer/index.js
Sources/Rendering/WebGPU/Texture/index.js
Sources/Rendering/WebGPU/TextureView/index.js
Sources/Rendering/WebGPU/UniformBuffer/index.js
Sources/Rendering/WebGPU/VolumePass/index.js
Sources/Rendering/WebGPU/VolumePassFSQ/index.js

Make use of pushDebugGroup and labels in WebGPU to
provide better debugging support.
Renamed the "name" property of many webgpu objects to "label"
to match what WebGPU uses to provide debugging hints.

feat(WebGPU): add debugging support

---

Sources/Rendering/WebGPU/VolumePass/index.js
Sources/Rendering/WebGPU/VolumePassFSQ/index.js

Update the volume rendering gradient calculation to also compute the
normal so it can be used in lighting equations.
Add in very basic lighting code as a placeholder in volume rendering for
more complex lighting to be added later.

feat(WebGPU): Add shading to volume rendering

---

Sources/IO/Core/ImageStream/example/pvw-server.py

UseGradientBackground has been replaced by BackgroundColorMode
ImageStream example was crashing with ParaView 5.10
Drop support of ParaView < 5.10
Works with ParaView 5.10.
Gradient does not seem to work though.
- **vtk.js**: 
- **OS**: 
- **Browser**:

docs(imagestream): add ParaView 5.10 support

---

Sources/Rendering/Core/ScalarBarActor/index.js
Sources/Rendering/OpenGL/Profiles/All.js
Sources/Rendering/OpenGL/Profiles/Geometry.js
Sources/Rendering/OpenGL/ScalarBarActor/index.js
Sources/Rendering/WebGPU/Profiles/All.js
Sources/Rendering/WebGPU/Profiles/Geometry.js
Sources/Rendering/WebGPU/ScalarBarActor/index.js

This MR fixes the missing text updates for the
scalar bar actor on some browsers. It also separates
the View dependent data and functions from the non-view
dependent through a new helper class. One helper should be
created per view. Unfortunately this results in a huge
code change and one breaking API change. When users provided
their own function to compute values, those functions will
need to be reworked to deal with the new helper class.
The default autolayout function has been modified and
can be used as an example of how to update your own function.

fix(ScalarBarActor): Fix missing text updates

---

Documentation/content/docs/develop_widget.md
Sources/Widgets/Widgets3D/ShapeWidget/behavior.js

Mouse move events are no longer propagated to other widgets when dragging ShapeWidget handles
- **vtk.js**: 22.4.0
- **OS**: Ubuntu 20.04 LTS
- **Browser**: Chromium 98.0.4697.0

fix(shapewidget): absorb mouseMove event while moving shapewidget handles

---

Sources/IO/Core/DataAccessHelper/HttpDataAccessHelper.js
Sources/IO/Core/DataAccessHelper/test/testHttpDataAccessHelperFetchArray.js

The URL to fetch a dataset is currently built using a base url and the basepath and id  located in data.ref.
(See https://github.com/Kitware/vtk-js/blob/master/Data/volume/headsq.vti/index.json#L31)
Instead of building the url, it can be useful to directly provide the url where to fetch the array. A use case is for signed URLs.
Add a check for array.ref.url in HttpDataAccessHelper.fetchArray, and use it if it exists, else use the default process.
- **OS**: Ubuntu 20.04
- **Browser**: Chrome 98.0.4758.80

Add support for defining a full url in array.refs in index.json 

---

Sources/Rendering/Core/Mapper/index.js
Sources/Rendering/Core/Mapper2D/index.js

Call `getFieldDataTupleId()` instead of a static `-1` when computing `colorMapColors`,
allowing `setFieldDataTupleId` to set the index of the data tuple by which the model should be colorized.
- fix #2266
In both `Mapper` and `Mapper2D`, when mapping scalars to colors, pass `publicAPI.getFieldDataTupleId()` rather than a static `-1` as third argument to `lut.mapScalars()`.
As `fieldDataTupleId` defaults to `-1`, base behavior is not changed, while a call to `setFieldDataTupleId` is now taken into account.
- Before: call of `setFieldDataTupleId` was inoperant, the vector values at first index was always used
- After: values at expected index are used to color the geometry
- **vtk.js**: 22.4.2
- **OS**: Ubuntu 20
- **Browser**: Any (Firefox, Chrome)

fix(rendering): take fieldDataTupleId into account when mapping colors

---

Sources/Rendering/OpenGL/index.js
Sources/Rendering/WebGPU/BufferManager/Constants.js
Sources/Rendering/WebGPU/BufferManager/index.js
Sources/Rendering/WebGPU/Device/index.js
Sources/Rendering/WebGPU/ImageMapper/index.js
Sources/Rendering/WebGPU/PolyDataMapper/index.js
Sources/Rendering/WebGPU/RenderEncoder/index.js
Sources/Rendering/WebGPU/SphereMapper/index.js
Sources/Rendering/WebGPU/StickMapper/index.js
Sources/Rendering/WebGPU/TextureManager/index.js
Sources/Rendering/WebGPU/VolumePass/index.js
Sources/Rendering/WebGPU/VolumePassFSQ/index.js
Sources/Rendering/WebGPU/index.js

1) Fix for missing WebGL ScalarBarActor
2) Update to lates WebGPU that renamed endPass() to end()
3) move buffer and texture caches into a single
device based cache that can be used more generally.
This is a precurser to adding index buffers and a
mapping between original points and flat interpolated cell
data safe points (e.g. each point is only used as the provoking
vertex of a cell once)
Addresses https://discourse.vtk.org/t/typeerror-cannot-read-properties-of-undefined-reading-traverse/7803

fix(Rendering): a few fixes for Rendering

---

Sources/Rendering/Misc/SynchronizableRenderWindow/index.d.ts

Fix the wrong import of vtkRenderWindow types
fix #2279
- **vtk.js**: 
- **OS**: 

docs(ts): fix SynchronizableRenderWindow ts defs

---

Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/WebGPU/RenderWindow/index.js

Some screenshot may need a custom size/resetCamera handling. This change provide the user with the flexibility of defining its own function to do a resetCamera which can also do some magic scaling internally.

fix(RenderWindow): captureNextImage can be passed a resetCamera function

---

Sources/Rendering/Core/ColorTransferFunction/index.js

Change vtkColorTransferFunction.setNodes() to update mtime if the field changes.
The symptom is that when we use SynchronizableRenderWindow to update the
colormap from a remote server, the browser doesn't update the renderview unless
the update also changes other fields of vtkColorTransferFunction.

fix(ColorTransferFunction): updates to nodes don't update mtime

---

Utilities/ci/run-tests-in-docker.sh

Firefox bump from 76.0 to 94.0.

ci(GraphicalTesting): Bump Docker image to thewtex/opengl:ubuntu2004

---

Sources/Widgets/Representations/ImplicitPlaneRepresentation/index.js

Change the widget's normal and origin handles to honor the value of
scaleInPixels.

feat(ImplicitPlaneRepresentation): Support scaleInPixels

---

Sources/index.d.ts
Sources/vtk.d.ts
Utilities/rollup/plugin-generate-references.js
rollup.config.js

This changes will allow the discovery of the available vtk classes, types and interfaces
This changes only affects the ESM build.
- **vtk.js**: 
- **OS**: 
_This contribution is funded by CSD._

docs(ts): allow vtk classes discovery

---

Sources/Common/Core/MatrixBuilder/index.d.ts
Sources/Common/DataModel/ImageData/index.d.ts

I'm not sure how `.d.ts` types are generated in `vtk.js`, probably manually?
I found two wrong type definitions and this PR fixes them.
Affected files:
- `Sources/Common/Core/MatrixBuilder` 
- `Sources/Common/DataModel/ImageData`

docs(ts): imageData optional arguments

---

.github/workflows/build-test.yml
.github/workflows/pr-checks.yml
.github/workflows/publish.yml
Sources/Rendering/OpenGL/VolumeMapper/test/testLabelmapOutlineManyRenderer.js
Utilities/Karma/reporting-template.html
Utilities/Karma/tape-html-reporter.js
karma.conf.js

- Different test browsers were being used in release workflows vs PR workflows
- Tests now run on chrome and firefox via xvfb.
- github workflows run the same test command
- test results are uploaded as an artifact
This updates the test environment. Green github action results means this works.

Make test harnesses the same for release and PRs

---

Sources/Imaging/Core/ImageInterpolator/index.js
Sources/Imaging/Core/ImageReslice/index.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/example/controlPanel.html
Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js

If we use data headsq.vti in the vtkResliceCursorWidget example, we can see that when we rotate a vue, there are artifacts in the rotated view because of the interpolation. A linear interpolation instead of a nearest interpolation is needed.
Before
After
Add methods in vtkImageInterpolator called when interpolation mode is LINEAR.
Allow to set the interpolation mode from vtkImageReslice.

feat(vtkimageinterpolator): add linear interpolation

---

Sources/Common/DataModel/BoundingBox/api.md
Sources/Common/DataModel/BoundingBox/index.js
Sources/Common/DataModel/BoundingBox/test/testBoundingBox.js

Also speed-up vtkBoundingBox constructor
Some vtkBoundingBox functions do not return anything.
It would be more convenient to return the updated bounds.
BEFORE:
```
const bbox = vtkBoundingBox.newInstance();
bbox.setBounds(originalBounds);
bbox.inflate(10);
return bbox.getBounds();
```
AFTER:
```
const bbox = vtkBoundingBox.newInstance();
bbox.setBounds(originalBounds);
return bbox.inflate(10);
```
- **Browser**: Chrome 99.0.4844.82

refactor(boundingbox): return updated bounds instead of nothing

---

Documentation/content/docs/concepts_widgets.md

It has been decided that the SVG layer is provided as a POC instead of a strong solution.
Update documentation regarding the choice.

docs(svg): add limitations regarding SVG layer

---

Sources/IO/Core/DataAccessHelper/index.d.ts

- https://discourse.vtk.org/t/dataaccesshelper-is-not-defined/8139/4
- `DataAccessHelper` default export now has `has`, `get`, and `registerType`.

fix(DataAccessHelper): ts defs default export

---

Sources/Common/Core/Math/index.js
Sources/Filters/General/OBBTree/index.js
Sources/Filters/General/OBBTree/test/testOBBTree.js

~`vtkMath.jacobi` is giving some strange results when off-diagonal components are not quite zero. In the below code, if `v=0`, then we get what we'd expect: the eigenvectors are the unit basis vectors. But if `v=1e-12`, then we do not get that, as shown below the code listing.~
Upon some more testing, the values are valid. I will do some last-minute testing to verify OBB outputs.
```
const vals = [0, 0, 0];
const vecs = [
[0, 0, 0],
[0, 0, 0],
[0, 0, 0],
];
const v = 1e-12;
vtkMath.jacobi(
[
[0.5, v, v],
[v, 0.5, v],
[v, v, 0.5],
],
vals,
vecs
);
console.log(vals)
console.log(vecs)
// eigenvalues: [0.500000000002, 0.499999999999, 0.49999999999899997]
// eigenvectors: 
//  [0.577348850073642, 0.7071067811853349, 0.40825029739163465]
//  [0.5773488500736421, -0.7071067811877602, …
```

fix(OBBTree): send almost-zero components to zero

---

Examples/Widgets/Box/BoxWidget.js
Sources/Rendering/OpenGL/HardwareSelector/index.js
Sources/Rendering/OpenGL/Renderer/index.js
Sources/Widgets/Widgets3D/AngleWidget/behavior.js
Sources/Widgets/Widgets3D/DistanceWidget/behavior.js
Sources/Widgets/Widgets3D/ImageCroppingWidget/behavior.js
Sources/Widgets/Widgets3D/ImplicitPlaneWidget/index.js
Sources/Widgets/Widgets3D/LabelWidget/behavior.js
Sources/Widgets/Widgets3D/LineWidget/behavior.js
Sources/Widgets/Widgets3D/PaintWidget/behavior.js
Sources/Widgets/Widgets3D/PolyLineWidget/behavior.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js
Sources/Widgets/Widgets3D/ShapeWidget/behavior.js
Sources/Widgets/Widgets3D/SphereWidget/behavior.js
Sources/Widgets/Widgets3D/SplineWidget/behavior.js

Commit ac8b26ce1f5c36f7c577f2363820416bd625a72b (merged in master, tag v24.0.0) made many model variables protected by suffixing them with _, but some variables have been forgotten. 
This commit fix this by renaming the remaining variables, mainly in the Widgets3D directory.
- **vtk.js**: 24.0.0
- **OS**: Ubuntu 20.04 LTS
- **Browser**: Chromium 98.0.4697.0

fix(getstate): fix getState() on VTK objects

---

Examples/Rendering/Actor2D/index.js
Sources/Rendering/OpenGL/Glyph3DMapper/index.js
Sources/Rendering/OpenGL/Helper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper2D/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js

When the line width attribute on vtkProperty2D is more than 1, the 2D mapper makes multiple
instanced draw calls and the vertex shader offsets the vertex position based on the instance index.
- [ x ] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [ x ] Run `npm run reformat` to have correctly formatted code

feat(rendering): support wide lines with vtkMapper and vtkMapper2D

---

Sources/Rendering/Core/CubeAxesActor/index.js

Was only passing one parameter to the scaleAboutCenter method

fix(CubeAxesActor): fix bounds calculation

---

Sources/Rendering/Core/RenderWindowInteractor/index.js
Sources/Widgets/Core/WidgetManager/index.js
Sources/Widgets/Widgets3D/PolyLineWidget/behavior.js
Sources/macros.d.ts
Sources/macros.js

- Touch events on widgets is currently not supported. Related issues: #2285
- Touch start should select widget handles.
This change means widget selection no longer happens asynchronously alongside interaction. Instead, widget selection occurs first, and then re-triggers the original event, allowing interactors to handle the event. If widget selection takes significant time, interaction will suffer (which was sort of the case prior to this PR, but only wrt widget picking).
- Tested widgets:
- PolyLineWidget
- SphereWidget
- ResliceCursorWidget

Touch support with the widget manager

---

Sources/IO/Core/HttpDataSetReader/index.d.ts
Sources/IO/Core/HttpDataSetReader/index.js

Currently the only way to fetch a dataset is to provide a URL pointing to a JSON file, this change
aims to allow client-code to directly provide this object instead of making an extra round-trip to
the server. It is useful for some users who directly holds the dataset in their client application.
Before:
```javascript
reader.setUrl('data/index.json', { loadData: true }).then(() => {
// ---
});
```
After:
```javascript
import dataset from "data/index.json";
reader.parseObject(dataset, { loadData: false, baseUrl: "data" }).then(() => {
// ---
});
```
A parseObject method have been added to the HttpDataSetReader public API.
Struggling to get a working test for now. (draft PR)
- **OS**: archlinux
- **Browser**: Firefox

feat(httpdatasetreader): allow dataset fetching using a user-provided object

---

Sources/Rendering/OpenGL/OrderIndependentTranslucentPass/index.js

The new order independent translucent pass was not
being bypassed during selection.

fix(WebGL): fix translucent selection on WebGL

---

Utilities/build/patches/rollup-plugin-web-worker-loader+1.6.1.patch

- https://discourse.vtk.org/t/error-in-production-mode-using-vite-vuejs/8010/5
rollup-plugin-web-worker-loader funcToSource does not work with minified
functions, which gets it into trouble when a minifier does a pass over
the webworker code. This patch is intended to work around this issue by
wrapping the function in a function call, since the results of
funcToSource are evaluated in a worker context in the end.
- vite prod build works
- Tested manually using vite, vtk.js, and a volume rendering example and building for prod.

fix(web-worker-loader): patch/fix vite prod build

---

Sources/Rendering/Core/ScalarBarActor/index.js
Sources/Rendering/SceneGraph/ViewNode/index.js
Sources/Rendering/WebGPU/CellArrayMapper/index.js
Sources/Rendering/WebGPU/FullScreenQuad/index.js
Sources/Rendering/WebGPU/Glyph3DMapper/index.js
Sources/Rendering/WebGPU/ImageMapper/index.js
Sources/Rendering/WebGPU/OrderIndependentTranslucentPass/index.js
Sources/Rendering/WebGPU/Pipeline/index.js
Sources/Rendering/WebGPU/PolyDataMapper/index.js
Sources/Rendering/WebGPU/README.md
Sources/Rendering/WebGPU/RenderEncoder/index.js
Sources/Rendering/WebGPU/Renderer/index.js
Sources/Rendering/WebGPU/ShaderDescription/index.js
Sources/Rendering/WebGPU/SimpleMapper/index.js
Sources/Rendering/WebGPU/SphereMapper/index.js
Sources/Rendering/WebGPU/StickMapper/index.js
Sources/Rendering/WebGPU/StorageBuffer/index.js
Sources/Rendering/WebGPU/UniformBuffer/index.js
Sources/Rendering/WebGPU/Volume/index.js
Sources/Rendering/WebGPU/VolumePass/index.js
Sources/Rendering/WebGPU/VolumePassFSQ/index.js

Cleanup and document WebGPU mapper architecture.
This is a first step in trying to make the mappers
for WebGPU cleaner, better documented and more extensible.
The main trust here is to create a CellArrayMapper and update
the polydatamapper to just instantiate and use that. For example
one cellarray mapper for each of verts, lines, polysm, and strips
as opposed to having the polydatamapper try to manage all that
internally.
Also renamed and documented many methods to be more clear, fit better
with WebGPU terminology and have a more clear defined process.
There is more work to be done, the goal being to make mappers both
1) easy to customize - add shader code, add arrays to the VertexInput
2) easy to extend - with data pipelines we can easly add more stages
(filters) to data processing in …

chore(WebGPU): cleanup webgpu mappers

---

Sources/Rendering/OpenGL/RenderWindow/index.d.ts

- **vtk.js**: 
- **OS**: 
- **Browser**:

Fix getContainer() return type

---

Sources/Rendering/OpenGL/OrderIndependentTranslucentPass/index.js

Order independent tranlucent pass had an issue were
when there were multiple viewports with translucent actors
the framebuffer was being cleared for only the active viewport
when it needs to be entirely cleared.
Fixes issue: https://github.com/Kitware/vtk-js/issues/2377

fix(WebGL): fix viewport issue with translucency

---

Sources/Rendering/WebGPU/BufferManager/index.js
Sources/Rendering/WebGPU/CellArrayMapper/index.js
Sources/Rendering/WebGPU/Device/index.js
Sources/Rendering/WebGPU/Glyph3DMapper/index.js
Sources/Rendering/WebGPU/ImageMapper/index.js
Sources/Rendering/WebGPU/SphereMapper/index.js
Sources/Rendering/WebGPU/StickMapper/index.js
Sources/Rendering/WebGPU/StorageBuffer/index.js
Sources/Rendering/WebGPU/Texture/index.js
Sources/Rendering/WebGPU/TextureManager/index.js
Sources/Rendering/WebGPU/UniformBuffer/index.js
Sources/Rendering/WebGPU/VolumePass/index.js
Sources/Rendering/WebGPU/VolumePassFSQ/index.js

Stick mapper was setting frag_depth inside an if statement and
that was not working. Moved it outside the if statement.
Updated the device cache to use a map of weakrefs instead
of a weakmap. The old approach had issues keeping objects
too long if their sources never were freed. Such as if an
array just changes mtime but not source (not the best approach
but it happens)  The new cache approach just uses a WeakRef to
avoid the issue with sources/owner and so that concept was removed.
Now it is just a hash -> weakRef(object) map approach and when the
object finalizes we remove the entry in the map.

fix(WebGPU): fix to caching and minor fix to stick mapper

---

Sources/Common/Core/CellArray/index.js
Sources/Rendering/Core/Mapper/index.js
Sources/Rendering/WebGPU/BindGroup/index.js
Sources/Rendering/WebGPU/BufferManager/Constants.js
Sources/Rendering/WebGPU/BufferManager/index.js
Sources/Rendering/WebGPU/CellArrayMapper/index.js
Sources/Rendering/WebGPU/IndexBuffer/index.js
Sources/Rendering/WebGPU/RenderEncoder/index.js
Sources/Rendering/WebGPU/SimpleMapper/index.js
Sources/Rendering/WebGPU/VertexInput/index.js
Sources/Rendering/WebGPU/VolumePass/index.js

Add support for index buffers to the webgpu backend and use them in the
CellArrayMapper by default.
This approach uses a flat interpolation approach to support celldata. In
that each primitive must start with a provoking vertex that is only used
for that cell (not primitive). The flat ibo building code handles this
and sets up maps from flatIds to source point and cell IDs. These
mappings can be used to build flat array buffers for point or cell data
to go along with the index buffer.
Note that this flat packing is typically larger than the original point
array as we have to be careful not to use the same point to provoke
multiple cells. In a fully connected triangle mesh each point is shared
by 6 triangles. The old code would explode the point array by 6 as a
brute force solution. This …

feat(WebGPU): add support for index buffers

---

Sources/Widgets/Representations/ArrowHandleRepresentation/index.js
Sources/Widgets/Representations/CircleContextRepresentation/index.js
Sources/Widgets/Representations/CubeHandleRepresentation/index.js
Sources/Widgets/Representations/SphereContextRepresentation/index.js
Sources/Widgets/Representations/SphereHandleRepresentation/index.js

getSelectedState() is calling getRepresentationStates(). When hiding a handle, the compositeID of
the visible handles change because of the invisible handle not being rendered.
WidgetRepresentation.getRepresentationStates() returns all handle substates, visible or not.
fix #2374
Hiding widget handles (i.e. setVisible(false)) disrupts the handle selection. 
When a sphere handle gets invisible, it does not get rendered.
However, an invisible handle could still get selected. 
Invisible handles no longer disrupt visible handle picking.
Synchronize handle state between rendering (requestData) and selecting (getSelectedState)

fix(widget): fix widget picking when substates are invisible

---

Sources/Common/Core/ScalarsToColors/Constants.d.ts
Sources/Common/Core/ScalarsToColors/index.d.ts
Sources/Common/DataModel/Box/index.d.ts
Sources/Common/DataModel/ITKHelper/index.d.ts
Sources/Common/DataModel/Line/index.d.ts
Sources/Common/DataModel/PolyData/Constants.d.ts
Sources/Common/DataModel/Spline3D/Constants.d.ts
Sources/Common/DataModel/Spline3D/index.d.ts
Sources/Filters/General/ImageCropFilter/index.d.ts
Sources/Interaction/Widgets/OrientationMarkerWidget/Constants.d.ts
Sources/Interaction/Widgets/OrientationMarkerWidget/index.d.ts
Sources/Rendering/Core/Mapper/Constants.d.ts
Sources/Rendering/Core/Mapper/index.d.ts
Sources/Rendering/Core/Property/Constants.d.ts
Sources/Rendering/Core/Property/index.d.ts
Sources/Rendering/Core/RenderWindowInteractor/Constants.d.ts
Sources/Rendering/Core/RenderWindowInteractor/index.d.ts
Sources/Rendering/Core/Viewport/index.d.ts
Sources/Rendering/Core/VolumeMapper/Constants.d.ts
Sources/Rendering/Core/VolumeMapper/index.d.ts
Sources/Rendering/Core/VolumeProperty/index.d.ts
Sources/Rendering/Misc/FullScreenRenderWindow/index.d.ts
Sources/Rendering/OpenGL/RenderWindow/index.d.ts

- **vtk.js**: 
- **OS**: 
- **Browser**:

docs(ts): fix typescript defs

---

Sources/Common/DataModel/Cell/index.js
Sources/Common/DataModel/CellTypes/index.js
Sources/Common/DataModel/Line/index.d.ts
Sources/Common/DataModel/Line/index.js
Sources/Common/DataModel/PolyLine/index.d.ts
Sources/Common/DataModel/PolyLine/index.js
Sources/Rendering/Core/CellPicker/index.js

Currently, the CellPicker can only pick triangles.
CellPicker will also try to pick edges.
- Added a PolyLine data model class.
- Implemented evaluateLocation in vtkLine
- Changes the picking workflow ; now using `vtkPolyData.getCell` and `vtkPolyData.getCellType`
- **vtk.js**: v19.4.0
- **OS**: ArchLinux
- **Browser**: Firefox 99.0.1

Add edge picking support to the Cellpicker

---

Sources/Common/DataModel/CardinalSpline1D/index.d.ts
Sources/Common/DataModel/CardinalSpline1D/index.js
Sources/Common/DataModel/KochanekSpline1D/index.d.ts
Sources/Common/DataModel/KochanekSpline1D/index.js
Sources/Common/DataModel/Spline1D/Constants.js
Sources/Common/DataModel/Spline1D/index.d.ts
Sources/Common/DataModel/Spline1D/index.js
Sources/Common/DataModel/Spline3D/index.js
Sources/Widgets/Representations/SplineContextRepresentation/index.js
Sources/Widgets/Widgets3D/SplineWidget/example/controlPanel.html
Sources/Widgets/Widgets3D/SplineWidget/example/index.js
Sources/Widgets/Widgets3D/SplineWidget/index.js
Sources/Widgets/Widgets3D/SplineWidget/state.js

Support open splines.
Open splines are supported. The two methods already implemented for closed splines are now implemented for open splines. Different boundary conditions are available (on the derivative, second derivative, or second derivative of first interiror point).
Figure 1: Result of example of open spline (computation with Kochanek method). New parameters have been added to example.
Class changed : SplineWidget, SplineExample, Spline3D, KochanekSpline1D, CardinalSpline1D.
The spline example has been changed (as can be seen on the picture above). The user can choose whether to see opened or closed spline and change the boundary condition. The values related for opened spline computation can also be chosen for the x and y axis.
- **vtk.js**: 24.5.6
- …

Open spline 1 d

---

.github/workflows/publish.yml

Closes #2403. `doc:publish` is not updating the local gh-pages branch as expected. Disable trimming gh-pages history for now.
Docs get updated.

chore(github): do not clear gh-pages on publish

---

Sources/Common/Core/LookupTable/index.d.ts

Fixes #2413
Some methods arguments (and return types) are typed `Range` when they should be `RGBAColor`
The TS compiler is happier.
Updated a few TS definitions in methods I use.

Fix TS definitions in LookupTable

---

Sources/Widgets/Widgets3D/AngleWidget/behavior.js
Sources/Widgets/Widgets3D/DistanceWidget/behavior.js
Sources/Widgets/Widgets3D/LabelWidget/behavior.js
Sources/Widgets/Widgets3D/PolyLineWidget/behavior.js
Sources/Widgets/Widgets3D/ShapeWidget/behavior.js

Some widgets with a handle links to mouse move don't work with a touchscreen.
As the mousemove is not correctly used in touchscreen for widget, we'll have to get the mouse position when user touches instead of getting the move handle position which is set to null.
- [x ] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x ] Run `npm run reformat` to have correctly formatted code
- [ x] Tests passed

fix(Widgets3D): Allow to place widgets on touchscreen

---

Sources/Widgets/Core/StateBuilder/index.js

When adding a new handle on a widget for example, this is not possible to set properties on the constructor as in other vtk classes.
Here is the improvement for the `AngleWidget` (for example):
Before:
```
const widgetState = this.widget.getWidgetState();
const newHandle = widgetState.addHandle();
newHandle.setColor(moveHandle.getColor());
newHandle.setScale1(moveHandle.getScale1());
newHandle.setOrigin(pointList[i]);
```
After:
```
const widgetState = this.widget.getWidgetState();
const newHandle = widgetState.addHandle({
color: moveHandle.getColor(),
scale1: moveHandle.getScale1(),
origin: pointList[i]
});
```
- [X ] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages

feat(StateBuilder): Allow to set initial values on mixins creation

---

Sources/Widgets/Widgets3D/ImageCroppingWidget/state.js

- https://discourse.vtk.org/t/deleted-widgets-callback-is-executed/8391
- ImageCroppingWidget state was being reused between factories
- new states should be entirely isolated from each other

fix(ImageCroppingWidget): avoid state reuse

---

BREAKING_CHANGES.md

between 23 and 24
Not all breaking changes between 23 and 24 were documented
Give hints to switch to v24 
- **vtk.js**: 
- **OS**: 
- **Browser**:

docs(breakingchanges): add breaking changes documentation

---

Sources/Widgets/Representations/ArrowHandleRepresentation/index.js

With #2381, getRepresentationStates() can be an empty array, hence a crash when getShape() is called
on a non-existant first element.
fix #2416
LineWidget example was crashing
LineWidget is no longer crashing
Support when getRepresentationStates() returns an empty array (no origin and visible sub states)

fix(arrowhandlerepresentation): fix crash in ArrowHandleRepresentation

---

Sources/Interaction/Style/InteractorStyleManipulator/index.js
Sources/Interaction/Style/InteractorStyleManipulator/test/testDollyToPosition.js

Dollying in a 2D renderer that doesn't fill the render window requires adjusting the 2D click position relative to where the renderer is. This fixes also fixes the ZoomToMouse functionality on arbitrarily placed 2D renderers.
FYI @WillCMcC 
- dollyToPosition on 2D renderers works when renderers have non-default viewports

fix(InteractorStyleManipulator): dolly in renderer

---

Sources/Rendering/Core/Actor/index.js
Sources/Rendering/Core/HardwareSelector/example/index.js
Sources/Rendering/Core/HardwareSelector/test/testHardwareSelector.js
Sources/Rendering/Core/HardwareSelector/test/testHardwareSelectorSpeed.js
Sources/Rendering/Core/Mapper/index.js
Sources/Rendering/Core/Prop/index.js
Sources/Rendering/OpenGL/CellArrayBufferObject/index.js
Sources/Rendering/OpenGL/HardwareSelector/Constants.js
Sources/Rendering/OpenGL/HardwareSelector/index.js
Sources/Rendering/OpenGL/Helper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js

The WebGL hardware selector currently does not support picking point and cell ids.
This adds support for picking points and cells with the hardware selector. Currently only implemented for the polydata mapper.
- **vtk.js**: 
- **OS**: 
- **Browser**:

feat(hardwareselector): add hardware picking for point and cell ids

---

Sources/Rendering/Core/ScalarBarActor/index.js

Say you have a `scalarBarActor` instance and you want to sometimes update its styling; doing something like that:
```js
const newOverlayColor = "green";
scalarBarActor.setAxisTextStyle({ fontColor: newOverlayColor });
scalarBarActor.setTickTextStyle({ fontColor: newOverlayColor });
renderWindow.render();
```
Currently this code does not work.
This PR makes it so any changes done using the `vtkScalarBarActor` public API triggers a redraw of the actor.
Check for the renderable modified time.
- **vtk.js**: v19.4.0
- **OS**: Archlinux
- **Browser**: Firefox 100.0 (64-bit)

fix(scalarbaractor): check for renderable mtime when deciding if we should update the actor

---

Sources/Rendering/Core/Camera/index.js

Redundant calls to compute camera light matrix lead to unexpected view matrix update. 
Fix VR examples. Camera light is not supported.
Removed calls to `computeCameraLightMatrix()` in `Core/Camera` until further investigation into the function.
- **Browser**: Chrome Version 101.0.4951.54 (Official Build) (64-bit)

fix(camera): remove calls to computeCameraLightTransform

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

Movement should be triggered regardless of if we've tracked the pointer.
For touch, events will only be triggered if there is at least one
tracked pointer.
Fixes #2450 
- Fix RenderWindowInteractor

fix(RenderWindowInteractor): trigger mousemove

---

Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

Shader code does not compile when switching `ShadingOn` from `true` to `false`. This is a fix for MR [#2432](https://github.com/Kitware/vtk-js/pull/2432).
Test on all flags related to shading: shading; opacity gradient; density gradient; parallel projection; two sided lighting. No further bugs found.
Added additional condition `#if defined vtkGradientOpacityOn` so normal is computed either when there's lighting or when gradient opacity is on.
- **Browser**: Chrome 89.0.4389.128

fix(Shader): fix condition statement for shadingOff

---

Sources/IO/Core/WSLinkClient/index.d.ts
Sources/Rendering/Misc/RemoteView/example/index.js
Sources/Rendering/Misc/RemoteView/index.d.ts

Update sample to pass viewStream on vtkRemoteView creation,
rather than connecting it with the static connectImageStream,
allowing better lifecycle management.
Also update a couple of typescript definitions.

docs(RemoteView): improve sample viewStream creation

---

Sources/Rendering/WebGPU/RenderWindow/index.js

Fix the canvas creation call to use the new width, height,
alpha mode. Get the preferred format from the gpu now.

fix(WebGPU): update webgpu code to the latest chrome canary

---

Sources/Filters/General/OBBTree/test/testOBBTree.js

As explained [here](https://github.com/Kitware/vtk-js/pull/2339#issuecomment-1143758856), testing the bounding box on itself is not relevant since several bounding boxes could be computed while still being correct.
First test on OBBTree have been removed. Epsilon have been put back to 0.0001 to have more precise tests for the other tests.
- Chromium: 99.0.4844.88 for Ubuntu 18.04
- Chromium: 100.0.4852.0 for Windows 10
- Firefox: 98.0.2 (64-bit) for Windows 10 
- Firefox: 91.0 (64-bit) on Ubuntu 18.04

revert(testobbtree): delete obbtree box test

---

Sources/Interaction/Manipulators/MouseRangeManipulator/index.js

Race conditions can lead to the `onButtonDown` method to be called after `onPointerLockMove`, this means that `previousPosition` will be set to `undefined` while `onPointerLockMove` tries to access its `x` and `y` properties.
- **vtk.js**: 
- **OS**: 
This contribution is funded by [Sirona Medical](https://sironamedical.com).

fix: prevent unsafe model.previousPosition property access

---

Sources/Rendering/Core/VolumeMapper/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

Pull request for adding volume shadow support as part of realistic rendering module, also referred to as secondary shadow ray/secondary scatter. This pull request aligns with recent changes in VTK, but adds optimizations and two extra parameters to further  speed up rendering. Four parameters are included: 
- `volumetricScatteringBlending`: 
* range [0.0,1.0]
* 0.0: surface shadow
* 1.0: volume/global shadow
- `globalIlluminationReach`: 
* range [0.0,1.0]
* 0.0: maximum volume shadow ray length is equal to 1 unit of sampling distance
* 1.0: maximum volume shadow ray length is equal to the largest possible value of sqrt(3), i.e. no restriction on shadow ray
- `volumeShadowSamplingDistFactor`: 
* range [1.0, Infinity]
* modifies sampling distance of shadow ray (`SamplingDistanceISVS`) based …

feat(volume shadow): add volume shadow support for all lighting conditions

---

Sources/Rendering/WebGPU/VolumePass/index.js

Had a type that caused constant buffer reallocations
for volume rendering on WebGPU

fix(WebGPU): fix extra rebuild on volume rendering

---

Sources/Rendering/OpenGL/RenderWindow/index.js

Attaching event listeners anytime `get3dcontext` is called is very expensive and slows everything down.
get3dcontext will be almost free with this change.
- **vtk.js**: 
- **OS**: 
This contribution is funded by [Sirona Medical](https://sironamedical.com).

perf: attach webglcontextlost/webglcontextrestored only once

---

Sources/Rendering/OpenGL/RenderWindow/index.js

Calling the webgl.getParameter is relatively slow, and if called many times can result in a bottleneck.
From my understanding the result of this call will not vary during a single session so it's safe to cache it.
- **vtk.js**: 
- **OS**: 
- **Browser**:

perf: cache publicAPI.getHardwareMaximumLineWidth result

---

Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js

When computing the new center of the reslice cursor widget during mouse wheel, we previously applied twice the sign of the dirproj. Now it's applied only once.
@finetjul

fix(ResliceCursorWidget): Use correct moving factor

---

Sources/Widgets/Widgets3D/AngleWidget/behavior.js
Sources/Widgets/Widgets3D/DistanceWidget/behavior.js
Sources/Widgets/Widgets3D/ImageCroppingWidget/behavior.js
Sources/Widgets/Widgets3D/ImplicitPlaneWidget/index.js
Sources/Widgets/Widgets3D/LabelWidget/behavior.js
Sources/Widgets/Widgets3D/LineWidget/behavior.js
Sources/Widgets/Widgets3D/LineWidget/index.js
Sources/Widgets/Widgets3D/PolyLineWidget/behavior.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js
Sources/Widgets/Widgets3D/ShapeWidget/behavior.js
Sources/Widgets/Widgets3D/SphereWidget/behavior.js
Sources/Widgets/Widgets3D/SplineWidget/behavior.js

Uniformize dragging behavior to make it similar between all widgets: 
- always add the protected variable `_isDragging` in the model (if the widget can be dragged)
- do not change cursor & do not request animation if `model.dragable` is false
- refactor `handleLeftButtonRelease()` method to always return a value (`macro.VOID` or `macro.EVENT_ABORT`), and to correctly call `invokeEndInteractionEvent()`
- fix some cursors inconsistencies 
Also fixes a small bug in Angle/Distance/PolyLineWidget where we were calling `setOrigin` on a
PolyLineRepresentation.

fix(dragging): uniformize dragging behavior between widgets

---

Sources/Rendering/Core/CellPicker/index.js

Currently there is a `vtkCellTypes.deleteCell(cellId)` public method which set the type of the cell with the given `cellIId` to `VTK_EMPTY_CELL`.
I think the expected behavior from calling such a method is that the cell is simply ignored in most logic within VTK.js, picking included.
```
const someCellIdIWantToDelete = 5234;
polyData.buildCells();
const cellTypes = polyData.getCells();
cellTypes.deleteCell(someCellIdIWantToDelete)
```
Doing this kind of things and then trying to pick at the position of the cell will ignore the said cell.
Add a condition to skip empty cells in vtkCellPicker
- **vtk.js**: v19.4.0
- **OS**: linux
- **Browser**: firefox 100.0 (64-bit)

fix(cellpicker): skip cells that have the VTK_EMPTY_CELL type

---

Sources/Widgets/Representations/PolyLineRepresentation/index.js
Sources/Widgets/Widgets3D/AngleWidget/behavior.js
Sources/Widgets/Widgets3D/DistanceWidget/behavior.js
Sources/Widgets/Widgets3D/LineWidget/behavior.js
Sources/Widgets/Widgets3D/LineWidget/helpers.js
Sources/Widgets/Widgets3D/PolyLineWidget/behavior.js

Method `setMoveHandleVisibility` was called when the moveHandle origin was still `null`, causing it
to be filtered out (see ArrowHandleRepresentation:getRepresentationStates) and not rendered. 
Fix removing method `setMoveHandleVisibility` and using `updateHandleVisibility` to update moveHandle visibility.
---
When rendering a PolyLineRepresentation, the last point was ignored if not visible. On a LineWidget,
this was causing the line to disappear if the second point was hidden. 
Fix this by setting the origin of the moveHandle is set to null once the widget is placed.

fix(linewidget): moveHandle not visible and last point of polyline is ignored

---

Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

Shader doesn't compile when `VolumetricScatteringBlending` is set to 1.0 due to an error in conditional statement. 
Fixed issue
Changed #ifdef statement for gradient based lighting function declaration in vtkVolumeFS.glsl
- **Browser**: Chrome 89.0.4389.128

fix(Shader): fix condition statement for gradient-based shadow

---

Sources/Widgets/Widgets3D/ShapeWidget/behavior.js

Subtract needed a third parameter as output (even though it also returns the result) and not putting it was throwing an error. I added a third vector

fix(shapewidget): fix subtraction in compute text position

---

Sources/Widgets/Core/AbstractWidgetFactory/index.js
Sources/Widgets/Widgets3D/AngleWidget/index.js
Sources/Widgets/Widgets3D/DistanceWidget/index.js
Sources/Widgets/Widgets3D/EllipseWidget/index.js
Sources/Widgets/Widgets3D/ImageCroppingWidget/index.js
Sources/Widgets/Widgets3D/ImplicitPlaneWidget/index.js
Sources/Widgets/Widgets3D/InteractiveOrientationWidget/index.js
Sources/Widgets/Widgets3D/LabelWidget/index.js
Sources/Widgets/Widgets3D/LineWidget/index.js
Sources/Widgets/Widgets3D/PaintWidget/index.js
Sources/Widgets/Widgets3D/PolyLineWidget/index.js
Sources/Widgets/Widgets3D/RectangleWidget/index.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/index.js
Sources/Widgets/Widgets3D/SphereWidget/index.js
Sources/Widgets/Widgets3D/SplineWidget/index.js

The setTimeout can cause a race condition, where a widget can be
instantiated and subsequently deleted, causing an error.
This changes the way widgets are to be written. Rather than assigning
behavior and widgetState members directly, we pass them into the
vtkAbstractWidgetFactory constructor.
- Removes a race condition in vtkAbstractWidgetFactory

fix(AbstractWidgetFactory): avoid race condition

---

Sources/Rendering/WebGPU/Actor2D/index.js
Sources/Rendering/WebGPU/BufferManager/index.js
Sources/Rendering/WebGPU/CellArrayMapper/index.js
Sources/Rendering/WebGPU/Texture/index.js
Sources/Rendering/WebGPU/Types/index.js

Since WebGPU tests were last run a number of issues crept in
some due to WebGPU changes some due to changes in classes
outside of WebGPU.
- fix a bad use of string.contains which should have
been string.includes
- fix a case where cell normals and point normals
were using the shader program, shared pipeline hash
- better support for 3d texture coordinates
- fix a case where Actor2D could use an undefined matrix
There are still some new failures due to the Hardware selector
test being modified to test features that were only implemented
on the WebGL side plus failures that were present from before.

fix(WebGPU): fix a number of test failures

---

Utilities/ParaView/export-scene-macro.py

Although ParaView supports exporting a scene to `*.vtkjs`, the `export_scene_macro` is still useful for rapid customization, prototyping, and educational purposes.
One of the examples is https://discourse.paraview.org/t/trouble-exporting-scene-to-vtkjs/9829/10, where the native export was incomplete, but fixing it in C++ was infeasible for me. This is why I looked at the macro, update
[SceneExplorer_node-18.x.html.zip](https://github.com/Kitware/vtk-js/files/9050061/SceneExplorer_node-18.x.html.zip)
d it to support Python 3, fixed some issues and added the features that were missing for my use case.
This PR also fixes https://github.com/Kitware/vtk-js/issues/2499 which I found while looking at the code.
* The macro runs again (didn't any more, tested in ParaView 5.10.1 on macOS)
* The …

chore(export_scene_macro): fixes and improvements

---

Sources/Rendering/WebGPU/ImageMapper/index.js
Sources/Rendering/WebGPU/Pipeline/index.js
Sources/Rendering/WebGPU/RenderEncoder/index.js
Sources/Rendering/WebGPU/SimpleMapper/index.js

Fix an issue where the renderer UBO was being shared between
pipelines causing some multiviewport renderings to use an
incorrect UBO
Fix an issue in the ImageMapper where the world coordinates
and texture coordinates were not consistent with the new
definition of pixel ceneterd images.
Fix an issue where the range of a color transfer function
was being ignored in one place while used in building the table.

fix(WebGPU): fix two issues in WebGPU

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

Short-term fix for issue where touching the screen on an Android device
during an AR session would crash the scene as a result of bad touch
event handling and XR Gamepad API polling. New behavior is no crash.
Future commit should add ability to parse data from event for interactivity.
Supports recent WebXR developments on mobile, including feedback from [WebXR examples](https://kitware.github.io/vtk-js/docs/develop_webxr.html).
AR scene no longer crashes on touch on Android device in local testing.
- Fixes issue with bad access on touch-end event
- Fixes issue with unexpected handedness parameter for WebXR Gamepad data
- **vtk.js**:  `master`
- **OS**:  Windows 10, Android 11
- **Browser**:  Chrome 103.0.5060.114

fix(renderwindowinteractor): resolve WebXR AR touch event error on Android

---

Sources/Rendering/OpenGL/ImageMapper/index.js

ImageMapper cropping planes are not correctly positioned.  This codesandbox illustrates the issue:
https://codesandbox.io/s/volume-rendering-bounds-forked-e8433n?file=/src/index.js
Fixes crop planes on ImageMapper.
Need to transform cropping plane normals by `transpose(inverse(worldToIndex))` rather than just `worldToIndex`
Can test with this modified ImageCroppingWidget example that has ImageSlices
```
import { vec3, quat, mat4 } from 'gl-matrix';
import 'vtk.js/Sources/favicon';
// Load the rendering pieces we want to use (for both WebGL and WebGPU)
import 'vtk.js/Sources/Rendering/Profiles/Geometry';
import 'vtk.js/Sources/Rendering/Profiles/Volume';
import 'vtk.js/Sources/Rendering/Profiles/Glyph';
import vtkFullScreenRenderWindow from …
```

fix(ImageMapper): cropping planes on ImageData's with non-uniform transforms

---

Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

fix #2520 
No shader compile errors.
Fallback to classic lighting when 2+ components
`npm run example TestVolumeTypes` and add components.
- **OS**: Ubuntu 22.04
- **Browser**: Chrome 103

fix(volume-shader): disable cinematic rendering if 2+ components

---

Sources/Rendering/Core/VolumeMapper/index.d.ts
Sources/Rendering/Core/VolumeMapper/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

Add local ambient occlusion feature as part of the cinematic rendering module. Volumetric shading often return sharp shadows that completely occlude parts of the volume. LAO renders soft shadow and provides an alternative to work around the issue.
Images taken with different kernel size and kernel radius, only ambient lighting is on:
Two other interactive samples are available:
[Ultrasound data](https://kitwaremedical.github.io/vtk.js-render-tests/LAODemoFetus.html)
[Head CT](https://kitwaremedical.github.io/vtk.js-render-tests/LAODemoHead.html)
Random directions are sampled by combining `Math.random()` function and shader's jitter texture. Final light translucency is thresholded to be greater than 0.3 to reduce variance. To speed up rendering, full brightness is returned at sample …

Local ambient occlusion

---

.github/workflows/build-test.yml
.github/workflows/pr-checks.yml
.github/workflows/publish.yml
README.md

Node v16 is the current active release.
N/A
- Updated github actions workflow
N/A

chore(github): drop node 12 from testing

---

Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js

- Starting a dolly before mouse move or mouse press and then moving the mouse results in usage of `model.previousPosition` when it's not yet set.
- No more console errors for this corner case.
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(InteractorStyleTrackballCamera): null guard

---

Sources/Rendering/OpenGL/RenderWindow/ContextProxy.js
Sources/Rendering/OpenGL/RenderWindow/index.js

This is the continuation of #2484, since I could not push to @FezVrasta's branch.
We use ES6 proxies to cache calls to getParameter and depthMask.
- improved performance on repeated calls to getParameter, which go through the cache rather than the webgl context.

perf(OpenGLRenderWindow): caching proxy gl context

---

Sources/Rendering/WebGPU/ForwardPass/index.js
Sources/Rendering/WebGPU/OpaquePass/index.js
Sources/Rendering/WebGPU/OrderIndependentTranslucentPass/index.js
Sources/Rendering/WebGPU/RenderEncoder/index.js
Sources/Rendering/WebGPU/RenderWindow/index.js
Sources/Rendering/WebGPU/TextureView/index.js
Sources/Rendering/WebGPU/VolumePass/index.js

With this MR the WebGPU backend will use half float
buffers for the opaque pass, and blit that into the
target preferredFormat for the canvas.

feat(WebGPU): update to use half float buffers

---

Sources/Common/DataModel/Quad/Constants.js
Sources/Common/DataModel/Quad/index.d.ts
Sources/Common/DataModel/Quad/index.js
Sources/Common/DataModel/Quad/test/testQuad.js
Sources/Common/DataModel/Triangle/index.d.ts
Sources/Rendering/Core/CellPicker/index.js
Sources/Rendering/Core/CellPicker/test/testCellPicker.js

This MR aims to implement the vtkQuad class as suggested by @finetjul in #2508 
Created vtkQuad class. Type script updated but unsure on how to change documentation?
Added unit tests but two are failing for the pcoords, I have copied the behaviour in the cxx library but the tests are from the vtkTriangle vtk.js class so they may be incorrect, I am not familiar enough with how these are calculated as to whether they are correct. Maybe @finetjul you could take a look?
- **vtk.js**: latest
- **OS**: Mac OS 12.4
- **Browser**:  Chrome (through karma)

Implement vtkQuad

---

Sources/Filters/General/ClipClosedSurface/index.js

fix(vtkClipClosedSurface): Fix stack overflow when inputPolys.getCellSizes() is too big

---

Sources/Rendering/Core/AbstractMapper/index.d.ts
Sources/Rendering/Core/AbstractMapper/index.js

Removing a clipping plane was modifying the mapper, while removing them all wasn't.
See #1287 
Mapper is modified when removing all clipping planes

fix(mapper): modify mapper when clearing clipping planes

---

Sources/Rendering/OpenGL/RenderWindow/ContextProxy.js

Fixes #2558. Makes the receiver the WebGL2Context directly when using Reflect.
XR/AR works again.

fix(RenderWindow): use gl as receiver directly

---

Sources/Common/Core/CellArray/index.d.ts
Sources/Common/Core/DataArray/index.d.ts
Sources/Common/Core/MatrixBuilder/index.d.ts
Sources/types.d.ts

Type `TypedArray` shouldn't include `number[]`
- **vtk.js**: 
- **OS**: 
- **Browser**:

docs(ts): fix TypedArray definition

---

Sources/Filters/General/TubeFilter/index.js
Sources/Filters/General/TubeFilter/test/testTubeFilter.js

Fixes #2559 
Updated when npts was allocated and changed to use computeOffset which does the same calcualtion but if ever needs changing at least it is only in one place
Edit and uncomment the section below if relevant

fix(tubeFilter): update npts and change to global func

---

Examples/Volume/VolumeMapperBlendModes/controller.html
Examples/Volume/VolumeMapperBlendModes/index.js
Sources/Rendering/Core/VolumeMapper/Constants.d.ts
Sources/Rendering/Core/VolumeMapper/Constants.js
Sources/Rendering/Core/VolumeMapper/index.d.ts
Sources/Rendering/Core/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

Add the possibility to use the radon transform in blending mode.
Updated vtkVolumeFS glsl file to introduce radon transform.
You can see the changes by running the VolumeMapperBlendModes example.
@finetjul @martinken 
The first needed code review is for the glsl file. I'll update the example code later.

feat(OpenGLRendering): Add radon blending mode

---

Sources/Rendering/Core/ScalarBarActor/example/controlPanel.html
Sources/Rendering/Core/ScalarBarActor/example/index.js

I needed to debug vtkScalarBarActor hence I wanted a convenient way to play with it.
I added an example to ply with vtkScalarBarActor.

docs(scalarbaractor): add ScalarBarActor example

---

Sources/Rendering/OpenGL/HardwareSelector/index.js
Sources/Widgets/Core/WidgetManager/index.js

- Touch widget support is broken. Related: https://discourse.vtk.org/t/reslicecursorwidget-does-not-operate-the-cross-selector-normally-on-the-mobile-touch-screen/8743/8
- Multiple widget managers cause freezes. Related: #2435, #2438
FYI @finetjul. I'm still investigating, but here is something that might work.
- touch should work on widgets
- multiple widget managers should not freeze
- polyline widget with an orientation marker widget

fix(WidgetManager): handle touch support

---

Sources/Rendering/OpenGL/CellArrayBufferObject/index.js

New cells array was created using points length and would overflow in some cases. Fixed to use cells length.
Using vtk.js version 25.8.3. We have functionality where surfaces of a visualization can be hidden. A few surfaces before everything is hidden the OpenGL selectionsMap cell&point counts change so that there are more cells than points.
The cells array length is initiated with length from points, thus causing Int32Array overflow.
```
CellArrayBufferObject.js:280 Uncaught RangeError: offset is out of bounds
at Int32Array.set (<anonymous>)
at publicAPI.createVBO (CellArrayBufferObject.js:280:18)
at publicAPI.buildBufferObjects (PolyDataMapper.js:1274:63)
at publicAPI.updateBufferObjects (PolyDataMapper.js:1144:17)
at publicAPI.renderPieceStart (PolyDataMapper.js:1041:15)
at …
```

fix(cellarraybufferobject.js): fix selectionsMaps cells array creation

---

Sources/Interaction/Manipulators/MouseRangeManipulator/index.js
Sources/Interaction/Manipulators/MouseRangeManipulator/test/testMouseRangeManipulator.js

The MouseRangeManipulator incorrectly deletes the horiz listener when calling removeVerticalListener, and vice-versa.
Correct deletion of the appropriate listener.

fix(MouseRangeManipulator): swap listener deletion

---

Sources/Rendering/Core/Prop3D/index.js
Sources/Testing/testMacro.js
Sources/Widgets/Representations/WidgetRepresentation/index.js
Sources/Widgets/SVG/SVGLandmarkRepresentation/index.js
Sources/macros.d.ts
Sources/macros.js

fix #2575 
Improve rendering performances when having widgets in the renderer.
Create a new 'object' type in `macro.setGet()` or `macro.set()`

Add object set

---

Sources/Common/Core/ClassHierarchy/index.js

Small perf improvement that avoids a quite frequent GC event from happening.
- **vtk.js**: 
- **OS**: 
- **Browser**:

perf: avoid GC calls

---

Sources/Rendering/Core/HardwareSelector/example/index.js
Sources/Rendering/Core/HardwareSelector/test/testHardwareSelectorPoints.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js

Bug in the hardware selector, when in edge + surface mode and in FIELD_ASSOCIATION_CELLS mode.
The hardware selector doesn't find the cell ID when picking exactly on an edge.
The cell ID is now right when picking exactly on an edge.
- Fixed and improved the hardware selector example.
- Fixed a call to `creatVBO` in the PolyDataMapper.
No test added or changed.

Fix hardware selector on edges

---

Sources/Rendering/Core/ColorTransferFunction/index.d.ts
Sources/Rendering/Core/ColorTransferFunction/index.js

In order to support sigmoid LUT based on dicom standard, non-linear LUT's need to be created on the fly any time a user changes the WW/WL. The current buildFunctionFromTable only support linearly spaced x input which is inefficient sampling for sigmoid functions. This change simply allows users to build functions from the long format as used in RGBLong.
This change simply allows users to build functions from the long format as used in RGBLong.
Because this is a surgical change, no new tests have been added.

feat: added nonlinear param to buildFunctionFromTable

---

Sources/Rendering/Core/ColorTransferFunction/index.js
Sources/Rendering/Core/ColorTransferFunction/test/testColorTransferFunction.js

Similar shaped color maps passed to `ColorTransferFunction.applyColorMap()` did not always trigger publicAPI.modified()
More exhaustive change checking in `applyColorMap`
- **vtk.js**: 25.9.2
- **OS**: LInux
- **Browser**: Chrome 105

fix(ColorTransferFunction): applyColorMap calls modified in more cases

---

Sources/Rendering/Core/ScalarBarActor/example/index.js

Scalarbar actor ticks for negative values were displayed as NaN.
d3 uses minus character instead of hyphen-minus. This is why parseFloat failed to convert the string to a number.
Negative values are now correctly displayed.
Replace minus char with hyphen-minus char.

docs(scalarbaractor): support negative numbers

---

Sources/Common/DataModel/BoundingBox/index.js
Sources/Common/DataModel/IncrementalOctreeNode/index.d.ts
Sources/Common/DataModel/IncrementalOctreeNode/index.js
Sources/Common/DataModel/IncrementalOctreePointLocator/index.js
Sources/Common/DataModel/Polygon/index.js
Sources/Filters/General/ClipClosedSurface/index.js
Sources/Filters/General/ContourTriangulator/helper.js

Fix vtkClipClosedSurface filter.
The filter was taking a long time to compute.
This speeds-up the computation.
This fix correctly merge polylines into a unique polygon but also compute polygon tolerance.
Closes #2570 
- [] This change adds or fixes unit tests 

Fix clip closed surface

---

Sources/Common/Core/Math/Constants.js
Sources/Common/Core/Math/index.d.ts
Sources/Common/Core/Math/index.js
Sources/Common/Core/MatrixBuilder/index.d.ts
Sources/Common/Core/MatrixBuilder/index.js
Sources/Common/DataModel/ImageData/index.js
Sources/Common/Transform/Transform/index.js
Sources/Common/Transform/index.js
Sources/Imaging/Core/ImageReslice/index.js
Sources/Imaging/Core/ImageReslice/test/testImageReslice.js
Sources/Imaging/Core/ImageReslice/test/testImageReslice.py
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/VolumeMapper/test/testLabelmapOutlineManyRenderer.js
Sources/macros.js
package.json

DICOM files may produce oriented image data (vtkImageData.getDirection() returns a non identity 3x3 matrix). 
Oriented images are currently not supported in vtkImageReslice.
This PR adds support of oriented image data in vtkImageReslice.
It is therefore available in the ResliceCursor widget.
vtkImageReslice.resliceTransform is also supported for homogeneous transforms.

Image reslice oriented image support

---

Sources/Common/Core/ScalarsToColors/index.d.ts
Sources/Common/Core/ScalarsToColors/index.js

vtkScalarsToColors.getRange() should ignore min max values
#2603 related

fix: vtkScalarsToColors.getRange() should ignore min max values

---

Sources/Rendering/SceneGraph/ViewNode/index.js

Scene graph node destructors are not invoked when pruned. As a result, certain references may be retained (e.g. in [vtkOpenGLVolumeMapper](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/VolumeMapper/index.js#L1115)), resulting in a memory leak.
- Scene graph nodes have their `.delete()` method called appropriately.
- No tests are changed. Test results are checked by CI.

fix(ViewNode): delete scene graph nodes

---

Sources/Common/DataModel/EdgeLocator/index.d.ts
Sources/Common/DataModel/EdgeLocator/index.js

The docs generation is failing due to an invalid jsdoctype entry in the EdgeLocator type definitions.
FYI @finetjul @daker  I've made some updates to the types to be more specific than just `any`.
The docs should generate cleanly.
No tests are modified by this change.

docs(EdgeLocator): fix parse and update types

---

Documentation/content/docs/concepts_widgets.md
Sources/Rendering/OpenGL/RenderWindow/index.d.ts
Sources/Rendering/SceneGraph/RenderWindowViewNode/index.js
Sources/Widgets/Core/WidgetManager/index.js
Sources/Widgets/Core/WidgetManager/test/testWidgetManager.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js

Widget handles with `scaleInPixels` appear smaller when window.devicePixelRatio is more than 1.  Expected them to be the same CSS pixel size.
Smaller when screen "scale" setting is 200%:
100% scale
200% scale
Adds vtkRenderWindowViewNode.getComputedDevicePixelRatio using DOM container CSS pixel size and user set rendering pixel size.
`npm run example -- ImageCroppingWidget` and change display settings or browser zoom.
- **vtk.js**: 25.9.1
- **OS**: Linux
- **Browser**: Chrome 105

Fix widgets with scaleInPixels by adding RenderWindowViewNode.getComputedDevicePixelRatio

---

Sources/Widgets/Core/AbstractWidget/index.js
Sources/Widgets/Core/WidgetManager/index.js

The WidgetManager triggers unnecessary renders which can be expensive while performing the picking operation.
- The WidgetManager triggers a render only when a widget selection changes.

perf(WidgetManager): reduce capture/render calls

---

Sources/Filters/General/index.js

- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(Filters): Correctly export three filters

---

Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js

In PolyDataMapper and ImageMapper, `lastRenderPassShaderReplacement` was sometimes not updated.
It should have been updated in `getNeedToRebuildShaders`, but when this function was not called, the update didn't occur.
Fixed this behaviour by moving the update of `lastRenderPassShaderReplacement` in the render function.

Avoid side effects of getNeedToRebuildShaders

---

Sources/Interaction/Widgets/OrientationMarkerWidget/index.js
Sources/Rendering/Core/RenderWindowInteractor/index.d.ts
Sources/Rendering/Core/RenderWindowInteractor/index.js

Edit findPokedRenderer to handle a case when `rc` is an empt list (used to return undefined)
Edit typescript header as findPokedRenderer sometimes return null
Edit a call to this function in OrientationMarkerWidget accordingly, which sometimes caused errors

Add null to findPokedRenderer return type

---

Sources/Rendering/Core/SphereMapper/example/controlPanel.html
Sources/Rendering/Core/SphereMapper/example/index.js
Sources/Rendering/Core/SphereMapper/index.d.ts
Sources/Rendering/Core/SphereMapper/index.js
Sources/Rendering/OpenGL/SphereMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkSphereMapperVS.glsl
Sources/Rendering/WebGPU/SphereMapper/index.js

- fix #2036 
- Added `scaleFactor` property in `SphereMapper`
Run the `SphereMapper` example, try to modify `ScaleFactor` and observe the sphere radii change.
- **OS**: ubuntu
- **Browser**: Chrome 107.0.5304.121

feat(SphereMapper): add scaleFactor to scale radius of sphere

---

Sources/Rendering/Core/HardwareSelector/example/index.js

Add an actor to the HardwaerSelector example.
It is a polydata containing a vert, a line and a poly.
This highlights a bug with actors containing multiple primitive types.
There is a bug in the HardwareSelector which makes it pick the wrong cell when multiple cell primitives (vert, line, poly) are used.
This pull request only provides an example highlighting the bug.
Add an actor to the HardwareSelector example.

docs(HardwareSelector): add a new example actor

---

Sources/Interaction/Manipulators/MouseRangeManipulator/index.js
Sources/Interaction/Style/InteractorStyleImage/index.js
Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js
Sources/Rendering/Core/RenderWindowInteractor/index.js
Sources/Widgets/Widgets3D/LineWidget/behavior.js
Sources/Widgets/Widgets3D/PaintWidget/behavior.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js

When doing a single mouse wheel scroll (for mouses with notches on their wheel) on one of the views of the widget, one can expect a single slice change. However, this does not occur since the startMouseWheel method of the widget does not call handleMouseWheel.

fix(reslicecursorwidget): fix ResliceCursorWidget small mouse wheel scroll

---

Sources/Rendering/Core/RenderWindowInteractor/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js

Remove `webglcontextlost` and `webglcontextrestored` eventListeners added for canvas when deleting the RenderWindow.
fix #2670
It is no longer leaking memory through these event listeners.
No changes to API, clean up internally.
- **vtk.js**: 25.8.5
- **OS**: 12.6.2
- **Browser**: Chrome 108.0.5359.124

Clean OpenGL RenderWindow eventListeners

---

Sources/Rendering/OpenGL/Texture/index.js

Preferring texStorage2D/3D over texImage2D/3D inherently comes with a performance improvement because they ensure that the texture is complete at allocation.
Using texStorage ensures that textures are complete at allocation time

perf(rendering): use texStorage for WebGL2 texture allocations

---

Sources/Widgets/Representations/ConvexFaceContextRepresentation/index.js

Regression from fe5d3f9
Closes #2684
Crash in InteractiveOrientationWidget example
No more crash in InteractiveOrientationWidget example

fix(convexfacecontextrepresentation): fix allocateSize crash

---

.eslintrc.js
Sources/macros.js

Adds BigInt64 support in order to handle converting `int64` datatypes from VTK.
- BigInt64 and UBigInt64 should now be supported.

feat: add (U)BigInt64 support

---

Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

This change fixes some performance issues in the cinematic volume rendering shader namely,
- jittering sample distance with larger values when computing the shadow 
- optimizing the shadow computation

Volume cvr fixes

---

Sources/Common/Core/Math/index.d.ts
Sources/Common/Core/Math/index.js
Sources/Common/DataModel/BoundingBox/index.js
Sources/Common/DataModel/ImageData/index.js
Sources/Proxy/Core/ProxyManager/example/index.js
Sources/Proxy/Core/ProxyManager/example/proxy.js
Sources/Proxy/Core/View2DProxy/example/index.js
Sources/Proxy/Core/View2DProxy/example/proxy.js
Sources/Proxy/Core/View2DProxy/index.js
Sources/Proxy/Core/ViewProxy/index.js
Sources/Widgets/Widgets3D/ShapeWidget/behavior.js

Add an option to fit camera to bounds
When this option is checked and the view is parallel, calling resetCamera will zoom until the bounds of the props fit as most as possible in the field of view
Works too when the camera is not aligned with the axes and with any prop
This can be easily extended to also work when the camera is not parallel, as visiblePoints remain valid (do not use viewBounds wihtout a parallel camera as it will be less precise)
See [this issue](https://github.com/Kitware/glance/issues/356) from glance
Without fitting:
With fitting:
Because the fitting uses bounds, it is not always perfect.
For example, in the View2DProxy example, you can move the camera using these lines of code:
```
view2DProxy.getCamera().setViewUp([Math.sqrt(2), 0, -Math.sqrt(2)]);
view2DProxy …
```

feat(cameraFit): add view2DProxy option to fit camera to bounds

---

Sources/Rendering/Core/HardwareSelector/test/testHardwareSelectorPoints.js
Sources/Rendering/OpenGL/CellArrayBufferObject/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js

Take cellOffset into account in `selectionMaps` when creating a VBO with `createVBO()`
Disable rendering of edges when rendering for picking
Added a test for this bug
Closes #2664

Fix HardwareSelector picking of actors with both polylines and polys

---

Sources/Rendering/OpenGL/RenderWindow/index.d.ts
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/Texture/index.js

Fixes #2681, `preferSizeOverAccuracy` enables `halfFloat` use which overrides `norm16`
Safari is able to use half float textures from uint16/int16 array buffers.
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix: use half float flag overrides norm16 flag

---

Sources/Common/Core/CellArray/index.d.ts
Sources/Common/Core/CellArray/index.js
Sources/Widgets/Representations/PolyLineRepresentation/index.js

The lines cell array did not contain any cell.
The linewidget example was not showing any line between the 2 handles.
The line is now visible in the LineWidget example.
- **OS**: Windows 

fix(linewidget): restore the hidden line in the LineWidget

---

Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

Regression from a6d9d32d. Closes #2658
fix #2658
Radon transform example was displaying a fully white volume.
With change the volume is now back to a grayscale volume.

fix(radon): fix radon transform following half-float support

---

Sources/Proxy/Core/View2DProxy/example/index.js
Sources/Proxy/Core/View2DProxy/index.js

The estimated hull of an ImageSlice was too coarse when `indexToWorld` matrix of the underlying ImageData was used, `getPropCoarseHull` didn't use this matrix.
Update `getPropCoarseHull` to take this matrix into account when possible and better fit the view to the ImageSlice.
See PR #2689 which introduces the feature "camera fit props".

Better fitProps with ImageSlice in View2DProxy

---

Sources/Rendering/Core/ImageMapper/index.d.ts

- **vtk.js**: 
- **OS**: 
- **Browser**:

Update vtkImageMapper interface

---

Sources/Rendering/OpenGL/ImageMapper/index.js

This addresses issue #2710:
TypeError is thrown on call to `texture.bind()` due to releasing texture but not re-allocating it. A temporary fix is to use the resizable flag so that a delete/create of textures is not required (`ImageMapper` textures are no longer immutable).
- **vtk.js**: master 
- **OS**: Windows 11 
- **Browser**: Chrome 109.0.5414.120 (Official Build) **(64-bit)**

fix(ImageMapper): TypeError in ImageMapper bindTexture

---

Sources/Proxy/Core/ViewProxy/index.d.ts

Typescript .d.ts mismatch on case of GL in ViewProxy::getOpenGLRenderWindow()
Updates case of ViewProxy::getOpenGLRenderWindow() in .d.ts.

fix(ViewProxy): in .d.ts change case of gl in getOpenGLRenderWindow

---

Sources/Rendering/OpenGL/Texture/index.js

When creating a texture from an image which dimensions are not powers of 2, vtk.js used to:
- create a canvas bigger than the image, which dimensions are powers of 2
- paint and stretch the image to fill the canvas
- use as texture a piece of the canvas which has the same size as the image
Fixed this behaviour by using the size of the canvas instead of the size of the image to create the texture.
To illustrate the bug, here is an example with a 1500x700 image applied to a plane
Before the fix, the image was stretched to 2048x1024 and then cropped to 1500x700
Before
After

Fix texture from image cropping when size is not a power of two

---

Examples/Geometry/Picking/controller.html
Examples/Geometry/Picking/index.js
Sources/Rendering/OpenGL/HardwareSelector/index.js

When picking points, the hardware selector ensures that the depthbuffer is not written to in the selection render pass. This change removes the additional preserve depth buffer call that is unnecessary and was generating wrong z-buffer values between successive selections.
Fixes https://github.com/Kitware/react-vtk-js/issues/93

fix(picking): point picking Z-values with hardware selector

---

Sources/Rendering/Core/SphereMapper/example/controlPanel.html
Sources/Rendering/Core/SphereMapper/example/index.js
Sources/Rendering/OpenGL/glsl/vtkSphereMapperVS.glsl

Add picking support for the sphere mapper
Add picking to the `SphereMapper` example
Closes #2659

Add sphere mapper picking support

---

Sources/Rendering/OpenGL/OrderIndependentTranslucentPass/index.js
Sources/Rendering/OpenGL/SurfaceLIC/SurfaceLICInterface/index.js
Sources/Rendering/OpenGL/SurfaceLIC/SurfaceLICMapper/index.js

Order independant translucent pass uses draw buffer location 1.
Surface LIC was also using location 1 making it impossible to use in a scene with translucent objects.
Moved locations 1 and 2 to locations 2 and 3.
The order independant translucent pass used an 'opaquePass' to get the Z-buffer.
This pass doesn't work for objects rendered with LIC and is not optimized for Z buffer rendering (no need to compute colors, or render edges). As a result, translucent objects were renderd on top of LIC objects.
Replaced this 'opaquePass' with an 'opaqueZBufferPass'.

Fix LIC and translucency

---

BREAKING_CHANGES.md
Sources/Common/Core/DataArray/index.js
Sources/Common/Core/ScalarsToColors/index.d.ts
Sources/Common/Core/ScalarsToColors/index.js
Sources/Rendering/Core/Mapper/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Widgets/Core/AbstractWidget/index.js
Sources/Widgets/Core/AbstractWidgetFactory/index.d.ts
Sources/Widgets/Core/AbstractWidgetFactory/index.js
Sources/Widgets/Core/StateBuilder/color3Mixin.js
Sources/Widgets/Core/StateBuilder/originMixin.js
Sources/Widgets/Core/WidgetManager/index.d.ts
Sources/Widgets/Core/WidgetManager/index.js
Sources/Widgets/Representations/GlyphRepresentation/index.js
Sources/Widgets/Representations/ImplicitPlaneRepresentation/index.js
Sources/Widgets/Representations/PolyLineRepresentation/index.js
Sources/Widgets/Representations/WidgetRepresentation/api.md
Sources/Widgets/Representations/WidgetRepresentation/index.js
Sources/Widgets/Widgets3D/LineWidget/example/index.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/api.md
Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/example/controlPanel.html
Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/helpers.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/index.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/state.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/test/testMultipleRotationPlanes.js

Improve the ResliceCursorWidget following the recent breaking change in v26
Allow fine control over visiblity and pickability of the ResliceCursorWidget handles.
- **Browser**: Chrome latest

Fix widgets

---

Sources/Rendering/OpenGL/Actor/index.js
Sources/Rendering/OpenGL/Camera/index.js
Sources/Rendering/OpenGL/ForwardPass/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/ImageSlice/index.js
Sources/Rendering/OpenGL/OrderIndependentTranslucentPass/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/Renderer/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

The old opaqueZBufferPass rendered the depth of translucent actors too
Renamed it zBufferPass and created a new opaqueZBufferPass which only renders the depth of opaque actors
opaqueZBufferPass is used by the OrderIndependantTranslucentPass to occlude fragments hidden by opaque actors
zBufferPass is used when picking or rendering depth for volume occlusion

Rename opaqueZBufferPass to zBufferPass and create a real opaqueZBufferPass

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

Discussion here: https://github.com/Kitware/vtk-js/pull/2680
vtkjs uses a spinY threshold of `> .4 ` to decide if a wheel event is sent from the trackpad. 
Instead we want it to use `>=.3` to detect some common logitech mice
Wheel scroll on logitech mice now allows slice by slice scrolling
a change to a hardcoded value in the conditional logic of RenderWindowInteractor
Test various mice to make sure that scroll still feels responsive. I have tested a logitech mx ergo (the culprit), a logitech g305, a logitech g203, and an apple magic trackpad.
This contribution is funded by [Sirona Medical](https://sironamedical.com/).

fix(renderwindowinteractor): adjust the threshold for spinY values when detecting trackpads

---

Sources/Interaction/Manipulators/MouseRangeManipulator/example/index.js
Sources/Interaction/Manipulators/MouseRangeManipulator/index.js
Sources/Interaction/Manipulators/MouseRangeManipulator/test/testMouseRangeManipulator.js

Fix a bug where the `scrollListener` behaves in an asymmetric manner when comparing increasing value against decreasing value. This specifically occurs when using fractional `scale` values such as `0.5`. Bug is due to the use of `Math.round()` function and its application to the independently calculated `newValue`. Additionally, `Math.round()` also behaves asymmetrically when applied to the value of 0.5, as it always rounds towards `+infinity`.
The correct approach is to calculate the number of accumulated steps from the `newDelta` and round down to the closest lower integer using `Math.floor()`. This new approach also requires that the `listener.step` value be always positive. A required check has been added to the input value. If the caller needs to flip the scroll wheel direction, they …

fix(MouseRangeManipulator): asymmetric scroll wheel behaviour

---

.eslintrc.js
Sources/Testing/index.js
Sources/Testing/setupTestEnv.js
karma.conf.js

Chrome was hanging due to `window.__karma__.complete` not being called.
This had two root causes:
1. Chrome's timer task queue is no longer deprioritized to the end of
DOM loading (due to deprecation of a field test)
2. BufferedObjectPipe doesn't drain the existing buffer when the reader
is set. For some reason, Chrome sets the reader on the buffered pipe
later than Firefox does.
- Chrome should now report completed statuses when running the browser tests.
- Instead of editing `karma.conf.js` to modify the test targets, you now must edit `Sources/Testing/index.js`.
Passing CI likely means this worked.

Fix the issues where Chrome times out when running tests

---

Sources/Interaction/Style/InteractorStyleRemoteMouse/index.js

This modifies the remote mouse events to use `createRemoteEvent()` similarly to the other mouse events. One thing this adds is the `x` and `y` positions of the mouse, which can be used to determine which renderer the mouse is hovering over.
This is needed as a first step for fixing pyvista/pyvista#4020
The next step is to fix the web protocol to use the mouse position to determine which renderer the mouse is over.
I have tested this locally and it appears to work properly.

fix(RemoteMouse): send position in wheel event

---

Sources/Rendering/Misc/SynchronizableRenderWindow/BehaviorManager/CameraSynchronizer.js
Sources/Rendering/Misc/SynchronizableRenderWindow/BehaviorManager/index.js
Sources/Rendering/Misc/SynchronizableRenderWindow/ObjectManager/index.js

View synchronization (Remote view with local rendering) only support state exchange and therefore miss behaviors that are managed by widgets (i.e. orientation widget). 
This PR provide the base infrastructure to add such support.
We added a cameraSynchronizer class that can be use to mimic orientation widget behavior along with the infrastructure to start adding more.

fix(SynchronizableRenderWindow): Add infrastructure for behaviors

---

Sources/Rendering/Core/Renderer/index.d.ts
Sources/Rendering/Core/Renderer/index.js
Sources/Rendering/Core/Viewport/index.js

In trame-vtk, we have a call to [add a light](https://github.com/Kitware/trame-vtk/blob/e2c09edfbfc28ce57959174d72e1eaa6527d4f86/trame_vtk/modules/vtk/serializers/render_windows.py#L48-L50).
Sometimes, this would be triggered multiple times, like if the user toggled
local view on/off.
It doesn't really make sense to add the same light twice (you can just modify
the intensity instead). So, similar to [the view prop check](https://github.com/Kitware/vtk-js/blob/24d26e040e3454f61b882ab7d95982d084f03a9d/Sources/Rendering/Core/Viewport/index.js#L19-L25),
add a check to prevent the same light from being added twice.

fix(lights): do not add duplicate lights

---

Sources/Rendering/Misc/SynchronizableRenderWindow/BehaviorManager/index.js
Sources/Rendering/Misc/SynchronizableRenderWindow/ObjectManager/index.js
Sources/Rendering/Misc/SynchronizableRenderWindow/index.js

Now remote VTK renderer can be synchronized with vtk.js to show vtkOrientationMarkerWidget. 
This is mainly for __trame__ with examples like https://github.com/Kitware/trame-vtk/pull/34/files#diff-f3098b8f9ebd4e483da691b3f1272b8300903ba316978ee1c04c680cfc8ec2e6

fix(SynchronizableRenderWindow): Handle vtkOrientationMarkerWidget

---

Sources/Rendering/OpenGL/Texture/index.js

Computing scale offsets in vtkOpenGLTexture can be slow for 3d textures.
Using the fastComputeRange utility from vtkDataArray makes it faster.
Usually yields a +50% speedup.
See https://github.com/Julesdevops/texture-test/blob/master/src/index.ts
- **vtk.js**: 26.9.12
- **OS**: linux
- **Browser**: Firefox 111

perf(vtkOpenGLTexture): use fastComputeRange in computeScaleOffsets

---

Sources/Interaction/Widgets/OrientationMarkerWidget/index.js
Sources/Testing/testMacro.js
Sources/Widgets/Representations/WidgetRepresentation/index.js
Sources/Widgets/Widgets3D/AngleWidget/index.js
Sources/macros.js

By adding a function _onPropChanged into the model, the function will be called each time prop is changed but before modified() is called.
Sometimes it is useful to call extra code whenever a prop changes.
Each time an XXX prop is modified via the `macro.set`, `macro.setGet` or `macro.setArray` and if `model` contains `_onXXXChanged`, then it will be called automatically after changing the value but before `modified` is called.
Closes #2765 
- **Browser**: Chrome latest

refactor(macros): add support for _onPropChanged callback

---

Sources/Rendering/OpenGL/ImageResliceMapper/index.js
Sources/Rendering/OpenGL/Texture/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

computeScaleOffsets used to iterate over all pixels of the volume to find min and max
Using a vtkDataArray instead of raw data enables caching of min/max values per component
create3DFilterableFromRaw uses create3DFilterableFromDataArray and create a wrapper array around the raw data
create3DFilterableFromRaw is not used anymore (deprecate ?)

perf(Texture): cache scale/offset using dataArray

---

Sources/Rendering/Core/VolumeMapper/example/controller.html
Sources/Rendering/Core/VolumeMapper/example/index.js
Sources/Rendering/Core/VolumeMapper/index.d.ts
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

- **vtk.js**: 
- **OS**: 
- **Browser**:

Volume local ambient occlusion combined with gradient shading

---

.github/workflows/pr-checks.yml

Well, turns out I do need to mask commitlint on merge_group events. Unsure if merge_group contains a sha to work off of, but PR checks should run just fine for gating PRs prior to merging.

chore(github): no commitlint on merge queue

---

Sources/IO/Misc/OBJReader/index.js

It's possible for OBJReader to become deleted while fetchData is loading.
- loadData resolves to false instead of throwing an error about being deleted
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(OBJReader): race condition on loadData

---

Sources/Interaction/Manipulators/MouseCameraAxisRotateManipulator/index.js

- Camera's viewUp param is updated incorrectly
- sticky at the axes
- Avoids stickiness at the axes.
- camera viewUp is correct
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(MouseCameraAxisRotateManipulator): no sticky

---

Sources/Rendering/OpenGL/Texture/index.js

For large array inputs, there is a measurable difference in total execution time of the containing loop (observed initially on Chrome).
- Faster half float loop
Timing results on Chrome provided below. The relevant timing lines are described.
* "toHalf module local fn fewer lookups": this PR
* "toHalf module": original behavior
Timing on Firefox:

perf(OpenGL/Texture): reduce lookups in hot loop

---

Sources/Widgets/Core/WidgetManager/index.d.ts
Sources/Widgets/Core/WidgetManager/index.js

Adds `widgetManager.getActiveWidget()`, which allows users to query the currently active widget, if any. This is most useful if you want to perform operations that depend on whether a widget is currently selected.
`widgetManager.getActiveWidget()` returns the currently active widget, or null.
No testing is needed. This further develops and exposes an already-used property.

feat(WidgetManager): add getActiveWidget()

---

Sources/Rendering/Core/ImageMapper/index.js

According to the implementation of the multiply3x3_vect3 function, mat_3x3 should be a one-dimensional array
```javascript
export function multiply3x3_vect3(mat_3x3, in_3, out_3) {
const x = mat_3x3[0] * in_3[0] + mat_3x3[1] * in_3[1] + mat_3x3[2] * in_3[2];
const y = mat_3x3[3] * in_3[0] + mat_3x3[4] * in_3[1] + mat_3x3[5] * in_3[2];
const z = mat_3x3[6] * in_3[0] + mat_3x3[7] * in_3[1] + mat_3x3[8] * in_3[2];
out_3[0] = x;
out_3[1] = y;
out_3[2] = z;
}
```
i am not saying  it is not my image "direction", i mean multiplying an array by a number may be a NaN or 0

fix: directly assign the value from getDirection to mat3

---

Sources/Common/Transform/LandmarkTransform/index.js

fix #2632
Crash within LandmarkTransform
No more crash
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(landmarktransform): fix ds and dt crash

---

Sources/Common/DataModel/BoundingBox/index.js
Sources/Proxy/Core/View2DProxy/index.js
Sources/Rendering/Core/ImageArrayMapper/index.d.ts
Sources/Rendering/Core/ImageMapper/index.d.ts
Sources/Rendering/Core/ImageSlice/index.d.ts
Sources/Rendering/Core/ImageSlice/index.js

Documentation was wrongly making mandatory the first parameter of the getBoundsForSlice() function.
Documentation now correctly informs that the first parameter of the getBoudnsForSlice() function is optional
Update documentation and cleanup code
- [] Tested environment:
- **vtk.js**: 
- **OS**: 
- **Browser**:

2758 fix get bounds for slice doc

---

Sources/Common/DataModel/DataSetAttributes/FieldData.js
Sources/Common/DataModel/DataSetAttributes/test/testDataSetAttributes.js

Arrays are stored in a 'data' sub object
fix #2813
Crash when `removeArray` was called.
No more crash
Crash was due to a regression.
- **Browser**: Chrome 112

fix(fielddata): fix removeArray

---

Sources/Rendering/Misc/SynchronizableRenderWindow/ObjectManager/index.js

Prevent overriding of two distinct arrays that have same exact data and thus hash but have different meaning as defined by their name.
fix #2815
Described in the Issue #2815
Our application was crashing on not finding one of the arrays, with this fix it's working again.
The code was internal to the module so no TS or documentation changes were necessary.
- **vtk.js**:  latest master
- **OS**: OSX 12.6.5 
- **Browser**: Chrome 112.0.5615.137 (Official Build) (arm64)  
Ping @psavery for the latest change that caused the issue.

fix(synchronizablerenderwindow/objectmanager): fix ObjectManager array processing

---

Sources/Filters/General/ContourTriangulator/example/index.js
Sources/Filters/General/ContourTriangulator/index.d.ts
Sources/Filters/General/ContourTriangulator/index.js
Sources/Rendering/Core/Renderer/index.d.ts
Sources/Rendering/Misc/FullScreenRenderWindow/index.d.ts
Sources/Rendering/Misc/GenericRenderWindow/index.d.ts

vtkContourTriangulator was broken, filter output polydata had no lines/polys.
vtkContourTriangulator example now show a triangulated contour.
Input normal was empty and not computed. This fix makes sure the normal is computed.
- **Browser**: Latest Chrome

2775 fix contour triangulator

---

Sources/Widgets/Widgets3D/index.js

LabelWidget and SphereWidget are missing from UMD module.
The widgets are now available in UMD module
- **Browser**: Chrome 113

feat(labelwidget): expose vtkLabelWidget and vtkSphereWidget to UMD module

---

Sources/Proxy/Core/View2DProxy/example/index.js

Fix console errors, and setSize function that
causes blank page.
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(View2DProxy): broken View2DProxy example

---

Sources/Common/Core/LookupTable/index.js
Sources/Rendering/Misc/SynchronizableRenderWindow/ObjectManager/index.js

- Allow regular vtkLookupTable to be used for local rendering with custom color Table.
- Not supported before and needed to use the ColorTransferFunction class by converting the server data
Tested with PyVista [Color subset](https://github.com/Kitware/trame-vtk/blob/master/examples/validation/PyVistaLookupTable.py) + Preset selector in same dir (not yet there)

fix(LookupTable): Allow JS 2D arrays to setTable

---

Sources/Rendering/Misc/SynchronizableRenderWindow/BehaviorManager/index.js

Allow widget behavior for local view to work with decorated RenderWindow rather than only supporting only SynchronizableRenderWindow class instance.

Support widget behavior on decorated rw

---

Sources/Common/Core/StringArray/index.js
Sources/IO/XML/XMLReader/index.js

XMLReader doesn't process field data and doesn't support reading in string arrays.
XMLReader now supports field data and handling of string arrays.
- Fix zlib data parsing by finding the first zlib magic byte.
- Refactor out common logic between processDataArray and
processStringArray.
- **vtk.js**: 
- **OS**: 
- **Browser**:

feat(XMLReader): read in string arrays

---

Sources/Rendering/Core/Mapper/index.js

When creating VBOs, the call to modified() induced by the setter caused a performance hit
The mtime of the mapper doesn't need to be modified when calling this setter
`selectionWebGLIdsToVTKIds` is only used when processing a selection made with the hardware selector and the mtime of the mapper doesn't change this behavior

Remove call to modified() in setSelectionWebGLIdsToVTKIds()

---

Documentation/content/docs/develop_webxr.md
Examples/Applications/GeometryViewer/index.js
Examples/Volume/WebXRVolume/index.js

Updates the default XR session type preference in WebXRVolume and GeometryViewer examples to better reflect our current XR supported devices list. 
re #2862
Previously single-screen mobile devices were the only devices supporting both VR (Cardboard) and AR sessions with AR generally favored, so AR mode was made the default. Recently vtk.js added support for HMDs compatible with both VR and AR (passthrough) mode, which require stereoscopic AR rendering different from the mobile AR approach. 
Under the status quo the default behavior on such an HMD was to attempt to render in AR mobile as if it were a mobile device, which would produce incorrect renderings. This change prefers rendering in VR mode such that default HMD behavior will be rendering in full virtual reality and some mobile …

docs(webxr): prefer VR over AR session in XR documentation

---

Sources/Common/Core/DataArray/index.js

Calling `getRange()` and then `getRange(0)` on scalar data computes the range twice, when it should be computed once.
- Avoids recomputing the range of scalar data
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(DataArray): scalar data implies index 0

---

Sources/Rendering/OpenGL/ImageMapper/index.js

TypedArray.subarray is slower than just looping through values and copying them.
- ImageMapper.buildBufferObjects is faster for large arrays.
- **vtk.js**: 
- **OS**: 
- **Browser**:

perf(ImageMapper): do not use subarray

---

Sources/Rendering/OpenGL/RenderWindow/index.d.ts
Sources/Rendering/OpenGL/RenderWindow/index.js

Removes `vtkOpenGLRenderWindow.HaveVRDisplay` event. This event is unused internally and was previously left over from WebVR to WebXR integration to avoid API breakage.
Under previous behavior the `navigator.xr` check was called eagerly at construction, which could result in an unhandled exception. This change removes that eager check so that `navigator.xr` is referenced only if an XR-related method such as `startXR` is called.
Applications should query `navigator.xr` directly to determine whether a given session type may be supported.
Resolves https://github.com/Kitware/vtk-js/issues/2537
Also removes outdated WebVR-related TypeScript definitions from `vtkOpenGLRenderWindow`. Affected method implementations were previously removed in transition from WebVR to WebXR.
`navigator.xr` is only …

fix(vtkOpenGLRenderWindow): Remove unused `HaveVRDisplay` event and outdated TypeScript definitions

---

Sources/Rendering/Core/VolumeMapper/index.d.ts

`getInitialInteractionScale` and `getInteractionSampleDistanceFactor` default values were wrong

VolumeMapper fix default values in the docs

---

Sources/Rendering/Core/ColorTransferFunction/index.js

Fixes #2881 
- getNanColor returns an array and accepts no parameters.
- getNodeValue sets nodeVal to an array, not object.
- Correct usage of getNanColor and getNodeValue

fix(ColorTransferFunction): misuse of return value

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

Certain versions of Safari on iOS do not implement document.exitPointerLock.
Closes #2668
- document.exitPointerLock doesn't error out on iOS safari.
I don't have a device to test this on, so it's not tested.

fix(RenderWindowInteractor): guard against undefined exitPointerLock

---

Sources/Rendering/Core/AbstractImageMapper/index.d.ts
Sources/Rendering/Core/AbstractImageMapper/index.js
Sources/Rendering/Core/AbstractMapper3D/index.js
Sources/Rendering/Core/ImageArrayMapper/index.d.ts
Sources/Rendering/Core/ImageMapper/index.d.ts
Sources/Rendering/Core/ImageSlice/index.d.ts

Addresses issue: https://github.com/Kitware/vtk-js/issues/2878
Fix typescript definition error when using `vtkImageResliceMapper` with `vtkImageSlice`. Change `vtkImageSlice` to accept `vtkAbstractImageMapper` when calling `setMapper`.
Fixes errors such as:
```
Argument of type 'vtkImageResliceMapper' is not assignable to parameter of type
'vtkImageMapper'. Type 'vtkImageResliceMapper' is missing the following
properties from type 'vtkImageMapper': getSliceAtPosition, getClosestIJKAxis,
getBoundsForSlice, getRenderToRectangle, and 15 more.
```
- **vtk.js**:  latest master
- **OS**:  Windows 11 Pro
- **Browser**:  MS Edge Version 115.0.1901.203 (Official build) (64-bit)

Fix vtkImageSlice typescript definitions

---

Sources/Widgets/Representations/PolyLineRepresentation/index.js

Inserting this code into PolyLineWidget/example
```
const widget = vtkPolyLineWidget.newInstance();
widget.placeWidget(cone.getOutputData().getBounds());
const widgetInstance = widgetManager.addWidget(widget);
widgetInstance.setClosePolyLine(true);
```
Broke line rendering
Fixed
Last CellData element was incorrect for closePolyLine true case.

fix(PolyLineRepresentation): when closePolyLine is true

---

Sources/Proxy/Representations/ResliceRepresentationProxy/example/index.js
Sources/Proxy/Representations/ResliceRepresentationProxy/index.d.ts
Sources/Proxy/Representations/ResliceRepresentationProxy/index.js

Some applications may want to highlight a the slicing polygon geometry with a colored outline (specially to identify a slice across multiple views). Upgrade the representation proxy to allow for optional rendering of such an outline. Default visibility is off. Exposed properties include `outlineColor`, `outlineVisibility`, and `outlineLineWidth`.
These changes are added during the following VolView development:
https://github.com/Kitware/VolView/pull/359
- **vtk.js**:  master
- **OS**:  Windows 11, Pro
- **Browser**:  Chrome Version 116.0.5845.141 (Official Build) (64-bit)

feat(ResliceRepresentationProxy): add outline to slice geometry

---

Sources/Filters/General/ImageMarchingSquares/api.md
Sources/Filters/General/ImageMarchingSquares/example/controller.html
Sources/Filters/General/ImageMarchingSquares/example/index.js
Sources/Filters/General/ImageMarchingSquares/index.js

The vtkImageMarchingSquares filter currently only supports K slicing. 
I and J slicing has been discussed before, but has not been implemented yet:
[Apply Marching Squares to ImageSlices](https://discourse.vtk.org/t/apply-marching-squares-to-imageslices/4279)
These changes enable using I and J slicing modes so it is now possible to run the vtkImageMarchingSquares filter in all IJK directions.
The vtkImageMarchingSquares class has been changed to dynamically select IJK/XYZ indices based on the provided `slicingMode`. This enables slicing in all IJK directions.
Added new method:
`(set/get)SlicingMode` - Set/Get the slicing mode (IJK) which determines the direction to slice. By
default the slicingMode = 2.
Documentation of the vtkImageMarchingSquares class has been updated to include this …

Add I and J slicing to vtkImageMarchingSquares filter

---

Sources/Proxy/Representations/GeometryRepresentationProxy/index.d.ts
Sources/Proxy/Representations/GeometryRepresentationProxy/index.js

Required for VolView development: https://github.com/Kitware/VolView/pull/359
- **vtk.js**:  latest master
- **OS**:  Windows 11, Pro
- **Browser**:  Chrome Version 116.0.5845.140 (Official Build) (64-bit)

Add typescript definitions and expose lineWidth in vtkGeometryRepresentationProxy

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

Allow user to override position computation so it can be used outside of a RenderWindow.

fix(RenderWindowInteractor): Allow usage without RenderWindow

---

Sources/Common/Core/Math/index.d.ts
Sources/Common/Core/Math/index.js
Sources/Common/Core/Math/test/testMath.js
Sources/Rendering/Core/ImageMapper/index.js

Two mappers with two different slicing modes could have the same ijkMode
For example, two mappers with X and Y slicing mode could both show slice J
Also remove the warning about inaccurate slicing because oblique slicing should be done with the new ImageResliceMapper and the slicing modes XYZ are intentionally used to snap to IJK
Add a function to vtkMath (with tests and docs)

Fix logic of computeClosestIJKAxis

---

Documentation/content/docs/intro_vtk_as_es6_dependency.md
package-lock.json
package.json
webpack.common.js

Updates the browserslist db and bumps babel to output ES6 code for `@kitware/vtk.js`. The `vtk.js` package remains the same.
ESM build now outputs to ES6 according to the browserslist db. We use the default browserslist browsers.
No testing has been done.

Update the ESM build with newer browserslist db + babel

---

Sources/Common/Core/DataArray/index.js
Sources/Common/Core/DataArray/test/testDataArray.js

Fix #2920: the range of data arrays with NaN as first value was wrongly computed (always returned NaN). Fixed by properly initializing the min/max values in the `fastComputeRange` function.
Changes are captured by the newly added tests.
- **vtk.js**: 28.11.0
- **OS**:  Windows
- **Browser**: Edge

fix(DataArray): fix range for data arrays with NaN values

---

Sources/Common/Core/DataArray/index.d.ts
Sources/Common/Core/DataArray/index.js
Sources/Common/Core/DataArray/test/testDataArray.js
Sources/Common/Core/Points/index.d.ts
Sources/Common/Core/Points/index.js
Sources/Filters/Core/Cutter/example/controlPanel.html
Sources/Filters/Core/Cutter/example/index.js
Sources/Filters/Core/Cutter/index.js
Sources/Filters/Core/Cutter/test/testCutter.js

Avoid using subarray that is costly
https://discourse.vtk.org/t/cutter-performance/12282/5
Went from roughly 30ms to 20ms on DragonFly.
- **vtk.js**: master -->
- **Browser**: Latest Chrome

perf(vtkcutter): improve vtkCutter performances

---

Sources/Filters/Core/PolyDataNormals/example/controlPanel.html
Sources/Filters/Core/PolyDataNormals/example/index.js
Sources/Filters/Core/PolyDataNormals/index.js
Sources/Filters/Core/PolyDataNormals/test/testPolyDataNormals.js
Sources/Rendering/Core/Glyph3DMapper/index.d.ts
Sources/Rendering/Core/Glyph3DMapper/index.js

fix #2434 
Add `setComputePointNormals` and `setComputeCellNormals`

2434 vtk poly data normals add compute cell normals

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

I was trying to consume @kitware/vtk.js inside a webworker which I encountered an error regarding MouseEvent not being available (since it is worker context). This PR will check if the MouseEvent is available then use it
Added conditional check for mouseEvent
replaces 
```js
EMPTY_MOUSE_EVENT = new MouseEvent('');
``` 
with
```js
let EMPTY_MOUSE_EVENT;
if (typeof MouseEvent !== 'undefined') {
EMPTY_MOUSE_EVENT = new MouseEvent('');
} else {
// Provide a fallback or handle differently for web worker context
EMPTY_MOUSE_EVENT = {
ctrlKey: false,
altKey: false,
shiftKey: false,
};
}
```
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(interactor): mouseEvent is not available in the worker

---

Sources/Widgets/Representations/GlyphRepresentation/index.js
Sources/Widgets/Representations/LineHandleRepresentation/index.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/index.js

Remove lighting
Spin cyclinder representations to avoid cropping of the cylinder by the imageReslice

Change style of reslice cursor widget back to as it was in v25

---

Sources/Proxy/Representations/GeometryRepresentationProxy/index.d.ts

Fix setOpacity() and getOpacity() param and return types.
Also fixed some indentation and ordering of function declarations.
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(GeometryRepresentationProxy): setOpacity typedef param type

---

Sources/Filters/General/Calculator/index.js
Sources/Filters/General/Calculator/test/testCalculator.js

fix #2257
we can now use `vtkCalculator` with a `vtkImageData`
Do not pass point coordinates to formula function in case of `vtkImageData` input since it relies on the `getPoints` function which does not exist on `vtkImageData`.
Also avoid to call `getPoints` to get number of points, directly use `getNumberOfPoints` on the input dataset.
- **OS**: linux
- **Browser**: firefox 118.0.1, chrome Version 117.0.5938.132 (Official Build) (64-bit)

Fix calculator for image data

---

Sources/Testing/testSerialization.js
Sources/macros.js

The behavior of JSON.stringify for typed arrays is to serialize them as objects with numeric keys. This cause crashes when re-building the object since it would try to fit an object where a typed array is required. This changes makes it so getState replaces typed arrays with plain javascript arrays.
Typical example is `vtkImageData` direction property, which is by default Float64Array
minimal reproduction:
```javascript
import vtk from '@kitware/vtk.js/vtk';
import vtkImageData from '../../Sources/Common/DataModel/ImageData';
const imdt = vtkImageData.newInstance();
const jsonRepr = JSON.stringify(imdt);
const jsonDeserialize = JSON.parse(jsonRepr);
const vtkObj = vtk(jsonDeserialize); // this should crash
```
see also https://github.com/Kitware/glance/issues/480
makes …

Fix typed arrays serialization deserialization

---

Sources/Imaging/Core/ImageReslice/index.js

Direction of input image was not correctly supported by the ImageReslice
Direction of output image was not supported at all
Use `getWorldToIndex` and `getIndexToWorld` instead of trying to compute the matrix by hand
Fix the directions and refactor the code to make it clearer (remove `optimizedTransform`, initialize `indexMatrix`)

Fix ImageReslice direction matrix and quick refactor

---

Examples/Rendering/Actor2D/index.js
Examples/Rendering/QuadView/index.js
Sources/Interaction/UI/FPSMonitor/index.js
Sources/Rendering/Core/ImageProperty/index.js
Sources/Rendering/Core/Mapper2D/index.js
Sources/Rendering/Core/RenderWindow/index.js
Sources/Rendering/Core/VolumeProperty/index.js
Sources/Rendering/OpenGL/BufferObject/index.js
Sources/Rendering/OpenGL/Helper/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/ImageResliceMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper2D/index.js
Sources/Rendering/OpenGL/RenderWindow/index.d.ts
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/Renderer/index.js
Sources/Rendering/OpenGL/ShaderCache/api.md
Sources/Rendering/OpenGL/ShaderCache/index.js
Sources/Rendering/OpenGL/ShaderProgram/index.js
Sources/Rendering/OpenGL/Texture/index.js
Sources/Rendering/OpenGL/TextureUnitManager/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

Add ability to cache graphics resources at the context level and have mappers re-use them if they are looking at the same data in the same render window. 
This ability opens up graphics resource sharing across viewports in applications where the same dataset is being rendered by different mappers. An example of this is provided with a QuadView that has three image reslice views and a volume view, all looking at the same 3D vtkImageData. Without this change, each mapper would be uploading the whole dataset to the GPU. 
- **vtk.js**: 
- **OS**: 
- **Browser**:

Shareable graphics resources

---

Sources/Rendering/OpenGL/ImageMapper/index.js

Using immutable textures caused warning when calling create2DFromRaw on the textures.
The warnings are visible in the [reslice cusor example](https://kitware.github.io/vtk-js/examples/ResliceCursorWidget/index.html).

Make textures in ImageMapper resizable

---

Sources/Rendering/OpenGL/VolumeMapper/index.js

This PR aims to fix the problem occuring when both options z-Buffer and Image Outline are configured. As this two options declare the same variable names when activated, it gives error in shader compilation
- **vtk.js**:  27.3.1
- Browser:  Chrome 117.0.5938.152

refactor(mapper): multiple configuration

---

BREAKING_CHANGES.md
Examples/Applications/SkyboxViewer/index.js
Sources/IO/Core/ImageStream/example/index.md
Sources/Proxy/Core/ProxyManager/example/index.js
Sources/Proxy/Core/View2DProxy/example/index.js
Sources/Proxy/Core/ViewProxy/index.d.ts
Sources/Proxy/Representations/ResliceRepresentationProxy/example/index.js
Sources/Rendering/Core/RenderWindow/index.d.ts
Sources/Rendering/Misc/FullScreenRenderWindow/index.d.ts
Sources/Rendering/Misc/FullScreenRenderWindow/index.js
Sources/Rendering/Misc/GenericRenderWindow/index.d.ts
Sources/Rendering/Misc/GenericRenderWindow/index.js
Sources/Rendering/Misc/GenericRenderWindow/test/testGenericRenderWindowCreateDelete.js
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/WebGPU/RenderWindow/index.js
Sources/Widgets/Core/WidgetManager/index.js
Sources/Widgets/Core/WidgetManager/test/testWidgetManager.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js

Running the LineWidget example with WebGPU backend generated an error because WidgetManager requires onWindowResizeEvent public function.
Moreover in many places `getOpenGLRenderWindow()` was still called (even in a WebGPU context)
Expose onWindowResizeEvent and trigger it when the size of the window is modified.
Rename `getOpenGLRenderWindow()` into `getApiSpecificRenderWindow()`
- **Browser**: Chrome Canary

fix(webgpu): Fix support of WebGPU render backend

---

Examples/Applications/OfflineLocalView/index.js

- **vtk.js**: 
- **OS**: 
- **Browser**:

docs(OfflineLocalView): defer data loading when not visible

---

Sources/Rendering/OpenGL/Volume/index.js

The method `getKeyMatrices` computed inverse instead of inverse+transpose
Close #2922 
Close #2949

fix(volume): Fix key normal matrix for volume

---

Examples/Geometry/ItkWasmGeometry/index.js
Sources/Common/Core/DataArray/index.js
Sources/Common/DataModel/ITKHelper/index.js

Fix ITKHelper.  
Improve ItkWasmGeometry example.  
Improve vtkDataArray constructor  
Rendering of ItkWasmGeometry example is now correct.  
fix https://github.com/Kitware/vtk-js/issues/2853
- **vtk.js**: 
- **OS**: 
- **Browser**:

Fix itkwasmgeometry example

---

Examples/Volume/VolumeOutline/index.js
Sources/Rendering/Core/VolumeProperty/index.d.ts
Sources/Rendering/Core/VolumeProperty/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

This pull request will introduce a method to specify individual segment outline thicknesses for the label map outline.
It will look like this with different outline thickness for each segment.
The signature of the `setLabelOutlineThickness` has been changed to support both a single number (old API) and a new way of handling it (via an array).
```js
setLabelOutlineThickness(2) => will set 2px for all segments
setLabelOutlineThickness([2]) => will set 2px for all segments
setLabelOutlineThickness([1,3]) => will set 1px for segment index 1  and 3 px for segment index 2 
```
- **vtk.js**: Latest
- **OS**: MacOS 13.5.2 (22G91)
- **Browser**:  Chrome Version 119.0.6045.159 (Official Build) (arm64)

feat(labelOutline): add per segment label outline thickness

---

Sources/Filters/General/TubeFilter/index.js
Sources/Filters/General/TubeFilter/test/testTubeFilter.js

Output cell/point arrays were being dropped when they shouldn't be. Every update invocation creates a new polydata array, so there are no old arrays to be dropped.
Related: https://discourse.vtk.org/t/tubefilter-broken-for-celldata/12863
Cell and point data arrays should be properly copied to the output polydata.
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(TubeFilter): do not drop output arrays

---

Sources/Rendering/Core/Follower/index.js

When parallelProjection is true, vtkFollower cannot correct show actor, actor will disappear.
[Reproduce demo.](https://stackblitz.com/edit/dyqwbp-jtgvof?file=src%2Fcellpicker-volume-surface.vue)
The code mistakes `vec3.set` param, so change the array param to spread operation one.
[glMatrix vec3.set](https://glmatrix.net/docs/module-vec3.html) 
- Rectify execution function  param for vec3.set in vtkFollower.
[ ] This change adds or fixes unit tests 
[&#10004;] Tested environment:
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(vtkFollower): fix vtkFollower set vpn param bug when  camera.getParallelProjection() is true

---

Sources/Imaging/Core/AbstractImageInterpolator/Constants.d.ts
Sources/Imaging/Core/ImageReslice/Constants.d.ts
Sources/Imaging/Core/ImageReslice/index.d.ts
Sources/Imaging/Core/ImageReslice/index.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/Constants.d.ts

Main addition: ImageReslice typescript header

Add typescript definitions

---

Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.js
Sources/Widgets/Widgets3D/ResliceCursorWidget/example/index.md
Sources/Widgets/Widgets3D/ResliceCursorWidget/index.d.ts
Sources/Widgets/Widgets3D/ResliceCursorWidget/index.js

This is useful to control the center using sliders.
It is not obvious how to control the reslice cursor widget with sliders.
This PR demonstrates how to control the reslice cursor widget with sliders and expose a convient function.

feat(reslicecursor): expose a convenient getPlaneExtremities function

---

Sources/Rendering/Core/Picker/index.d.ts

- **vtk.js**: 
- **OS**: 
- **Browser**:

docs(vtkpicker): update doc and typing

---

Sources/Rendering/Core/Picker/index.d.ts

Bring back methods from vtkPicker that were wrongly removed in 1411330c8d3e8abde8fb8c93311407dd Also removes FIXME for invokePickChange and onPickChange after checking and updating their actual signature.
- **vtk.js**: 
- **OS**: 
- **Browser**:

docs(vtkpicker): fix and improve typing

---

Sources/Widgets/Widgets3D/PaintWidget/behavior.js

Events were being aborted even when the manipulator returns no world coordinates.
The paint widget does not abort events during non-intersecting actions.

fix(PaintWidget): blocked event w/o intersection

---

.github/workflows/pr-checks.yml
Sources/Widgets/Widgets3D/ResliceCursorWidget/index.d.ts

The release is being blocked by API doc generation. This should be caught during PR checks, and not during release.
API doc generation does not block a release.
This will be considered tested once release is unblocked.

Ensure that API docs can be generated

---

Sources/Rendering/Core/RenderWindowInteractor/index.d.ts
Sources/Rendering/Core/RenderWindowInteractor/index.js

When rebinding events with a different container, make sure all timeouts and state variables from previous container are cleared.
This PR is part of a react-vtk-js fix for out-of-focus wheel events (https://github.com/Kitware/react-vtk-js/pull/125)
- **vtk.js**: latest master 
- **OS**: Windows 11, macOS Sonoma 
- **Browser**: Chrome 120

fix(handleWheel): mouse scrolling behavior for out-of-focus windows

---

Sources/Widgets/Widgets3D/PaintWidget/behavior.js

Using the paint widget with a manipulator that can return null.
Paint widget no longer errors when worldCoords is null.

fix(PaintWidget): worldCoords can be null

---

Sources/Widgets/Manipulators/PickerManipulator/index.js
Sources/Widgets/Widgets3D/PaintWidget/behavior.js
Sources/Widgets/Widgets3D/SeedWidget/behavior.js

While using a PaintWidget on a 3D object with a PickerManipulator, the user cannot rotate the object while painting is active.
https://github.com/Kitware/vtk-js/assets/44912689/638e8c3f-1e30-4c25-9a83-9d99bb29722a
Behavior was tested using the following code (for both before and after videos):
[index.txt](https://github.com/Kitware/vtk-js/files/14085010/index.txt)
(This was converted from `.js` to `.txt` for GH upload)
A user can rotate an object while using an active PaintWidget. Drag motions that start with the mouse over the object result in a paint event. Drag motions that start with the mouse not over the object result in a default interaction event. 
https://github.com/Kitware/vtk-js/assets/44912689/3c724351-6eaf-4040-8c77-7b60bd379212
- **vtk.js**: 29.4.5
- **OS**: Ubuntu 20.04.6 …

Fix Paint Widget Rotation Interaction

---

Sources/Rendering/Core/RenderWindow/index.js
Sources/Rendering/WebGPU/CellArrayMapper/index.js
Sources/Rendering/WebGPU/ForwardPass/index.js
Sources/Rendering/WebGPU/Renderer/index.js

WebGPU rendering pipeline was not behaving correctly:
-  With firefox nightly (and chrome canary), several WGSL shaders  were not compiling due to type errors.
-  RenderWindow.getStatistics() was calling undefined functions when manipulation WebGPU specialized classes like vtkWebGPURenderWindow or vtkWebGPUPolyDataMapper #2942.
Now the PBR example run when choosing the webGPU Api.  
- Fix various type errors inside WGSL shaders (most of the time, missing floating point for floats)
- Added guards inside RenderWindow.getStatistics() to prevent the call of undefined methods for webGPU specifics objects 
- **vtk.js**: 29.4.1
- **OS**: Linux
- **Browser**: Firefox nightly 123.0a1

Several fixes for WebGPU

---

Sources/Common/Core/DataArray/index.d.ts
Sources/Widgets/Core/AbstractWidgetFactory/index.d.ts
Sources/Widgets/Core/WidgetManager/index.d.ts
Sources/Widgets/Widgets3D/InteractiveOrientationWidget/index.d.ts
Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.d.ts
Sources/Widgets/Widgets3D/ResliceCursorWidget/index.d.ts

Use Symbols in the type of extend function as typescript can't differentiate two `extend` functions.

Add typescript specific to widget behavior

---

Sources/Common/Core/Math/index.d.ts
Sources/Common/Core/Math/index.js
Sources/Filters/General/ScalarToRGBA/index.js
Sources/Rendering/Core/AxesActor/index.js
Sources/Rendering/Core/ColorTransferFunction/CssFilters.d.ts
Sources/Rendering/Core/ColorTransferFunction/CssFilters.js
Sources/Rendering/Core/ColorTransferFunction/test/testCssFilters.js
Sources/Rendering/OpenGL/ImageCPRMapper/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/ImageResliceMapper/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/WebGPU/ImageMapper/index.js
Sources/Rendering/WebGPU/SphereMapper/index.js
Sources/Rendering/WebGPU/StickMapper/index.js
Sources/Rendering/WebGPU/VolumePassFSQ/index.js

Create utility functions to manipulate equivalent of filters in vtk.js.
Based on the W3C specification.

Add a CSS helper for CSS filters

---

Sources/Filters/General/ContourLoopExtraction/example/controlPanel.html
Sources/Filters/General/ContourLoopExtraction/example/index.js
Sources/Filters/General/ContourLoopExtraction/index.d.ts
Sources/Filters/General/ContourLoopExtraction/index.js

- Thanks to @floryst for providing me the `contourLoopExtraction` code, I am just providing an example, as well as typing and submitting a pull request.
This PR introduces the `vtkContourLoopExtraction` filter, which is designed to extract closed loop contours from the output of the vtkPolyData. 
Unlike tools like `vtkCutter`, which lack sufficient clustering information about the cuts, `vtkContourLoopExtraction` efficiently traverses the points to identify loops.
I've included an example that demonstrates this amazing feature. In this particular example, we obtain the output of the `vtkCutter` and then pass it to the `vtkContourLoopExtraction`. Finally, we generate separate polyData for each individual contour, with each contour having its own unique color. …

feat(filter): Add contour loop extraction filter

---

Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

The labelmap outline in the volume/image mapper used the condition `tColor.a > 0.01` to improve performance by skipping the background. However, this meant that we couldn't render the outline when the fill is 0 (or a small number).You can see [the bug here in this code sand box](https://codesandbox.io/p/sandbox/volume-outline-bug-when-not-filled-sdgpxm?file=%2Fsrc%2Findex.js%3A100%2C1-101%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252 …

fix(imageOutline): fix the bug where outline was not showing without filling

---

Sources/Rendering/Core/Renderer/index.d.ts

Reported on the forum https://discourse.vtk.org/t/vtkrenderer-setpreservecolorbuffer-typo-in-either-the-d-ts-or-the-js-same-with-setpreservedepthbuffer/13303
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(types): improve vtkrenderer type definitions

---

Sources/IO/Core/HttpDataSetReader/index.js
Sources/IO/Core/HttpDataSetReader/test/MockDataAccessHelper.js
Sources/IO/Core/HttpDataSetReader/test/testHttpDataSetReader.js

The introduction of a cache limit in ``vtkHttpDataSetReader`` introduced a bug where if the cache is disabled and concurrent calls requested the same URL, an uncaught error would be raised.
Error raised due to this issue:
```
VM15652 index.js:4384 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'lastAccess')
```
This PR fixes this small issue and adds regression tests to account for this scenario.
The only change required is to check if caching is enabled before updating the cache access timestamps on cache entries.
from ``Sources/IO/Core/HttpDataSetReader/index.js``
```javascript
//  Update last access for cache retention rules (if caching is enabled)
if (model.maxCacheSize) {
cachedArraysMetaData[arrayId].lastAccess = new Date();
}
```
To test the fix, the …

fix: Errors on concurrent access with disabled cache

---

Sources/Rendering/OpenGL/Framebuffer/index.js
Sources/Rendering/OpenGL/HardwareSelector/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/SurfaceLIC/LineIntegralConvolution2D/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

If the OpenGL render window has [0,0] size, it's possible for the associated framebuffer to not be correctly initialized ([see these lines](https://github.com/Kitware/vtk-js/blob/b9988635d1beed28a1b13f7c5e1ac8b668b77e6c/Sources/Rendering/OpenGL/ForwardPass/index.js#L60-L68)). The resulting error is opaque (errors in `renderPieceStart`) and is not indicative of the root cause.
If the framebuffer is not yet initialized, return null as the size. This matches some existing usages of `framebuffer.getSize()` that checks for null-ness.

fix(OpenGL/Framebuffer): size can be null

---

Sources/Rendering/OpenGL/OrderIndependentTranslucentPass/index.js

The OrderIndependentTranslucentPass was not restoring the original scissor box + viewport parameters. This caused issues under scenarios with the following properties:
* the renderer is smaller than the render window
* the renderer's scene has multiple geometries
* one or more of the geometries is translucent
Corrected rendering (the wireframe geometry is now correctly inside the blue box):

OrderIndependentTranslucentPass: restore scissor box + viewport

---

Sources/Common/Core/DataArray/Constants.js
Sources/Common/Core/ScalarsToColors/index.js

This PR fixes a bug in vtk.js when one creates a color definition with UInt8Clamped array structure
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(Colors): fix UInt8Clamped array color definition

---

Sources/Common/Core/StringArray/index.js

Resolves #3036. 
The error described in the issue is no longer raised.
This PR includes only a one-line change, adding `empty: true` to the `newInstance` call in `newClone`, as suggested by @finetjul 
The following code raises an error on master and does not raise an error on this branch:
```
import vtkStringArray from 'vtk.js/Sources/Common/Core/StringArray';
const arr = vtkStringArray.newInstance({
name: 'testArray',
size: 1,
});
arr.setData(['foo'], 1);
console.log(arr);
const copy = arr.newClone();
```
- vtk.js version: 29.10.0
- Browsers: Chrome Version 122.0.6261.111 and Firefox 124.0
- OS: Ubuntu 20.04

fix(vtkStringArray): add `empty: true` to `newClone` implementation

---

Sources/Rendering/Core/ImageCPRMapper/example/controller.html
Sources/Rendering/Core/ImageCPRMapper/example/index.js
Sources/Rendering/OpenGL/ImageCPRMapper/index.js

Documentation says for the projection slab thickness:
>  Thickness of the projection slab in image coordinates (NOT in voxels)
> Usually in millimeters if the spacing of the input image is set from a DICOM
But the implementation used voxels as unit which doesn't make a lot of sense as it can vary along axes
This PR fixes the unit of this value and the example accordingly.

Fix projection slab thickness unit in ImageCPRMapper

---

Sources/Interaction/Manipulators/3DControllerModelSelectorManipulator/index.d.ts
Sources/Interaction/Manipulators/3DControllerModelSelectorManipulator/index.js
Sources/Interaction/Manipulators/CompositeVRManipulator/index.d.ts
Sources/Interaction/Manipulators/CompositeVRManipulator/index.js
Sources/Interaction/Manipulators/VRButtonPanManipulator/index.js
Sources/Interaction/Style/InteractorStyleHMDXR/example/controller.html
Sources/Interaction/Style/InteractorStyleHMDXR/example/index.js
Sources/Interaction/Style/InteractorStyleHMDXR/index.d.ts
Sources/Interaction/Style/InteractorStyleHMDXR/index.js
Sources/Interaction/Style/InteractorStyleManipulator/index.js
Sources/Rendering/Core/Prop3D/index.d.ts
Sources/Rendering/Core/Prop3D/index.js
Sources/Rendering/Core/RenderWindowInteractor/index.d.ts
Sources/Rendering/Core/RenderWindowInteractor/index.js
Sources/Rendering/WebXR/RenderWindowHelper/index.js

VTK.js supports for interactions in a WebXR scene currently does not support manipulating props.
Also, it seems like the support of the Microsoft Hololens is not satisfying.
This PR is currently draft and based upon https://github.com/Kitware/vtk-js/pull/3020
Reviewers are kindly asked to make any high-level/architecture/naming feedback. 
Using the new interactor style (detailed below in the changes section), the support for Microsoft Hololens is now well integrated. The changes should also benefits to other XR Head Mounted Display (HMD) devices, but this has not been tested yet. I will try to test it in the next few days on a Valve Index but as of now, I did not manage to even make it work with VTK.js.
An example is also included for this new interactor style.
I'm aware that there are …

WebXR: add prop interactions through targetRaySpace of XRInputSources

---

BREAKING_CHANGES.md

This is a follow up of #3033.
Improve breaking-change document.

Improve breaking change doc

---

Sources/Rendering/Core/VolumeMapper/example/index.js

Typo in the `VolumeMapper` example
Force linear interpolation -> Force **nearest** interpolation

fix(VolumeMapper): Fix typo in volume mapper example

---

Sources/Rendering/Core/Picker/index.js
Sources/Rendering/Core/Picker/test/testPicker.js

latest changes on `vtkPicker` introduced regression on volume picking.
fix `VolumePicker` example
fix testing for opacity + add test for `vtkPicker` usage with `vtkVolume`
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(picker): opacity test for volume picking

---

Sources/Widgets/Core/WidgetManager/index.d.ts
Sources/Widgets/Core/WidgetManager/index.js

https://discourse.vtk.org/t/cannot-change-default-cursor-or-reslicecursorwidget/13609/3
The widget manager doesn't support customizing the default cursor styles.
The widget manager now exposes an API to configure the default + hover cursor styles.
- `vtkWidgetManager.setCursorStyles()` API added.
- **vtk.js**: 
- **OS**: 
- **Browser**:

feat(WidgetManager): customize cursor styles

---

Examples/Geometry/CubeAxes/index.js
Sources/Rendering/Core/CubeAxesActor/index.js

This lets users control the ticks of the grid
One might want to control the spacing of the ticks.
The tick generation function is exposed to be changed.

feat(cubeaxesactor): expose generateTicks() internal function

---

Examples/Geometry/CubeAxes/index.js
Sources/Rendering/Core/CubeAxesActor/index.js

Changing the number of ticks requires resizing the associated texture.
Texture was stretched when number of ticks was changed.
It is now correctly resized.
Allow resizing of the texture

Expose cube axes actor tick generation 2

---

Sources/Rendering/Core/Renderer/index.d.ts
Sources/Widgets/Widgets3D/ResliceCursorWidget/behavior.d.ts

A breaking change of v30 that makes this replacement needed:
```ts
// This
widgetInstance.invokeInternalInteractionEvent();
// becomes this
widgetInstance.invokeInteractionEvent(widgetInstance.getActiveInteraction());
```
Adding `getActiveInteraction` ensures that the project using typescript can keep using it.
Add other functions to avoid doing pull requests for each needed method one by one.

docs(RCW): Add some methods to the TS header of RCW behavior

---

Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl

There seems to be a left out debugging statement (by me), in the older PR which prevents the zero outline value
One should be able to turn off the outline for one segment by setting it to 0. 
`labelMap.actor.getProperty().setLabelOutlineThickness([0, 3]);`
Right now it makes it blue (meant for debugging)
After 
You can now set the outline to 0 and the outline for that segment will be off
Removed the debugging if statement
- **vtk.js**: Latest
- **OS**: macOS Ventura
- **Browser**: Latest Chrome

fix(ImageOutline): allow zero outline by hiding it

---

Examples/Rendering/ManyRenderWindows/index.js
Sources/Rendering/Core/RenderWindow/index.d.ts
Sources/Rendering/Core/RenderWindow/index.js
Sources/Rendering/OpenGL/ForwardPass/index.js
Sources/Rendering/OpenGL/RenderWindow/index.d.ts
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/Renderer/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/SceneGraph/ViewNode/index.d.ts
Sources/Rendering/SceneGraph/ViewNode/index.js
Sources/Rendering/SceneGraph/ViewNodeFactory/index.d.ts
Sources/Rendering/SceneGraph/ViewNodeFactory/index.js
Sources/Rendering/WebGPU/RenderWindow/index.js

Add possibility to share a single context for several render windows.
This enables GPU ressource sharing accross render windows.
This feature uses `drawImage` from the main WebGL context to the child render window's canvas. It is slow if there are a lot of render windows on Firefox: see [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426).

Share GPU ressources across render windows

---

Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

Incorrect logic prevents each segment from having a 0 outline. The previous logic defaulted to the first segment when the thickness was 0. The accurate approach should be to default to the first segment when it is undefined, as it should be permissible to set any segment's thickness to 0.
`labelMap.actor.getProperty().setLabelOutlineThickness([3, 0]);` (segment 1 (red)-> 3 , segment 2 (green) -> 0)
**Previously** 
**After**
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(outlineThickness): allow 0 thickness per segment index

---

Sources/Rendering/Core/ColorTransferFunction/index.js

In this case issue was created in vtk discourse
Discourse post thread: https://discourse.vtk.org/t/set-desired-scale-in-vtkcolortransferfunction/13736
Results:
Now you can access the Scale variable.
Changes:
Simply added access to changing the value of the Scale variable by the user with getScale() and setScale() in vtkColorTransferFunction, which was not there for some reason.

fix(colortransferfunction): add access to set/get Scale

---

Sources/Rendering/Core/ScalarBarActor/example/controlPanel.html
Sources/Rendering/Core/ScalarBarActor/example/index.js

Improve vtkScalarBarActor example to demonstrate the Log scale.
Adds a "Log" checkbox to the vtkScalarBarActor example.

Expose log in scalarbaractor example

---

Examples/Rendering/ManyRenderWindows/index.js
Sources/Rendering/OpenGL/ImageResliceMapper/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

Fixes the issues mentionned in #3059
The picking has been tested and should work fine.
I kept it in a stash but it is maybe better to share it in a branch:
I modified the HW selector test to show that picking still works in the children render windows [in my fork](https://github.com/bruyeret/vtk-js/tree/picking-multi-render-window).
Close #3059

Fix ImageResliceMapper and improve example

---

Sources/Widgets/Widgets3D/ImplicitPlaneWidget/index.js

Manipulators need to have their normals set prior to handleEvent.
ImplicitWidget still exhibits jumpy behavior.
Fixes jumpy behavior.
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(ImplicitPlaneWidget): jumpy behavior

---

Examples/Rendering/ManyRenderWindows/index.js
Sources/Rendering/Core/RenderWindow/index.d.ts
Sources/Rendering/Core/RenderWindow/index.js
Sources/Rendering/OpenGL/Actor/index.js
Sources/Rendering/OpenGL/Actor2D/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/ImageResliceMapper/index.js
Sources/Rendering/OpenGL/ImageSlice/index.js
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/Volume/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/Rendering/SceneGraph/ViewNode/index.d.ts
Sources/Rendering/SceneGraph/ViewNode/index.js

- Avoid crash when releasing of graphics resources using `releaseGraphicsResourcesForObject()` and the released texture is used by other parts of the code
- Add code in the example to show how to release graphics resources by hand (this process should be automated in a near future)
- Add the possibility to remove child render windows and show how to do it in the example

Cleanup of resource sharing accross render windows

---

Examples/Rendering/ManyRenderWindows/index.js
Sources/Rendering/OpenGL/ImageCPRMapper/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/ImageResliceMapper/index.js
Sources/Rendering/OpenGL/PixelSpaceCallbackMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper2D/index.js
Sources/Rendering/OpenGL/Texture/index.js

If this function deletes a node, it should be called "deleteNode" not "removeNode"
This caused an error in the example `ManyRenderWindows`

Remove node deletion from "removeNode"

---

Sources/Interaction/Style/InteractorStyleImage/index.js
Sources/Interaction/Style/InteractorStyleManipulator/index.js
Sources/Interaction/Style/InteractorStyleTrackballCamera/index.js
Sources/Interaction/Widgets/OrientationMarkerWidget/index.d.ts
Sources/Interaction/Widgets/OrientationMarkerWidget/index.js
Sources/Rendering/Core/InteractorStyle/index.d.ts
Sources/Rendering/Core/InteractorStyle/index.js
Sources/Widgets/Widgets3D/InteractiveOrientationWidget/example/index.js
Sources/Widgets/Widgets3D/InteractiveOrientationWidget/helpers.d.ts
Sources/Widgets/Widgets3D/InteractiveOrientationWidget/helpers.js

See https://github.com/Kitware/vtk-js/issues/2858
A solution is provided to make widget works as intended.
The provided solution expose a new API on InteractorStyle to force an explicit renderer instead of using the event poked renderer.
The second change is to make the OrientationMarkerWidget self renderer interactive.
Third fix is in the example itself, it consists of calling `setParentRenderer` on the OrientationMarkerWidget instance with the renderer that should be used for camera synchronization.
- **vtk.js**: 
- **OS**: 
- **Browser**:

Fix interactive orientation widget

---

Sources/Rendering/Core/ImageProperty/index.d.ts

`imageProperty.setRGBTransferFunction(index, null)` and `imageProperty.setScalarOpacity(index, null)` should be allowed in the types.
Types are fixed to allow null functions.
N/A

fix(ImageProperty): color + opacity funcs can be null

---

Sources/Rendering/OpenGL/CellArrayBufferObject/index.js

There used to be issues when using mixed types of cells (verts, lines, polys, strip)
Take cell offset into account to compute the cell ID

Fix cell id in cell cell array buffer object

---

Sources/Rendering/Core/Property/index.d.ts

`property.getShading()` doesn't exist. https://discourse.vtk.org/t/vtkjs-shading-comparison-to-python/14108/1
Since these methods don't exist, drop them from the types.
N/A

fix(Property): get/setShading doesn't exist

---

Examples/Rendering/ManyRenderWindows/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/ImageResliceMapper/index.js
Sources/Rendering/OpenGL/RenderWindow/index.d.ts
Sources/Rendering/OpenGL/RenderWindow/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

Add garbage collection of shared graphics resources.
The render window now owns the shared resources.
Owners of graphics resources are responsible to register and unregister their usage of graphics resources.
Remove sharing of `scalars` from the cpu image reslice mapper, as it owns the scalars and doesn't share them as the volume mapper and the gpu image reslice mapper do.
Users don't have to do anything - except using a parent RenderWindow - to use this feature.

GPU resources garbage collection

---

Sources/Rendering/Misc/FullScreenRenderWindow/index.js
Sources/Rendering/Misc/GenericRenderWindow/index.js

GenericRenderWindow doesn't clean up event listeners on delete. https://discourse.paraview.org/t/need-help-getboundingclientrect-error-on-screen-resize/14911/2
Event listeners are cleaned up on delete.
N/A

fix(GenericRenderWindow): remove event listeners

---

Sources/Widgets/Widgets3D/LineWidget/index.js

#3062 reported a memory leak with vtkLineWidget. It remains to be seen if widgets generally leak memory.
- Line widget no longer leaks memory
N/A

fix(LineWidget): onModified memory leak

---

Sources/Rendering/Core/Mapper/index.js

Coloring was broken when using direct scalars with cellData
See [this comment](https://github.com/Kitware/vtk-js/pull/3075#discussion_r1676413103) that explains the issue
See [this comment](https://github.com/Kitware/vtk-js/pull/3095#issuecomment-2256835425) that asks for a separate PR
To merge before #3095

Fix color mapping for direct scalars

---

Sources/Widgets/Widgets3D/ShapeWidget/example/controlPanel.html
Sources/Widgets/Widgets3D/ShapeWidget/example/index.js

It is not easy to place an ellipse widget programatically.
https://discourse.vtk.org/t/how-to-programmatically-add-the-ellipsewidget/14199/2
Update the existing ShapeWidget example.
It's not perfect though...

docs(shapewidget): programmatically place shape widgets

---

Sources/Rendering/Core/ImageArrayMapper/index.d.ts
Sources/Rendering/Core/ImageCPRMapper/index.d.ts
Sources/Rendering/Core/ImageMapper/index.d.ts
Sources/Rendering/Core/ImageResliceMapper/index.d.ts
Sources/Rendering/Core/Mapper/CoincidentTopologyHelper.d.ts
Sources/Rendering/Core/Mapper/CoincidentTopologyHelper.js
Sources/Rendering/Core/Mapper/Static.js
Sources/Rendering/Core/Mapper/index.d.ts
Sources/Rendering/OpenGL/ImageCPRMapper/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/ImageResliceMapper/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Testing/testMacro.js
Sources/Widgets/Representations/CircleContextRepresentation/index.js
Sources/macros.js

- `mapper.set({ relativeCoincidentTopologyLineOffsetParameters: { factor, offset } })` does not work because the coincident topology setters do not support single-object parameters. This is (mostly) inconsistent with how we expect setters to work.
- Refactored the coincident topology helper types to reduce repetition and inconsistencies with type definitions across mappers.
- improved types and coincident topology API
N/A

Fix resolve coincident topology api

---

Sources/Rendering/OpenGL/Texture/index.d.ts
Sources/Rendering/OpenGL/Texture/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

computed range is only used for `additive` and `average` blend mode, and for other blend modes it is not needed at all, so it can be skipped for performance reasons
This PR refactors the code to allow direct usage of `create3DFromRaw`. Previously, applications had to use `create3DFilterableFromRaw` or `create3DFilterableFromDataArray`, which required passing in the full, large data array. With this refactoring, `create3DFromRaw` can be used directly, which may be preferable for applications that stream data.
Nothing changes, only error handling and refactoring
Add a check to only use it when available
- **OS**: macOS

fix(volumeMapper): error handling when computed scale is not available

---

Examples/Rendering/QuadView/index.js
Examples/Volume/VolumeMapperLightAndShadow/index.js

Two examples did the same mistake (there were a copy paste).
They should add the coordinates instead of subtract.
Use `vtkBoundingBox.getCenter` instead.

Fix wrong center computation from bounding box

---

Sources/Rendering/OpenGL/Texture/index.js

The origin of the problem is this bug in OHIF, a consumer of vtk: https://github.com/OHIF/Viewers/issues/4286
For certain mobile Android devices, instead of rendering a texture, the canvas was solid gray/black. It happens regardless of OS version/browser, but eventually I narrowed it down to devices that use Mali GPUs (which is likely because they don't support OES_texture_float_linear).
Since it was working everywhere previously and I had a good version of OHIF, I bisected until this [first bad commit](https://github.com/OHIF/Viewers/commit/21e8a2bd0b7cc72f90a31e472d285d761be15d30), which among other things, bumps the version of vtk.js from `29.3.0` to `29.7.0`. After checking all the vtk versions in that range, I found that `29.5.0` was the last good one, and `29.5.1` was the first bad …

fix: force half float in texture if it's exact and OES_texture_float_linear is not available

---

Sources/Rendering/Misc/RemoteView/example/index.md

Fix doc to account for ParaView 5.13 removing wslink but enabling external venv

docs(pv5.13): update remote view example

---

Sources/Rendering/WebXR/RenderWindowHelper/index.js
Sources/Rendering/WebXR/index.js
Sources/Rendering/index.js

WebXR wasn't exposed in the file sent by CDNs
See [this post](https://discourse.vtk.org/t/vtkxrrenderwindow-is-web-served-vtk-js-service/14554) in the discourse

feat: Add WebXR to default Rendering export

---

Examples/Applications/ImageViewer/index.js

The current ImageViewer example application required some fixes to update the `vtkScalarBarActor` as the window/level values are changed by the user's mouse click-drag operation. This fix will help us demonstrate the continuous update / animate capability of `vtkScalarBarActor`.
| Before | After
-- | --
- **vtk.js**:  latest master
- **OS**:  Windows 11 Pro
- **Browser**:  Edge Version 129.0.2792.52 (Official build)

fix(eg-ImageViewer): animate scalarBar ticks with window level adjust

---

Sources/Rendering/OpenGL/ImageSlice/test/testForceRenderPass.js

Left a test.only tag in testForceRenderPass.js: `test.onlyIfWebGL.only` 😬

chore(tests): remove .only from testForceRenderPass.js

---

Sources/Rendering/OpenGL/RenderWindow/index.js

The screenshot feature did not work with several renderwindows linked to a root render window.
To reproduce the issue, you can edit the `ManyRenderWindows` example.
Change the action of the `Remove render window` button to make screenshots.
To do so, at the line `button.addEventListener`, replace the listener using this code:
```js
button.addEventListener('click', () => {
renderWindowView.captureNextImage(null, { scale: 5 }).then((result) => {
const newWindow = window.open('');
newWindow.document.write(`<img src="${result}" alt="Image Preview" />`);
});
renderWindow.render();
});
```

Fix screenshots with scaling or size argument

---

.github/ISSUE_TEMPLATE/feature_request.yml

Most important thing to capture is the user's problem/motivation/usecase. So put that first.  Implimentation could take many forms.  Maintainers will probly suggest a different approach anyway.
closes #3127

chore(issue-template): update feature request template

---

Sources/Rendering/Core/Mapper/CoincidentTopologyHelper.js
Sources/Rendering/Core/Mapper/test/testCoincidentTopologyHelper.js

When calling the static mapper `vtkMapper.setResolveCoincidentTopologyPolygonOffsetParameters`, there is an error because the "class" does not have a publicAPI  with a `modified()` function.  `publicAPI.modifed()` is called by macros.js object setter macro.
Does not error now when calling `vtkMapper.setResolveCoincidentTopologyPolygonOffsetParameters`.  
The error fix involved adding a noOp `modified` function.  Alternatives could be to check if `publicAPI` has `modified` in macros.js or upgrade the Mapper static object with macros.js' `function obj(publicAPI = {}, model = {})` "constructor."   
- **vtk.js**: 
- **OS**: 
- **Browser**:

Fix static vtkMapper coincident topology functions 

---

Sources/Rendering/Core/ImageResliceMapper/test/testImageResliceMapperShareOpenGLTexture.js
Sources/Rendering/Core/ImageResliceMapper/test/testImageResliceMapperSlabTypes.js
Sources/Rendering/OpenGL/ImageCPRMapper/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/ImageResliceMapper/index.js
Sources/Rendering/OpenGL/RenderWindow/resourceSharingHelper.d.ts
Sources/Rendering/OpenGL/RenderWindow/resourceSharingHelper.js
Sources/Rendering/OpenGL/VolumeMapper/index.js

See https://github.com/Kitware/vtk-js/pull/3137.
It adds the same kind of support for multi image, but for the vtkImageResliceMapper.
The vtkImageResliceMapper now supports up to 4 inputs, each representing a component.
The first volume property will be used for all rendering properties except interpolationType.

Image reslice multi component

---

Sources/Rendering/OpenGL/ImageMapper/index.js

Two issues:
1. Constant label outline thickness texture re-uploads when nothing changes
2. Incorrect blending between two labelmaps with label outline turned on
- I am not yet sure if there is an underlying bug in the OIT implementation, and I haven't spent the time to debug this further. The second commit fixes the issue with minimal changes.
FYI @sedghi 
- Only update the label outline thickness texture when the underlying array reference actually changes
- Blending two labelmaps with label outline on works.

Fix imagemapper blending and rerendering

---

Sources/Rendering/Core/RenderWindowInteractor/index.d.ts

fix #3164
interface IPosition is exported solving the issue `variable x has or is using the name IPosition from the external module @kitware/vtk.js/Rendering/Core/RenderWindowInteractor, but it cannot be named`
- **vtk.js**: 
- **OS**: 
- **Browser**:

Export interface IPosition in Rendering/Core/RenderWindowInteractor

---

Sources/Rendering/Core/PointPicker/index.js

When using multiple actors with PointPicker, the pointID is overwritten by the latter actor, regardless of whether it finds a point. I referred to VTK C++ to modify this part.
- **vtk.js**: 
- **OS**: 
- **Browser**:

PointPicker: PointId would be overwritten with multiple actors.

---

Sources/IO/XML/XMLPolyDataWriter/index.js

- **vtk.js**: 
- **OS**: 
- **Browser**:

fix: vtkXMLPolyDataWriter Support Save FieldData

---

Sources/Rendering/Misc/CanvasView/index.js
Sources/Rendering/Misc/RemoteView/index.d.ts
Sources/Rendering/Misc/RemoteView/index.js

Allow setting the canvas element for `RemoteView`
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(CanvasView): allow setting canvas element

---

Sources/IO/Geometry/IFCImporter/example/controller.html
Sources/IO/Geometry/IFCImporter/example/index.js
Sources/IO/Geometry/IFCImporter/index.js

fix #3189
https://github.com/user-attachments/assets/6db63ed2-ff76-4a48-862b-fa9c4d173bd5
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(IFCImporter): fix normals

---

Sources/IO/Geometry/DracoReader/example/index.js
Sources/IO/Geometry/DracoReader/index.d.ts
Sources/IO/Geometry/DracoReader/index.js
Sources/IO/Geometry/GLTFImporter/Extensions.js
Sources/IO/Geometry/GLTFImporter/example/index.js
Sources/IO/Geometry/GLTFImporter/index.d.ts
Sources/IO/Geometry/GLTFImporter/index.js

fix #3192
https://github.com/user-attachments/assets/742a0bfd-aae1-4aee-b2bc-92ebb4312eef
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(GLTFImporter): fix GLTF Draco normals

---

Sources/Widgets/Widgets3D/ShapeWidget/example/index.js

In oblique mode, depending on the plane normal, the compute histogram function was not covering the entire ellipse.
All the voxels in the ellipse are now covered.

docs(shapewidgetexample): fix ellipse coverage in oblique mode

---

Sources/Rendering/OpenGL/Texture/index.js
Sources/Rendering/OpenGL/Texture/supportsNorm16Linear.js

On certain hardware, combining linear texture filtering with the normalized fixed point types from EXT_texture_norm16 results in black pixels and a WebGL warning from the browser.
```
[.WebGL-0x7202996900]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
```
According to [this proposed webgpu extension](https://github.com/gpuweb/gpuweb/issues/3839), there are a lot of mobile devices that don't support linear filtering for norm16 (eg Adreno 5XX, 7XX devices). This includes recent flagships like the Samsung Galaxy 24 Ultra, where I found this issue.
~~Unlike floats which have the OES_texture_float_linear extension, it doesn't seem possible to check using webgl if linear filtering is present for …

fix: avoid norm16 for textures with linear filtering

---

Sources/Filters/General/ContourTriangulator/helper.js

Fix a small bug in vtkClipClosedSurface, referring a wrong bidimensional array initialization.
It causes a lot of bugs previously in Cornerstone3D, and the vtkClipClosedSurface was removed
https://github.com/cornerstonejs/cornerstone3D/issues/1046
but it seems that it will be needed for future developments
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(vtkclipclosedsurface): fix initialization of a bidimensional array

---

Sources/Common/Core/URLExtract/index.js

Certain URLs are incorrectly parsed, e.g. URL parameters that have equal signs (`=`) as part of their value. (Yes, those symbols should be percent-encoded, but that's not always the case.)
See: https://github.com/Kitware/VolView/issues/688
Use URLSearchParams to parse the URL instead of string splits.
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(URLExtract): use builtin parser

---

.github/workflows/build-test.yml
.github/workflows/publish.yml

This PR updates the github workflows:
- Run on node v20 and v22
- Use actions/upload-artifact@v4, as v3 is deprecated

chore(github): update workflows

---

Sources/Rendering/Core/Glyph3DMapper/index.d.ts

The mapper expects array name strings for the scale and orientation arrays. This change ensures that the typescript definition reflects the same.
BREAKING CHANGE: scaleArray and orientationArray changed API from `number[]` to `string`
The Glyph3DMapper had inconsistent API typescript definitions for scale and orientation array parameters.
- **vtk.js**: 
- **OS**: 
- **Browser**:

refactor(glyph3dmapper): Typescript definition

---

.github/workflows/publish.yml
Documentation/content/index.pug
package.json

Constantly adding to the gh-pages branch bloats the repo size. Instead, use the deploy-pages action to publish the website.

chore: deprecate gh-pages in favor of pages action

---

.github/workflows/build-test.yml
.github/workflows/pr-checks.yml
.github/workflows/publish.yml

Updates the github runners from 20.04: https://github.com/actions/runner-images/issues/11101

chore(github): move off of 20.04 (deprecated)

---

Sources/Rendering/WebXR/RenderWindowHelper/index.js

When using `vtkWebXRRenderWindowHelper` with `drawControllersRay=true`, rays are drawn to represent the controllers
but they are not removed when stopping the XR session. This leads to the camera not being centered correctly.
Here's a comparison of before starting the XR session and after stopping it:
Thanks to this small fix, the rays' actors are removed when exiting the XR session, and the camera can be re-centered 
When `vtkWebXRRenderWindowHelper.stopXR()` is called, every ray's actor is removed so they are not visible anymore.
- No changes in definitions
- **vtk.js**: latest master ([413f07a](https://github.com/Kitware/vtk-js/commit/413f07a1cd4fe0166e3e5564a4e1899260dc01b1))
- **OS**: Windows 11 WSL2 Debian 12
- **Browser**: Chromium 133.0.6943.98

fix(webxr): remove controllers rays when stopping XR

---

Sources/Widgets/Core/WidgetManager/index.d.ts
Sources/Widgets/Representations/WidgetRepresentation/index.d.ts
Sources/Widgets/Widgets3D/ResliceCursorWidget/index.d.ts

Currently, the `getPixelWorldHeightAtCoord` function in `Sources/Widgets/Core/WidgetManager/index.js` has a second parameter in its implementation, but the corresponding TypeScript definition in `Sources/Widgets/Core/WidgetManager/index.d.ts` is missing this parameter. This discrepancy may lead to type errors for TypeScript users.
Relevant code locations:
- [index.js](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Core/WidgetManager/index.js)
- [index.d.ts](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Core/WidgetManager/index.d.ts)
This change updates the TypeScript definition to align with the implementation, preventing type errors when using `getPixelWorldHeightAtCoord`.
```typescript
getPixelWorldHeightAtCoord(coord: number[]): number;
```
```typescript …
```

fix(index.d.ts): fix getPixelWorldHeightAtCoord missing parameter

---

BREAKING_CHANGES.md
Sources/Rendering/OpenGL/Framebuffer/index.js
Sources/Rendering/OpenGL/ImageCPRMapper/index.js
Sources/Rendering/OpenGL/ImageMapper/index.js
Sources/Rendering/OpenGL/ImageResliceMapper/index.js
Sources/Rendering/OpenGL/OrderIndependentTranslucentPass/index.js
Sources/Rendering/OpenGL/PolyDataMapper/index.js
Sources/Rendering/OpenGL/SurfaceLIC/LineIntegralConvolution2D/pingpong.js
Sources/Rendering/OpenGL/SurfaceLIC/SurfaceLICInterface/index.js
Sources/Rendering/OpenGL/Texture/index.d.ts
Sources/Rendering/OpenGL/Texture/index.js
Sources/Rendering/OpenGL/VolumeMapper/index.js
Sources/macros.js

The create* methods have enough parameters to warrant using named parameters.
Closes #3222 
- vtkOpenGLTexture `create*` methods now use named parameters
- **vtk.js**: 
- **OS**: 
- **Browser**:

refactor(OpenGL/Texture): use named parameters

---

Sources/Interaction/Manipulators/MouseCameraTrackballFirstPersonManipulator/index.js
Sources/Interaction/Style/InteractorStyleManipulator/index.d.ts
Sources/Interaction/Style/InteractorStyleManipulator/index.js
Sources/Rendering/Core/RenderWindowInteractor/Constants.d.ts
Sources/Rendering/Core/RenderWindowInteractor/Constants.js
Sources/Rendering/Core/RenderWindowInteractor/index.d.ts
Sources/Rendering/Core/RenderWindowInteractor/index.js

Fix pending TODO in MouseCameraTrackballFirstPersonManipulator to move pointerLock mouse movement logic to vtkRenderWindowInteractor
Modify RenderWindowInteractor to return mouse movement data in pointerLock mode
Freeze InteractorStyleManipulator manipulator during pointer
Lock Update MouseCameraTrackballFirstPersonManipulator

feat(RenderWindowInteractor): commit mouse movement data in pointerlock

---

Sources/Rendering/Core/ColorTransferFunction/index.d.ts
Sources/Rendering/Core/Mapper/index.js

Scalars array was already mapped with log scaling but texture coordinates were incorrectly mapped using the linear range and value. Log color mapping was working if scalar interpolation was off when scalars were not directly mapped to textures.
Also added some missing types to ColorTransferFunction.
In the following screenshots the first rectangle has point values of 1 everywhere, second has 100 and the last 1000.
| Linear | Log before | Log after |
| -- | -- | --|
|  <img width="715" alt="Screenshot 2025-05-02 at 11 02 06" src="https://github.com/user-attachments/assets/211f6acc-53e0-4f52-989b-ea024ec6d0cb" /> |  <img width="703" alt="Screenshot 2025-05-02 at 11 07 54" src="https://github.com/user-attachments/assets/5c551629-7f7d-4988-b5cb-062b1de026ed" /> |  <img width="709" …

fix(mapper.js): fix color texture coordinate mapping when using logarithmic scale

---

Sources/IO/Geometry/GLTFImporter/Reader.js
Sources/Rendering/Core/Property/index.d.ts
Sources/Rendering/Core/Property/index.js
Sources/Rendering/WebGPU/CellArrayMapper/index.js

Add for support for combined RM/ORM texture
fixes #2961
- **vtk.js**: 
- **OS**: 
- **Browser**:

feat(PBR): add for support for combined RM/ORM texture

---

Examples/Rendering/ImageLabelOutline/index.js
Sources/Rendering/Core/ImageProperty/index.d.ts
Sources/Rendering/OpenGL/ImageMapper/index.js

Label outlines now have finer-grained opacity controls. Each label can now specify its own outline opacity via setLabelOutlineOpacity(array).
- **vtk.js**: 
- **OS**: 
- **Browser**:

feat(ImageMapper): array-based outline opacity

---

Sources/Rendering/Core/RenderWindowInteractor/index.js

Sometimes the container may be null
Uncaught TypeError: Cannot read properties of null (reading 'removeEventListener')
at _unbindEvents (RenderWindowInteractor.js:242:15)
at publicAPI.setContainer (RenderWindowInteractor.js:994:5)
- **vtk.js**:
- **OS**:
- **Browser**:

fix(RenderWindowInteractor):  ensure the container is not empty

---

Sources/Common/Core/CellArray/index.d.ts
Sources/Common/Core/CellArray/index.js
Sources/Common/Core/DataArray/index.d.ts
Sources/Common/Core/DataArray/index.js
Sources/Common/Core/DataArray/test/testDataArray.js
Sources/IO/Geometry/DracoReader/index.js
Sources/IO/Geometry/GLTFImporter/Reader.js

vtkDataArray.resize() actually changes the number of tuples, while vtkDataArray.allocate() simply allocate memory without changing the number of tuples.
fix #3282
DracoReader produces a cell data array filled with zeros and then with actual cells.
This is because vtkDataArray.resize() first allocate a new array filled with zeros, and insertNextCell() calls do extend the array with new values.
No more 0-filled array in the DracoReader output cell data array.
A new function vtkDataArray.allocate() is added.

fix(vtkdataarray): fix double allocation when using vtkDataArray.resize

---

Sources/IO/Misc/OBJWriter/index.js

Due to a last minute change i switch to OffscreenCanvas which now causes an error to due to missing toBlob method
```js
Uncaught (in promise) TypeError: s.toBlob is not a function
at OBJWriter.js:1:631961
at new Promise (<anonymous>)
at e.exportAsZip (OBJWriter.js:1:631942)
```
Switch back to `document.createElement('canvas')`
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(OBJWriter): OffscreenCanvas doesn't have toBlob

---

Sources/Rendering/OpenGL/Glyph3DMapper/index.js

The glyphmapper does not handle large coordinates, resulting in jittering
Large coordinates no longer jitter when using the glyph3dmapper
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(Glyph3DMapper): shift+scale for large coords

---

Sources/Widgets/Core/WidgetManager/index.js

Widgets should not remain in an active state if interaction occurs outside of the containing renderer.
An alternative to deactivating all widgets in the widget manager in such a scenario is to filter out interaction events at the widget level that are not targeting the widget's renderer. Such an alternative has the benefit of allowing widgets to remain active for future in-renderer interactions.
I'm still figuring out if this change might break any existing expectations.
Addresses #3144. 
- Fixes #3144, and probably any other widget that operates in a overlapping renderer
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(WidgetManager): cross-renderer widget usage

---

Documentation/content/docs/intro_vtk_as_external_script.md
Documentation/content/docs/vtk-js-demo.html
Examples/Volume/VolumeMapperParallelProjection/index.js
Examples/Volume/VolumeRenderingWithPolyData/index.js

Recommend the use of importmaps
- **vtk.js**: 
- **OS**: 
- **Browser**:

docs(importmaps): use importmaps for external script

---

Sources/Interaction/Manipulators/MouseCameraTrackballPanManipulatorAutoCenter/index.js
Sources/Interaction/Style/InteractorStyleManipulator/api.md
Sources/Interaction/Style/InteractorStyleManipulator/index.js
Sources/Interaction/Style/InteractorStyleManipulatorRotateCameraCenter/example/index.js

Rolls back InteractorStyleManipulator center of rotation behaior to not update on pan.
Adds `vtkMouseCameraTrackballPanManipulatorAutoCenter` for the auto update on center of rotation for mouse only input.
`npm run example InteractorStyleManipulator`
Compare to 
`npm run example InteractorStyleManipulatorRotateCameraCenter`
closes #3309

Revert center of rotation change after pan

---

Utilities/ExampleRunner/template-config.js
package-lock.json
package.json

This is required when running example from a clean build
From a clean vtk.js, there are errors when runnning `npm run example AnExampleHere`
It is now possible to run examples.
- **OS**: Ubuntu

build(webpack-cli): upgrade webpack-cli version

---

Sources/Common/DataModel/BoundingBox/index.js
Sources/Interaction/Style/InteractorStyleMPRSlice/index.js
Sources/Rendering/Core/Prop3D/index.js

When a vtkImageData had a rotation/direction matrix, getSliceRange was "too wide".
getSliceRange is now better fitting the image data bounds.

Fix get slice range

---

Sources/Interaction/Style/InteractorStyleManipulator/index.js

The buttonDown event in the manipulator requests animation but that was not being canceled in the successive buttonUp event. This change fixes that.
fix #3286, #3323
- **vtk.js**: 
- **OS**: 
- **Browser**:

fix(manipulator): cancel animation when ending interaction
